export const DisciplineType = [
  ["Anthropology", "Anthropology"],
  ["Economics", "Economics"],
  ["History", "History"],
  ["PoliticalScience", "Political Science"],
  ["Psychology", "Psychology"],
  ["PublicAdministration", "Public Administration"],
  ["Sociology", "Sociology"],
  ["Mathematics", "Mathematics"],
  ["Hindi", "Hindi"],
  ["Urdu", "Urdu"],
  ["English", "English"],
  ["Sanskrit", "Sanskrit"],
  ["Education", "Education"],
  ["Philosophy", "Philosophy"],
  ["Botany", "Botany"],
  ["Chemistry", "Chemistry"],
  ["Geography", "Geography"],
  ["Geology", "Geology"],
  ["Physics", "Physics"],
  ["Zoology", "Zoology"],
  ["Other", "Other"],
  ["None", "None"],
];
