export const courses = [
  // BAG, Bachelor of Arts
  {
    code: "BANC 131",
    title: "Anthropology and Research Methods",
    studyMaterial: [],
  },
  {
    code: "BANC 132",
    title: "Fundamentals of Biological Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANC 133",
    title: "Fundamentals of Social and Cultural Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANC 134",
    title: "Fundamentals of Archaeological Anthropology",
    studyMaterial: [],
  },
  {
    code: "BECC 131",
    title: "Principles of Microeconomics-I",
    studyMaterial: [],
  },
  {
    code: "BECC 132",
    title: "Principles of Microeconomics-II",
    studyMaterial: [],
  },
  {
    code: "BECC 133",
    title: "Principles of Macroeconomics-I",
    studyMaterial: [],
  },
  {
    code: "BECC 134",
    title: "Principles of Macroeconomics-II",
    studyMaterial: [],
  },
  {
    code: "BHIC 131",
    title: "History of India from the Earliest Times upto c. 300 CE",
    studyMaterial: [],
  },
  {
    code: "BHIC 132",
    title: "History of India from c.300 to 1206",
    studyMaterial: [],
  },
  {
    code: "BHIC 133",
    title: "History of India from c.1206 to 1707",
    studyMaterial: [],
  },
  {
    code: "BHIC 134",
    title: "History of India from c. 1707 to 1950",
    studyMaterial: [],
  },
  {
    code: "BPSC 131",
    title: "Introduction to Political Theory",
    studyMaterial: [],
  },
  {
    code: "BPSC 132",
    title: "Indian Government and Politics",
    studyMaterial: [],
  },
  {
    code: "BPSC 133",
    title: "Comparative Government and Politics",
    studyMaterial: [],
  },
  {
    code: "BPSC 134",
    title: "Introduction to International Relations",
    studyMaterial: [],
  },
  {
    code: "BPCC 131",
    title: "Foundations of Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCC 132",
    title: "Introduction to Social Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCC 133",
    title: "Psychological Disorders",
    studyMaterial: [],
  },
  {
    code: "BPCC 134",
    title: "Statistical Methods and Psychological Research",
    studyMaterial: [],
  },
  {
    code: "BPAC 131",
    title: "Perspectives on Public Administration",
    studyMaterial: [],
  },
  {
    code: "BPAC 132",
    title: "Administrative Thinkers",
    studyMaterial: [],
  },
  {
    code: "BPAC 133",
    title: "Administrative system at Union Level",
    studyMaterial: [],
  },
  {
    code: "BPAC 134",
    title: "Administrative system at State and DistrictLevels",
    studyMaterial: [],
  },
  {
    code: "BSOC 131",
    title: "Introduction to Sociology",
    studyMaterial: [],
  },
  {
    code: "BSOC 132",
    title: "Sociology of India",
    studyMaterial: [],
  },
  {
    code: "BSOC 133",
    title: "Sociological Theories",
    studyMaterial: [],
  },
  {
    code: "BSOC 134",
    title: "Methods of Sociological Enquiry",
    studyMaterial: [],
  },
  {
    code: "BHDC 131",
    title: "�हंद�सा�हत्यकाइ�तहास",
    studyMaterial: [],
  },
  {
    code: "BHDC 132",
    title: "मध्यकाल�न�हंद�क�वता",
    studyMaterial: [],
  },
  {
    code: "BHDC 133",
    title: "आधु�नक�हंद�क�वता",
    studyMaterial: [],
  },
  {
    code: "BHDC 134",
    title: "�हंद�गद्यसा�हत्य",
    studyMaterial: [],
  },
  {
    code: "BHDLA 135",
    title: "�हंद�भाषा : �व�वधप्रयोग",
    studyMaterial: [],
  },
  {
    code: "BHDLA 136",
    title: "�हंद�भाषा : लेखनकौशल",
    studyMaterial: [],
  },
  {
    code: "BHDLA 137",
    title: "�हंद�भाषा : संप्रेषाकौशल",
    studyMaterial: [],
  },
  {
    code: "BHDLA 138",
    title: "�हंद�सा�हत्य : �व�वध�वधाएँ",
    studyMaterial: [],
  },
  {
    code: "BUDC 131",
    title: "Study of Prose & Poetic Form in Urdu",
    studyMaterial: [],
  },
  {
    code: "BUDC 132",
    title: "Study of Urdu Classical Ghazal",
    studyMaterial: [],
  },
  {
    code: "BUDC 133",
    title: "Origin & Development of Urdu Language",
    studyMaterial: [],
  },
  {
    code: "BUDC 134",
    title: "Study of Urdu Nazm",
    studyMaterial: [],
  },
  {
    code: "BUDLA 135",
    title: "Study of Modern Urdu Prose & Poetry",
    studyMaterial: [],
  },
  {
    code: "BEGC 131",
    title: "Individual & Society",
    studyMaterial: [],
  },
  {
    code: "BEGC 132",
    title: "Selections From Indian Writing: CulturalDiversity",
    studyMaterial: [],
  },
  {
    code: "BEGC 133",
    title: "British Literature",
    studyMaterial: [],
  },
  {
    code: "BEGC 134",
    title: "Reading The Novel",
    studyMaterial: [],
  },
  {
    code: "BEGLA 135",
    title: "English In Daily Life",
    studyMaterial: [],
  },
  {
    code: "BEGLA 136",
    title: "English At The Work Place",
    studyMaterial: [],
  },
  {
    code: "BEGLA 137",
    title: "Language Through Literature",
    studyMaterial: [],
  },
  {
    code: "BEGLA 138",
    title: "Reading and Speaking Skills",
    studyMaterial: [],
  },
  {
    code: "BSKC 131",
    title: "संस्कृत पद्य सा�हत्य",
    studyMaterial: [],
  },
  {
    code: "BSKC 132",
    title: "संस्कृत गद्य सा�हत्य",
    studyMaterial: [],
  },
  { code: "BSKC 133", title: "संस्कृत नाटक", studyMaterial: [] },
  {
    code: "BSKC 134",
    title: "संस्कृत व्याकरण",
    studyMaterial: [],
  },
  {
    code: "BSKLA 135",
    title: "संस्कृत सा�हत्य एवं व्याकरण",
    studyMaterial: [],
  },
  {
    code: "BODLA 135",
    title: "Modern Indian Language: Odia",
    studyMaterial: [],
  },
  {
    code: "BGULA 135",
    title: "Modern Indian Language: Gujarati",
    studyMaterial: [],
  },
  {
    code: "BMYLA 135",
    title: "Modern Indian Language: Malayalam",
    studyMaterial: [],
  },
  {
    code: "BPBLA",
    title: "Modern Indian Language: Punjabi",
    studyMaterial: [],
  },
  { code: "BMTC 131", title: "Calculus", studyMaterial: [] },
  {
    code: "BMTC 132",
    title: "Differential Equations",
    studyMaterial: [],
  },
  { code: "BMTC 133", title: "Real Analysis", studyMaterial: [] },
  { code: "BMTC 134", title: "Algebra", studyMaterial: [] },
  {
    code: "BESC 131",
    title: "Education: Concept, Nature and Perspectives",
    studyMaterial: [],
  },
  {
    code: "BESC 132",
    title: "Structure and Management of Education ",
    studyMaterial: [],
  },
  {
    code: "BESC 133",
    title: "Curriculum, Teaching-Learning and Assessment",
    studyMaterial: [],
  },
  {
    code: "BESC 134",
    title: "Education as a Practice",
    studyMaterial: [],
  },
  {
    code: "BPYC 131",
    title: "Indian Philosophy",
    studyMaterial: [],
  },
  { code: "BPYC 132", title: "Ethics", studyMaterial: [] },
  { code: "BPYC 133", title: "Logic", studyMaterial: [] },
  {
    code: "BPYC 134",
    title: "Western Philosophy: Modern",
    studyMaterial: [],
  },
  {
    code: "BANE 145",
    title: "Applied Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANE 146",
    title: "Anthropology of Indigenous People",
    studyMaterial: [],
  },
  {
    code: "BECE 145",
    title: "Indian Economy – I",
    studyMaterial: [],
  },
  {
    code: "BECE 146",
    title: "Indian Economy – II",
    studyMaterial: [],
  },
  {
    code: "BHIE 141",
    title: "History of China: C. 1840-1978",
    studyMaterial: [],
  },
  {
    code: "BHIE 142",
    title: "History of Modern East Asia: Japan (1868-1945)",
    studyMaterial: [],
  },
  {
    code: "BHIE 143",
    title: "History of Environment",
    studyMaterial: [],
  },
  {
    code: "BHIE 144",
    title: "Traditions of History Writing in India",
    studyMaterial: [],
  },
  {
    code: "BHIE 145",
    title: "Some aspects of European History: C. 1789 – 1945",
    studyMaterial: [],
  },
  {
    code: "BPSE 141",
    title: "Gandhi and the Contemporary World",
    studyMaterial: [],
  },
  {
    code: "BPSE 142",
    title: "India’s Foreign Policy in a Changing World",
    studyMaterial: [],
  },
  {
    code: "BPSE 143",
    title: "State Politics in India",
    studyMaterial: [],
  },
  {
    code: "BPSE 144",
    title: "Introduction to South Asia",
    studyMaterial: [],
  },
  {
    code: "BPSE 145",
    title: "Democracy and Development in Northeast India",
    studyMaterial: [],
  },
  {
    code: "BPSE 146",
    title: "Conflict Resolution and Peace building",
    studyMaterial: [],
  },
  {
    code: "BPCE 145",
    title: "Counselling Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCE 146",
    title: "Industrial/ Organisational Psychology",
    studyMaterial: [],
  },
  {
    code: "BPAE 141",
    title: "Right to Information",
    studyMaterial: [],
  },
  {
    code: "BPAE 142",
    title: "Organisational Behaviour",
    studyMaterial: [],
  },
  {
    code: "BPAE 143",
    title: "Administrative System in BRICS",
    studyMaterial: [],
  },
  {
    code: "BPAE 144",
    title: "Social Policies and Administration",
    studyMaterial: [],
  },
  {
    code: "BSOE 145",
    title: "Religion and Society",
    studyMaterial: [],
  },
  {
    code: "BSOE 146",
    title: "Marriage, Family and Kinship",
    studyMaterial: [],
  },
  {
    code: "BSOE 148",
    title: "Social Stratification",
    studyMaterial: [],
  },
  {
    code: "BHDE 141",
    title: "अिस्मतामूलक �वमशर् और �हंद� सा�हत्य",
    studyMaterial: [],
  },
  {
    code: "BHDE 142",
    title: "राष्ट्र�य काव्यधारा",
    studyMaterial: [],
  },
  { code: "BHDE 143", title: "प्रेमचंद", studyMaterial: [] },
  { code: "BHDE 144", title: "छायावाद", studyMaterial: [] },
  {
    code: "BUDE 141",
    title: "Study of Poet Mirza Ghalib",
    studyMaterial: [],
  },
  {
    code: "BUDE 142",
    title: "Study of Prose Writer Meer Amman Dehlawi",
    studyMaterial: [],
  },
  {
    code: "BEGE 141",
    title: "Understanding Prose",
    studyMaterial: [],
  },
  {
    code: "BEGE 142",
    title: "Understanding Drama",
    studyMaterial: [],
  },
  {
    code: "BEGE 143",
    title: "Understanding Poetry",
    studyMaterial: [],
  },
  { code: "BEGE 145", title: "Soft Skills", studyMaterial: [] },
  {
    code: "BSKE 141",
    title: "आयुव�द के मूल आधार",
    studyMaterial: [],
  },
  {
    code: "BSKE 142",
    title: "रंगमंच और नाट्य कला",
    studyMaterial: [],
  },
  {
    code: "BMTE 141",
    title: "Linear Algebra",
    studyMaterial: [],
  },
  {
    code: "BMTE 144",
    title: "Numerical Analysis",
    studyMaterial: [],
  },
  {
    code: "BESE 141",
    title: "ICT in Education",
    studyMaterial: [],
  },
  {
    code: "BESE 142",
    title: "Lifelong Learning",
    studyMaterial: [],
  },
  { code: "BPYE 141", title: "Metaphysics", studyMaterial: [] },
  {
    code: "BPYE 142",
    title: "Social and Political Philosophy",
    studyMaterial: [],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: [],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANS 184",
    title: "Public Health and Epidemiology",
    studyMaterial: [],
  },
  { code: "BECS 184", title: "Data Analysis", studyMaterial: [] },
  {
    code: "BPCS 183",
    title: "Emotional Intelligence",
    studyMaterial: [],
  },
  {
    code: "BPCS 184",
    title: "School Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCS 185",
    title: "Developing Emotional Competence",
    studyMaterial: [],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: [],
  },
  {
    code: "BPCS 187",
    title: "Managing Human Resources",
    studyMaterial: [],
  },
  {
    code: "BPCS 188",
    title: "Application of Social Psychology",
    studyMaterial: [],
  },
  {
    code: "BPAS 184",
    title: "Logistics Management",
    studyMaterial: [],
  },
  {
    code: "BPAS 186",
    title: "Stress and Time Management ",
    studyMaterial: [],
  },
  {
    code: "BSOS 184",
    title: "Techniques of Ethnographic Film Making",
    studyMaterial: [],
  },
  {
    code: "BSOS 185",
    title: "Society through the Visual",
    studyMaterial: [],
  },
  {
    code: "BHDS 183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    studyMaterial: [],
  },
  { code: "BHDS 184", title: "रे�डयो लेखन", studyMaterial: [] },
  {
    code: "BEGS 183",
    title: "Writing And Study Skills",
    studyMaterial: [],
  },
  {
    code: "BEGS 185",
    title: "English Language Teaching",
    studyMaterial: [],
  },
  {
    code: "BEGS 186",
    title: "Business Communication",
    studyMaterial: [],
  },
  {
    code: "BGDG 172",
    title: "Gender Sensitization: Society and Culture",
    studyMaterial: [],
  },
  {
    code: "BPCG 171",
    title: "General Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCG 172",
    title: "Youth, Gender and Identity",
    studyMaterial: [],
  },
  {
    code: "BPCG 173",
    title: "Psychology for Health andWell-being",
    studyMaterial: [],
  },
  {
    code: "BPCG 174",
    title: "Psychology and Media",
    studyMaterial: [],
  },
  {
    code: "BPCG 175",
    title: "Psychology for Living",
    studyMaterial: [],
  },
  {
    code: "BPCG 176",
    title: "Psychology of Gender",
    studyMaterial: [],
  },
  {
    code: "BPAG 171",
    title: "Disaster Management",
    studyMaterial: [],
  },
  {
    code: "BPAG 172",
    title: "Governance: Issues and Challenges",
    studyMaterial: [],
  },
  { code: "BPAG 173", title: "E-Governance", studyMaterial: [] },
  {
    code: "BPAG 174",
    title: "Sustainable Development",
    studyMaterial: [],
  },
  {
    code: "BSOG 171",
    title: "Indian Society: Images and Realities",
    studyMaterial: [],
  },
  {
    code: "BSOG 173",
    title: "Rethinking Development",
    studyMaterial: [],
  },
  {
    code: "BSOG 176",
    title: "Economy and Society",
    studyMaterial: [],
  },
  {
    code: "BHDG 173",
    title: "समाचार पत्र और फ�चर लेखन",
    studyMaterial: [],
  },
  {
    code: "BEGG 171",
    title: "Media and Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BEGG 172",
    title: "Language and Linguistics",
    studyMaterial: [],
  },
  {
    code: "BEGG 173",
    title: "Academic Writing & Composition",
    studyMaterial: [],
  },
  {
    code: "BEGG 174",
    title: "Creative Writing",
    studyMaterial: [],
  },
  {
    code: "BABG 171",
    title: "Understanding Ambedkar",
    studyMaterial: [],
  },
  {
    code: "BPYG 171",
    title: "Applied Ethics",
    studyMaterial: [],
  },
  {
    code: "BPYG 172",
    title: "Philosophy of Religion",
    studyMaterial: [],
  },
  // BCOMG, Bachelor of Commerce
  {
    code: "BCOC 131",
    title: "Financial Accounting",
    studyMaterial: [],
  },
  {
    code: "BCOC 132",
    title: "Business Organization and Management",
    studyMaterial: [],
  },
  { code: "BCOC 133", title: "Business Law", studyMaterial: [] },
  {
    code: "BCOC 134",
    title: "Business Mathematics and Statistics",
    studyMaterial: [],
  },
  { code: "BCOC 135", title: "Company Law", studyMaterial: [] },
  {
    code: "BCOC 136",
    title: "Income Tax Law and Practice",
    studyMaterial: [],
  },
  {
    code: "BCOC 137",
    title: "Corporate Accounting",
    studyMaterial: [],
  },
  {
    code: "BCOE 141",
    title: "Principles of Marketing",
    studyMaterial: [],
  },
  {
    code: "BCOE 143",
    title: "Fundamentals of Financial Management",
    studyMaterial: [],
  },
  {
    code: "BCOE 142",
    title: "Management Accounting",
    studyMaterial: [],
  },
  {
    code: "BCOE 144",
    title: "Office Management and Secretarial Practice",
    studyMaterial: [],
  },
  {
    code: "BCOS 183",
    title: "Computer Application in Business",
    studyMaterial: [],
  },
  { code: "BCOS 184", title: "E-Commerce", studyMaterial: [] },
  {
    code: "BCOS 185",
    title: "Entrepreneurship",
    studyMaterial: [],
  },
  {
    code: "BCOS 186",
    title: "Personal Selling and Salesmanship",
    studyMaterial: [],
  },
  {
    code: "BCOG 171",
    title: "Principles of Micro Economics",
    studyMaterial: [],
  },
  {
    code: "BCOG 172",
    title: "Indian Economy",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: [],
  },
  {
    code: "BEGLA 135",
    title: "English In Daily Life",
    studyMaterial: [],
  },
  {
    code: "BEGLA 136",
    title: "English At The Work Place",
    studyMaterial: [],
  },
  {
    code: "BEGLA 137",
    title: "Language Through Literature",
    studyMaterial: [],
  },
  {
    code: "BCOLA 138",
    title: "Business Communication",
    studyMaterial: [],
  },
  {
    code: "BHDLA 136",
    title: "�हंद� भाषा: लेखन कौशल",
    studyMaterial: [],
  },
  {
    code: "BHDLA 137",
    title: "�हंद� भाषा: सम्प्रेषण कौशल",
    studyMaterial: [],
  },
  // BSCG, Bachelor of Science
  {
    code: "BBYCT 131",
    title: "Biodiversity (Microbes, Algae, Fungi and Archegoniates)",
    studyMaterial: [],
  },
  {
    code: "BBYCL 132",
    title:
      "Biodiversity (Microbes, Algae, Fungi and Archegoniates): Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBYCT 133",
    title: "Plant Ecology and Taxonomy",
    studyMaterial: [],
  },
  {
    code: "BBYCL 134",
    title: "Plant Ecology and Taxonomy: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBYCT 135",
    title: "Plant Anatomy and Embryology",
    studyMaterial: [],
  },
  {
    code: "BBYCL 136",
    title: "Plant Anatomy and Embryology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBYCT 137",
    title: "Plant Physiology and Metabolism",
    studyMaterial: [],
  },
  {
    code: "BBYCL 138",
    title: "Plant Physiology and Metabolism: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHCT 131",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons",
    studyMaterial: [],
  },
  {
    code: "BCHCL 132",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHCT 133",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry-I",
    studyMaterial: [],
  },
  {
    code: "BCHCL 134",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry-I : Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHCT 135",
    title:
      "Solutions, Phase equilibrium, Conductance, Electrochemistry and Functional Group Organic Chemistry-II",
    studyMaterial: [],
  },
  {
    code: "BCHCL 136",
    title:
      "Solutions, Phase equilibrium, Conductance, Electrochemistry and Functional Group Organic Chemistry-II : Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHCT 137",
    title: "Coordination Chemistry, States of Matter and Chemical Kinetics",
    studyMaterial: [],
  },
  {
    code: "BCHCL 138",
    title:
      "Coordination Chemistry, States of Matter and Chemical Kinetics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BGGCT 131",
    title: "Physical Geography",
    studyMaterial: [],
  },
  {
    code: "BGGCT 132",
    title: "Human Geography",
    studyMaterial: [],
  },
  {
    code: "BGGCT 133",
    title: "General Cartography",
    studyMaterial: [],
  },
  {
    code: "BGGCL 134",
    title: "General Cartography: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BGGCT 135",
    title: "Environmental Geography",
    studyMaterial: [],
  },
  {
    code: "BGYCT 131",
    title: "Physical and Structural Geology",
    studyMaterial: [],
  },
  {
    code: "BGYCL 132",
    title: "Physical and Structural Geology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BGYCT 133",
    title: "Crystallography, Mineralogy and Economic Geology",
    studyMaterial: [],
  },
  {
    code: "BGYCL 134",
    title: "Crystallography, Mineralogy and Economic Geology: Laboratory",
    studyMaterial: [],
  },
  { code: "BGYCT 135", title: "Petrology", studyMaterial: [] },
  {
    code: "BGYCL 136",
    title: "Petrology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BGYCT 137",
    title: "Stratigraphy and Palaeontology",
    studyMaterial: [],
  },
  {
    code: "BGYCL 138",
    title: "Stratigraphy and Palaeontology: Laboratory",
    studyMaterial: [],
  },
  { code: "BMTC 131", title: "Calculus", studyMaterial: [] },
  {
    code: "BMTC 132",
    title: "Differential Equations",
    studyMaterial: [],
  },
  { code: "BMTC 133", title: "Real Analysis", studyMaterial: [] },
  { code: "BMTC 134", title: "Algebra", studyMaterial: [] },
  { code: "BPHCT 131", title: "Mechanics", studyMaterial: [] },
  {
    code: "BPHCL 132",
    title: "Mechanics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BPHCT 133",
    title: "Electricity and Magnetism",
    studyMaterial: [],
  },
  {
    code: "BPHCL 134",
    title: "Electricity and Magnetism: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BPHCT 135",
    title: "Thermal Physics and Statistical Mechanics",
    studyMaterial: [],
  },
  {
    code: "BPHCL 136",
    title: "Thermal Physics and Statistical Mechanics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BPHCT 137",
    title: "Wave and Optics",
    studyMaterial: [],
  },
  {
    code: "BPHCL 138",
    title: "Wave and Optics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BZYCT 131",
    title: "Animal Diversity",
    studyMaterial: [],
  },
  {
    code: "BZYCL 132",
    title: "Animal Diversity: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BZYCT 133",
    title: "Comparative Anatomy and Developmental Biology of Vertebrates",
    studyMaterial: [],
  },
  {
    code: "BZYCL 134",
    title:
      "Comparative Anatomy and Developmental Biology of Vertebrates: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BZYCT 135",
    title: "Physiology and Biochemistry",
    studyMaterial: [],
  },
  {
    code: "BZYCL 136",
    title: "Physiology and Biochemistry: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BZYCT 137",
    title: "Genetics and Evolutionary Biology",
    studyMaterial: [],
  },
  {
    code: "BZYCL 138",
    title: "Genetics and Evolutionary Biology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBYET 141",
    title: "Cell and Molecular Biology",
    studyMaterial: [],
  },
  {
    code: "BBYEL 142",
    title: "Cell and Molecular Biology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBYET 143",
    title: "Economic Botany and Biotechnology",
    studyMaterial: [],
  },
  {
    code: "BBYEL 144",
    title: "Economic Botany and Biotechnology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHET 141",
    title: "Analytical Methods in Chemistry",
    studyMaterial: [],
  },
  {
    code: "BCHEL 142",
    title: "Analytical Methods in Chemistry: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHET 147",
    title:
      "Organometallics, Bioinorganic Chemistry, PolynuclearHyderocarbons and UV, IR Spectroscopy",
    studyMaterial: [],
  },
  {
    code: "BCHEL 148",
    title:
      "Organometallics, Bioinorganic Chemistry, Polynuclear Hydrocarbons and UV, IR Spectroscopy: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHET 149",
    title: "Molecules of Life",
    studyMaterial: [],
  },
  {
    code: "BCHEL 150",
    title: "Molecules of Life: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BGGET 141",
    title: "Geography of India",
    studyMaterial: [],
  },
  {
    code: "BGGET 142",
    title: "Economic Geography",
    studyMaterial: [],
  },
  {
    code: "BGYET 141",
    title: "Ore Geology and Industrial Minerals",
    studyMaterial: [],
  },
  {
    code: "BGYEL 142",
    title: "Ore Geology and Industrial Minerals: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BGYET 147",
    title: "Geomorphology and Geotectonics",
    studyMaterial: [],
  },
  {
    code: "BGYEL 148",
    title: "Geomorphology and Geotectonics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BMTE 141",
    title: "Linear Algebra",
    studyMaterial: [],
  },
  {
    code: "BMTE 144",
    title: "Numerical Analysis",
    studyMaterial: [],
  },
  {
    code: "BPHET 141",
    title: "Elements of Modern Physics",
    studyMaterial: [],
  },
  {
    code: "BPHEL 142",
    title: "Elements of Modern Physics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BPHET 143",
    title: "Digital and Analog Circuits and Instrumentation",
    studyMaterial: [],
  },
  {
    code: "BPHEL 144",
    title: "Digital and Analog Circuits and Instrumentation: Laboratory",
    studyMaterial: [],
  },
  { code: "BZYET 141", title: "Immunology", studyMaterial: [] },
  {
    code: "BZYEL 142",
    title: "Immunology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BZYET 143",
    title: "Insect Vectors and Vector Borne Diseases",
    studyMaterial: [],
  },
  {
    code: "BZYEL 144",
    title: "Insect Vectors and Vector Borne Diseases: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: [],
  },
  {
    code: "BPCS 185",
    title: "Developing Emotional Competence",
    studyMaterial: [],
  },
  {
    code: "BEGS 183",
    title: "Writing and Study Skills",
    studyMaterial: [],
  },
  {
    code: "BCOS 183",
    title: "Computer Application in Business",
    studyMaterial: [],
  },
  {
    code: "BHDS 183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    studyMaterial: [],
  },
  {
    code: "BANS 184",
    title: "Public Health and Epidemiology",
    studyMaterial: [],
  },
  { code: "BECS 184", title: "Data Analysis", studyMaterial: [] },
  { code: "BCOS 184", title: "E-Commerce", studyMaterial: [] },
  {
    code: "BPAS 184",
    title: "Logistics Management",
    studyMaterial: [],
  },
  {
    code: "BPCS 184",
    title: "School Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: [],
  },
  {
    code: "BSOS 184",
    title: "Techniques of Ethnographic Film Making",
    studyMaterial: [],
  },
  { code: "BHDS 184", title: "रे �डयो लेखन", studyMaterial: [] },
  {
    code: "BPCS 187",
    title: "Managing Human Resources",
    studyMaterial: [],
  },
  {
    code: "BSOS 185",
    title: "Society through the Visual",
    studyMaterial: [],
  },
  {
    code: "BEGS 185",
    title: "English Language Teaching",
    studyMaterial: [],
  },
  {
    code: "BCOS 185",
    title: "Entrepreneurship",
    studyMaterial: [],
  },
  {
    code: "BPAS 186",
    title: "Stress and Time Management",
    studyMaterial: [],
  },
  {
    code: "BPCS 188",
    title: "Application of Social Psychology",
    studyMaterial: [],
  },
  {
    code: "BEGS 186",
    title: "Business Communication",
    studyMaterial: [],
  },
  {
    code: "BCOS 186",
    title: "Personal Selling and Slesmanship",
    studyMaterial: [],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: [],
  },
  // BCA, Bachelor of Computer Applications
  {
    code: "FEG 2",
    title: "Foundation course in English -2",
    studyMaterial: [],
  },
  {
    code: "ECO 1",
    title: "Business Organization",
    studyMaterial: [],
  },
  {
    code: "BCS 11",
    title: "Computer Basics and PC Software",
    studyMaterial: [],
  },
  { code: "BCS 12", title: "Mathematics", studyMaterial: [] },
  {
    code: "BCSL 13",
    title: "Computer Basics and PC Software Lab",
    studyMaterial: [],
  },
  { code: "ECO 2", title: "Accountancy-I", studyMaterial: [] },
  {
    code: "MCS 11",
    title: "Problem Solving and Programming",
    studyMaterial: [],
  },
  {
    code: "MCS 12",
    title: "Computer Organization and Assembly Language Programming",
    studyMaterial: [],
  },
  {
    code: "MCS 15",
    title: "Communication Skills",
    studyMaterial: [],
  },
  {
    code: "MCS 13",
    title: "Discrete Mathematics",
    studyMaterial: [],
  },
  {
    code: "BCSL 21",
    title: "C Language Programming Lab",
    studyMaterial: [],
  },
  {
    code: "BCSL 22",
    title: "Assembly Language Programming Lab",
    studyMaterial: [],
  },
  {
    code: "MCS 21",
    title: "Data and File Structures",
    studyMaterial: [],
  },
  {
    code: "MCS 23",
    title: "Introduction to Database Management Systems",
    studyMaterial: [],
  },
  {
    code: "MCS 14",
    title: "Systems Analysis andDesign",
    studyMaterial: [],
  },
  {
    code: "BCS 31",
    title: "Programming in C++",
    studyMaterial: [],
  },
  {
    code: "BCSL 32",
    title: "C++ Programming Lab",
    studyMaterial: [],
  },
  {
    code: "BCSL 33",
    title: "Data and File Structures Lab",
    studyMaterial: [],
  },
  { code: "BCSL 34", title: "DBMS Lab", studyMaterial: [] },
  {
    code: "BCS 40",
    title: "Statistical Techniques",
    studyMaterial: [],
  },
  {
    code: "MCS 24",
    title: "Object Oriented Technologies and Java Programming",
    studyMaterial: [],
  },
  {
    code: "BCS 41",
    title: "Fundamentals of Computer Networks",
    studyMaterial: [],
  },
  {
    code: "BCS 42",
    title: "Introduction to Algorithm Design",
    studyMaterial: [],
  },
  {
    code: "MCSL 16",
    title: "Internet Concepts and Web Design",
    studyMaterial: [],
  },
  {
    code: "BCSL 43",
    title: "Java Programming Lab",
    studyMaterial: [],
  },
  {
    code: "BCSL 44",
    title: "Statistical Techniques Lab",
    studyMaterial: [],
  },
  {
    code: "BCSL 45",
    title: "Algorithm Design Lab",
    studyMaterial: [],
  },
  {
    code: "BCS 51",
    title: "Introduction to Software Engineering",
    studyMaterial: [],
  },
  {
    code: "BCS 52",
    title: "Network Programming and Administration",
    studyMaterial: [],
  },
  { code: "BCS 53", title: "Web Programming", studyMaterial: [] },
  {
    code: "BCS 54",
    title: "Computer Oriented Numerical Techniques",
    studyMaterial: [],
  },
  {
    code: "BCS 55",
    title: "Business Communication",
    studyMaterial: [],
  },
  {
    code: "BCSL 56",
    title: "Network Programming and Administration Lab",
    studyMaterial: [],
  },
  {
    code: "BCSL 57",
    title: "Web Programming Lab",
    studyMaterial: [],
  },
  {
    code: "BCSL 58",
    title: "Computer Oriented Numerical Techniques Lab",
    studyMaterial: [],
  },
  { code: "BCS 62", title: "E-Commerce", studyMaterial: [] },
  {
    code: "MCS 22",
    title: "Operating System Concepts and Networking Management",
    studyMaterial: [],
  },
  {
    code: "BCSL 63",
    title: "Operating System Concepts & Networking Management Lab",
    studyMaterial: [],
  },
  { code: "BCSP 64", title: "Project", studyMaterial: [] },
  // BLIS, Bachelor of Library and Information Sciences
  {
    code: "BHDLA 135",
    title: "Hindi Bhasha: Vivid Prayog",
    studyMaterial: [],
  },
  {
    code: "BEGLA 135",
    title: "English in Daily Life",
    studyMaterial: [],
  },
  {
    code: "BSW 121",
    title: "Professional Social Work and its Values",
    studyMaterial: [],
  },
  {
    code: "BSWL 104",
    title: "Social Work Practicum – IV",
    studyMaterial: [],
  },
  {
    code: "BSW 122",
    title: "Society, Social Institutions and Social Problems",
    studyMaterial: [],
  },
  {
    code: "BSW 123",
    title: "Community Organisation and Communication",
    studyMaterial: [],
  },
  {
    code: "BSWL 105",
    title: "Social Work Practicum – V",
    studyMaterial: [],
  },
  {
    code: "BSW 124",
    title: "Human Growth, Behaviour and Counselling",
    studyMaterial: [],
  },
  {
    code: "BSW 125",
    title: "Social Case Work and Social Group Work",
    studyMaterial: [],
  },
  {
    code: "BSWL 106",
    title: "Social Work Practicum – VI",
    studyMaterial: [],
  },
  {
    code: "BSW 126",
    title: "Social Work in Family Setting",
    studyMaterial: [],
  },
  {
    code: "BSW 127",
    title: "Public Health and HIV/AIDS",
    studyMaterial: [],
  },
  {
    code: "BSWL 107",
    title: "Social Work Practicum – VII",
    studyMaterial: [],
  },
  {
    code: "BSW 128",
    title: "Social Policy and Social Development",
    studyMaterial: [],
  },
  {
    code: "BSW 129",
    title: "Research Methods in Social Work",
    studyMaterial: [],
  },
  {
    code: "BSWL 108",
    title: "Social Work Practicum – VIII",
    studyMaterial: [],
  },
  {
    code: "BSW 130",
    title: "Prevention of Substance Abuse",
    studyMaterial: [],
  },
  {
    code: "BSW 131",
    title: "Social Welfare Administration and Social Action",
    studyMaterial: [],
  },
  {
    code: "BSWL 109",
    title: "Social Work Practicum – IX",
    studyMaterial: [],
  },
  // BBARL, Bachelor of Business Administration (Retailing)
  {
    code: "BRL 1",
    title: "Overview of Retailing",
    studyMaterial: [],
  },
  {
    code: "BRL 2",
    title: "Retail Marketing and Communication",
    studyMaterial: [],
  },
  {
    code: "BRL 3",
    title: "Retail Management Perspectives and Communication",
    studyMaterial: [],
  },
  {
    code: "BRL 4",
    title: "Customer Service Management",
    studyMaterial: [],
  },
  {
    code: "BRLT 5",
    title: "Internship and Viva-Voce",
    studyMaterial: [],
  },
  {
    code: "BRL 6",
    title: "Buying and Merchandising-I",
    studyMaterial: [],
  },
  {
    code: "BRL 7",
    title: "Store Operations-I",
    studyMaterial: [],
  },
  { code: "BRL 8", title: "Human Resources", studyMaterial: [] },
  {
    code: "ECO 1",
    title: "Business Organisation",
    studyMaterial: [],
  },
  {
    code: "BCOA 1",
    title: "Business Communication and Enterpreneurship",
    studyMaterial: [],
  },
  { code: "AMK 1", title: "Marketing", studyMaterial: [] },
  {
    code: "BRLT 9",
    title: "On the Job Training and Viva-Voce",
    studyMaterial: [],
  },
  {
    code: "BRL 10",
    title: "Buying and Merchandising-II",
    studyMaterial: [],
  },
  {
    code: "BRL 11",
    title: "Retail Operations and Store Management-II",
    studyMaterial: [],
  },
  {
    code: "BRL 12",
    title: "Visual Merchandising and Store Management",
    studyMaterial: [],
  },
  {
    code: "BRL 13",
    title: "Customer Value Management",
    studyMaterial: [],
  },
  {
    code: "BRL 15",
    title: "IT Application in Retail",
    studyMaterial: [],
  },
  { code: "BRLT 16", title: "Marketing", studyMaterial: [] },
  // BAVTM, Bachelor of Arts (Vocational Studies) Tourism Management
  {
    code: "BTMC-131",
    title: "History of Tourism – I",
    studyMaterial: [],
  },
  {
    code: "BTMC-132",
    title: "Fundamentals of Management",
    studyMaterial: [],
  },
  {
    code: "BTMC-133",
    title: "History of Tourism – II",
    studyMaterial: [],
  },
  {
    code: "BTMC-134",
    title: "Entrepreneurship and Small Business",
    studyMaterial: [],
  },
  {
    code: "BTMC-135",
    title: "Concept and Impacts of Tourism",
    studyMaterial: [],
  },
  {
    code: "BTMC-136",
    title: "Tourism Marketing",
    studyMaterial: [],
  },
  {
    code: "BTMC-137",
    title: "Profile of Modern Tourism",
    studyMaterial: [],
  },
  {
    code: "BTMC-138",
    title: "Managerial Accounting and Finance in Tourism",
    studyMaterial: [],
  },
  {
    code: "BTME-141",
    title: "Tourism Undertaking",
    studyMaterial: [],
  },
  { code: "BTMP-142", title: "Project", studyMaterial: [] },
  {
    code: "BTME-143",
    title: "Procedure and Operations in the Tourism Business",
    studyMaterial: [],
  },
  { code: "BTME-144", title: "Globalization", studyMaterial: [] },
  {
    code: "BCOS-183",
    title: "Computer Applications in Business",
    studyMaterial: [],
  },
  { code: "BCOS-184", title: "E-Commerce", studyMaterial: [] },
  {
    code: "BTMS-185",
    title: "Airport Handling",
    studyMaterial: [],
  },
  {
    code: "BEGS-186",
    title: "Business Communication",
    studyMaterial: [],
  },
  {
    code: "BTMG-171",
    title: "Culture in Indian Subcontinent I",
    studyMaterial: [],
  },
  {
    code: "BTMG-172",
    title: "Culture in Indian Subcontinent II",
    studyMaterial: [],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और सम्प्रेषण",
    studyMaterial: [],
  },
  {
    code: "BEGLA -135",
    title: "English In Daily Life",
    studyMaterial: [],
  },
  {
    code: "BEGLA -136",
    title: "English At The WorkPlace",
    studyMaterial: [],
  },
  {
    code: "BEGLA -137",
    title: "Language Through Literature",
    studyMaterial: [],
  },
  {
    code: "BEGLA -138",
    title: "Reading and Speaking Skills",
    studyMaterial: [],
  },
  {
    code: "BHDLA 135",
    title: "�हंद� भाषा: �व�वध प्रयोग",
    studyMaterial: [],
  },
  {
    code: "BHDLA 136",
    title: "�हंद� भाषा: लेखन कौशल",
    studyMaterial: [],
  },
  {
    code: "BHDLA 137",
    title: "�हंद� भाषा: सम्प्रेषण कौशल",
    studyMaterial: [],
  },
  {
    code: "BHDLA 138",
    title: "�हंद� भाषा: �व�वध �वधाएँ",
    studyMaterial: [],
  },
  { code: "BUDLA 135", title: "Urdu", studyMaterial: [] },
  { code: "BSKLA 135", title: "Sanskrit", studyMaterial: [] },
  // Bachelor of Arts (Honours) Degree Programmes
  {
    code: "BECC-101",
    title: "Introductory Microeconomics",
    studyMaterial: [],
  },
  {
    code: "BECC-102",
    title: "Mathematical Methods for Economics I",
    studyMaterial: [],
  },
  {
    code: "BECC 103",
    title: "Introductory Macroeconomics",
    studyMaterial: [],
  },
  {
    code: "BECC 104",
    title: "Mathematical Methods for Economics II",
    studyMaterial: [],
  },
  {
    code: "BECC 105",
    title: "Intermediate Microeconomics I",
    studyMaterial: [],
  },
  {
    code: "BECC 106",
    title: "Intermediate Macroeconomics I",
    studyMaterial: [],
  },
  {
    code: "BECC 107",
    title: "Statistical Methods for Economics",
    studyMaterial: [],
  },
  {
    code: "BECC 108",
    title: "Intermediate Microeconomics II",
    studyMaterial: [],
  },
  {
    code: "BECC 109",
    title: "Intermediate Macroeconomics II",
    studyMaterial: [],
  },
  {
    code: "BECC 110",
    title: "Introductory Econometrics",
    studyMaterial: [],
  },
  {
    code: "BECC 111",
    title: "Indian Economy I",
    studyMaterial: [],
  },
  {
    code: "BECC 112",
    title: "Development Economics I",
    studyMaterial: [],
  },
  {
    code: "BECC 113",
    title: "Indian Economy II",
    studyMaterial: [],
  },
  {
    code: "BECC 114",
    title: "Development Economics II",
    studyMaterial: [],
  },
  {
    code: "BHIC 101",
    title: "History of India –I",
    studyMaterial: [],
  },
  {
    code: "BHIC 102",
    title: "Social Formations and Cultural Patterns of the Ancient World",
    studyMaterial: [],
  },
  {
    code: "BHIC 103",
    title: "History of India –II",
    studyMaterial: [],
  },
  {
    code: "BHIC 104",
    title: "Social Formations and Cultural Patterns of the Medieval World",
    studyMaterial: [],
  },
  {
    code: "BHIC 105",
    title: "History of India –III ( c. 750 – 1206)",
    studyMaterial: [],
  },
  {
    code: "BHIC 106",
    title: "Rise of the Modern West – I",
    studyMaterial: [],
  },
  {
    code: "BHIC 107",
    title: "History of India – IV ( c. 1206 – 1550)",
    studyMaterial: [],
  },
  {
    code: "BHIC 108",
    title: "Rise of the Modern West – II",
    studyMaterial: [],
  },
  {
    code: "BHIC 109",
    title: "History of India –V ( c. 1550 – 1605)",
    studyMaterial: [],
  },
  {
    code: "BHIC 110",
    title: "History of India –VI ( c. 1750 – 1857)",
    studyMaterial: [],
  },
  {
    code: "BHIC 111",
    title: "History of Modern Europe - I ( c. 1780 - 1939)",
    studyMaterial: [],
  },
  {
    code: "BHIC 112",
    title: "History of India –VII ( c. 1605 – 1750)",
    studyMaterial: [],
  },
  {
    code: "BHIC 113",
    title: "History of India –VIII ( c. 1857 – 1950)",
    studyMaterial: [],
  },
  {
    code: "BHIC 114",
    title: "History of Modern Europe -II ( c. 1780 – 1939)",
    studyMaterial: [],
  },
  {
    code: "BPAC 101",
    title: "Perspectives on Public Administration",
    studyMaterial: [],
  },
  {
    code: "BPAC 108",
    title: "Public Policy and Administration in India",
    studyMaterial: [],
  },
  {
    code: "BPSC 101",
    title: "Understanding Political Theory",
    studyMaterial: [],
  },
  {
    code: "BPSC 102",
    title: "Constitutional Government and Democracy in India",
    studyMaterial: [],
  },
  {
    code: "BPSC 103",
    title: "Political Theory – Concepts and Debates",
    studyMaterial: [],
  },
  {
    code: "BPSC 104",
    title: "Political Process in India",
    studyMaterial: [],
  },
  {
    code: "BPSC 105",
    title: "Introduction to Comparative Government and Politics",
    studyMaterial: [],
  },
  {
    code: "BPSC 107",
    title: "Perspectives on International Relations and World History",
    studyMaterial: [],
  },
  {
    code: "BPSC 109",
    title: "Political Processes and Institutions in Comparative Perspective",
    studyMaterial: [],
  },
  {
    code: "BPSC 110",
    title: "Global Politics",
    studyMaterial: [],
  },
  {
    code: "BPSC 111",
    title: "Classical Political Philosophy",
    studyMaterial: [],
  },
  {
    code: "BPSC 112",
    title: "Indian Political Thought-I",
    studyMaterial: [],
  },
  {
    code: "BPSC 113",
    title: "Modern Political Philosophy",
    studyMaterial: [],
  },
  {
    code: "BPSC 114",
    title: "Indian Political Thought-II",
    studyMaterial: [],
  },
  {
    code: "BPCC 101",
    title: "Introduction to Psychology",
    studyMaterial: [],
  },
  { code: "BPCC 102", title: "Biopsychology", studyMaterial: [] },
  {
    code: "BPCC 103",
    title: "Psychology of Individual Differences",
    studyMaterial: [],
  },
  {
    code: "BPCC 104",
    title: "Statistical Methods for Psychological Research- I",
    studyMaterial: [],
  },
  {
    code: "BPCC 105",
    title: "Psychological Research",
    studyMaterial: [],
  },
  {
    code: "BPCC 106",
    title: "Development of Psychological Thought",
    studyMaterial: [],
  },
  {
    code: "BPCC 107",
    title: "Social Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCC 108",
    title: "Statistical Methods for Psychological Research - II",
    studyMaterial: [],
  },
  {
    code: "BPCC 109",
    title: "Developmental Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCC 110",
    title: "Applied Social Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCC 111",
    title: "Understanding Psychological Disorders",
    studyMaterial: [],
  },
  {
    code: "BPCC 112",
    title: "Organizational Behaviour",
    studyMaterial: [],
  },
  {
    code: "BPCC 113",
    title: "Understanding and Dealing with Psychological Disorders",
    studyMaterial: [],
  },
  {
    code: "BPCC 114",
    title: "Counselling Psychology",
    studyMaterial: [],
  },
  {
    code: "BPAC 101",
    title: "Perspectives on Public Administration",
    studyMaterial: [],
  },
  {
    code: "BPAC 102",
    title: "Administrative Thinkers",
    studyMaterial: [],
  },
  {
    code: "BPAC 103",
    title: "Administrative System at Union Level",
    studyMaterial: [],
  },
  {
    code: "BPAC 104",
    title: "Administrative System at State and District Levels",
    studyMaterial: [],
  },
  {
    code: "BPAC 105",
    title: "Personnel Administration",
    studyMaterial: [],
  },
  {
    code: "BPAC 106",
    title: "Understanding Public Policy",
    studyMaterial: [],
  },
  {
    code: "BPAC 107",
    title: "Comparative Public Administration",
    studyMaterial: [],
  },
  {
    code: "BPAC 108",
    title: "Public Policy and Administration in India",
    studyMaterial: [],
  },
  {
    code: "BPAC 109",
    title: "Public Systems Management",
    studyMaterial: [],
  },
  {
    code: "BPAC 110",
    title: "Urban Local Governance",
    studyMaterial: [],
  },
  {
    code: "BPAC 111",
    title: "Public Finance and Administration",
    studyMaterial: [],
  },
  {
    code: "BPAC 112",
    title: "Rural Local Governance",
    studyMaterial: [],
  },
  {
    code: "BPAC 113",
    title: "Development Administration",
    studyMaterial: [],
  },
  {
    code: "BPAC 114",
    title: "Contemporary Issues and Concerns in Indian Administration",
    studyMaterial: [],
  },
  {
    code: "BSOC 101",
    title: "Introduction to Sociology I",
    studyMaterial: [],
  },
  {
    code: "BSOC 102",
    title: "Sociology of India – I",
    studyMaterial: [],
  },
  {
    code: "BSOC 103",
    title: "Introduction to Sociology II",
    studyMaterial: [],
  },
  {
    code: "BSOC 104",
    title: "Sociology of India - II",
    studyMaterial: [],
  },
  {
    code: "BSOC 105",
    title: "Political Sociology",
    studyMaterial: [],
  },
  {
    code: "BSOC 106",
    title: "Sociology of Religion",
    studyMaterial: [],
  },
  {
    code: "BSOC 107",
    title: "Sociology of Gender",
    studyMaterial: [],
  },
  {
    code: "BSOC 108",
    title: "Economic Sociology",
    studyMaterial: [],
  },
  {
    code: "BSOC 109",
    title: "Sociology of Kinship",
    studyMaterial: [],
  },
  {
    code: "BSOC 110",
    title: "Social Stratification",
    studyMaterial: [],
  },
  {
    code: "BSOC 111",
    title: "Sociological Thinkers -I",
    studyMaterial: [],
  },
  {
    code: "BSOC 112",
    title: "Sociological Research Methods -I",
    studyMaterial: [],
  },
  {
    code: "BSOC 113",
    title: "Sociological Thinkers -II",
    studyMaterial: [],
  },
  {
    code: "BSOC 114",
    title: "Sociological Research Methods -II",
    studyMaterial: [],
  },
  {
    code: "BECE 141",
    title: "Economics of Health and Education",
    studyMaterial: [],
  },
  {
    code: "BECE 142",
    title: "Applied Econometrics",
    studyMaterial: [],
  },
  {
    code: "BECE 143",
    title: "Environmental Economics",
    studyMaterial: [],
  },
  {
    code: "BECE 144",
    title: "Financial Economics",
    studyMaterial: [],
  },
  {
    code: "BHIE 141",
    title: "History of China (C. 1840 – 1978)",
    studyMaterial: [],
  },
  {
    code: "BHIE 142",
    title: "History of Modern East Asia: Japan (C. 1868 – 1945)",
    studyMaterial: [],
  },
  {
    code: "BHIE 143",
    title: "History of Environment",
    studyMaterial: [],
  },
  {
    code: "BHIE 144",
    title: "Traditions of History Writing in India",
    studyMaterial: [],
  },
  {
    code: "BPSE 141",
    title: "Gandhi and the Contemporary World",
    studyMaterial: [],
  },
  {
    code: "BPSE-142",
    title: "India’s Foreign Policy in a Globalising World",
    studyMaterial: [],
  },
  {
    code: "BPSE 143",
    title: "State Politics in India",
    studyMaterial: [],
  },
  {
    code: "BPSE 144",
    title: "Introduction to South Asia",
    studyMaterial: [],
  },
  {
    code: "BPSE 145",
    title: "Democracy and Development in Northeast India",
    studyMaterial: [],
  },
  {
    code: "BPSE 146",
    title: "Conflict Resolution and Peace Building",
    studyMaterial: [],
  },
  {
    code: "BPAE 141",
    title: "Right to Information",
    studyMaterial: [],
  },
  {
    code: "BPAE-142",
    title: "Organizational Behaviour",
    studyMaterial: [],
  },
  {
    code: "BPAE 143",
    title: "Administrative System in BRICS",
    studyMaterial: [],
  },
  {
    code: "BPAE 144",
    title: "Social Policies and Administration",
    studyMaterial: [],
  },
  {
    code: "BPCE 141",
    title: "Positive Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCE 142",
    title: "Forensic Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCE 143",
    title: "Environmental Psychology",
    studyMaterial: [],
  },
  { code: "BPCE 144", title: "Dissertation", studyMaterial: [] },
  {
    code: "BSOE 141",
    title: "Urban Sociology",
    studyMaterial: [],
  },
  {
    code: "BSOE 142",
    title: "Indian Sociological Traditions",
    studyMaterial: [],
  },
  {
    code: "BSOE 143",
    title: "Environmental Sociology",
    studyMaterial: [],
  },
  {
    code: "BSOE 144",
    title: "Reading Ethnographies",
    studyMaterial: [],
  },
  {
    code: "BANE 143",
    title: "Tribal Cultures of India",
    studyMaterial: [],
  },
  {
    code: "BANE 144",
    title: "Visual Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANS 184",
    title: "Public Health and Epidemiology",
    studyMaterial: [],
  },
  { code: "BECS 184", title: "Data Analysis", studyMaterial: [] },
  {
    code: "BPCS 183",
    title: "Emotional Intelligence",
    studyMaterial: [],
  },
  {
    code: "BPCS 184",
    title: "School Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCS 185",
    title: "Developing Emotional Competence",
    studyMaterial: [],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: [],
  },
  {
    code: "BPCS 187",
    title: "Managing Human Resources",
    studyMaterial: [],
  },
  {
    code: "BPCS 188",
    title: "Application of Social Psychology",
    studyMaterial: [],
  },
  {
    code: "BPAS 184",
    title: "Logistics Management",
    studyMaterial: [],
  },
  {
    code: "BPAS 186",
    title: "Stress and Time Management",
    studyMaterial: [],
  },
  {
    code: "BSOS 184",
    title: "Techniques of Ethnographic Film Making",
    studyMaterial: [],
  },
  {
    code: "BSOS 185",
    title: "Society through the Visual",
    studyMaterial: [],
  },
  {
    code: "BHDS 183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    studyMaterial: [],
  },
  { code: "BHDS 184", title: "रे �डयो लेखन", studyMaterial: [] },
  {
    code: "BEGS 183",
    title: "Writing And Study Skills",
    studyMaterial: [],
  },
  {
    code: "BEGS 185",
    title: "English Language Teaching",
    studyMaterial: [],
  },
  {
    code: "BEGS 186",
    title: "Business Communication",
    studyMaterial: [],
  },
  {
    code: "BGDG 172",
    title: "Gender Sensitization: Society and Culture",
    studyMaterial: [],
  },
  {
    code: "BPCG 171",
    title: "General Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCG 172",
    title: "Youth, Gender and Identity",
    studyMaterial: [],
  },
  {
    code: "BPCG 173",
    title: "Psychology for Health and Well-being",
    studyMaterial: [],
  },
  {
    code: "BPCG 174",
    title: "Psychology and Media",
    studyMaterial: [],
  },
  {
    code: "BPCG 175",
    title: "Psychology for Living",
    studyMaterial: [],
  },
  {
    code: "BPCG 176",
    title: "Psychology of Gender",
    studyMaterial: [],
  },
  {
    code: "BPAG 171",
    title: "Disaster Management",
    studyMaterial: [],
  },
  {
    code: "BPAG 172",
    title: "Governance: Issues and Challenges",
    studyMaterial: [],
  },
  { code: "BPAG 173", title: "E-Governance", studyMaterial: [] },
  {
    code: "BPAG 174",
    title: "Sustainable Development",
    studyMaterial: [],
  },
  {
    code: "BSOG 171",
    title: "Indian Society: Images and Realities",
    studyMaterial: [],
  },
  {
    code: "BSOG 173",
    title: "Rethinking Development",
    studyMaterial: [],
  },
  {
    code: "BSOG 176",
    title: "Economy and Society",
    studyMaterial: [],
  },
  {
    code: "BHDG 173",
    title: "समाचार पत्र और फ�चर लेखन",
    studyMaterial: [],
  },
  {
    code: "BEGG 171",
    title: "Media and Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BEGG 172",
    title: "Language and Linguistics",
    studyMaterial: [],
  },
  {
    code: "BEGG 173",
    title: "Academic Writing & Composition",
    studyMaterial: [],
  },
  {
    code: "BEGG 174",
    title: "Creative Writing",
    studyMaterial: [],
  },
  {
    code: "BABG 171",
    title: "Understanding Ambedkar",
    studyMaterial: [],
  },
  {
    code: "BPYG 171",
    title: "Applied Ethics",
    studyMaterial: [],
  },
  {
    code: "BPYG 172",
    title: "Philosophy of Religion",
    studyMaterial: [],
  },
  {
    code: "BANC 101",
    title: "Introduction to Biological Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANC 102",
    title: "Introduction to Social and Cultural Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANC 103",
    title: "Archaeological Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANC 104",
    title: "Fundamentals of Human Origin and Evolution",
    studyMaterial: [],
  },
  {
    code: "BANC 105",
    title: "Tribes and Peasants in India",
    studyMaterial: [],
  },
  {
    code: "BANC 106",
    title: "Human Ecology: Biological and Cultural Dimensions",
    studyMaterial: [],
  },
  {
    code: "BANC 107",
    title: "Biological Diversity in Human Populations",
    studyMaterial: [],
  },
  {
    code: "BANC 108",
    title: "Theories of Culture and Society",
    studyMaterial: [],
  },
  {
    code: "BANC 109",
    title: "Human Growth and Development",
    studyMaterial: [],
  },
  {
    code: "BANC 110",
    title: "Research Methods",
    studyMaterial: [],
  },
  {
    code: "BANC 111",
    title: "Human Population Genetics",
    studyMaterial: [],
  },
  {
    code: "BANC 112",
    title: "Anthropology in Practice",
    studyMaterial: [],
  },
  {
    code: "BANC 113",
    title: "Forensic Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANC 114",
    title: "Anthropology of India",
    studyMaterial: [],
  },
  {
    code: "BANE 141",
    title: "Physiological Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANE 143",
    title: "Tribal Cultures of India",
    studyMaterial: [],
  },
  {
    code: "BANE 144",
    title: "Visual Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANE 147",
    title: "Urban Anthropology",
    studyMaterial: [],
  },
  { code: "BANE 154", title: "Dissertation", studyMaterial: [] },
  {
    code: "BSOE 144",
    title: "Reading Ethnographies",
    studyMaterial: [],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: [],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: [],
  },
  {
    code: "BANS 184",
    title: "Public Health and Epidemiology",
    studyMaterial: [],
  },
  { code: "BECS 184", title: "Data Analysis", studyMaterial: [] },
  {
    code: "BPCS 183",
    title: "Emotional Intelligence",
    studyMaterial: [],
  },
  {
    code: "BPCS 184",
    title: "School Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCS 185",
    title: "Developing Emotional Competence",
    studyMaterial: [],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: [],
  },
  {
    code: "BPCS 187",
    title: "Managing Human Resources",
    studyMaterial: [],
  },
  {
    code: "BPCS 188",
    title: "Application of Social Psychology",
    studyMaterial: [],
  },
  {
    code: "BPAS 184",
    title: "Logistics Management",
    studyMaterial: [],
  },
  {
    code: "BPAS 186",
    title: "Stress and Time Management",
    studyMaterial: [],
  },
  {
    code: "BSOS 184",
    title: "Techniques of Ethnographic Film Making",
    studyMaterial: [],
  },
  {
    code: "BSOS 185",
    title: "Society through the Visual",
    studyMaterial: [],
  },
  {
    code: "BHDS 183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    studyMaterial: [],
  },
  { code: "BHDS 184", title: "रे �डयो लेखन", studyMaterial: [] },
  {
    code: "BEGS 183",
    title: "Writing And Study Skills",
    studyMaterial: [],
  },
  {
    code: "BEGS 185",
    title: "English Language Teaching",
    studyMaterial: [],
  },
  {
    code: "BEGS 186",
    title: "Business Communication",
    studyMaterial: [],
  },
  {
    code: "BGDG 172",
    title: "Gender Sensitization: Society and Culture",
    studyMaterial: [],
  },
  {
    code: "BPCG 171",
    title: "General Psychology",
    studyMaterial: [],
  },
  {
    code: "BPCG 172",
    title: "Youth, Gender and Identity",
    studyMaterial: [],
  },
  {
    code: "BPCG 173",
    title: "Psychology for Health and Well-being",
    studyMaterial: [],
  },
  {
    code: "BPCG 174",
    title: "Psychology and Media",
    studyMaterial: [],
  },
  {
    code: "BPCG 175",
    title: "Psychology for Living",
    studyMaterial: [],
  },
  {
    code: "BPCG 176",
    title: "Psychology of Gender",
    studyMaterial: [],
  },
  {
    code: "BPAG 171",
    title: "Disaster Management",
    studyMaterial: [],
  },
  {
    code: "BPAG 172",
    title: "Governance: Issues and Challenges",
    studyMaterial: [],
  },
  { code: "BPAG 173", title: "E-Governance", studyMaterial: [] },
  {
    code: "BPAG 174",
    title: "Sustainable Development",
    studyMaterial: [],
  },
  {
    code: "BSOG 171",
    title: "Indian Society: Images and Realities",
    studyMaterial: [],
  },
  {
    code: "BSOG 173",
    title: "Rethinking Development",
    studyMaterial: [],
  },
  {
    code: "BSOG 176",
    title: "Economy and Society",
    studyMaterial: [],
  },
  {
    code: "BHDG 173",
    title: "समाचार पत्र और फ�चर लेखन",
    studyMaterial: [],
  },
  {
    code: "BEGG 171",
    title: "Media and Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BEGG 172",
    title: "Language and Linguistics",
    studyMaterial: [],
  },
  {
    code: "BEGG 173",
    title: "Academic Writing & Composition",
    studyMaterial: [],
  },
  {
    code: "BEGG 174",
    title: "Creative Writing",
    studyMaterial: [],
  },
  {
    code: "BABG 171",
    title: "Understanding Ambedkar",
    studyMaterial: [],
  },
  {
    code: "BPYG 171",
    title: "Applied Ethics",
    studyMaterial: [],
  },
  {
    code: "BPYG 172",
    title: "Philosophy of Religion",
    studyMaterial: [],
  },
  {
    code: "BBCCT-101",
    title: "Molecules of Life",
    studyMaterial: [],
  },
  {
    code: "BBCCL-102",
    title: "Molecules of Life: Laboratory",
    studyMaterial: [],
  },
  { code: "BBCCT-103", title: "Cell Biology", studyMaterial: [] },
  {
    code: "BBCCL-104",
    title: "Cell Biology: Laboratory",
    studyMaterial: [],
  },
  { code: "BBCCT-105", title: "Proteins", studyMaterial: [] },
  {
    code: "BBCCL-106",
    title: "Proteins: Laboratory",
    studyMaterial: [],
  },
  { code: "BBCCT-107", title: "Enzymes", studyMaterial: [] },
  {
    code: "BBCCL-108",
    title: "Enzymes: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-109",
    title: "Metabolism of Carbohydrates and Lipids",
    studyMaterial: [],
  },
  {
    code: "BBCCL-110",
    title: "Metabolism of Carbohydrates and Lipids",
    studyMaterial: [],
  },
  {
    code: "BBCCT-111",
    title: "Membrane Biology and Bioenergetics",
    studyMaterial: [],
  },
  {
    code: "BBCCL-112",
    title: "Membrane Biology And Bioenergetics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-113",
    title: "Metabolism of Amino Acids and Nucleotides",
    studyMaterial: [],
  },
  {
    code: "BBCCL-114",
    title: "Metabolism of Amino Acids and Nucleotides: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-115",
    title: "Human Physiology",
    studyMaterial: [],
  },
  {
    code: "BBCCL-116",
    title: "Human Physiology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-117",
    title: "Gene Organization Replication and Repair",
    studyMaterial: [],
  },
  {
    code: "BBCCL-118",
    title: "Gene Organization Replication and Repair: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-119",
    title: "Hormone: Biochemistry and Function",
    studyMaterial: [],
  },
  {
    code: "BBCCL-120",
    title: "Hormone: Biochemistry and Function: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-121",
    title: "Concepts in Genetics",
    studyMaterial: [],
  },
  {
    code: "BBCCL-122",
    title: "Concepts in Genetics: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-123",
    title: "Gene Expression and Regulation",
    studyMaterial: [],
  },
  {
    code: "BBCCL-124",
    title: "Gene Expression and Regulation: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCCT-125",
    title: "Genetic Engineering and Biotechnology",
    studyMaterial: [],
  },
  {
    code: "BBCCT-126",
    title: "Genetic Engineering and Biotechnology: Laboratory",
    studyMaterial: [],
  },
  { code: "BBCCT-127", title: "Immunology", studyMaterial: [] },
  {
    code: "BBCCL-128",
    title: "Immunology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCET-141",
    title: "Nutritional Biochemistry",
    studyMaterial: [],
  },
  {
    code: "BBCEL-142",
    title: "Nutritional Biochemistry: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCET-143",
    title: "Basic Microbiology",
    studyMaterial: [],
  },
  {
    code: "BBCEL-144",
    title: "Basic Microbiology: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCET-145",
    title: "Molecular basis of non-infectious human diseases",
    studyMaterial: [],
  },
  {
    code: "BBCEL-146",
    title: "Molecular basis of non-infectious human diseases: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBCET-151",
    title: "Plant Biochemistry",
    studyMaterial: [],
  },
  {
    code: "BBCEL-152",
    title: "Plant Biochemistry: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: [],
  },
  {
    code: "BBCS-183",
    title: "Tools & Techniques in Biochemistry",
    studyMaterial: [],
  },
  {
    code: "BBCS-185",
    title: "Bioinformatics",
    studyMaterial: [],
  },
  {
    code: "BCHCT 131",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons",
    studyMaterial: [],
  },
  {
    code: "BCHCL-132",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BCHCT 133",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry I",
    studyMaterial: [],
  },
  {
    code: "BCHCL 134",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry I: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BBYCT 131",
    title: "Biodiversity (Microbes, Algae, Fungi and Archegoniates)",
    studyMaterial: [],
  },
  {
    code: "BBYCL 132",
    title:
      "Biodiversity (Microbes, Algae, Fungi and Archegoniates): Laboratory",
    studyMaterial: [],
  },
  {
    code: "BZYCT 131",
    title: "Animal Diversity",
    studyMaterial: [],
  },
  {
    code: "BZYCL 132",
    title: "Animal Diversity: Laboratory",
    studyMaterial: [],
  },
  {
    code: "BEGC 101",
    title: "Indian Classical Literature",
    studyMaterial: [],
  },
  {
    code: "BEGC 102",
    title: "European Classical Literature",
    studyMaterial: [],
  },
  {
    code: "BEGC 103",
    title: "Indian Writing in English",
    studyMaterial: [],
  },
  {
    code: "BEGC 104",
    title: "British Poetry and Drama: 14th- 17th Centuries",
    studyMaterial: [],
  },
  {
    code: "BEGC 105",
    title: "American Literature",
    studyMaterial: [],
  },
  {
    code: "BEGC 106",
    title: "Popular Literature",
    studyMaterial: [],
  },
  {
    code: "BEGC 107",
    title: "British Poetry and Drama: 17th & 18th Centuries",
    studyMaterial: [],
  },
  {
    code: "BEGC 108",
    title: "British Literature: 18th Century",
    studyMaterial: [],
  },
  {
    code: "BEGC 109",
    title: "British Romantic Literature",
    studyMaterial: [],
  },
  {
    code: "BEGC 110",
    title: "British Literature: 19th Century",
    studyMaterial: [],
  },
  {
    code: "BEGC 111",
    title: "Women's Writing",
    studyMaterial: [],
  },
  {
    code: "BEGC 112",
    title: "British Literature: The Early 20th Century",
    studyMaterial: [],
  },
  {
    code: "BEGC 113",
    title: "Modern European Drama",
    studyMaterial: [],
  },
  {
    code: "BEGC 114",
    title: "Postcolonial Literatures",
    studyMaterial: [],
  },
  {
    code: "BEGE 141",
    title: "Understanding Prose",
    studyMaterial: [],
  },
  {
    code: "BEGE 143",
    title: "Understanding Poetry",
    studyMaterial: [],
  },
  {
    code: "BEGE 142",
    title: "Understanding Drama",
    studyMaterial: [],
  },
  {
    code: "BEGE 144",
    title: "Understanding The Novel",
    studyMaterial: [],
  },
  {
    code: "BEVAE 181",
    title: "Envirnoment Studies",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: [],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: [],
  },
  {
    code: "BEGS 183",
    title: "Writing and Study Skills",
    studyMaterial: [],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: [],
  },
  {
    code: "BSOG 171",
    title: "Indian Society: Images and Realities",
    studyMaterial: [],
  },
  {
    code: "BGDG 172",
    title: "Gender Sensitisation, Society & culture",
    studyMaterial: [],
  },
  {
    code: "BSOG 173",
    title: "Rethinking Development",
    studyMaterial: [],
  },
  {
    code: "BHDG 173",
    title: "समाचार पत्र और फ�चर लेखन",
    studyMaterial: [],
  },
  {
    code: "BPCG 174",
    title: "Psychology and Media",
    studyMaterial: [],
  },
  {
    code: "BHMCT 101",
    title: "Introduction to Hindustani Music and its Fundamentals",
    studyMaterial: [],
  },
  {
    code: "BHMCL 102",
    title: "Hindustani Music Vocal Practicum - 1",
    studyMaterial: [],
  },
  {
    code: "BHMCT 103",
    title: "Fundamentals of Hindustani Music",
    studyMaterial: [],
  },
  {
    code: "BHMCL 104",
    title: "Hindustani Music Vocal Practicum - 2",
    studyMaterial: [],
  },
  {
    code: "BHMCT 105",
    title: "Study of Forms, Instruments and Traditions of Hindustani Music",
    studyMaterial: [],
  },
  {
    code: "BHMCl 106",
    title: "Hindustani Music Vocal Practicum – 3",
    studyMaterial: [],
  },
  {
    code: "BHMCL 107",
    title: "Hindustani Music Vocal Practicum – 4",
    studyMaterial: [],
  },
  {
    code: "BHMCT 108",
    title: "Study of Treatises, Gharanas, Elementary Karnatak Music",
    studyMaterial: [],
  },
  { code: "BHMCP 109", title: "Dissertation", studyMaterial: [] },
  {
    code: "BHMCL 110",
    title: "Hindustani Music Vocal Practicum – 5",
    studyMaterial: [],
  },
  {
    code: "BHMCT 111",
    title: "Study of Modern Works, Gharanas, Biographies and Other Genres",
    studyMaterial: [],
  },
  {
    code: "BHMCL 112",
    title: "Hindustani Music Vocal Practicum – 6",
    studyMaterial: [],
  },
  {
    code: "BHMCT 113",
    title:
      "Study of Gharanas, Elementary Western Music, and Interdisciplinary study of Music",
    studyMaterial: [],
  },
  {
    code: "BHMCL 114",
    title: "Hindustani Music Vocal Practicum – 7",
    studyMaterial: [],
  },
  {
    code: "BPFT 141",
    title: "Study of Natyashastra",
    studyMaterial: [],
  },
  {
    code: "BPFT 142",
    title: "Arts and Aesthetics: Indian & Western Concepts",
    studyMaterial: [],
  },
  {
    code: "BFPT 143",
    title: "Pedagogy of Performing Arts",
    studyMaterial: [],
  },
  {
    code: "BFPT 144",
    title: "Integrated Performance project (Practical)",
    studyMaterial: [],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: [],
  },
  {
    code: "BEGAE 182",
    title: "Communication Skills in English Language",
    studyMaterial: [],
  },
  {
    code: "BHDAE 182",
    title: "Hindi Bhasha aur Sampreshan",
    studyMaterial: [],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: [],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: [],
  },
  {
    code: "BSOG 171",
    title: "Indian Society: Images and Reality",
    studyMaterial: [],
  },
  {
    code: "BGDG 172",
    title: "Gender Sensibility",
    studyMaterial: [],
  },
  {
    code: "BSOG 173",
    title: "Rethinking Development",
    studyMaterial: [],
  },
  {
    code: "BPCG 174",
    title: "Psychology and Media",
    studyMaterial: [],
  },
  // MCOM, Master of Commerce
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
];
