export const courses = [
  { code: "MS-43", title: "Management Control Systems", school: "SOMS" },
  { code: "MS-44", title: "Security Analysis and", school: "SOMS" },
  {
    code: "MS-1",
    title: "Management Functions Portfolio Management",
    school: "SOMS",
  },
  { code: "MS-45", title: "International Financial", school: "SOMS" },
  { code: "MS-2", title: "Management of Human Management", school: "SOMS" },
  { code: "MS-46", title: "Management of", school: "SOMS" },
  {
    code: "MS-3",
    title: "Economic and Social Financial Services",
    school: "SOMS",
  },
  { code: "MS-51", title: "Operations Research", school: "SOMS" },
  {
    code: "MS-4",
    title: "Accounting and Finance for Managers",
    school: "SOMS",
  },
  { code: "MS-52", title: "Project Management", school: "SOMS" },
  { code: "MS-5", title: "Management of Machines", school: "SOMS" },
  { code: "MS-53", title: "Production", school: "SOMS" },
  { code: "MS-6", title: "Marketing for Managers", school: "SOMS" },
  { code: "MS-54", title: "Management of Information Systems", school: "SOMS" },
  { code: "MS-7", title: "Information Systems for Managers", school: "SOMS" },
  {
    code: "MS-55",
    title: "Logistics and Supply Chain Management",
    school: "SOMS",
  },
  {
    code: "MS-8",
    title: "QuantitativeAnalysis for ManagerialApplications",
    school: "SOMS",
  },
  { code: "MS-56", title: "Materials Management", school: "SOMS" },
  { code: "MS-9", title: "Managerial Economics", school: "SOMS" },
  { code: "MS-57", title: "Maintenance Management", school: "SOMS" },
  { code: "MS-58", title: "Management of R", school: "SOMS" },
  {
    code: "MS-10",
    title: "Organization Design  Development and Change",
    school: "SOMS",
  },
  { code: "MS-61", title: "Consumer Behaviour", school: "SOMS" },
  { code: "MS-11", title: "Strategic Management", school: "SOMS" },
  { code: "MS-62", title: "Sales and Distribution", school: "SOMS" },
  { code: "MS-63", title: "Product Management", school: "SOMS" },
  { code: "MS-22", title: "Human Resource Development", school: "SOMS" },
  { code: "MS-64", title: "International Marketing", school: "SOMS" },
  { code: "MS-23", title: "Human Resource Planning", school: "SOMS" },
  { code: "MS-65", title: "Marketing of Services", school: "SOMS" },
  { code: "MS-24", title: "Employment Relations", school: "SOMS" },
  { code: "MS-66", title: "Marketing Research", school: "SOMS" },
  { code: "MS-25", title: "Managing Change in", school: "SOMS" },
  {
    code: "MS-68",
    title: "Management of Marketing Organisations",
    school: "SOMS",
  },
  { code: "MS-26", title: "Organisational Dynamics", school: "SOMS" },
  { code: "MS-91", title: "Advanced Strategic", school: "SOMS" },
  { code: "MS-27", title: "Wage and Salary Management", school: "SOMS" },
  { code: "MS-92", title: "Management of Public", school: "SOMS" },
  { code: "MS-28", title: "Labour Laws", school: "SOMS" },
  { code: "MS-29", title: "International Human", school: "SOMS" },
  { code: "MS-41", title: "Working Capital Management", school: "SOMS" },
  { code: "MS-94", title: "Technology Management", school: "SOMS" },
  { code: "MS-42", title: "Capital Investment and", school: "SOMS" },
  {
    code: "MS-95",
    title: "Research Methodology for Financing Decisions",
    school: "SOMS",
  },
  { code: "MS-96", title: "Total Quality Management", school: "SOMS" },
  { code: "ECO-10", title: "Elements of Costing", school: "SOMS" },
  { code: "MS-97", title: "International Business", school: "SOMS" },
  { code: "ECO-11", title: "Elements of Income Tax", school: "SOMS" },
  { code: "MS-422", title: "Bank Financial Management", school: "SOMS" },
  { code: "ECO-12", title: "Elements ofAuditing", school: "SOMS" },
  { code: "ECO-13", title: "Business of Environment", school: "SOMS" },
  { code: "MS-424", title: "International Banking", school: "SOMS" },
  { code: "ECO-14", title: "Accountancy", school: "SOMS" },
  { code: "MCO-01", title: "Organisation Theory and", school: "SOMS" },
  {
    code: "MS-425",
    title: "Electronic Banking and Behaviour IT in Banks",
    school: "SOMS",
  },
  { code: "MCO-03", title: "Research Methodology", school: "SOMS" },
  { code: "MS-611", title: "Rural Marketing", school: "SOMS" },
  { code: "MS-612", title: "Retail Management", school: "SOMS" },
  { code: "MCO-04", title: "Business Environment", school: "SOMS" },
  { code: "MCO-05", title: "Accounting for", school: "SOMS" },
  {
    code: "IBO-01",
    title: "International Business Managerial Decisions",
    school: "SOMS",
  },
  { code: "MCO-06", title: "Marketing Management", school: "SOMS" },
  {
    code: "IBO-02",
    title: "International Marketing Management",
    school: "SOMS",
  },
  { code: "MCO-07", title: "Financial Management", school: "SOMS" },
  { code: "IBO-03", title: "India", school: "SOMS" },
  { code: "PCO-01", title: "Preparatory Course in Commerce", school: "SOMS" },
  {
    code: "IBO-04",
    title: "Export Import Procedures and Documentation",
    school: "SOMS",
  },
  {
    code: "PCO-01",
    title: "Preparatory Course in Commerce (Odiya)",
    school: "SOMS",
  },
  {
    code: "IBO-05",
    title: "International Marketing Logistics",
    school: "SOMS",
  },
  { code: "BCOA-001", title: "Business Communication", school: "SOMS" },
  { code: "IBO-06", title: "International Business Finance", school: "SOMS" },
  { code: "BMS-01", title: "Introduction to NGO", school: "SOMS" },
  { code: "AED-01", title: "Export Procedure", school: "SOMS" },
  { code: "BMS-02", title: "Management Functions", school: "SOMS" },
  { code: "AMK-01", title: "Marketing", school: "SOMS" },
  { code: "BMS-03", title: "Health Care Management", school: "SOMS" },
  { code: "AOM-01", title: "Office Organisation", school: "SOMS" },
  {
    code: "CIE-01",
    title: "Introduction to Management Entrepreneurship",
    school: "SOMS",
  },
  { code: "ASP-01", title: "Secretarial Practice", school: "SOMS" },
  { code: "CIE-02", title: "BusinessApportunity", school: "SOMS" },
  { code: "ECO-01", title: "Business Organisation", school: "SOMS" },
  { code: "ECO-02", title: "Accountancy", school: "SOMS" },
  {
    code: "CIE-03",
    title: "Enterprise Creation and Legal Requirements",
    school: "SOMS",
  },
  { code: "ECO-03", title: "Management Theory", school: "SOMS" },
  { code: "CIE-04", title: "Enterprise Management", school: "SOMS" },
  { code: "ECO-05", title: "Mercantile Law", school: "SOMS" },
  { code: "CIE-05", title: "Computer for Entrepreneurs", school: "SOMS" },
  { code: "ECO-06", title: "Economic Theory", school: "SOMS" },
  { code: "BRL-001", title: "Overview of Retailing", school: "SOMS" },
  { code: "ECO-07", title: "Elements of Statistics", school: "SOMS" },
  {
    code: "BRL-002",
    title: "Retail Marketing and Communication",
    school: "SOMS",
  },
  { code: "ECO-08", title: "Company Law", school: "SOMS" },
  { code: "BRL-003", title: "Retail Management", school: "SOMS" },
  { code: "ECO-09", title: "Money Banking", school: "SOMS" },
  { code: "BRL-004", title: "Customer Service", school: "SOMS" },
  {
    code: "NGS-001",
    title: "Awareness Course on Gandhi Management",
    school: "SOSS",
  },
  { code: "BRLT-005Internship", title: "and Viva", school: "SOMS" },
  { code: "BRL-007", title: "Store Operation", school: "SOMS" },
  { code: "BWEE-012", title: "Women and Society", school: "SOSS" },
  { code: "BRL-008", title: "Human Resources", school: "SOMS" },
  { code: "PFM-1", title: "Participatory Forest", school: "SOSS" },
  {
    code: "MRR-101",
    title: "Understanding Development Management Caused Displacement",
    school: "SOSS",
  },
  { code: "MRR-102", title: "Role of Participation in", school: "SOSS" },
  {
    code: "PFM-2",
    title: "Participatory Forest Sustainable Development",
    school: "SOSS",
  },
  {
    code: "MRR-103",
    title: "Participating Planning for Resettlement and",
    school: "SOSS",
  },
  {
    code: "PFM-3",
    title: "Participatory Forest Rehabilitation",
    school: "SOSS",
  },
  { code: "MRR-104", title: "Participatory Implementing", school: "SOSS" },
  {
    code: "PFM-4",
    title: "Participatory Forest Rehabilitation",
    school: "SOSS",
  },
  { code: "MRR-005", title: "Theoretical Perspectives", school: "SOSS" },
  { code: "PFM-5", title: "lkfofu", school: "SOSS" },
  { code: "MRR-006", title: "Illustrative R", school: "SOSS" },
  { code: "ESO-11", title: "The Study of Society", school: "SOSS" },
  { code: "ESO-12", title: "Society in India", school: "SOSS" },
  { code: "MRRE", title: "Economic Planning of R", school: None },
  { code: "ESO-13", title: "Sociological Thought", school: "SOSS" },
  { code: "ESO-14", title: "Society and Stratification", school: "SOSS" },
  { code: "ESO-15", title: "Society and Religion", school: "SOSS" },
  { code: "MRRP-111", title: "Project Work Guide", school: "SOSS" },
  { code: "ESO-16", title: "Social Problem in India", school: "SOSS" },
  {
    code: "BLD-101",
    title:
      "Political Economy of Hkkjr ea lkekftd Labour in India Hkkjr ea Je dk",
    school: "SOSS",
  },
  { code: "MSO-001", title: "Sociological Theories and", school: "SOSS" },
  { code: "BLD-102", title: "Organising the Unorganised", school: "SOSS" },
  { code: "MSO-002", title: "Research Methodologies", school: "SOSS" },
  { code: "CLD-3", title: "Child and Bonded Labour", school: "SOSS" },
  { code: "MSO-003", title: "Sociology of Development", school: "SOSS" },
  { code: "CLD-4", title: "Migrant and Female Workers", school: "SOSS" },
  { code: "MSO-004", title: "Sociology in India", school: "SOSS" },
  { code: "MPSE-004", title: "Social and Political Thought", school: "SOSS" },
  { code: "MSOE-001", title: "Sociology of Education", school: "SOSS" },
  { code: "MPSE-005", title: "State and Society inAfrica", school: "SOSS" },
  { code: "MSOE-002", title: "Diaspora and Transnational", school: "SOSS" },
  { code: "MPSE-006", title: "Peace and Conflict Studies", school: "SOSS" },
  { code: "MSOE-003", title: "Sociology of Religion", school: "SOSS" },
  { code: "MPSE-007", title: "Social Movements and", school: "SOSS" },
  { code: "MSOE-004", title: "Urban Sociology", school: "SOSS" },
  { code: "MPSE-008", title: "State Politics in India", school: "SOSS" },
  { code: "MLISE-4", title: "Technical Writing", school: "SOSS" },
  { code: "MLISE-5", title: "Informetrics and Scienteomtrics", school: "SOSS" },
  { code: "MPSE-009", title: "Canada", school: "SOSS" },
  { code: "MLISE-6", title: "Public Library System", school: "SOSS" },
  { code: "MPSE-010", title: "Master ofArts", school: "SOSS" },
  {
    code: "MLI-101",
    title: "Information Communication (Political Science) Part Iand Society",
    school: "SOSS",
  },
  { code: "MPSE-011", title: "European Union in", school: "SOSS" },
  { code: "MLI-102", title: "Management of Library", school: "SOSS" },
  { code: "MPS-001", title: "", school: "SOSS" },
  { code: "MPSE-012", title: "State and Society inAustralia", school: "SOSS" },
  { code: "MPS-002", title: "International Relations", school: "SOSS" },
  { code: "MPSE-013", title: "Australia", school: "SOSS" },
  { code: "MPA-001", title: "Understanding Natural", school: "SOSS" },
  { code: "MPS-003", title: "India", school: "SOSS" },
  { code: "MPA-002", title: "Understanding Man", school: "SOSS" },
  { code: "MPS-004", title: "Comparative Politics", school: "SOSS" },
  { code: "MPA-003", title: "RiskAssessment and", school: "SOSS" },
  { code: "MPSE-001", title: "India and the World", school: "SOSS" },
  { code: "MPSE-002", title: "State and Society in", school: "SOSS" },
  { code: "MPA-004", title: "Disaster Preparedness", school: "SOSS" },
  { code: "MPA-005", title: "Disaster Response", school: "SOSS" },
  { code: "MPSE-003", title: "Western Political Thought", school: "SOSS" },
  { code: "MPA-006", title: "Disaster Medicine", school: "SOSS" },
  { code: "MPA-007", title: "Rehabilitation Reconstruction", school: "SOSS" },
  { code: "MPS-001", title: "Political Theory", school: "SOSS" },
  { code: "EPS-03", title: "Modern Indian Political Thought", school: "SOSS" },
  { code: "MPA-011", title: "State Society and", school: "SOSS" },
  { code: "EPS-06", title: "Government", school: "SOSS" },
  { code: "MPA-012", title: "Administrative Theory", school: "SOSS" },
  { code: "MPA-013", title: "Public System Management", school: "SOSS" },
  { code: "EPS-07", title: "International Relations", school: "SOSS" },
  { code: "MPA-014", title: "Human Resource Management", school: "SOSS" },
  { code: "EPS-08", title: "Government", school: "SOSS" },
  { code: "MPA-015", title: "Public Policy andAnalysis", school: "SOSS" },
  { code: "MPA-016", title: "Decentralisation and Local", school: "SOSS" },
  { code: "EPS-09", title: "Comparative Government", school: "SOSS" },
  { code: "MPA-017", title: "Electronic Governance", school: "SOSS" },
  { code: "EPS-11", title: "Political Ideas and Ideologies", school: "SOSS" },
  { code: "MPA-018", title: "Disaster Management", school: "SOSS" },
  { code: "MLII-101", title: "Information Sources ", school: "SOSS" },
  { code: "EPS-12", title: "Government", school: "SOSS" },
  { code: "MLII-102", title: "Information Processing", school: "SOSS" },
  { code: "EPS-15", title: "SouthAsia", school: "SOSS" },
  { code: "MLII-103", title: "Fundamentals of Information", school: "SOSS" },
  { code: "MHI-01", title: "Ancient and Medieval", school: "SOSS" },
  { code: "MLII-104", title: "Information Communication", school: "SOSS" },
  { code: "MLI-001", title: "Introduction to Computers", school: "SOSS" },
  { code: "MHI-02", title: "Modern World", school: "SOSS" },
  { code: "MLI-002", title: "LibraryAutomation", school: "SOSS" },
  { code: "MLI-003", title: "Information Systems", school: "SOSS" },
  { code: "MHI-03", title: "Historiography", school: "SOSS" },
  { code: "MLI-004", title: "Networking and Internet", school: "SOSS" },
  { code: "MHI-04", title: "Political Structures in India", school: "SOSS" },
  { code: "MLI-005", title: "Internet Resources", school: "SOSS" },
  { code: "MLI-006", title: "Content Development", school: "SOSS" },
  { code: "MHI-05", title: "History of Indian Econom", school: "SOSS" },
  { code: "MLI-007", title: "Programming", school: "SOSS" },
  { code: "MHI-06", title: "Evolution of Social Structures", school: "SOSS" },
  { code: "BECE-107", title: "Industrial Development", school: "SOSS" },
  { code: "EEC-10", title: "National IncomeAccounting", school: "SOSS" },
  { code: "MHI-08", title: "History of Ecology and", school: "SOSS" },
  { code: "EEC-11", title: "Fundamentals of Economics", school: "SOSS" },
  { code: "EEC-12", title: "Indian Economic Development", school: "SOSS" },
  { code: "EHI-1", title: "Modern India", school: "SOSS" },
  { code: "EHI-2", title: "History of India From Earliest", school: "SOSS" },
  { code: "EEC-13", title: "Elementary Statistical", school: "SOSS" },
  { code: "EHI-3", title: "India from", school: "SOSS" },
  { code: "EEC-19", title: "Indian Financial System", school: "SOSS" },
  { code: "EHI-4", title: "India from", school: "SOSS" },
  { code: "EPA-1", title: "Administrative Theory", school: "SOSS" },
  { code: "BPAE-102", title: "IndianAdministration", school: "SOSS" },
  { code: "EHI-5", title: "India Mid", school: "SOSS" },
  { code: "EPA-3", title: "DevelopmentAdministration Mid", school: "SOSS" },
  { code: "EPA-4", title: "PersonnelAdministration dkfeSd iz", school: "SOSS" },
  { code: "EHI-6", title: "History of China and Japan", school: "SOSS" },
  { code: "EPA-5", title: "FinancialAdministration", school: "SOSS" },
  { code: "EPA-6", title: "Public Policy", school: "SOSS" },
  { code: "EHI-7", title: "Modern Europe (Mid", school: "SOSS" },
  { code: "MEC-001", title: "MicroeconomicAnalysis", school: "SOSS" },
  { code: "MEC-002", title: "MacroeconomicAnalysis", school: "SOSS" },
  { code: "MEC-003", title: "Quantitative Methods", school: "SOSS" },
  { code: "BECE-002", title: "Indian Economic Development", school: "SOSS" },
  {
    code: "MEC-004",
    title: "Economics of Growth Issues and Perspectives",
    school: "SOSS",
  },
  { code: "BECE-214", title: "Agricultural Development", school: "SOSS" },
  { code: "MEC-105", title: "Indian Economic Policy", school: "SOSS" },
  { code: "MEC-006", title: "Public Economics", school: "SOSS" },
  { code: "BECE-15", title: "Elementary Mathematicals", school: "SOSS" },
  { code: "MEC-007", title: "International Trade and Finance", school: "SOSS" },
  { code: "BECE-16", title: "Economic Developments", school: "SOSS" },
  {
    code: "MEC-008",
    title: "Economics of Social Sector Contemporary Issues and Environment",
    school: "SOSS",
  },
  { code: "MEC-009", title: "Research Methods in", school: "SOSS" },
  { code: "MPC-002", title: "Life Span Psychology", school: "SOSS" },
  { code: "MPC-003", title: "Personality", school: "SOSS" },
  { code: "MECE-001", title: "Econometric Methods", school: "SOSS" },
  { code: "MECE-003", title: "Actuarial Economics", school: "SOSS" },
  { code: "MPC-004", title: "Advanced Social Psychology", school: "SOSS" },
  { code: "MPC-005", title: "Research Methods in", school: "SOSS" },
  { code: "MECE-004", title: "Financial Institutions and", school: "SOSS" },
  { code: "MPC-006", title: "Statistics in Psychology", school: "SOSS" },
  {
    code: "MLIE-101",
    title: "Preservation and Conservation of Library Materials",
    school: "SOSS",
  },
  { code: "MPC-051", title: "Fundamentals of Mental Health", school: "SOSS" },
  { code: "MLIE-102", title: "Research Methodology", school: "SOSS" },
  { code: "MPC-052", title: "Mental Disorders", school: "SOSS" },
  { code: "MLIE-103", title: "Academic Library System", school: "SOSS" },
  { code: "MPC-053", title: "Mental Health in Special Areas", school: "SOSS" },
  { code: "BSHF-101", title: "Foundation Course in", school: "SOSS" },
  { code: "MPC-054", title: "Services for the Mentally", school: "SOSS" },
  { code: "MPC-055", title: "Practicals", school: "SOSS" },
  {
    code: "MPCL-007",
    title: "Experimental Psychology and Psychological Testing",
    school: "SOSS",
  },
  {
    code: "OSS-101",
    title: "Preparatory Course in Social Sciences",
    school: "SOSS",
  },
  { code: "MPCE", title: "", school: None },
  { code: "MPCE", title: "", school: None },
  { code: "CDM-02", title: "Disaster Management", school: "SOSS" },
  { code: "MPCE", title: "", school: None },
  { code: "PFM-01", title: "Forest Resources and Use", school: "SOSS" },
  { code: "MECP-101", title: "Project Work", school: "SOSS" },
  { code: "MECP-101", title: "dyk fuiknu", school: "SOSS" },
  { code: "PFM-02", title: "Forester", school: "SOSS" },
  { code: "MPAP-01", title: "Project Handbook", school: "SOSS" },
  { code: "MLIP-02", title: "Project Work", school: "SOSS" },
  { code: "BPC-004", title: "Statistics in Psychology", school: "SOSS" },
  { code: "BPC-005", title: "Theories of Personality", school: "SOSS" },
  { code: "BPCL-007", title: "Practicals in Psychological", school: "SOSS" },
  { code: "BPC-006", title: "Social Psychology", school: "SOSS" },
  { code: "BPCE-014", title: "Psychopathology", school: "SOSS" },
  { code: "BPCE-021", title: "Forensic Psychology", school: "SOSS" },
  { code: "MPCE", title: "", school: None },
  { code: "BPC-001", title: "General Psychology", school: "SOSS" },
  { code: "BPC-002", title: "Developmental Psychology", school: "SOSS" },
  { code: "MANI-001", title: "Anthropology and Methods", school: "SOSS" },
  { code: "BPC-003", title: "Research Methods in of Research", school: "SOSS" },
  { code: "MANI-002", title: "PhysicalAnthropology", school: "SOSS" },
  { code: "MPC-001", title: "Cognitive Psychology ", school: "SOSS" },
  { code: "MAN-001", title: "SocialAnthoropology", school: "SOSS" },
  { code: "MAN-002", title: "Archaeological Anthoropology", school: "SOSS" },
  { code: "MANI-003", title: "PracticingAnthropology", school: "SOSS" },
  {
    code: "MTM-4",
    title: "Information Management Systems and Tourism",
    school: "SOTHSM",
  },
  { code: "MANE-001", title: "Human Genetics", school: "SOSS" },
  { code: "MTM-7", title: "Managing Sales and", school: "SOTHSM" },
  {
    code: "MANE-002",
    title: "Human Growth and Promotion in Tourism",
    school: "SOSS",
  },
  { code: "MTM-8", title: "Managing Entrepreneurship", school: "SOTHSM" },
  { code: "MANE-003", title: "Comparative Ethnography", school: "SOSS" },
  { code: "MANE-004", title: "Gender and Society", school: "SOSS" },
  { code: "MTM-9", title: "Understanding Tourism", school: "SOTHSM" },
  { code: "MANE-005", title: "EnvironmentalAnthropology", school: "SOSS" },
  { code: "BLI-221", title: "Library Information and", school: "SOSS" },
  { code: "MTM-10", title: "Tourism Impacts", school: "SOTHSM" },
  { code: "MTM-11", title: "Tourism Planning and", school: "SOTHSM" },
  {
    code: "BLI-222",
    title: "Information Sources and Development",
    school: "SOSS",
  },
  { code: "MTM-12", title: "Tourism Products", school: "SOTHSM" },
  {
    code: "BLI-223",
    title: "Organising and Managing and Development",
    school: "SOSS",
  },
  { code: "MTM-13", title: "Tourism Operations", school: "SOTHSM" },
  { code: "BLI-224", title: "ICT Fundamentals", school: "SOSS" },
  { code: "MTM-14", title: "Tourist Transport", school: "SOTHSM" },
  { code: "BLI-225", title: "Communication Skills", school: "SOSS" },
  { code: "BLIE-226", title: "Management of Library", school: "SOSS" },
  { code: "MTM", title: "", school: None },
  { code: "BLIE-227", title: "Document Processing Practice", school: "SOSS" },
  { code: "MTM-16", title: "Dissertation Guide", school: "SOTHSM" },
  { code: "BLIE-228", title: "Information Products", school: "SOSS" },
  { code: "TS-01", title: "Foundation Course in Tourism", school: "SOTHSM" },
  { code: "BLIE-229", title: "ICAT in Libraries", school: "SOSS" },
  { code: "TS-02", title: "Tourism Development", school: "SOTHSM" },
  { code: "BLII-011", title: "Libraries", school: "SOSS" },
  {
    code: "BLII-012",
    title: "Document Processing and lpkyu vkSj fLFkfr v",
    school: "SOSS",
  },
  { code: "TS-03", title: "Management in Tourism", school: "SOTHSM" },
  { code: "BLII-013", title: "Information Sources and i", school: "SOSS" },
  { code: "TS-04", title: "Indian Culture", school: "SOTHSM" },
  { code: "BLII-014", title: "ICT in Libraries", school: "SOSS" },
  {
    code: "TS-05",
    title:
      "Ecology Environment and SERVICE MANAGEMENT (SOTHSM) and Tourism ifjfLFkfrdh",
    school: "SOTHSM",
  },
  {
    code: "MTM-1",
    title: "Management Functions and Behaviour in Tourism",
    school: "SOTHSM",
  },
  { code: "TS-06", title: "Tourism Marketing", school: "SOTHSM" },
  {
    code: "MTM-2",
    title: "Human Resource Planning and Development in Tourism",
    school: "SOTHSM",
  },
  { code: "TS-07", title: "Human Resource", school: "SOTHSM" },
  {
    code: "MTM-3",
    title: "Managing Personnel in Development Tourism",
    school: "SOTHSM",
  },
  { code: "PTS", title: "", school: None },
  { code: "LSE-01", title: "Cell Biology", school: "SOS" },
  { code: "LSE-02", title: "Ecology", school: "SOS" },
  { code: "LSE-03", title: "Genetics", school: "SOS" },
  { code: "LSE-04", title: "Laboratory Course", school: "SOS" },
  { code: "FST-01", title: "Foundation Course in (L) iz", school: "SOS" },
  { code: "LSE-05", title: "Physiology", school: "SOS" },
  { code: "OMT-101", title: "Preparatory Course in", school: "SOS" },
  { code: "LSE-06", title: "Development Biology", school: "SOS" },
  { code: "LSE-07", title: "Taxonomy and Evolution", school: "SOS" },
  { code: "CHE-01", title: "Atoms and Molecule", school: "SOS" },
  { code: "LSE-08", title: "Laboratory Course", school: "SOS" },
  { code: "CHE-02", title: "Inorganic Chemistry", school: "SOS" },
  { code: "LSE-09", title: "Animal Diversity", school: "SOS" },
  { code: "CHE-03", title: "Chemistry Lab", school: "SOS" },
  { code: "LSE-10", title: "Animal Diversity", school: "SOS" },
  { code: "CHE-04", title: "Physical Chemistry", school: "SOS" },
  { code: "LSE-11", title: "Animal Diversity Lab", school: "SOS" },
  { code: "CHE-05", title: "Organic Chemistry", school: "SOS" },
  { code: "CHE-06", title: "Organic Reaction Mechanism", school: "SOS" },
  { code: "LSE-12", title: "Plant Diversity", school: "SOS" },
  { code: "LSE-13", title: "Plant Diversity", school: "SOS" },
  { code: "CHE-07", title: "Chemistry Lab", school: "SOS" },
  { code: "LSE-14", title: "(L) Plant Diversity Laboratory", school: "SOS" },
  { code: "CHE-08", title: "Chemistry Lab", school: "SOS" },
  { code: "ACE", title: "Appreciation Course on", school: None },
  { code: "CHE-09", title: "Biochemistry", school: "SOS" },
  { code: "CHE-10", title: "Spectroscopy", school: "SOS" },
  { code: "BAQL-001", title: "Freshwater Aquaculture", school: "SOS" },
  { code: "CHE-11", title: "Chemistry Lab", school: "SOS" },
  { code: "BAQL-002", title: "CoastalAquaculture Lab", school: "SOS" },
  { code: "BLS-001", title: "Basics ofAquaculture", school: "SOS" },
  { code: "CHE-12", title: "Chemistry Lab", school: "SOS" },
  { code: "BAQ-002", title: "Freshwater Aquaculture", school: "SOS" },
  { code: "BAQ-003", title: "CostalAquaculture", school: "SOS" },
  { code: "LMT-01", title: "Learning Mathematics", school: "SOS" },
  { code: "PHE-12", title: "Physics Laboratory", school: "SOS" },
  { code: "LT-01", title: "Good Laboratory Practices", school: "SOS" },
  { code: "PHE-13", title: "Physics of Solids", school: "SOS" },
  { code: "LT-02", title: "Laboratory Techniques in", school: "SOS" },
  { code: "PHE-14", title: "Mathematical Method in Biology", school: "SOS" },
  { code: "PHE-15", title: "Astronomy andAstrophysics", school: "SOS" },
  { code: "LT-03", title: "Laboratory Techniques in", school: "SOS" },
  { code: "PHE-16", title: "Communication Physics", school: "SOS" },
  { code: "LT-04", title: "Laboratory Techniques in", school: "SOS" },
  { code: "MED-001", title: "Understanding the", school: "SOS" },
  { code: "BPHE-101", title: "Elementary Mechanics", school: "SOS" },
  { code: "MED-002", title: "Sustainable Development", school: "SOS" },
  { code: "BPHE-102", title: "Oscillations and Waves", school: "SOS" },
  { code: "MED-003", title: "Energy and Environment", school: "SOS" },
  { code: "MED-004", title: "Towards Participatory", school: "SOS" },
  { code: "BPHL-103", title: "Physics Laboratory", school: "SOS" },
  { code: "MED-005", title: "Integrated Environmental", school: "SOS" },
  { code: "PHE-04", title: "Mathematical Methods Management", school: "SOS" },
  { code: "MED-006", title: "Natural Resources", school: "SOS" },
  { code: "PHE-05", title: "Mathematical Methods in", school: "SOS" },
  { code: "MED-007", title: "Agriculture and", school: "SOS" },
  { code: "PHE-06", title: "Thermodynamics and", school: "SOS" },
  { code: "MED-008", title: "Globalisation and lkf", school: "SOS" },
  { code: "PHE-07", title: "Electric and Magnetic", school: "SOS" },
  { code: "APM-01", title: "Integrated Pest Phenomena", school: "SOS" },
  { code: "PHE-08", title: "Physics Laboratory", school: "SOS" },
  { code: "AOR-01", title: "Operations Research", school: None },
  { code: "PHE-09", title: "Optics", school: "SOS" },
  { code: "MTE-01", title: "Calculus", school: "SOS" },
  { code: "PHE-10", title: "Electrical Circuits and", school: "SOS" },
  { code: "MTE-02", title: "Linear Algebra", school: "SOS" },
  { code: "MTE-03", title: "Mathematical Methods", school: "SOS" },
  { code: "PHE-11", title: "Modern Physics xf", school: "SOS" },
  { code: "MTE-04", title: "ElementaryAlgebra", school: "SOS" },
  { code: "MMT-005", title: "ComplexAnalysis", school: "SOS" },
  { code: "MMT-006", title: "FunctionalAnalysis", school: "SOS" },
  { code: "MTE-05", title: "Analytical Geometry", school: "SOS" },
  { code: "MMT-007", title: "Differential Equations and", school: "SOS" },
  { code: "MTE-06", title: "Abstract Algebra", school: "SOS" },
  { code: "MMT-008", title: "Probability and Statistics", school: "SOS" },
  { code: "MTE-07", title: "Advanced Calculus", school: "SOS" },
  { code: "MMT-009", title: "Mathematical", school: "SOS" },
  { code: "MTE-08", title: "Differential Equations", school: "SOS" },
  { code: "MESE-001", title: "Teaching", school: "SOE" },
  { code: "MTE-09", title: "RealAnalysis", school: "SOS" },
  { code: "MESE-002", title: "Exploring Physics in okLrfod fo", school: "SOE" },
  { code: "MTE-10", title: "NumericalAnalysis", school: "SOS" },
  { code: "MESE-003", title: "Biology Teaching", school: "SOE" },
  { code: "MESE-004", title: "Chemistry Teaching", school: "SOE" },
  { code: "MTE-11", title: "Probability and Statistics", school: "SOS" },
  { code: "MCHL-001", title: "BasicAnalytical izkf", school: "SOS" },
  { code: "MTE-12", title: "Linear Programming", school: "SOS" },
  { code: "MCHL-002", title: "Separation Methods Lab", school: "SOS" },
  { code: "MCHL-003", title: "Spectroscopic Method Lab", school: "SOS" },
  { code: "MTE-13", title: "Discrete Mathematics", school: "SOS" },
  { code: "MCHL-004", title: "Elecroanalytical and fofoDr xf", school: "SOS" },
  { code: "MTE-14", title: "Mathematical Modelling", school: "SOS" },
  { code: "MST-001", title: "Foundation in Mathematics xf", school: "SOS" },
  { code: "MST-002", title: "Descriptive Statistics", school: "SOS" },
  { code: "MST-003", title: "Probability Theory", school: "SOS" },
  { code: "MST-004", title: "Statistical Inference", school: "SOS" },
  { code: "AHE-1", title: "Human Environment", school: "SOS" },
  { code: "MST-005", title: "Statistical Techniques", school: "SOS" },
  { code: "AST-01", title: "Statistical Techniques", school: "SOS" },
  { code: "MSTE-001", title: "Industrial Statistics", school: "SOS" },
  { code: "MSTE-002", title: "Industrial Statistics II", school: "SOS" },
  { code: "AEC-1", title: "Environmental Chemistry", school: "SOS" },
  { code: "MGY-001", title: "Introduction to Geoinformatics", school: "SOS" },
  {
    code: "AMT-01",
    title: "Teaching of Primary School Mathematics",
    school: "SOS",
  },
  {
    code: "MGY-002",
    title: "Sensing and Image izkbZejh Ldyh xf",
    school: "SOS",
  },
  { code: "MGY-003", title: "Global Satellite", school: "SOS" },
  { code: "MMT-001", title: "Programming and Data", school: "SOS" },
  { code: "MMT-002", title: "Linear Algebra", school: "SOS" },
  { code: "MBI-001", title: "Introduction to Life Science", school: "SOS" },
  { code: "MMT-003", title: "Algebra", school: "SOS" },
  { code: "MBI-002", title: "", school: "SOS" },
  { code: "MMT-004", title: "RealAnalysis", school: "SOS" },
  { code: "MBI-003", title: "Essentials of Bioinformatics", school: "SOS" },
  { code: "MBI-004", title: "Bioinformatics", school: "SOS" },
  { code: "ET-502", title: "(A) Strength of Materials", school: "SOET" },
  { code: "MCH-001", title: "BasicAnalytical Chemistry", school: "SOS" },
  { code: "ET-502", title: "(B) Structural Analysis", school: "SOET" },
  { code: "MCH-002", title: "Separation Methods", school: "SOS" },
  { code: "ET-501", title: "(A) Soil Mechanics", school: "SOET" },
  { code: "MCH-003", title: "Spectroscopic Methods", school: "SOS" },
  {
    code: "ET-581",
    title: "(F) Mechanical Equipment in Construction",
    school: "SOET",
  },
  {
    code: "MCH-004",
    title: "Electroanalytical and other methods",
    school: "SOS",
  },
  {
    code: "ET-505",
    title: "Transportation and Traffic Engineering",
    school: "SOET",
  },
  { code: "BLS-001", title: "Basics ofAquaculture", school: "SOS" },
  { code: "ET-507", title: "(A) Pollutants and Water Supply", school: "SOET" },
  { code: "MSTL-001", title: "Basics Statistics Lab", school: "SOS" },
  { code: "ET-508", title: "(A) Structural Design", school: "SOET" },
  { code: "MSTL-002", title: "Industrial Statistics Lab", school: "SOS" },
  { code: "ET-508", title: "(B) Structural Design", school: "SOET" },
  { code: "ET-521", title: "(A) Planning", school: "SOET" },
  { code: "ET-521", title: "(B) BuildingArchitecture", school: "SOET" },
  { code: "ET-101", title: "(A)Mathematics", school: "SOET" },
  { code: "ET-521", title: "(C) Design Detailing", school: "SOET" },
  { code: "ET-101", title: "(B)Mathematics", school: "SOET" },
  { code: "ET-521", title: "(D) Quantity Surveying", school: "SOET" },
  { code: "ET-102", title: "Mathematics", school: "SOET" },
  { code: "ET-105", title: "(A) Physics", school: "SOET" },
  {
    code: "ET-522",
    title: "Concrete Technology and Construction Techniques",
    school: "SOET",
  },
  { code: "ET-105", title: "(B) Chemistry", school: "SOET" },
  { code: "ET-524(A)", title: "", school: "SOET" },
  { code: "ET-201", title: "(A) Mechanics of Fluids", school: "SOET" },
  { code: "ET-202", title: "(A) Engineering Mechanics", school: "SOET" },
  { code: "ET-524", title: "(B) Construction Management", school: "SOET" },
  { code: "ET-202", title: "(B) Principles of Electrical", school: "SOET" },
  { code: "ET-525", title: "Construction Management", school: "SOET" },
  { code: "ET-540", title: "(B) Flow in Open Channel", school: "SOET" },
  { code: "ET-201", title: "(B) Engineering Thermodynamics", school: "SOET" },
  {
    code: "ET-523",
    title: "(A) Construction Works Supervision",
    school: "SOET",
  },
  { code: "ET-204", title: "(A) Materials Science", school: "SOET" },
  { code: "ET-523", title: "(B) Operation and Maintenance", school: "SOET" },
  { code: "ET-204", title: "(B) Engineering Materials", school: "SOET" },
  { code: "ET-302", title: "(B) Computer Programming", school: "SOET" },
  {
    code: "ET-523",
    title: "(C) Repair and Maintenance of Buildings",
    school: "SOET",
  },
  { code: "ET-581", title: "(A) Testing for Quality Control", school: "SOET" },
  { code: "ET-301(A)", title: "", school: "SOET" },
  { code: "BME-001", title: "Engineering Mathematics", school: "SOET" },
  {
    code: "ET-302",
    title: "(A) Computer Programming and Numerical Methods",
    school: "SOET",
  },
  { code: "BME-002", title: "Computer Aided Design", school: "SOET" },
  { code: "ET-301", title: "(B) Computer Applications", school: "SOET" },
  { code: "BME-003", title: "Manufacturing Technology", school: "SOET" },
  { code: "ET-302", title: "(B) Technical Writing", school: "SOET" },
  {
    code: "BME-005",
    title: "Computer Integrated Manufacturing",
    school: "SOET",
  },
  { code: "ET-501", title: "(B) Foundation Engineering", school: "SOET" },
  { code: "BME-004", title: "CNC Technology", school: "SOET" },
  { code: "BMEL-003", title: "Laboratory", school: "SOET" },
  { code: "BME-006", title: "Mechatronics", school: "SOET" },
  { code: "BMEL-004", title: "Laboratory", school: "SOET" },
  { code: "BME-007", title: "Quality Engineering", school: "SOET" },
  { code: "BMEP-001", title: "Project", school: "SOET" },
  { code: "BME-008", title: "Machinary Technology", school: "SOET" },
  { code: "BEE-001", title: "Power Distribution Sector", school: "SOET" },
  {
    code: "BME-009",
    title: "Computer Programming andApplication",
    school: "SOET",
  },
  { code: "BEE-002", title: "Energy Management", school: "SOET" },
  { code: "BME-010", title: "Tool Engineering and Management", school: "SOET" },
  { code: "BEE-003", title: "Management of Power", school: "SOET" },
  { code: "BME-011", title: "Computer Aided Process Planning", school: "SOET" },
  { code: "OET-001", title: "World of Clay", school: "SOET" },
  { code: "BME-012", title: "Manufacturing Systems", school: "SOET" },
  { code: "OETL-002", title: "Static Clay Forms", school: "SOET" },
  { code: "BME-013", title: "Production Management", school: "SOET" },
  { code: "OETL-003", title: "Dynamic Clay Forms", school: "SOET" },
  { code: "BME-014", title: "Metrology andInstrumentation", school: "SOET" },
  {
    code: "OETL-004",
    title: "Understanding Design and Marketing",
    school: "SOET",
  },
  { code: "BME-015", title: "Engineering Mathematics", school: "SOET" },
  { code: "BCE-024", title: "Construction Technology", school: "SOET" },
  { code: "BME-016", title: "Engineering Mechanics", school: "SOET" },
  { code: "BCE-045", title: "Construction Drawing", school: "SOET" },
  { code: "BME-017", title: "Strength of Materials", school: "SOET" },
  { code: "BCE-052", title: "Transportation Engineering", school: "SOET" },
  { code: "BME-018", title: "Engineering Materials", school: "SOET" },
  { code: "BCE-043", title: "Construction Technology", school: "SOET" },
  { code: "BME-019", title: "Engineering Thermodynamics", school: "SOET" },
  { code: "BCE-033", title: "Environmental Engineering", school: "SOET" },
  {
    code: "BME-020",
    title: "Kinematics and Dynamics of Mechanisms",
    school: "SOET",
  },
  { code: "BCE-032", title: "Theory of Structures", school: "SOET" },
  { code: "BME-021", title: "Principles of Electrical and", school: "SOET" },
  {
    code: "BCE-046",
    title: "Soil Mechanics and Electronics Sciences",
    school: "SOET",
  },
  { code: "BME-022", title: "Soft Computing in CIM", school: "SOET" },
  { code: "BCE-031", title: "Advanced Survey", school: "SOET" },
  { code: "BET-037", title: "Fluid Mechanics", school: "SOET" },
  { code: "BME-024", title: "Mechnical EngineeringDesign", school: "SOET" },
  { code: "BET-036", title: "Technical Documentation", school: "SOET" },
  {
    code: "BME-025",
    title: "Condition Monitoring and Maintenance Engineering",
    school: "SOET",
  },
  { code: "BET-011", title: "Mathematics", school: "SOET" },
  { code: "BME-028", title: "", school: "SOET" },
  { code: "BET-012", title: "Physics", school: "SOET" },
  { code: "BME-029", title: "Robotics", school: "SOET" },
  { code: "BET-014", title: "Applied Mechanics", school: "SOET" },
  { code: "BME-027", title: "Heat and Man Transfer", school: "SOET" },
  { code: "BET-015", title: "Engineering Materials", school: "SOET" },
  { code: "BET-021", title: "Mathematics", school: "SOET" },
  {
    code: "BME-035",
    title: "Industrial Engineering and Operations Research",
    school: "SOET",
  },
  { code: "BET-022", title: "Strength of Materials", school: "SOET" },
  { code: "BMEL-001", title: "Laboratory I", school: "SOET" },
  { code: "BET-023", title: "Elements of Survey", school: "SOET" },
  { code: "BET-016", title: "Engineering Drawing", school: "SOET" },
  { code: "BMEL-002", title: "Laboratory II", school: "SOET" },
  { code: "BET-026", title: "Workship Technology", school: "SOET" },
  { code: "BET-024", title: "E", school: "SOET" },
  {
    code: "OETL-023",
    title: "Practical in Shoe Upper Stitching",
    school: "SOET",
  },
  { code: "BET-017", title: "Computer Basics", school: "SOET" },
  { code: "OET-011", title: "vij dfVx ds eyk", school: "SOET" },
  { code: "BET-052", title: "Construction Equipment", school: "SOET" },
  { code: "OET-012", title: "Lkkexh dhykxr vkSj dfVx", school: "SOET" },
  { code: "BET-013", title: "Chemistry", school: "SOET" },
  { code: "OET-013", title: "vij dfVx ea", school: "SOET" },
  { code: "BCE-034", title: "ESQ", school: "SOET" },
  { code: "BCE-024", title: "Construction Technology", school: "SOET" },
  { code: "OET-021", title: "vij flykbZ dk eyHkr", school: "SOET" },
  { code: "BCE-031", title: "Advanced Survey", school: "SOET" },
  { code: "BCE-032", title: "", school: "SOET" },
  { code: "OET-022", title: "vij oukuk vkj", school: "SOET" },
  { code: "BCE-041", title: "Theory of Structures", school: "SOET" },
  { code: "OETL-023", title: "trs ds vij flykbZ dk iz", school: "SOET" },
  { code: "BCE", title: "", school: None },
  { code: "BETL-022", title: "Lab", school: "SOET" },
  { code: "BCE-044", title: "Concrete Technology", school: "SOET" },
  { code: "NET-001", title: "CMSR LVkVj fdV", school: "SOET" },
  { code: "BCEE-052", title: "Construction Equipment", school: "SOET" },
  { code: "NET-002", title: "Motorcycle Service", school: "SOET" },
  { code: "BCE-061", title: "Irrigation Engineering", school: "SOET" },
  { code: "BCEE-061", title: "Pre", school: "SOET" },
  { code: "NET-003", title: "Motorcycle Repair and", school: "SOET" },
  { code: "BNA-011", title: "Applied Mathematics", school: "SOET" },
  { code: "BNA-012", title: "Applied Science", school: "SOET" },
  { code: "BNA-013", title: "Applied Electricity and", school: "SOET" },
  { code: "BME-023", title: "Advanced Manufacturing", school: "SOET" },
  { code: "BNA-014", title: "Navigation", school: "SOET" },
  { code: "BME-030", title: "Elective Course", school: "SOET" },
  { code: "BNA-015", title: "Navigation", school: "SOET" },
  { code: "BME-031", title: "Energy Conversion", school: "SOET" },
  { code: "BMEL-005", title: "Mechanical Engineering", school: "SOET" },
  { code: "BNA-016", title: "Cargo Handling Stowage", school: "SOET" },
  { code: "BME-050", title: "Engineering Materials", school: "SOET" },
  { code: "BET-22", title: "", school: "SOET" },
  { code: "BNA-017", title: "English", school: "SOET" },
  { code: "BET-036", title: "Technical Documentation", school: "SOET" },
  { code: "BNA-017", title: "English", school: "SOET" },
  { code: "OET-011", title: "Basics of Shoe Upper Cutting", school: "SOET" },
  { code: "BNAL-011", title: "Applied Sciences Laboratory", school: "SOET" },
  { code: "OET-012", title: "Material Costing and Cutting", school: "SOET" },
  { code: "BNAL-012", title: "Computer Laboratory", school: "SOET" },
  { code: "OETL-013", title: "Practical in Shoe Upper", school: "SOET" },
  { code: "BNA-031", title: "Ship Safety", school: "SOET" },
  { code: "BNA-041", title: "NavigationalAids and", school: "SOET" },
  { code: "OET-021", title: "Basics of Upper Stitching", school: "SOET" },
  { code: "BNA-051", title: "Ship Manoeuvring", school: "SOET" },
  { code: "OET-022", title: "Upper Assembly and Future Issue", school: "SOET" },
  { code: "ET-507(B)", title: "Waste Water Treatment", school: "SOET" },
  { code: "BPVI-004", title: "Food Processing and Engineering", school: "SOA" },
  { code: "ET-531(A)", title: "Earth", school: "SOET" },
  { code: "ET-531(B)", title: "Soil Sciences", school: "SOET" },
  { code: "ET-532(A)", title: "Hydrology", school: "SOET" },
  { code: "BPVI-005", title: "Food Microbiology", school: "SOA" },
  { code: "ET-532(B)", title: "Ground Water Development", school: "SOET" },
  { code: "BPVI-006", title: "Food Processing and", school: "SOA" },
  { code: "ET-533(A)", title: "Irrigation Engineering", school: "SOET" },
  { code: "ET-533(B)", title: "Open Channel Flow", school: "SOET" },
  { code: "ET-534(C)", title: "Water Resource Planning", school: "SOET" },
  { code: "BPVI-007", title: "Food Quality Testing", school: "SOA" },
  { code: "ET-535(A)", title: "Elementary Hydrology", school: "SOET" },
  { code: "ET-535(B)", title: "Hydraulic Structures", school: "SOET" },
  { code: "ET-536(A)", title: "Hydraulic Structures", school: "SOET" },
  { code: "BPVI-008", title: "Entrepreneurship and Marketing", school: "SOA" },
  { code: "ET-536(B)", title: "Hydraulic Structures", school: "SOET" },
  { code: "ET-537(A)", title: "Soil Conservation", school: "SOET" },
  { code: "BPVI-011", title: "Milk Production and Agronomy", school: "SOA" },
  { code: "ET-537(B)", title: "Agricultural Legislation", school: "SOET" },
  { code: "ET-571", title: "Laboratory", school: "SOET" },
  {
    code: "BPVI-012",
    title: "Dairy Equipment and Their Maintenance",
    school: "SOA",
  },
  { code: "ET-573", title: "Laboratory", school: "SOET" },
  { code: "ET-574", title: "Laboratory", school: "SOET" },
  { code: "BPVI-013", title: "Milk Processing and Packaging", school: "SOA" },
  { code: "ET-581(B)", title: "Inventory", school: "SOET" },
  { code: "BPVI-014", title: "Dairy Products", school: "SOA" },
  { code: "ET-581(C)", title: "Building Services", school: "SOET" },
  { code: "BPVI-015", title: "Dairy Products", school: "SOA" },
  { code: "BPVI-001", title: "Food Fundamentals", school: "SOA" },
  { code: "BPVI-016", title: "Dairy Products", school: "SOA" },
  { code: "BPVI-002", title: "Principles of Post Harvest", school: "SOA" },
  {
    code: "BPVI-017",
    title: "QualityAssurance Management of Fruits",
    school: "SOA",
  },
  { code: "BPVI-018", title: "Dairy Management and Qy oa lfCt", school: "SOA" },
  { code: "BPVI-021", title: "Fundamentals of Food", school: "SOA" },
  { code: "BPVI-003", title: "Food Chemistry and Meat Science", school: "SOA" },
  { code: "BPVI-022", title: "MeatAnimals andAbattair dkf", school: "SOA" },
  { code: "BPVI-023", title: "Fresh Meat Technology", school: "SOA" },
  {
    code: "BPVI-036",
    title: "Processing of Pulses and Oil Seeds",
    school: "SOA",
  },
  { code: "BPVI-024", title: "Processed Meat nkyk", school: "SOA" },
  { code: "BAPI-001", title: "Organic Production System", school: "SOA" },
  { code: "BPVI-037", title: "Food Quality Testing and", school: "SOA" },
  {
    code: "BAPI-002",
    title: "Inspection and Certification Evaluation of Organic Produce",
    school: "SOA",
  },
  {
    code: "BAPI-003",
    title: "Economics and Marketing of Organic Produce",
    school: "SOA",
  },
  { code: "BPVI-038", title: "Entrepreneurship and Marketing", school: "SOA" },
  { code: "BLPI-001", title: "Introduction to Sericulture", school: "SOA" },
  { code: "BLP-004", title: "Crop Production", school: "SOA" },
  { code: "BPVI-027", title: "Utilization ofAnimal By", school: "SOA" },
  {
    code: "BAP-001",
    title: "Introduction to Organic Manual) Farming",
    school: "SOA",
  },
  { code: "BPVI-028", title: "Marketing and", school: "SOA" },
  {
    code: "NPV-001",
    title: "Awareness Programme Entrepreneurship",
    school: "SOA",
  },
  {
    code: "MNR-001",
    title: "IndianAgricultural Qyka rFkk lfCt",
    school: "SOA",
  },
  { code: "MNR-002", title: "Agriculture Policy", school: "SOA" },
  { code: "BLPI-002", title: "Host Plants Cultivation", school: "SOA" },
  { code: "BLPI-003", title: "Silkworm Reasing", school: "SOA" },
  { code: "MNRE-015", title: "Cooperatives and", school: "SOA" },
  { code: "NEX-01", title: "M", school: "SOA" },
  { code: "MNRE-016", title: "Project Analysis", school: "SOA" },
  {
    code: "BPVI-025",
    title: "Meat Packaging and Quantity Assurance",
    school: "SOA",
  },
  { code: "OLP-001", title: "Introduction to Poultry Farming", school: "SOA" },
  { code: "BPVI-026", title: "Poultry Products Technology", school: "SOA" },
  { code: "OLPI-001", title: "Poultry Housing and", school: "SOA" },
  { code: "BPVI-031", title: "Food Fundamentals", school: "SOA" },
  { code: "OLPI-002", title: "Poultry Feeds and Feeding", school: "SOA" },
  { code: "BPVI-032", title: "Food Microbiology", school: "SOA" },
  { code: "OLPI-002", title: "Poultry Feeds and Feeding", school: "SOA" },
  {
    code: "BPVI-033",
    title: "Milling of Wheat Maize and Coarse Grains",
    school: "SOA",
  },
  { code: "OLPL-001", title: "Poultry Health Care and", school: "SOA" },
  { code: "BPVI-034", title: "Baking and Flour", school: "SOA" },
  { code: "OLPL-002", title: "Poultry Farm Training", school: "SOA" },
  { code: "ONR-001", title: "Introduction to Water Harvesting", school: "SOA" },
  { code: "BPVI-035", title: "Padding Processing", school: "SOA" },
  { code: "ONR-002", title: "Basics of Hydrology", school: "SOA" },
  { code: "BLP-001", title: "(English)", school: "SOA" },
  { code: "ONR-003", title: "Water Harvesting ", school: "SOA" },
  { code: "BLP-001", title: "(Hindi)", school: "SOA" },
  { code: "MVPP", title: "", school: None },
  { code: "ONRL-001", title: "Practical Training at Water", school: "SOA" },
  { code: "MAM-001", title: "Introduction to Plantation", school: "SOA" },
  { code: "MDE-411", title: "Growth", school: None },
  { code: "MAM-002", title: "Crop Production", school: "SOA" },
  { code: "MDE-413", title: "Learner Support Technology", school: None },
  { code: "MAM-003", title: "Post Harvest Management", school: "SOA" },
  {
    code: "MDE-414",
    title: "Management of Distance and Value Addition Education",
    school: None,
  },
  { code: "MAM-004", title: "Human Resource ", school: "SOA" },
  { code: "MDE-415", title: "Research for Distance Marketing", school: None },
  { code: "MDE-416", title: "Curriculum Development", school: None },
  { code: "MAMP-001", title: "Project Handbook", school: "SOA" },
  { code: "MVP-001", title: "Food Fundamentals and", school: "SOA" },
  {
    code: "MDE-418",
    title: "Educational Communication Chemistry Technologies",
    school: None,
  },
  { code: "MVPI-001", title: "Food Microbiology", school: "SOA" },
  { code: "MDE-419", title: "Staff Training", school: None },
  { code: "MVP-002", title: "Food Laws and Standards", school: "SOA" },
  { code: "MVP-003", title: "Principles of Food Safety", school: "SOA" },
  { code: "MDEP-420", title: "Project Work", school: None },
  { code: "MVP-004", title: "Food Safety and Quality", school: "SOA" },
  { code: "MVPL-001", title: "Food Safety and Quality", school: "SOA" },
  { code: "ATR-1", title: "Translation Management Systems O", school: "SOH" },
  { code: "MVPL-002", title: "Chemical Analysis and", school: "SOA" },
  { code: "AFW-1", title: "Feature Writing", school: "SOH" },
  { code: "AWRE-01", title: "Writing for Radio", school: "SOH" },
  { code: "BEG-004", title: "English in Daily Life", school: "SOH" },
  { code: "BAPI-003", title: "tSfod mit dh vFkZO", school: "SOA" },
  { code: "BEG-005", title: "English in Education", school: "SOH" },
  { code: "BEG-006", title: "Joining the Work Force", school: "SOH" },
  { code: "BAP-001", title: "tSfod", school: "SOA" },
  { code: "BEGE-101", title: "From Language to", school: "SOH" },
  { code: "BAPI-001", title: "TSkfod mRiknu iz", school: "SOA" },
  { code: "BAPI-002", title: "tSfod mit dk fujh", school: "SOA" },
  { code: "BEGE-102", title: "The Structure of  oa izek", school: "SOH" },
  { code: "BEGE-103", title: "Communication Skills in English", school: "SOH" },
  { code: "BEGE-104", title: "English for Business", school: "SOH" },
  { code: "MEG-10", title: "English Studies in India", school: "SOH" },
  { code: "MEG-10", title: "Reader", school: "SOH" },
  { code: "BEGE-105", title: "Understanding Prose", school: "SOH" },
  { code: "MEG-11", title: "American Novel", school: "SOH" },
  { code: "BEGE-106", title: "Understanding Poetry", school: "SOH" },
  { code: "MEG-12", title: "A Survey Course in", school: "SOH" },
  { code: "BEGE-108", title: "Reading the Novel", school: "SOH" },
  { code: "MEG-14", title: "Contemporary Indian", school: "SOH" },
  {
    code: "DCE-1",
    title: "General Principles of Literature in English Writing",
    school: "SOH",
  },
  { code: "DCE-2", title: "Feature Writing", school: "SOH" },
  { code: "MEG-14", title: "Reader", school: "SOH" },
  { code: "DCE-3", title: "Short Story", school: "SOH" },
  { code: "BHDE-101", title: "fgnh ea sfPNd", school: "SOH" },
  { code: "DCE-4", title: "Writing for Media Radio ikB", school: "SOH" },
  { code: "EHD-02", title: "fgUnh dkO", school: "SOH" },
  { code: "DCE-5", title: "Writing Poetry", school: "SOH" },
  { code: "EHD-03", title: "fgnh lkfgR", school: "SOH" },
  { code: "FEG-01", title: "Foundation Course  oa lkfgR", school: "SOH" },
  { code: "EHD-04", title: "e", school: "SOH" },
  { code: "FEG-02", title: "Foundation Course lkfgR", school: "SOH" },
  { code: "CTE-01", title: "The Language Learner", school: "SOH" },
  { code: "EHD-05", title: "vk", school: "SOH" },
  { code: "CTE-02", title: "The Structure of English", school: "SOH" },
  { code: "CTE-03", title: "Teaching Strategies", school: "SOH" },
  { code: "BHDE-106", title: "fgnh Hkkkk", school: "SOH" },
  { code: "CTE-04", title: "Teaching English", school: "SOH" },
  { code: "BHDE-107", title: "fgnh ljpuk", school: "SOH" },
  { code: "CTE-05", title: "Teaching English", school: "SOH" },
  { code: "BHDE-108", title: "iz", school: "SOH" },
  { code: "BHDA-101", title: "lekpkj y", school: "SOH" },
  { code: "MEG-01", title: "British Poetry", school: "SOH" },
  { code: "MEG-02", title: "British Drama", school: "SOH" },
  { code: "BHDF-101", title: "fgUnh ea vk", school: "SOH" },
  { code: "MEG-03", title: "The British Novel", school: "SOH" },
  { code: "FHD-02", title: "fgUnh ea vk", school: "SOH" },
  { code: "MEG-04", title: "Aspects of Language", school: "SOH" },
  { code: "BRPA-101", title: "jfM", school: "SOH" },
  { code: "MEG-05", title: "Literary Criticism and", school: "SOH" },
  { code: "BSKF-01", title: "lLdr ea vk", school: "SOH" },
  { code: "MEG-06", title: "American Literature", school: "SOH" },
  { code: "MHD-01", title: "fgUnh dkO", school: "SOH" },
  { code: "MEG-07", title: "Indian English Literature", school: "SOH" },
  { code: "MHD-02", title: "vk", school: "SOH" },
  { code: "MEG-07", title: "Reader", school: "SOH" },
  { code: "MHD-03", title: "miU", school: "SOH" },
  { code: "MEG-08", title: "New Literatures in English", school: "SOH" },
  { code: "MHD-04", title: "UkkVd vkSj vU", school: "SOH" },
  { code: "MEG-09", title: "Australian Literature", school: "SOH" },
  { code: "MHD-05", title: "lkfgR", school: "SOH" },
  {
    code: "MBP-001",
    title: "Introduction to Publishing lekykpuk",
    school: "SOH",
  },
  { code: "MHD-06", title: "fgUnh Hkkkk vkSj lkfgR", school: "SOH" },
  { code: "MBP-002", title: "Editing and Pre", school: "SOH" },
  { code: "MBP-003", title: "Production", school: "SOH" },
  { code: "MHD-07", title: "Hkkkk foKku vkSj fgUnh Hkkkk", school: "SOH" },
  { code: "MBP-004", title: "Marketing", school: "SOH" },
  { code: "MHD-09", title: "dgkuh dk Lo", school: "SOH" },
  { code: "MBP-005", title: "Editing Books for Children", school: "SOH" },
  { code: "MHD-11", title: "fgUnh dgkuh", school: "SOH" },
  { code: "MBP-006", title: "Editing Scientific", school: "SOH" },
  { code: "MHD-13", title: "miU", school: "SOH" },
  { code: "MBP-007", title: "Editing Textbooks", school: "SOH" },
  { code: "MHD-14", title: "fgUnh miU", school: "SOH" },
  { code: "MBP-008", title: "Training Manual", school: "SOH" },
  { code: "BBHF-001", title: "Bhojpuri", school: "SOH" },
  { code: "MHD-15", title: "fgUnh miU", school: "SOH" },
  { code: "BULE-001", title: "(Urdu)", school: "SOH" },
  { code: "MHD-16", title: "Hkkjrh", school: "SOH" },
  { code: "BULE-002", title: "(Urdu)", school: "SOH" },
  { code: "MHD-21", title: "ehjk dk fo'kk v", school: "SOH" },
  {
    code: "FAS-01",
    title: "Foundation Course in SCHOOL OF LAW (SOL) Assamese",
    school: "SOH",
  },
  { code: "MIR-011", title: "Cyberspace Technology and", school: "SOL" },
  {
    code: "FBG-01",
    title: "Foundation Course in Social Issues",
    school: "SOH",
  },
  { code: "MIR-012", title: "Regulation of Cyberspace", school: "SOL" },
  { code: "FGT-01", title: "Foundation Course in", school: "SOH" },
  { code: "MIR-013", title: "Commerce and Cyberspace", school: "SOL" },
  { code: "MIR-014", title: "Privacy and Data Protection", school: "SOL" },
  { code: "FKD-01", title: "Foundation Course in Kanada", school: "SOH" },
  { code: "CHR-11", title: "Human Rights", school: "SOL" },
  { code: "FMT-01", title: "Foundation Course in ekuo vf", school: "SOH" },
  { code: "FML-01", title: "Foundation Course in", school: "SOH" },
  { code: "CHR-12", title: "Human Rights in India", school: "SOL" },
  { code: "FOR-01", title: "Foundation", school: "SOH" },
  { code: "MIR-021", title: "Overview of Intellectual", school: "SOL" },
  { code: "FPB-01", title: "Foundation Course in", school: "SOH" },
  { code: "MIR-022", title: "International Framework for", school: "SOL" },
  { code: "FTG-01", title: "Foundation Course in", school: "SOH" },
  { code: "MIR-023", title: "Indian Patent Law and", school: "SOL" },
  { code: "FTM-01", title: "Foundation Course in", school: "SOH" },
  { code: "MIRP-001", title: "Project Handbook", school: "SOL" },
  { code: "CPI", title: "Consumer Protection Issues", school: None },
  { code: "FUD-01", title: "Foundation Course in Urdu", school: "SOH" },
  { code: "ACS-01", title: "Application Oriented Course", school: "SOL" },
  { code: "MLE-024", title: "National Environmental", school: "SOL" },
  {
    code: "MLE-025",
    title: "National Legal Frameworks and Processes",
    school: "SOL",
  },
  {
    code: "BLEP-001",
    title: "Clinical Course on Legal Research Writing",
    school: "SOL",
  },
  { code: "MLE-026", title: "Environment Protection Advocacy", school: "SOL" },
  { code: "BLE-001", title: "Introduction to the Indian", school: "SOL" },
  { code: "MLEP-027", title: "Project", school: "SOL" },
  { code: "BLE-031", title: "Understanding Human", school: "SOL" },
  { code: "BLE-002", title: "Introduction to Law", school: "SOL" },
  { code: "BLE-003", title: "Law", school: "SOL" },
  {
    code: "BLE-032",
    title: "Law Policies and Institutional Groups",
    school: "SOL",
  },
  { code: "BLE-004", title: "Rural Local Self dkuuh uhfr", school: "SOL" },
  { code: "BLE-011", title: "Co", school: "SOL" },
  { code: "BLE-033", title: "Rehabilitation and", school: "SOL" },
  { code: "BLE-012", title: "Co", school: "SOL" },
  { code: "BLE-035", title: "Understanding International", school: "SOL" },
  {
    code: "BLE-013",
    title: "Business Law asApplicable Humanitarian Law",
    school: "SOL",
  },
  { code: "BLE-036", title: "Application of IHL", school: "SOL" },
  { code: "BLE-014", title: "Business Law asApplicable to Co", school: "SOL" },
  {
    code: "BLE-037",
    title: "IHL Issues of Concern in SouthAsia",
    school: "SOL",
  },
  { code: "MLE-011", title: "Criminal Justice System", school: "SOL" },
  { code: "MIP-101", title: "General Introduction to", school: "SOL" },
  { code: "MLE-012", title: "Indian Penal Code", school: "SOL" },
  { code: "MLE-013", title: "Criminal Justice Processes", school: "SOL" },
  { code: "MIP-102", title: "Patents", school: "SOL" },
  { code: "MLE-014", title: "Criminal JusticeAdministration", school: "SOL" },
  { code: "MIP-103", title: "(English)", school: "SOL" },
  {
    code: "MLE-015",
    title: "Challenges to Criminal Layout Designs of Justice System",
    school: "SOL",
  },
  {
    code: "MLE-016",
    title: "Criminal Justice Research and Advocacy",
    school: "SOL",
  },
  { code: "MIP-104", title: "Trademarks Domain", school: "SOL" },
  { code: "MLEP-017", title: "Clinical Course Project", school: "SOL" },
  { code: "MLE-021", title: "Introduction to Environment", school: "SOL" },
  { code: "MIP-105", title: "Copyrights and Related", school: "SOL" },
  {
    code: "MLE-022",
    title: "Introduction to Environment Rights Law and Policy",
    school: "SOL",
  },
  { code: "MIP-106", title: "Plant Varieties Protection", school: "SOL" },
  {
    code: "MLE-023",
    title: "International Environmental Biotechnology and Law and Policy",
    school: "SOL",
  },
  { code: "MIP-107", title: "Trade Secrets ", school: "SOL" },
  { code: "BOS-001", title: "B", school: "SOHS" },
  { code: "BOS-002", title: "B", school: "SOHS" },
  { code: "MIP-108", title: "Management of IPRS", school: "SOL" },
  { code: "BOS-003", title: "B", school: "SOHS" },
  { code: "BOS-004", title: "B", school: "SOHS" },
  {
    code: "MCC-001",
    title: "Fundamentals of Ophthalmic Techniques Cardiovascular System",
    school: "SOHS",
  },
  { code: "BOS-005", title: "B", school: "SOHS" },
  {
    code: "MCC-002",
    title: "Fundamentals of Ophthalmic Techniques Cardiovascular System",
    school: "SOHS",
  },
  { code: "MME-005", title: "Clinical Geriatrics", school: "SOHS" },
  { code: "MCC-003", title: "Common Cardiovascular Diseases", school: "SOHS" },
  { code: "MMEL-005", title: "Clinical Geriatrics Practical", school: "SOHS" },
  { code: "MCC-004", title: "Common Cardiovascular", school: "SOHS" },
  { code: "MME-004", title: "Basic Geriatrics", school: "SOHS" },
  { code: "MMEL-004", title: "Basic Geriatrics", school: "SOHS" },
  { code: "MCC-005", title: "Common Cardiovascular Diseases", school: "SOHS" },
  { code: "BNS-101", title: "Nursing Foundation", school: "SOHS" },
  { code: "MCC-006", title: "Preventive Cardiology", school: "SOHS" },
  { code: "BNSL-101", title: "Nursing Foundation", school: "SOHS" },
  { code: "MCC-007", title: "Cardiovascular Related", school: "SOHS" },
  { code: "BNS-102", title: "Applied Sciences", school: "SOHS" },
  { code: "BNSL-102", title: "Applied Sciences", school: "SOHS" },
  { code: "MCCL-001", title: "Cardiovascular Evaluation", school: "SOHS" },
  { code: "BNS-103", title: "Maternal Health Nursing", school: "SOHS" },
  { code: "MCCL-002", title: "Cardiovascular Evaluation", school: "SOHS" },
  { code: "BNSL-103", title: "Maternal Health Nursing", school: "SOHS" },
  { code: "MCCL-003", title: "Management of Common", school: "SOHS" },
  { code: "BNS-105", title: "Behavioural Sciences", school: "SOHS" },
  { code: "BNSL-105", title: "Behavioural Sciences", school: "SOHS" },
  {
    code: "MCCL-004",
    title: "Management of Congenital Heart Diseases",
    school: "SOHS",
  },
  { code: "BNS-106", title: "Medical Surgical Nursing", school: "SOHS" },
  { code: "MCCL-005", title: "Preventive Cardiology", school: "SOHS" },
  {
    code: "BNSL-106",
    title: "MedicalSurgicalNursing Practice",
    school: "SOHS",
  },
  { code: "MCCL-006", title: "Intensive Coronary Care", school: "SOHS" },
  { code: "BNS-107", title: "Paediatric Nursing", school: "SOHS" },
  { code: "MME-201", title: "Preventive MCH", school: "SOHS" },
  { code: "BNSL-107", title: "Paediatric Nursing", school: "SOHS" },
  { code: "MMEL-201", title: "Preventive MCH (Practical", school: "SOHS" },
  { code: "BNS-108", title: "Mental Health Nursing", school: "SOHS" },
  { code: "MME-202", title: "Reproductive Health", school: "SOHS" },
  { code: "BNSL-108", title: "Mental Health Nursing", school: "SOHS" },
  { code: "BNS-109", title: "Community Health Nursing", school: "SOHS" },
  { code: "MMEL-202", title: "Reproductive Health", school: "SOHS" },
  { code: "BNSL-109", title: "Community Health Nursing", school: "SOHS" },
  { code: "MME-203", title: "Child Health", school: "SOHS" },
  { code: "BNS-110", title: "NursingAdministration", school: "SOHS" },
  { code: "MMEL-203", title: "Child Health (Practical ", school: "SOHS" },
  { code: "BNSL-110", title: "NursingAdministration and", school: "SOHS" },
  { code: "BNS-111", title: "Nursing Education and", school: "SOHS" },
  { code: "BNS-014", title: "Resource Management", school: "SOHS" },
  { code: "BNSL-012", title: "Nursing Service", school: "SOHS" },
  {
    code: "BNSL-111",
    title: "Nursing Education and Administration",
    school: "SOHS",
  },
  { code: "BNSL-011", title: "Nursing Service", school: "SOHS" },
  { code: "BNSL-112", title: "Computer in Nursing", school: "SOHS" },
  { code: "BNS-104", title: "Communicative English", school: "SOHS" },
  { code: "BNS-013", title: "Group Dynamics", school: "SOHS" },
  { code: "BNSL", title: "", school: None },
  { code: "BNS-012", title: "Management of Educational", school: "SOHS" },
  { code: "BNSL-017", title: "Institute Hospital and", school: "SOHS" },
  { code: "BNSL-016", title: "Nursing Practices and", school: "SOHS" },
  { code: "BNS-011", title: "Principles and Practices of", school: "SOHS" },
  { code: "MDTL-001", title: "Practical of Fundamental", school: "SOHS" },
  { code: "BHM-01", title: "Fundamentals", school: "SOHS" },
  { code: "MDTL-002", title: "Practical of Fundamental", school: "SOHS" },
  { code: "BHM-02", title: "Health Care Waste", school: "SOHS" },
  { code: "MDT-003", title: "Clinical Endodontics", school: "SOHS" },
  { code: "BNS-001", title: "Community Heath", school: "SOHS" },
  { code: "MDT-002", title: "Clinical Endodontics", school: "SOHS" },
  { code: "BNSL-001", title: "Community Health", school: "SOHS" },
  {
    code: "MDT-001",
    title: "Fundamentals of (Practical Manual) Endodontics",
    school: "SOHS",
  },
  { code: "BNS-002", title: "Reproductive", school: "SOHS" },
  { code: "MDTL-004", title: "Implantology I", school: "SOHS" },
  { code: "BNSL-002", title: "PracticalAspects of", school: "SOHS" },
  { code: "MDTL-004", title: "Practicals of Oral", school: "SOHS" },
  { code: "MDT-005", title: "Advanced Surgical", school: "SOHS" },
  {
    code: "BNS-003",
    title: "Community Health Implantology Service",
    school: "SOHS",
  },
  { code: "MDT-004", title: "Fundamentals of", school: "SOHS" },
  {
    code: "BNSL-003",
    title: "Community Health Implantology Service (PM)",
    school: "SOHS",
  },
  { code: "BNS-002", title: "Reproductive and", school: "SOHS" },
  { code: "BNS-004", title: "Management of", school: "SOHS" },
  { code: "BNSL-004", title: "Management of", school: "SOHS" },
  { code: "BNS-017", title: "Community Health Community", school: "SOHS" },
  { code: "BNSL-015", title: "Integrated Management", school: "SOHS" },
  {
    code: "CHEP-01",
    title: "PracticalAspects of of Sick New Born Environment",
    school: "SOHS",
  },
  { code: "CHET-01", title: "Our Environment", school: "SOHS" },
  { code: "BNS-015", title: "Nursing Care of New", school: "SOHS" },
  { code: "CHET-02", title: "Promoting Health", school: "SOHS" },
  { code: "BOSL", title: "", school: None },
  { code: "CRSI-01", title: "Basics", school: "SOHS" },
  { code: "BOSL", title: "", school: None },
  { code: "CRSI-02", title: "Speciality Surgery", school: "SOHS" },
  { code: "CPE", title: "", school: None },
  { code: "CRSI-03", title: "General Surgery", school: "SOHS" },
  { code: "CPE", title: "", school: None },
  { code: "CRSI-04", title: "Orthopaedics", school: "SOHS" },
  { code: "MHMI-11", title: "", school: "SOHS" },
  { code: "CRSI-05", title: "ENT", school: "SOHS" },
  { code: "MHMI-12", title: "", school: "SOHS" },
  { code: "CRSI-06", title: "Obstetrics", school: "SOHS" },
  { code: "MHMI-13", title: "", school: "SOHS" },
  { code: "PGDHHM-01", title: "Introduction to", school: "SOHS" },
  { code: "MHM-10", title: "", school: "SOHS" },
  { code: "CNSHC", title: "", school: None },
  { code: "PGDHHM-02", title: "Introduction to Management", school: "SOHS" },
  { code: "CNSHC-001", title: "", school: "SOHS" },
  {
    code: "PGDHHM-03",
    title: "Organisation and oMf aHnoasgpeitmalesnt",
    school: "SOHS",
  },
  { code: "PGDHHM-04", title: "Clinical Diagnostic", school: "SOHS" },
  { code: "MFN-001", title: "Applied Physiology", school: "SOCE" },
  { code: "MFN-002", title: "Nutritional Biochemistry", school: "SOCE" },
  { code: "PGDHHM-05", title: "Support and", school: "SOHS" },
  {
    code: "MFN-003",
    title: "Food Microbiology and Utility Services",
    school: "SOCE",
  },
  { code: "MFN-004", title: "Advance Nutrition", school: "SOCE" },
  { code: "PGDHHM-06Health", title: "System Management", school: "SOHS" },
  {
    code: "MFN-005",
    title: "Clinical and Therapeutic Nutrition",
    school: "SOCE",
  },
  { code: "DNHE-02", title: "Public Health and Hygienic", school: "SOCE" },
  { code: "MFN-006", title: "Public Nutrition", school: "SOCE" },
  { code: "DNHE-04", title: "Project Work", school: "SOCE" },
  { code: "MFN-007", title: "Entrepreneurship", school: "SOCE" },
  { code: "BOS-007", title: "Visual Optics", school: "SOHS" },
  { code: "MFN-008", title: "Principles of Food Science", school: "SOCE" },
  { code: "BOS-008", title: "Dispensing Optics", school: "SOHS" },
  { code: "BOS-009", title: "Basic Orthotics", school: "SOHS" },
  { code: "MFN-009", title: "The Search Methods", school: "SOCE" },
  { code: "BOS-010", title: "Ocular Diseases", school: "SOHS" },
  { code: "MFN-010", title: "Understanding Computer", school: "SOCE" },
  { code: "PGDHHM", title: "Log Book", school: None },
  { code: "BOS-15", title: "", school: "SOHS" },
  { code: "MFNL-002", title: "Nutritional Biochemistry", school: "SOCE" },
  { code: "BOS-14", title: "", school: "SOHS" },
  { code: "MFNL-003", title: "Food Microbiology", school: "SOCE" },
  { code: "BOS-13", title: "", school: "SOHS" },
  { code: "MFNL-004", title: "Advance Nutrition", school: "SOCE" },
  { code: "BOS-11", title: "", school: "SOHS" },
  { code: "MFNL-005", title: "Clinical", school: "SOCE" },
  { code: "BOSL", title: "", school: None },
  { code: "MFNL-006", title: "Public Nutrition", school: "SOCE" },
  { code: "BOSL", title: "", school: None },
  { code: "MFNL-007", title: "Entrepreneurship", school: "SOCE" },
  {
    code: "MRDE-004",
    title: "Entrepreneurship and Service Management Rural Development",
    school: "SOCE",
  },
  { code: "MFNL-008", title: "Principles of Food Services", school: "SOCE" },
  { code: "CNCC-1", title: "Nutrition for the", school: "SOCE" },
  { code: "MFNP-011", title: "Internship", school: "SOCE" },
  { code: "MFNP-012", title: "Dissertation", school: "SOCE" },
  { code: "JMC-01", title: "Introduction to Journalism", school: "SOCE" },
  { code: "CNCC-2", title: "Organizing Child Care", school: "SOCE" },
  { code: "JMC-02", title: "Mass Media and Society", school: "SOCE" },
  { code: "JMC-03", title: "Reporting Writing", school: "SOCE" },
  { code: "CNCC-2", title: "Organizing Child Care Services", school: "SOCE" },
  { code: "JMC-04", title: "Public Relations", school: "SOCE" },
  { code: "RDD-5", title: "Research and Project Work", school: "SOCE" },
  { code: "RDD-6", title: "Rural Health Care", school: "SOCE" },
  { code: "MRDP-001", title: "Project Work Handbook", school: "SOCE" },
  { code: "RDD-7", title: "Communication", school: "SOCE" },
  { code: "MRDE-101", title: "Rural Social Development", school: "SOCE" },
  { code: "BFN-001", title: "Hazards to Food Safety", school: "SOCE" },
  { code: "MRDE", title: "", school: None },
  { code: "BFN-002", title: "Hazards to Food Safety", school: "SOCE" },
  { code: "MRDE-002", title: "Volntary Action in Rurla", school: "SOCE" },
  { code: "BFN-003", title: "Food Safety and Quality", school: "SOCE" },
  { code: "MRD-101", title: "Rural Development", school: "SOCE" },
  {
    code: "MRDE-003",
    title: "Land Reforms and Rural Development",
    school: "SOCE",
  },
  {
    code: "MRD-103",
    title: "Rural Development Hkfe fodkl vkSj Planning and Management",
    school: "SOCE",
  },
  { code: "DNHE-1", title: "Nutrition for the vkSj izca", school: "SOCE" },
  { code: "MFNP-011", title: "Internship", school: "SOCE" },
  { code: "DNHE-2", title: "tu LokLF", school: "SOCE" },
  { code: "MFNP-012", title: "Dissertation", school: "SOCE" },
  { code: "MFNL-007", title: "Entrepreneurship", school: "SOCE" },
  {
    code: "DNHE-3",
    title: "Nutrition and Health and Food Service Education",
    school: "SOCE",
  },
  { code: "CNCC-1", title: "Nutrition for the", school: "SOCE" },
  { code: "DECE-3", title: "", school: "SOCE" },
  { code: "BWEE-002", title: "Gander Training Part", school: "SOSS" },
  { code: "BWEE-006", title: "Organization and", school: "SOSS" },
  { code: "AFE", title: "", school: None },
  { code: "BFEE-102", title: "", school: "SOCE" },
  { code: "BWEE-007", title: "Work and Enterpreneurship", school: "SOSS" },
  { code: "AFE", title: "", school: None },
  { code: "BFEE-103", title: "", school: "SOCE" },
  { code: "BWEE-008", title: "Credit and Finance", school: "SOSS" },
  { code: "AFE", title: "", school: None },
  { code: "DNHE-1", title: "Nutrition for the Community", school: "SOCE" },
  { code: "BFEE-104", title: "", school: "SOCE" },
  { code: "AFE", title: "", school: None },
  { code: "BFEP-01", title: "", school: "SOCE" },
  { code: "DNHE-02", title: "tu LokLF", school: "SOCE" },
  { code: "CFN-01", title: "You and Your Food", school: "SOCE" },
  { code: "CFN-02", title: "Your Food and its", school: "SOCE" },
  {
    code: "DNHE-03",
    title: "Nutrition and Health Utilization",
    school: "SOCE",
  },
  { code: "CFN-03", title: "Economics of Food", school: "SOCE" },
  { code: "DECE-01", title: "Organising Child Care", school: "SOCE" },
  { code: "DECE-02", title: "Child Health and Nutrition", school: "SOCE" },
  { code: "DECE-3", title: "cPpka ds fy lok", school: "SOCE" },
  { code: "DECE-03", title: "Services", school: "SOCE" },
  { code: "DNHE-4", title: "ifj", school: "SOCE" },
  { code: "DECE-04", title: "Project Work", school: "SOCE" },
  { code: "RDD-09", title: "vula", school: "SOCE" },
  { code: "ERD-01", title: "Rural Development in India", school: "SOCE" },
  { code: "MRDE-101", title: "xkeh", school: "SOCE" },
  { code: "NCD-001", title: "Awareness", school: "SOCE" },
  {
    code: "MRD-102",
    title: "Rural Development Package in Disability Programmes (Mental",
    school: "SOCE",
  },
  { code: "NCD-002", title: "Awareness", school: "SOCE" },
  { code: "RDD-06", title: "xkeh", school: "SOCE" },
  {
    code: "ACC-01",
    title: "Organising Child Care (Visual Impairment) Services",
    school: "SOCE",
  },
  { code: "NCD-003", title: "Awareness", school: "SOCE" },
  { code: "AFE", title: "", school: None },
  { code: "AFE", title: "", school: None },
  { code: "MRD-101", title: "xke fodkl", school: "SOCE" },
  { code: "AFE", title: "", school: None },
  { code: "MRD-004", title: "xke fodkl ea vula", school: "SOCE" },
  {
    code: "MRD-004",
    title: "Research Methods in Rural Development",
    school: "SOCE",
  },
  { code: "MCS-041", title: "Operating Systems", school: "SOCIS" },
  {
    code: "MCS-042",
    title: "Data Communication and Networks",
    school: "SOCIS",
  },
  {
    code: "MCS-011",
    title: "Problem Solving and Programming",
    school: "SOCIS",
  },
  {
    code: "MCS-043",
    title: "Advanced Database Management Systems",
    school: "SOCIS",
  },
  { code: "MCS-012", title: "Computer Organisation", school: "SOCIS" },
  { code: "MCS-044", title: "Mini Project", school: "SOCIS" },
  { code: "MCSL-045", title: "Lab (UNIX", school: "SOCIS" },
  { code: "MCS-013", title: "Discrete Mathematics", school: "SOCIS" },
  { code: "MCS-051", title: "Advanced Internet Technologies", school: "SOCIS" },
  { code: "MCS-014", title: "SystemAnalysis and Design", school: "SOCIS" },
  { code: "MCS-052", title: "Principles of Management", school: "SOCIS" },
  { code: "MCS-015", title: "Communication Skills", school: "SOCIS" },
  { code: "MCS-053", title: "Computer Graphics", school: "SOCIS" },
  {
    code: "MCSL-016",
    title: "Internet Concepts and Web Multimedia",
    school: "SOCIS",
  },
  { code: "MCSL-054", title: "Lab Course in", school: "SOCIS" },
  {
    code: "MCSL-017",
    title:
      "Lab (C and Assembly Advanced Internet Language Programming) Technologies and Course",
    school: "SOCIS",
  },
  { code: "MCS-021", title: "Data and File Structures", school: "SOCIS" },
  { code: "MCS-022", title: "Operating System Concepts", school: "SOCIS" },
  {
    code: "MCSE-003",
    title: "Artificial Intelligence and and Networking Knowledge Management",
    school: "SOCIS",
  },
  { code: "MCSE-004", title: "Numerical and Statistical", school: "SOCIS" },
  {
    code: "MCS-023",
    title: "Introduction to Database Computing",
    school: "SOCIS",
  },
  { code: "MCSE-011", title: "Parallel Computing", school: "SOCIS" },
  { code: "MCS-024", title: "Object Oriented Technology", school: "SOCIS" },
  { code: "BCS-011", title: "Computer Basics and", school: "SOCIS" },
  { code: "MCSL-025", title: "Lab Course (for Data", school: "SOCIS" },
  { code: "BCS-012", title: "Basic Mathematics", school: "SOCIS" },
  { code: "BCSL-013", title: "Computer Basics", school: "SOCIS" },
  { code: "MCS-031", title: "Design and Analysis of", school: "SOCIS" },
  { code: "BCSL-021", title: "C Language", school: "SOCIS" },
  { code: "MCS-032", title: "Object OrientedAnalysis", school: "SOCIS" },
  { code: "BCSL-022", title: "Assembly Language", school: "SOCIS" },
  { code: "MCS-033", title: "Advanced Discrete", school: "SOCIS" },
  { code: "BCS-031", title: "Programming in C", school: "SOCIS" },
  { code: "BCS-032", title: "C", school: "SOCIS" },
  { code: "MCS-034", title: "Software Engineering", school: "SOCIS" },
  { code: "BCSL-033", title: "Data and File", school: "SOCIS" },
  {
    code: "MCS-035",
    title: "Accountancy and Financial Structure Lab Management",
    school: "SOCIS",
  },
  { code: "BCSL-034", title: "Statistical Techniques", school: "SOCIS" },
  { code: "MCSL-036", title: "Lab Course", school: "SOCIS" },
  { code: "BCS-040", title: "Statistical Techniques", school: "SOCIS" },
  { code: "ES-333", title: "Educational Evaluation", school: "SOE" },
  { code: "BCS-041", title: "Fundamentals of", school: "SOCIS" },
  { code: "ES-334", title: "Education and Society", school: "SOE" },
  { code: "BCS-042", title: "Introductions", school: "SOCIS" },
  { code: "ES-335", title: "Teacher and School", school: "SOE" },
  { code: "BCSL-043", title: "Java Programming Lab", school: "SOCIS" },
  { code: "BCSL-044", title: "Statistical Techniques Lab", school: "SOCIS" },
  { code: "ES-341", title: "Teaching of Science", school: "SOE" },
  { code: "BCSL-045", title: "Algorithm Design Lab", school: "SOCIS" },
  { code: "BCS-051", title: "Introduction to Software", school: "SOCIS" },
  { code: "ES-342", title: "Teaching of Mathematics", school: "SOE" },
  { code: "BCS-052", title: "Network Programming", school: "SOCIS" },
  { code: "ES-343", title: "Teaching of Social Studies", school: "SOE" },
  { code: "BCS-053", title: "Web Programming", school: "SOCIS" },
  { code: "BCS-054", title: "Computer Oriented", school: "SOCIS" },
  { code: "ES-344", title: "Teaching of English", school: "SOE" },
  { code: "ES-345", title: "", school: "SOE" },
  { code: "BCS-055", title: "Business Communication", school: "SOCIS" },
  { code: "ES-361", title: "Educational Technology", school: "SOE" },
  { code: "BCSL-056", title: "Network Programming", school: "SOCIS" },
  { code: "BCSL-057", title: "Web Programming Lab", school: "SOCIS" },
  { code: "ES-362", title: "Computers in Education", school: "SOE" },
  { code: "BCSL-058", title: "Computer Oriented", school: "SOCIS" },
  { code: "ES-363", title: "Guidance and Counselling", school: "SOE" },
  { code: "BCS-062", title: "E", school: "SOCIS" },
  { code: "BCSL-063", title: "Operating Systems", school: "SOCIS" },
  { code: "ES-364", title: "Distance Education", school: "SOE" },
  { code: "MES-051", title: "Education", school: "SOE" },
  { code: "CIT-001", title: "Fundamentals of Computer", school: "SOCIS" },
  { code: "MES-052", title: "Psychology of Learning and", school: "SOE" },
  { code: "CIT-002", title: "Introduction to Information", school: "SOCIS" },
  { code: "MES-053", title: "Educational Management", school: "SOE" },
  { code: "CIT-003", title: "Web based Technologies", school: "SOCIS" },
  { code: "MES-054", title: "Methodology of Educational", school: "SOE" },
  { code: "CITL-001", title: "Laboratory Course", school: "SOCIS" },
  {
    code: "MES-111",
    title:
      "Growth and Philosophy of SCHOOL OF EDUCATION (SOE) Distance Education",
    school: "SOE",
  },
  { code: "ES-331", title: "Curriculum and Instruction", school: "SOE" },
  { code: "MES-056", title: "Educational Technology", school: "SOE" },
  { code: "MESE-057", title: "Measurement and Evaluation", school: "SOE" },
  { code: "ES-332", title: "Psychology of Development", school: "SOE" },
  { code: "MESE-058", title: "Educational and Vocational", school: "SOE" },
  { code: "MESE-059", title: "Teacher Education in Indian", school: "SOE" },
  { code: "NES-104", title: "Guiding Socio", school: "SOE" },
  { code: "MES-055", title: "Comparative Education", school: "SOE" },
  {
    code: "MES-015",
    title: "Operational Dimensions National and International of Education",
    school: "SOE",
  },
  { code: "MES-016", title: "Educational Research", school: "SOE" },
  { code: "MESE-060", title: "Curriculum Development", school: "SOE" },
  { code: "MES-031", title: "ET", school: "SOE" },
  { code: "ES-201", title: "Language Teaching", school: "SOE" },
  { code: "MES-032", title: "Communication and Hkkkk fdj", school: "SOE" },
  { code: "ES-202", title: "Curriculum Planning", school: "SOE" },
  { code: "MES-033", title: "Computer Technology", school: "SOE" },
  { code: "MES-034", title: "Designing Courseware", school: "SOE" },
  { code: "MES-112", title: "Design and Development of", school: "SOE" },
  { code: "ES-203", title: "Ik", school: "SOE" },
  { code: "MES-113", title: "Learner Support Services", school: "SOE" },
  { code: "ES-204", title: "LokLF", school: "SOE" },
  { code: "MES-114", title: "Management of Distance vkSj dk", school: "SOE" },
  { code: "ES-211", title: "izkFkfed Lrj ij", school: "SOE" },
  { code: "MES-115", title: "Communication Technology for f", school: "SOE" },
  { code: "ES-212", title: "izkFkfed fo", school: "SOE" },
  { code: "MESP-49", title: "Project Work", school: None },
  { code: "MES-005", title: "Human Resource Development", school: "SOE" },
  { code: "ES-213", title: "fok", school: "SOE" },
  { code: "MES-006", title: "Managing Teaching", school: "SOE" },
  { code: "ES-221", title: "izkFkfed fo", school: "SOE" },
  { code: "MES-007", title: "School Governance and", school: "SOE" },
  { code: "ES-222", title: "fodklksUe", school: "SOE" },
  { code: "MES-008", title: "Leadership for Better Schools", school: "SOE" },
  { code: "MES-101", title: "Higher Education", school: "SOE" },
  { code: "MES-047", title: "Distance and Open Learning", school: "SOE" },
  { code: "MES-105", title: "Project Work", school: "SOE" },
  { code: "MES-102", title: "Instruction in Higher Education", school: "SOE" },
  { code: "MES-011", title: "Understanding Education", school: "SOE" },
  { code: "MES-103", title: "Higher Education", school: "SOE" },
  { code: "MES-012", title: "Education", school: "SOE" },
  { code: "MES-104", title: "Planning", school: "SOE" },
  {
    code: "MES-013",
    title: "Learning Learner and Higher Education Development",
    school: "SOE",
  },
  { code: "NES-101", title: "Understanding the Elementary", school: "SOE" },
  { code: "MES-014", title: "Societal Context of Education", school: "SOE" },
  { code: "MES-045", title: "School Education", school: "SOE" },
  { code: "NES-102", title: "Facilitating Growth and", school: "SOE" },
  {
    code: "MESE-061",
    title: "Open and Distance Theory Learning Systems (Optional)",
    school: "SOE",
  },
  { code: "NES-103", title: "Guiding Children", school: "SOE" },
  { code: "ES-345", title: "fgnh f'k", school: "SOE" },
  { code: "BES-001", title: "(Diploma in Elementary", school: "SOE" },
  { code: "OVA-001", title: "Indian Cultural Heritage", school: "SOPVA" },
  { code: "OVA-002", title: "Understanding Indian", school: "SOPVA" },
  { code: "BES-002", title: "Diploma in Elementary", school: "SOE" },
  { code: "OVA-003", title: "An Introduction to IndianArts", school: "SOPVA" },
  {
    code: "BES-004",
    title: "Contemparary Indian Society and Education",
    school: "SOE",
  },
  {
    code: "OMU-001",
    title: "Introduction to Hindustan Music",
    school: "SOPVA",
  },
  { code: "BES-008", title: "Language and Early Literacy", school: "SOE" },
  { code: "OMU-005", title: "Introduction to", school: "SOPVA" },
  {
    code: "BES-009",
    title: "Teaching of Mathematics for Karnatak Music",
    school: "SOE",
  },
  { code: "ODN-001", title: "Introduction to Indian", school: "SOPVA" },
  {
    code: "BES-10",
    title: "Teaching of Environmental Dance Forms",
    school: "SOE",
  },
  { code: "OTH-001", title: "Introduction to Theatre", school: "SOPVA" },
  { code: "BES-016", title: "Life Enrichment and and Drama", school: "SOE" },
  { code: "MFC-001", title: "Folklore and Culture", school: "SOITS" },
  {
    code: "BES-017",
    title: "School Education Leadership Conceptual Perspectives",
    school: "SOE",
  },
  { code: "MFC-002", title: "Tradition Identity and", school: "SOITS" },
  { code: "BES-012", title: "Teaching of Mathematics", school: "SOE" },
  { code: "BES-018", title: "Teaching of Social Science", school: "SOE" },
  { code: "MFC-003", title: "Cultural and Societal", school: "SOITS" },
  { code: "BES-019", title: "Teaching of Science", school: "SOE" },
  { code: "BES-020", title: "Teaching of English", school: "SOE" },
  {
    code: "MES-01",
    title:
      "Teaching Learning Process SCHOOL OF VOCATIONAL EDUCATION and Evaluation",
    school: "SOE",
  },
  { code: "MES-02", title: "Life Enrichment and Self", school: "SOE" },
  {
    code: "BPOI-001",
    title: "Diploma in Business Development",
    school: "SOVET",
  },
  { code: "MES-03", title: "Foundation Course", school: "SOE" },
  { code: "MES-04", title: "Head Teaching as", school: "SOE" },
  { code: "BPOI-002", title: "Fundamental of School Leaders", school: "SOVET" },
  { code: "BPOI-003", title: "Procure to Pay ea e", school: "SOVET" },
  { code: "MES-06", title: "Managing Teaching", school: "SOE" },
  { code: "BPOI-004", title: "Order to Cash", school: "SOVET" },
  {
    code: "BPOI-006",
    title: "Social Skills on Business Commu nication",
    school: "SOVET",
  },
  {
    code: "MES-07",
    title: "School Governance and Financial Management",
    school: "SOE",
  },
  { code: "BPOI-007", title: "Diploma in Business fo", school: "SOVET" },
  { code: "MESE-061", title: "Open and Distance Theory", school: "SOE" },
  {
    code: "MVE-001",
    title: "Introduction toAnatomy  Learning Systems (Optional)",
    school: "SOSW",
  },
  { code: "MVE-002", title: "Pharmacology and", school: "SOSW" },
  {
    code: "MSW-002",
    title: "Origin and Development of Toxicology",
    school: "SOSW",
  },
  { code: "MVE-003", title: "Pharmaceutics", school: "SOSW" },
  { code: "MVE-004", title: "Drug Regulatory Affairs", school: "SOSW" },
  { code: "MSW-003", title: "Social Science Concepts for", school: "SOSW" },
  { code: "MVE-005", title: "Introduction and Social Workers", school: "SOSW" },
  { code: "MVE-006", title: "Sales Management", school: "SOSW" },
  { code: "MVEI-011", title: "Understanding the Learner", school: "SOVET" },
  { code: "MSW-004", title: "Social Work and Social", school: "SOSW" },
  {
    code: "MVEI-012",
    title: "Assertive and Adoptive Development",
    school: "SOVET",
  },
  { code: "MVEI-013", title: "Software for Visually", school: "SOVET" },
  { code: "MVEI-014", title: "Communication Skills", school: "SOVET" },
  { code: "MSW-005", title: "Social Work Practicum", school: "SOSW" },
  {
    code: "MVEI-021",
    title: "Education and Vocational Education",
    school: "SOVET",
  },
  { code: "MSW-006", title: "Social Work Research", school: "SOSW" },
  { code: "MVEI-022", title: "ICT for Vocational", school: "SOVET" },
  { code: "MSW-007", title: "Case Work", school: "SOSW" },
  { code: "MVEI-023", title: "Communication Skills", school: "SOVET" },
  { code: "MSW-008", title: "Social Group Work", school: "SOSW" },
  { code: "MVEI-024", title: "Pedagogy", school: "SOVET" },
  { code: "MSW-009", title: "Community of Organisation", school: "SOSW" },
  { code: "MSWE", title: "", school: None },
  { code: "BSWE-001", title: "Introduction to Social Work", school: "SOSW" },
  { code: "BSWL-001", title: "Field Work Journal", school: "SOSW" },
  { code: "MSWL-001", title: "Social Work Practicum", school: "SOSW" },
  { code: "BSWL", title: "Field Work Guide", school: None },
  { code: "MSWL-002", title: "Field Work Practicum", school: "SOSW" },
  {
    code: "BSWE-002",
    title: "Social Work Intervention (Practical)",
    school: "SOSW",
  },
  { code: "MSWP-001", title: "Project Work Hand Book on", school: "SOSW" },
  { code: "BSWL-002", title: "Field Work Journal", school: "SOSW" },
  { code: "BSWE-003", title: "Social Work Intervention with", school: "SOSW" },
  { code: "MVE-002", title: "Pharmacology and Toxicology", school: "SOSW" },
  { code: "MVE-003", title: "Pharmaceutics", school: "SOSW" },
  { code: "BSWL-003", title: "Field Work Journal", school: "SOSW" },
  { code: "MVE-004", title: "Drugs Regulatory Affairs", school: "SOSW" },
  {
    code: "BSWE-004",
    title: "Introduction to Family Education",
    school: "SOSW",
  },
  { code: "MVE-005", title: "Introduction to Management", school: "SOSW" },
  {
    code: "MSW-001",
    title: "Origin and Development of Social Work",
    school: "SOSW",
  },
  { code: "MVE-006", title: "Sales Management", school: "SOSW" },
  { code: "BSWE-005", title: "Introduction to HIV", school: "SOSW" },
  { code: "BSWE-006", title: "SubstanceAbuse and CounseLling", school: "SOSW" },
  { code: "BFE-101", title: "Basics of HIV", school: "SOSW" },
  {
    code: "MEDS-003",
    title: "Problems and Issues in Development",
    school: "SOEDS",
  },
  { code: "BFE-102", title: "Basics of Family Educations", school: "SOSW" },
  { code: "MAE-001", title: "Understanding", school: "SOEDS" },
  { code: "BFEE-101", title: "Elective on HIV", school: "SOCE" },
  { code: "BFEE-102", title: "Elective on Family Educations", school: "SOCE" },
  { code: "MAE-002", title: "Policy Planning and", school: "SOEDS" },
  { code: "BFEE", title: "", school: None },
  {
    code: "BFEE-104",
    title: "Communication and Counselling in HIV",
    school: "SOCE",
  },
  {
    code: "MAE-003",
    title:
      "Knowledge Management Information Dissemination and Networking inAdult Education",
    school: "SOEDS",
  },
  { code: "MAEL-001", title: "Practical Work Components", school: "SOEDS" },
  { code: "MEDS-005", title: "Planning and Management", school: "SOEDS" },
  { code: "MJM-001", title: "Introduction to Broadcasting", school: "SOJNMS" },
  { code: "MEDS-006", title: "Research Methods in", school: "SOEDS" },
  { code: "MJM-002", title: "Production and Presentation", school: "SOJNMS" },
  { code: "MJM-003", title: "Recording and Editing", school: "SOJNMS" },
  { code: "MEDSP-007", title: "Project Work", school: "SOEDS" },
  { code: "MJME-001", title: "Practical Manual", school: "SOJNMS" },
  { code: "MEDSP-004", title: "Project Work", school: "SOEDS" },
  {
    code: "CCR-BJM-001",
    title: "Introduction to Community Radio",
    school: "SOJNMS",
  },
  { code: "MEDSP-007", title: "Project Work", school: "SOEDS" },
  { code: "MEDS-010", title: "Training for Development", school: "SOEDS" },
  { code: "MAE-002", title: "Policy Planning and", school: "SOEDS" },
  { code: "CCR-BJMP-001", title: "Internship Manual", school: "SOJNMS" },
  { code: "CCR-BJM-002", title: "Operating a", school: "SOJNMS" },
  {
    code: "MAEL-001",
    title: "Practical Work Community Radio Components",
    school: "SOEDS",
  },
  { code: "MEDS-008", title: "Extension Communication", school: "SOEDS" },
  { code: "JMC-001", title: "", school: "SOCE" },
  { code: "JMC-002", title: "", school: "SOCE" },
  { code: "MEDS-009", title: "Development in India", school: "SOEDS" },
  { code: "JMC-003", title: "", school: "SOCE" },
  { code: "JMC-004", title: "", school: "SOCE" },
  { code: "MEDS-010", title: "Training for Development", school: "SOEDS" },
  { code: "MEDS-011", title: "Local Self Governance", school: "SOEDS" },
  { code: "MEDSE-015", title: "Family Healthcare", school: "SOEDS" },
  {
    code: "MEDS-001",
    title: "Introduction to Extension Education",
    school: "SOEDS",
  },
  { code: "BEDS-001", title: "Overview and", school: "SOEDS" },
  {
    code: "MEDS-002",
    title: "Dynamics of Extension Perspective of Values and Development",
    school: "SOEDS",
  },
  { code: "BEDS-002", title: "Socio", school: "SOEDS" },
  { code: "BEDS-003", title: "Pedagogy of Values", school: "SOEDS" },
  { code: "BEDS-004", title: "Application and Support", school: "SOEDS" },
  { code: "MFC-01", title: "Folklore and Culture", school: "SOITS" },
  { code: "MEDS-041", title: "Introduction to Urban", school: "SOEDS" },
  {
    code: "MFC-02",
    title: "Tradition Identity and Development Cultural Production",
    school: "SOITS",
  },
  { code: "MEDS-042", title: "Challenges in Urban", school: "SOEDS" },
  {
    code: "MFC-03",
    title: "Cultural and Societal Issues and Planning",
    school: "SOITS",
  },
  { code: "MFC-04", title: "Tribes of India", school: "SOITS" },
  { code: "MEDS-043", title: "Dynamics of Urban", school: "SOEDS" },
  { code: "MPYE-16", title: "Philosophy of Sri Aurobindo", school: "SOITS" },
  { code: "MEDS-044", title: "Monitoring and", school: "SOEDS" },
  { code: "MPYE-15", title: "Gandhian Philosophy", school: "SOITS" },
  { code: "MPYE-14", title: "Philosophy of Mind", school: "SOITS" },
  { code: "MPYE-13", title: "Philosophy of Technology", school: "SOITS" },
  { code: "MEDSP-045", title: "Post Graduate Diploma", school: "SOEDS" },
  { code: "MPYE-12", title: "Tribal Philosophy", school: "SOITS" },
  { code: "MPYE-11", title: "Philosophy of Art", school: "SOITS" },
  { code: "MEDSE-046", title: "Development Issues", school: "SOEDS" },
  { code: "MPYE-10", title: "Philosophy of Religion", school: "SOITS" },
  { code: "MEDSP-17", title: "Dissertation Handbook", school: "SOEDS" },
  { code: "MPYE-09", title: "Philosophy of Science", school: "SOITS" },
  { code: "MAEP-01", title: "Handbook in", school: "SOEDS" },
  { code: "MPYE-08", title: "Metaphysics", school: "SOITS" },
  { code: "MAE-004", title: "Extension Education", school: "SOEDS" },
  {
    code: "MPYE-07",
    title: "Research Methodology and Development in Philosophy",
    school: "SOITS",
  },
  { code: "MAEE-001", title: "Sustainable Development", school: "SOEDS" },
  { code: "MPYE-06", title: "Dalit Philosophy", school: "SOITS" },
  { code: "MAE-005", title: "(English)", school: "SOEDS" },
  { code: "MPYE-05", title: "World Religions", school: "SOITS" },
  {
    code: "MPYE-04",
    title: "Philosophy of Human Development Education Person",
    school: "SOITS",
  },
  { code: "MAEE-002", title: "Basics of Legal", school: "SOEDS" },
  { code: "MPYE-03", title: "Epistemology", school: "SOITS" },
  { code: "MPYE-02", title: "Ethics", school: "SOITS" },
  { code: "MPYE-01", title: "Logic", school: "SOITS" },
  { code: "MPY-01", title: "Indian Philosophy", school: "SOITS" },
  { code: "BAL-001", title: "Basics ofArabic", school: "SOFL" },
  { code: "MPY-02", title: "Western Philosophy", school: "SOITS" },
  { code: "BAL-002", title: "Communication Skills", school: "SOFL" },
  { code: "BPY-01", title: "Indian Philosophy", school: "SOITS" },
  { code: "DTG-001", title: "General Principles of Teaching", school: "SOFL" },
  { code: "BPY-02", title: "Logic", school: "SOITS" },
  { code: "BPY-003", title: "Ancient and Medieval", school: "SOITS" },
  { code: "MTT-17", title: "dk'kfoKku", school: "SOTST" },
  { code: "BPY-04", title: "Religions of the World", school: "SOITS" },
  { code: "MTT-20", title: "vuokn izf", school: "SOTST" },
  { code: "BPY-05", title: "Indian Philosophy", school: "SOITS" },
  { code: "MTT-21", title: "vuokn izf'k", school: "SOTST" },
  { code: "BPY-06", title: "Metaphysics", school: "SOITS" },
  { code: "PGDT-01", title: "vuokn", school: "SOTST" },
  { code: "BPY-07", title: "Ethics", school: "SOITS" },
  { code: "PGDT-02", title: "vuokn dk Hkkfkd vkj Philosophy", school: "SOTST" },
  { code: "BPY-09", title: "Contemporary Western", school: "SOITS" },
  { code: "PGDT-03", title: "O", school: "SOTST" },
  { code: "BPY-10", title: "Epistemology", school: "SOITS" },
  { code: "BPY-11", title: "Philosophy of Human", school: "SOITS" },
  { code: "PGDT-04", title: "iz", school: "SOTST" },
  {
    code: "BPY-12",
    title:
      "Philosophy of Science SCHOOL OF GENDER AND DEVELOPMENT and Cosmology",
    school: "SOITS",
  },
  { code: "BPYE-01", title: "Philosophy of Religion", school: "SOITS" },
  { code: "MWG-001", title: "Theories of Women", school: "SOGDS" },
  { code: "BPYE-02", title: "Tribal and Dalit Philosophy", school: "SOITS" },
  { code: "MWG-002", title: "Gender and Power", school: "SOGDS" },
  { code: "MWG-003", title: "Constructing Gender", school: "SOGDS" },
  { code: "MTT-001", title: "Hkkjrh", school: "SOTST" },
  { code: "MTT-002", title: "caXyk", school: "SOTST" },
  {
    code: "MWG-004",
    title: "Gendered Bodies and ryuk vkSj iqu",
    school: "SOGDS",
  },
  { code: "MTT-003", title: "caXyk vkSj fgnh ds fofHkUu", school: "SOTST" },
  { code: "MWGP-001", title: "Project Work Manuall", school: "SOGDS" },
  { code: "MWG-005", title: "Research Methods", school: "SOGDS" },
  { code: "MTT-004", title: "ey", school: "SOTST" },
  { code: "MWG-006", title: "Gendered", school: "SOGDS" },
  { code: "MWG-007", title: "Postmodernism", school: "SOGDS" },
  { code: "MTT-005", title: "ey", school: "SOTST" },
  { code: "MWG-008", title: "Gender", school: "SOGDS" },
  { code: "MTT-10", title: "vuokn fl)kr", school: "SOTST" },
  { code: "MWG-009", title: "Women and Social Structure", school: "SOGDS" },
  { code: "MTT-11", title: "vuokn", school: "SOTST" },
  { code: "MWG-010", title: "Women and Political Process", school: "SOGDS" },
  { code: "MTT-12", title: "vuokn vkSj HkkkkfoKku", school: "SOTST" },
  { code: "MWG-011", title: "Women in the Economy", school: "SOGDS" },
  { code: "MTT-13", title: "vuokn ds", school: "SOTST" },
  { code: "MGS-001", title: "Gender and Development", school: "SOGDS" },
  { code: "MTT-15", title: "vuokn vkSj lkfgR", school: "SOTST" },
  { code: "MTT-16", title: "vuokn vkSj tulpkj", school: "SOTST" },
  { code: "MGS-002", title: "Gender Development", school: "SOGDS" },
  {
    code: "MGSE-004",
    title: "Gender Issues in Goals and Praxis",
    school: "SOGDS",
  },
  { code: "MGS-003", title: "Gender Analysis", school: "SOGDS" },
  { code: "MGS-004", title: "Gender", school: "SOGDS" },
  {
    code: "MGSE-006",
    title: "Gender Resources and Policy Making",
    school: "SOGDS",
  },
  { code: "MGS-005", title: "Research Methodologies", school: "SOGDS" },
  {
    code: "MGSE-009",
    title:
      "Gender Issues in Work  in Gender and Employment and Development Studies",
    school: "SOGDS",
  },
  { code: "MGSP-001", title: "Internship", school: "SOGDS" },
  { code: "MGSE-013", title: "Training and Research Project", school: "SOGDS" },
  { code: "MGSE-001", title: "Gender Planning and", school: "SOGDS" },
  {
    code: "MGSE-020",
    title: "Gender and Development Policies",
    school: "SOGDS",
  },
  { code: "MGSE-002", title: "Gender Audit and Gender", school: "SOGDS" },
  { code: "MGSP-002", title: "Internship", school: "SOGDS" },
  { code: "MGSE-003", title: "Gender Mainstreaming", school: "SOGDS" },
];
