export const courses = [
  { code: "MS-43", title: "Management Control Systems" },
  { code: "MS-44", title: "Security Analysis and" },
  { code: "MS-1", title: "Management Functions Portfolio Management" },
  { code: "MS-45", title: "International Financial" },
  { code: "MS-2", title: "Management of Human Management" },
  { code: "MS-46", title: "Management of" },
  { code: "MS-3", title: "Economic and Social Financial Services" },
  { code: "MS-51", title: "Operations Research" },
  { code: "MS-4", title: "Accounting and Finance for Managers" },
  { code: "MS-52", title: "Project Management" },
  { code: "MS-5", title: "Management of Machines" },
  { code: "MS-53", title: "Production" },
  { code: "MS-6", title: "Marketing for Managers" },
  { code: "MS-54", title: "Management of Information Systems" },
  { code: "MS-7", title: "Information Systems for Managers" },
  { code: "MS-55", title: "Logistics and Supply Chain Management" },
  { code: "MS-8", title: "QuantitativeAnalysis for ManagerialApplications" },
  { code: "MS-56", title: "Materials Management" },
  { code: "MS-9", title: "Managerial Economics" },
  { code: "MS-57", title: "Maintenance Management" },
  { code: "MS-58", title: "Management of R" },
  { code: "MS-10", title: "Organization Design  Development and Change" },
  { code: "MS-61", title: "Consumer Behaviour" },
  { code: "MS-11", title: "Strategic Management" },
  { code: "MS-62", title: "Sales and Distribution" },
  { code: "MS-63", title: "Product Management" },
  { code: "MS-22", title: "Human Resource Development" },
  { code: "MS-64", title: "International Marketing" },
  { code: "MS-23", title: "Human Resource Planning" },
  { code: "MS-65", title: "Marketing of Services" },
  { code: "MS-24", title: "Employment Relations" },
  { code: "MS-66", title: "Marketing Research" },
  { code: "MS-25", title: "Managing Change in" },
  { code: "MS-68", title: "Management of Marketing Organisations" },
  { code: "MS-26", title: "Organisational Dynamics" },
  { code: "MS-91", title: "Advanced Strategic" },
  { code: "MS-27", title: "Wage and Salary Management" },
  { code: "MS-92", title: "Management of Public" },
  { code: "MS-28", title: "Labour Laws" },
  { code: "MS-29", title: "International Human" },
  { code: "MS-41", title: "Working Capital Management" },
  { code: "MS-94", title: "Technology Management" },
  { code: "MS-42", title: "Capital Investment and" },
  { code: "MS-95", title: "Research Methodology for Financing Decisions" },
  { code: "MS-96", title: "Total Quality Management" },
  { code: "ECO-10", title: "Elements of Costing" },
  { code: "MS-97", title: "International Business" },
  { code: "ECO-11", title: "Elements of Income Tax" },
  { code: "MS-422", title: "Bank Financial Management" },
  { code: "ECO-12", title: "Elements ofAuditing" },
  { code: "ECO-13", title: "Business of Environment" },
  { code: "MS-424", title: "International Banking" },
  { code: "ECO-14", title: "Accountancy" },
  { code: "MCO-01", title: "Organisation Theory and" },
  { code: "MS-425", title: "Electronic Banking and Behaviour IT in Banks" },
  { code: "MCO-03", title: "Research Methodology" },
  { code: "MS-611", title: "Rural Marketing" },
  { code: "MS-612", title: "Retail Management" },
  { code: "MCO-04", title: "Business Environment" },
  { code: "MCO-05", title: "Accounting for" },
  { code: "IBO-01", title: "International Business Managerial Decisions" },
  { code: "MCO-06", title: "Marketing Management" },
  { code: "IBO-02", title: "International Marketing Management" },
  { code: "MCO-07", title: "Financial Management" },
  { code: "IBO-03", title: "India" },
  { code: "PCO-01", title: "Preparatory Course in Commerce" },
  { code: "IBO-04", title: "Export Import Procedures and Documentation" },
  { code: "PCO-01", title: "Preparatory Course in Commerce (Odiya)" },
  { code: "IBO-05", title: "International Marketing Logistics" },
  { code: "BCOA-001", title: "Business Communication" },
  { code: "IBO-06", title: "International Business Finance" },
  { code: "BMS-01", title: "Introduction to NGO" },
  { code: "AED-01", title: "Export Procedure" },
  { code: "BMS-02", title: "Management Functions" },
  { code: "AMK-01", title: "Marketing" },
  { code: "BMS-03", title: "Health Care Management" },
  { code: "AOM-01", title: "Office Organisation" },
  { code: "CIE-01", title: "Introduction to Management Entrepreneurship" },
  { code: "ASP-01", title: "Secretarial Practice" },
  { code: "CIE-02", title: "BusinessApportunity" },
  { code: "ECO-01", title: "Business Organisation" },
  { code: "ECO-02", title: "Accountancy" },
  { code: "CIE-03", title: "Enterprise Creation and Legal Requirements" },
  { code: "ECO-03", title: "Management Theory" },
  { code: "CIE-04", title: "Enterprise Management" },
  { code: "ECO-05", title: "Mercantile Law" },
  { code: "CIE-05", title: "Computer for Entrepreneurs" },
  { code: "ECO-06", title: "Economic Theory" },
  { code: "BRL-001", title: "Overview of Retailing" },
  { code: "ECO-07", title: "Elements of Statistics" },
  { code: "BRL-002", title: "Retail Marketing and Communication" },
  { code: "ECO-08", title: "Company Law" },
  { code: "BRL-003", title: "Retail Management" },
  { code: "ECO-09", title: "Money Banking" },
  { code: "BRL-004", title: "Customer Service" },
  { code: "NGS-001", title: "Awareness Course on Gandhi Management" },
  { code: "BRLT-005Internship", title: "and Viva" },
  { code: "BRL-007", title: "Store Operation" },
  { code: "BWEE-012", title: "Women and Society" },
  { code: "BRL-008", title: "Human Resources" },
  { code: "PFM-1", title: "Participatory Forest" },
  {
    code: "MRR-101",
    title: "Understanding Development Management Caused Displacement",
  },
  { code: "MRR-102", title: "Role of Participation in" },
  { code: "PFM-2", title: "Participatory Forest Sustainable Development" },
  { code: "MRR-103", title: "Participating Planning for Resettlement and" },
  { code: "PFM-3", title: "Participatory Forest Rehabilitation" },
  { code: "MRR-104", title: "Participatory Implementing" },
  { code: "PFM-4", title: "Participatory Forest Rehabilitation" },
  { code: "MRR-005", title: "Theoretical Perspectives" },
  { code: "PFM-5", title: "lkfofu" },
  { code: "MRR-006", title: "Illustrative R" },
  { code: "ESO-11", title: "The Study of Society" },
  { code: "ESO-12", title: "Society in India" },
  { code: "MRRE", title: "Economic Planning of R" },
  { code: "ESO-13", title: "Sociological Thought" },
  { code: "ESO-14", title: "Society and Stratification" },
  { code: "ESO-15", title: "Society and Religion" },
  { code: "MRRP-111", title: "Project Work Guide" },
  { code: "ESO-16", title: "Social Problem in India" },
  {
    code: "BLD-101",
    title:
      "Political Economy of Hkkjr ea lkekftd Labour in India Hkkjr ea Je dk",
  },
  { code: "MSO-001", title: "Sociological Theories and" },
  { code: "BLD-102", title: "Organising the Unorganised" },
  { code: "MSO-002", title: "Research Methodologies" },
  { code: "CLD-3", title: "Child and Bonded Labour" },
  { code: "MSO-003", title: "Sociology of Development" },
  { code: "CLD-4", title: "Migrant and Female Workers" },
  { code: "MSO-004", title: "Sociology in India" },
  { code: "MPSE-004", title: "Social and Political Thought" },
  { code: "MSOE-001", title: "Sociology of Education" },
  { code: "MPSE-005", title: "State and Society inAfrica" },
  { code: "MSOE-002", title: "Diaspora and Transnational" },
  { code: "MPSE-006", title: "Peace and Conflict Studies" },
  { code: "MSOE-003", title: "Sociology of Religion" },
  { code: "MPSE-007", title: "Social Movements and" },
  { code: "MSOE-004", title: "Urban Sociology" },
  { code: "MPSE-008", title: "State Politics in India" },
  { code: "MLISE-4", title: "Technical Writing" },
  { code: "MLISE-5", title: "Informetrics and Scienteomtrics" },
  { code: "MPSE-009", title: "Canada" },
  { code: "MLISE-6", title: "Public Library System" },
  { code: "MPSE-010", title: "Master ofArts" },
  {
    code: "MLI-101",
    title: "Information Communication (Political Science) Part Iand Society",
  },
  { code: "MPSE-011", title: "European Union in" },
  { code: "MLI-102", title: "Management of Library" },
  { code: "MPS-001", title: "" },
  { code: "MPSE-012", title: "State and Society inAustralia" },
  { code: "MPS-002", title: "International Relations" },
  { code: "MPSE-013", title: "Australia" },
  { code: "MPA-001", title: "Understanding Natural" },
  { code: "MPS-003", title: "India" },
  { code: "MPA-002", title: "Understanding Man" },
  { code: "MPS-004", title: "Comparative Politics" },
  { code: "MPA-003", title: "RiskAssessment and" },
  { code: "MPSE-001", title: "India and the World" },
  { code: "MPSE-002", title: "State and Society in" },
  { code: "MPA-004", title: "Disaster Preparedness" },
  { code: "MPA-005", title: "Disaster Response" },
  { code: "MPSE-003", title: "Western Political Thought" },
  { code: "MPA-006", title: "Disaster Medicine" },
  { code: "MPA-007", title: "Rehabilitation Reconstruction" },
  { code: "MPS-001", title: "Political Theory" },
  { code: "EPS-03", title: "Modern Indian Political Thought" },
  { code: "MPA-011", title: "State Society and" },
  { code: "EPS-06", title: "Government" },
  { code: "MPA-012", title: "Administrative Theory" },
  { code: "MPA-013", title: "Public System Management" },
  { code: "EPS-07", title: "International Relations" },
  { code: "MPA-014", title: "Human Resource Management" },
  { code: "EPS-08", title: "Government" },
  { code: "MPA-015", title: "Public Policy andAnalysis" },
  { code: "MPA-016", title: "Decentralisation and Local" },
  { code: "EPS-09", title: "Comparative Government" },
  { code: "MPA-017", title: "Electronic Governance" },
  { code: "EPS-11", title: "Political Ideas and Ideologies" },
  { code: "MPA-018", title: "Disaster Management" },
  { code: "MLII-101", title: "Information Sources " },
  { code: "EPS-12", title: "Government" },
  { code: "MLII-102", title: "Information Processing" },
  { code: "EPS-15", title: "SouthAsia" },
  { code: "MLII-103", title: "Fundamentals of Information" },
  { code: "MHI-01", title: "Ancient and Medieval" },
  { code: "MLII-104", title: "Information Communication" },
  { code: "MLI-001", title: "Introduction to Computers" },
  { code: "MHI-02", title: "Modern World" },
  { code: "MLI-002", title: "LibraryAutomation" },
  { code: "MLI-003", title: "Information Systems" },
  { code: "MHI-03", title: "Historiography" },
  { code: "MLI-004", title: "Networking and Internet" },
  { code: "MHI-04", title: "Political Structures in India" },
  { code: "MLI-005", title: "Internet Resources" },
  { code: "MLI-006", title: "Content Development" },
  { code: "MHI-05", title: "History of Indian Econom" },
  { code: "MLI-007", title: "Programming" },
  { code: "MHI-06", title: "Evolution of Social Structures" },
  { code: "BECE-107", title: "Industrial Development" },
  { code: "EEC-10", title: "National IncomeAccounting" },
  { code: "MHI-08", title: "History of Ecology and" },
  { code: "EEC-11", title: "Fundamentals of Economics" },
  { code: "EEC-12", title: "Indian Economic Development" },
  { code: "EHI-1", title: "Modern India" },
  { code: "EHI-2", title: "History of India From Earliest" },
  { code: "EEC-13", title: "Elementary Statistical" },
  { code: "EHI-3", title: "India from" },
  { code: "EEC-19", title: "Indian Financial System" },
  { code: "EHI-4", title: "India from" },
  { code: "EPA-1", title: "Administrative Theory" },
  { code: "BPAE-102", title: "IndianAdministration" },
  { code: "EHI-5", title: "India Mid" },
  { code: "EPA-3", title: "DevelopmentAdministration Mid" },
  { code: "EPA-4", title: "PersonnelAdministration dkfeSd iz" },
  { code: "EHI-6", title: "History of China and Japan" },
  { code: "EPA-5", title: "FinancialAdministration" },
  { code: "EPA-6", title: "Public Policy" },
  { code: "EHI-7", title: "Modern Europe (Mid" },
  { code: "MEC-001", title: "MicroeconomicAnalysis" },
  { code: "MEC-002", title: "MacroeconomicAnalysis" },
  { code: "MEC-003", title: "Quantitative Methods" },
  { code: "BECE-002", title: "Indian Economic Development" },
  { code: "MEC-004", title: "Economics of Growth Issues and Perspectives" },
  { code: "BECE-214", title: "Agricultural Development" },
  { code: "MEC-105", title: "Indian Economic Policy" },
  { code: "MEC-006", title: "Public Economics" },
  { code: "BECE-15", title: "Elementary Mathematicals" },
  { code: "MEC-007", title: "International Trade and Finance" },
  { code: "BECE-16", title: "Economic Developments" },
  {
    code: "MEC-008",
    title: "Economics of Social Sector Contemporary Issues and Environment",
  },
  { code: "MEC-009", title: "Research Methods in" },
  { code: "MPC-002", title: "Life Span Psychology" },
  { code: "MPC-003", title: "Personality" },
  { code: "MECE-001", title: "Econometric Methods" },
  { code: "MECE-003", title: "Actuarial Economics" },
  { code: "MPC-004", title: "Advanced Social Psychology" },
  { code: "MPC-005", title: "Research Methods in" },
  { code: "MECE-004", title: "Financial Institutions and" },
  { code: "MPC-006", title: "Statistics in Psychology" },
  {
    code: "MLIE-101",
    title: "Preservation and Conservation of Library Materials",
  },
  { code: "MPC-051", title: "Fundamentals of Mental Health" },
  { code: "MLIE-102", title: "Research Methodology" },
  { code: "MPC-052", title: "Mental Disorders" },
  { code: "MLIE-103", title: "Academic Library System" },
  { code: "MPC-053", title: "Mental Health in Special Areas" },
  { code: "BSHF-101", title: "Foundation Course in" },
  { code: "MPC-054", title: "Services for the Mentally" },
  { code: "MPC-055", title: "Practicals" },
  {
    code: "MPCL-007",
    title: "Experimental Psychology and Psychological Testing",
  },
  { code: "OSS-101", title: "Preparatory Course in Social Sciences" },
  { code: "MPCE", title: "" },
  { code: "MPCE", title: "" },
  { code: "CDM-02", title: "Disaster Management" },
  { code: "MPCE", title: "" },
  { code: "PFM-01", title: "Forest Resources and Use" },
  { code: "MECP-101", title: "Project Work" },
  { code: "MECP-101", title: "dyk fuiknu" },
  { code: "PFM-02", title: "Forester" },
  { code: "MPAP-01", title: "Project Handbook" },
  { code: "MLIP-02", title: "Project Work" },
  { code: "BPC-004", title: "Statistics in Psychology" },
  { code: "BPC-005", title: "Theories of Personality" },
  { code: "BPCL-007", title: "Practicals in Psychological" },
  { code: "BPC-006", title: "Social Psychology" },
  { code: "BPCE-014", title: "Psychopathology" },
  { code: "BPCE-021", title: "Forensic Psychology" },
  { code: "MPCE", title: "" },
  { code: "BPC-001", title: "General Psychology" },
  { code: "BPC-002", title: "Developmental Psychology" },
  { code: "MANI-001", title: "Anthropology and Methods" },
  { code: "BPC-003", title: "Research Methods in of Research" },
  { code: "MANI-002", title: "PhysicalAnthropology" },
  { code: "MPC-001", title: "Cognitive Psychology " },
  { code: "MAN-001", title: "SocialAnthoropology" },
  { code: "MAN-002", title: "Archaeological Anthoropology" },
  { code: "MANI-003", title: "PracticingAnthropology" },
  { code: "MTM-4", title: "Information Management Systems and Tourism" },
  { code: "MANE-001", title: "Human Genetics" },
  { code: "MTM-7", title: "Managing Sales and" },
  { code: "MANE-002", title: "Human Growth and Promotion in Tourism" },
  { code: "MTM-8", title: "Managing Entrepreneurship" },
  { code: "MANE-003", title: "Comparative Ethnography" },
  { code: "MANE-004", title: "Gender and Society" },
  { code: "MTM-9", title: "Understanding Tourism" },
  { code: "MANE-005", title: "EnvironmentalAnthropology" },
  { code: "BLI-221", title: "Library Information and" },
  { code: "MTM-10", title: "Tourism Impacts" },
  { code: "MTM-11", title: "Tourism Planning and" },
  { code: "BLI-222", title: "Information Sources and Development" },
  { code: "MTM-12", title: "Tourism Products" },
  { code: "BLI-223", title: "Organising and Managing and Development" },
  { code: "MTM-13", title: "Tourism Operations" },
  { code: "BLI-224", title: "ICT Fundamentals" },
  { code: "MTM-14", title: "Tourist Transport" },
  { code: "BLI-225", title: "Communication Skills" },
  { code: "BLIE-226", title: "Management of Library" },
  { code: "MTM", title: "" },
  { code: "BLIE-227", title: "Document Processing Practice" },
  { code: "MTM-16", title: "Dissertation Guide" },
  { code: "BLIE-228", title: "Information Products" },
  { code: "TS-01", title: "Foundation Course in Tourism" },
  { code: "BLIE-229", title: "ICAT in Libraries" },
  { code: "TS-02", title: "Tourism Development" },
  { code: "BLII-011", title: "Libraries" },
  { code: "BLII-012", title: "Document Processing and lpkyu vkSj fLFkfr v" },
  { code: "TS-03", title: "Management in Tourism" },
  { code: "BLII-013", title: "Information Sources and i" },
  { code: "TS-04", title: "Indian Culture" },
  { code: "BLII-014", title: "ICT in Libraries" },
  {
    code: "TS-05",
    title:
      "Ecology Environment and SERVICE MANAGEMENT (SOTHSM) and Tourism ifjfLFkfrdh",
  },
  { code: "MTM-1", title: "Management Functions and Behaviour in Tourism" },
  { code: "TS-06", title: "Tourism Marketing" },
  {
    code: "MTM-2",
    title: "Human Resource Planning and Development in Tourism",
  },
  { code: "TS-07", title: "Human Resource" },
  { code: "MTM-3", title: "Managing Personnel in Development Tourism" },
  { code: "PTS", title: "" },
  { code: "LSE-01", title: "Cell Biology" },
  { code: "LSE-02", title: "Ecology" },
  { code: "LSE-03", title: "Genetics" },
  { code: "LSE-04", title: "Laboratory Course" },
  { code: "FST-01", title: "Foundation Course in (L) iz" },
  { code: "LSE-05", title: "Physiology" },
  { code: "OMT-101", title: "Preparatory Course in" },
  { code: "LSE-06", title: "Development Biology" },
  { code: "LSE-07", title: "Taxonomy and Evolution" },
  { code: "CHE-01", title: "Atoms and Molecule" },
  { code: "LSE-08", title: "Laboratory Course" },
  { code: "CHE-02", title: "Inorganic Chemistry" },
  { code: "LSE-09", title: "Animal Diversity" },
  { code: "CHE-03", title: "Chemistry Lab" },
  { code: "LSE-10", title: "Animal Diversity" },
  { code: "CHE-04", title: "Physical Chemistry" },
  { code: "LSE-11", title: "Animal Diversity Lab" },
  { code: "CHE-05", title: "Organic Chemistry" },
  { code: "CHE-06", title: "Organic Reaction Mechanism" },
  { code: "LSE-12", title: "Plant Diversity" },
  { code: "LSE-13", title: "Plant Diversity" },
  { code: "CHE-07", title: "Chemistry Lab" },
  { code: "LSE-14", title: "(L) Plant Diversity Laboratory" },
  { code: "CHE-08", title: "Chemistry Lab" },
  { code: "ACE", title: "Appreciation Course on" },
  { code: "CHE-09", title: "Biochemistry" },
  { code: "CHE-10", title: "Spectroscopy" },
  { code: "BAQL-001", title: "Freshwater Aquaculture" },
  { code: "CHE-11", title: "Chemistry Lab" },
  { code: "BAQL-002", title: "CoastalAquaculture Lab" },
  { code: "BLS-001", title: "Basics ofAquaculture" },
  { code: "CHE-12", title: "Chemistry Lab" },
  { code: "BAQ-002", title: "Freshwater Aquaculture" },
  { code: "BAQ-003", title: "CostalAquaculture" },
  { code: "LMT-01", title: "Learning Mathematics" },
  { code: "PHE-12", title: "Physics Laboratory" },
  { code: "LT-01", title: "Good Laboratory Practices" },
  { code: "PHE-13", title: "Physics of Solids" },
  { code: "LT-02", title: "Laboratory Techniques in" },
  { code: "PHE-14", title: "Mathematical Method in Biology" },
  { code: "PHE-15", title: "Astronomy andAstrophysics" },
  { code: "LT-03", title: "Laboratory Techniques in" },
  { code: "PHE-16", title: "Communication Physics" },
  { code: "LT-04", title: "Laboratory Techniques in" },
  { code: "MED-001", title: "Understanding the" },
  { code: "BPHE-101", title: "Elementary Mechanics" },
  { code: "MED-002", title: "Sustainable Development" },
  { code: "BPHE-102", title: "Oscillations and Waves" },
  { code: "MED-003", title: "Energy and Environment" },
  { code: "MED-004", title: "Towards Participatory" },
  { code: "BPHL-103", title: "Physics Laboratory" },
  { code: "MED-005", title: "Integrated Environmental" },
  { code: "PHE-04", title: "Mathematical Methods Management" },
  { code: "MED-006", title: "Natural Resources" },
  { code: "PHE-05", title: "Mathematical Methods in" },
  { code: "MED-007", title: "Agriculture and" },
  { code: "PHE-06", title: "Thermodynamics and" },
  { code: "MED-008", title: "Globalisation and lkf" },
  { code: "PHE-07", title: "Electric and Magnetic" },
  { code: "APM-01", title: "Integrated Pest Phenomena" },
  { code: "PHE-08", title: "Physics Laboratory" },
  { code: "AOR-01", title: "Operations Research" },
  { code: "PHE-09", title: "Optics" },
  { code: "MTE-01", title: "Calculus" },
  { code: "PHE-10", title: "Electrical Circuits and" },
  { code: "MTE-02", title: "Linear Algebra" },
  { code: "MTE-03", title: "Mathematical Methods" },
  { code: "PHE-11", title: "Modern Physics xf" },
  { code: "MTE-04", title: "ElementaryAlgebra" },
  { code: "MMT-005", title: "ComplexAnalysis" },
  { code: "MMT-006", title: "FunctionalAnalysis" },
  { code: "MTE-05", title: "Analytical Geometry" },
  { code: "MMT-007", title: "Differential Equations and" },
  { code: "MTE-06", title: "Abstract Algebra" },
  { code: "MMT-008", title: "Probability and Statistics" },
  { code: "MTE-07", title: "Advanced Calculus" },
  { code: "MMT-009", title: "Mathematical" },
  { code: "MTE-08", title: "Differential Equations" },
  { code: "MESE-001", title: "Teaching" },
  { code: "MTE-09", title: "RealAnalysis" },
  { code: "MESE-002", title: "Exploring Physics in okLrfod fo" },
  { code: "MTE-10", title: "NumericalAnalysis" },
  { code: "MESE-003", title: "Biology Teaching" },
  { code: "MESE-004", title: "Chemistry Teaching" },
  { code: "MTE-11", title: "Probability and Statistics" },
  { code: "MCHL-001", title: "BasicAnalytical izkf" },
  { code: "MTE-12", title: "Linear Programming" },
  { code: "MCHL-002", title: "Separation Methods Lab" },
  { code: "MCHL-003", title: "Spectroscopic Method Lab" },
  { code: "MTE-13", title: "Discrete Mathematics" },
  { code: "MCHL-004", title: "Elecroanalytical and fofoDr xf" },
  { code: "MTE-14", title: "Mathematical Modelling" },
  { code: "MST-001", title: "Foundation in Mathematics xf" },
  { code: "MST-002", title: "Descriptive Statistics" },
  { code: "MST-003", title: "Probability Theory" },
  { code: "MST-004", title: "Statistical Inference" },
  { code: "AHE-1", title: "Human Environment" },
  { code: "MST-005", title: "Statistical Techniques" },
  { code: "AST-01", title: "Statistical Techniques" },
  { code: "MSTE-001", title: "Industrial Statistics" },
  { code: "MSTE-002", title: "Industrial Statistics II" },
  { code: "AEC-1", title: "Environmental Chemistry" },
  { code: "MGY-001", title: "Introduction to Geoinformatics" },
  { code: "AMT-01", title: "Teaching of Primary School Mathematics" },
  { code: "MGY-002", title: "Sensing and Image izkbZejh Ldyh xf" },
  { code: "MGY-003", title: "Global Satellite" },
  { code: "MMT-001", title: "Programming and Data" },
  { code: "MMT-002", title: "Linear Algebra" },
  { code: "MBI-001", title: "Introduction to Life Science" },
  { code: "MMT-003", title: "Algebra" },
  { code: "MBI-002", title: "" },
  { code: "MMT-004", title: "RealAnalysis" },
  { code: "MBI-003", title: "Essentials of Bioinformatics" },
  { code: "MBI-004", title: "Bioinformatics" },
  { code: "ET-502", title: "(A) Strength of Materials" },
  { code: "MCH-001", title: "BasicAnalytical Chemistry" },
  { code: "ET-502", title: "(B) Structural Analysis" },
  { code: "MCH-002", title: "Separation Methods" },
  { code: "ET-501", title: "(A) Soil Mechanics" },
  { code: "MCH-003", title: "Spectroscopic Methods" },
  { code: "ET-581", title: "(F) Mechanical Equipment in Construction" },
  { code: "MCH-004", title: "Electroanalytical and other methods" },
  { code: "ET-505", title: "Transportation and Traffic Engineering" },
  { code: "BLS-001", title: "Basics ofAquaculture" },
  { code: "ET-507", title: "(A) Pollutants and Water Supply" },
  { code: "MSTL-001", title: "Basics Statistics Lab" },
  { code: "ET-508", title: "(A) Structural Design" },
  { code: "MSTL-002", title: "Industrial Statistics Lab" },
  { code: "ET-508", title: "(B) Structural Design" },
  { code: "ET-521", title: "(A) Planning" },
  { code: "ET-521", title: "(B) BuildingArchitecture" },
  { code: "ET-101", title: "(A)Mathematics" },
  { code: "ET-521", title: "(C) Design Detailing" },
  { code: "ET-101", title: "(B)Mathematics" },
  { code: "ET-521", title: "(D) Quantity Surveying" },
  { code: "ET-102", title: "Mathematics" },
  { code: "ET-105", title: "(A) Physics" },
  { code: "ET-522", title: "Concrete Technology and Construction Techniques" },
  { code: "ET-105", title: "(B) Chemistry" },
  { code: "ET-524(A)", title: "" },
  { code: "ET-201", title: "(A) Mechanics of Fluids" },
  { code: "ET-202", title: "(A) Engineering Mechanics" },
  { code: "ET-524", title: "(B) Construction Management" },
  { code: "ET-202", title: "(B) Principles of Electrical" },
  { code: "ET-525", title: "Construction Management" },
  { code: "ET-540", title: "(B) Flow in Open Channel" },
  { code: "ET-201", title: "(B) Engineering Thermodynamics" },
  { code: "ET-523", title: "(A) Construction Works Supervision" },
  { code: "ET-204", title: "(A) Materials Science" },
  { code: "ET-523", title: "(B) Operation and Maintenance" },
  { code: "ET-204", title: "(B) Engineering Materials" },
  { code: "ET-302", title: "(B) Computer Programming" },
  { code: "ET-523", title: "(C) Repair and Maintenance of Buildings" },
  { code: "ET-581", title: "(A) Testing for Quality Control" },
  { code: "ET-301(A)", title: "" },
  { code: "BME-001", title: "Engineering Mathematics" },
  { code: "ET-302", title: "(A) Computer Programming and Numerical Methods" },
  { code: "BME-002", title: "Computer Aided Design" },
  { code: "ET-301", title: "(B) Computer Applications" },
  { code: "BME-003", title: "Manufacturing Technology" },
  { code: "ET-302", title: "(B) Technical Writing" },
  { code: "BME-005", title: "Computer Integrated Manufacturing" },
  { code: "ET-501", title: "(B) Foundation Engineering" },
  { code: "BME-004", title: "CNC Technology" },
  { code: "BMEL-003", title: "Laboratory" },
  { code: "BME-006", title: "Mechatronics" },
  { code: "BMEL-004", title: "Laboratory" },
  { code: "BME-007", title: "Quality Engineering" },
  { code: "BMEP-001", title: "Project" },
  { code: "BME-008", title: "Machinary Technology" },
  { code: "BEE-001", title: "Power Distribution Sector" },
  { code: "BME-009", title: "Computer Programming andApplication" },
  { code: "BEE-002", title: "Energy Management" },
  { code: "BME-010", title: "Tool Engineering and Management" },
  { code: "BEE-003", title: "Management of Power" },
  { code: "BME-011", title: "Computer Aided Process Planning" },
  { code: "OET-001", title: "World of Clay" },
  { code: "BME-012", title: "Manufacturing Systems" },
  { code: "OETL-002", title: "Static Clay Forms" },
  { code: "BME-013", title: "Production Management" },
  { code: "OETL-003", title: "Dynamic Clay Forms" },
  { code: "BME-014", title: "Metrology andInstrumentation" },
  { code: "OETL-004", title: "Understanding Design and Marketing" },
  { code: "BME-015", title: "Engineering Mathematics" },
  { code: "BCE-024", title: "Construction Technology" },
  { code: "BME-016", title: "Engineering Mechanics" },
  { code: "BCE-045", title: "Construction Drawing" },
  { code: "BME-017", title: "Strength of Materials" },
  { code: "BCE-052", title: "Transportation Engineering" },
  { code: "BME-018", title: "Engineering Materials" },
  { code: "BCE-043", title: "Construction Technology" },
  { code: "BME-019", title: "Engineering Thermodynamics" },
  { code: "BCE-033", title: "Environmental Engineering" },
  { code: "BME-020", title: "Kinematics and Dynamics of Mechanisms" },
  { code: "BCE-032", title: "Theory of Structures" },
  { code: "BME-021", title: "Principles of Electrical and" },
  { code: "BCE-046", title: "Soil Mechanics and Electronics Sciences" },
  { code: "BME-022", title: "Soft Computing in CIM" },
  { code: "BCE-031", title: "Advanced Survey" },
  { code: "BET-037", title: "Fluid Mechanics" },
  { code: "BME-024", title: "Mechnical EngineeringDesign" },
  { code: "BET-036", title: "Technical Documentation" },
  {
    code: "BME-025",
    title: "Condition Monitoring and Maintenance Engineering",
  },
  { code: "BET-011", title: "Mathematics" },
  { code: "BME-028", title: "" },
  { code: "BET-012", title: "Physics" },
  { code: "BME-029", title: "Robotics" },
  { code: "BET-014", title: "Applied Mechanics" },
  { code: "BME-027", title: "Heat and Man Transfer" },
  { code: "BET-015", title: "Engineering Materials" },
  { code: "BET-021", title: "Mathematics" },
  { code: "BME-035", title: "Industrial Engineering and Operations Research" },
  { code: "BET-022", title: "Strength of Materials" },
  { code: "BMEL-001", title: "Laboratory I" },
  { code: "BET-023", title: "Elements of Survey" },
  { code: "BET-016", title: "Engineering Drawing" },
  { code: "BMEL-002", title: "Laboratory II" },
  { code: "BET-026", title: "Workship Technology" },
  { code: "BET-024", title: "E" },
  { code: "OETL-023", title: "Practical in Shoe Upper Stitching" },
  { code: "BET-017", title: "Computer Basics" },
  { code: "OET-011", title: "vij dfVx ds eyk" },
  { code: "BET-052", title: "Construction Equipment" },
  { code: "OET-012", title: "Lkkexh dhykxr vkSj dfVx" },
  { code: "BET-013", title: "Chemistry" },
  { code: "OET-013", title: "vij dfVx ea" },
  { code: "BCE-034", title: "ESQ" },
  { code: "BCE-024", title: "Construction Technology" },
  { code: "OET-021", title: "vij flykbZ dk eyHkr" },
  { code: "BCE-031", title: "Advanced Survey" },
  { code: "BCE-032", title: "" },
  { code: "OET-022", title: "vij oukuk vkj" },
  { code: "BCE-041", title: "Theory of Structures" },
  { code: "OETL-023", title: "trs ds vij flykbZ dk iz" },
  { code: "BCE", title: "" },
  { code: "BETL-022", title: "Lab" },
  { code: "BCE-044", title: "Concrete Technology" },
  { code: "NET-001", title: "CMSR LVkVj fdV" },
  { code: "BCEE-052", title: "Construction Equipment" },
  { code: "NET-002", title: "Motorcycle Service" },
  { code: "BCE-061", title: "Irrigation Engineering" },
  { code: "BCEE-061", title: "Pre" },
  { code: "NET-003", title: "Motorcycle Repair and" },
  { code: "BNA-011", title: "Applied Mathematics" },
  { code: "BNA-012", title: "Applied Science" },
  { code: "BNA-013", title: "Applied Electricity and" },
  { code: "BME-023", title: "Advanced Manufacturing" },
  { code: "BNA-014", title: "Navigation" },
  { code: "BME-030", title: "Elective Course" },
  { code: "BNA-015", title: "Navigation" },
  { code: "BME-031", title: "Energy Conversion" },
  { code: "BMEL-005", title: "Mechanical Engineering" },
  { code: "BNA-016", title: "Cargo Handling Stowage" },
  { code: "BME-050", title: "Engineering Materials" },
  { code: "BET-22", title: "" },
  { code: "BNA-017", title: "English" },
  { code: "BET-036", title: "Technical Documentation" },
  { code: "BNA-017", title: "English" },
  { code: "OET-011", title: "Basics of Shoe Upper Cutting" },
  { code: "BNAL-011", title: "Applied Sciences Laboratory" },
  { code: "OET-012", title: "Material Costing and Cutting" },
  { code: "BNAL-012", title: "Computer Laboratory" },
  { code: "OETL-013", title: "Practical in Shoe Upper" },
  { code: "BNA-031", title: "Ship Safety" },
  { code: "BNA-041", title: "NavigationalAids and" },
  { code: "OET-021", title: "Basics of Upper Stitching" },
  { code: "BNA-051", title: "Ship Manoeuvring" },
  { code: "OET-022", title: "Upper Assembly and Future Issue" },
  { code: "ET-507(B)", title: "Waste Water Treatment" },
  { code: "BPVI-004", title: "Food Processing and Engineering" },
  { code: "ET-531(A)", title: "Earth" },
  { code: "ET-531(B)", title: "Soil Sciences" },
  { code: "ET-532(A)", title: "Hydrology" },
  { code: "BPVI-005", title: "Food Microbiology" },
  { code: "ET-532(B)", title: "Ground Water Development" },
  { code: "BPVI-006", title: "Food Processing and" },
  { code: "ET-533(A)", title: "Irrigation Engineering" },
  { code: "ET-533(B)", title: "Open Channel Flow" },
  { code: "ET-534(C)", title: "Water Resource Planning" },
  { code: "BPVI-007", title: "Food Quality Testing" },
  { code: "ET-535(A)", title: "Elementary Hydrology" },
  { code: "ET-535(B)", title: "Hydraulic Structures" },
  { code: "ET-536(A)", title: "Hydraulic Structures" },
  { code: "BPVI-008", title: "Entrepreneurship and Marketing" },
  { code: "ET-536(B)", title: "Hydraulic Structures" },
  { code: "ET-537(A)", title: "Soil Conservation" },
  { code: "BPVI-011", title: "Milk Production and Agronomy" },
  { code: "ET-537(B)", title: "Agricultural Legislation" },
  { code: "ET-571", title: "Laboratory" },
  { code: "BPVI-012", title: "Dairy Equipment and Their Maintenance" },
  { code: "ET-573", title: "Laboratory" },
  { code: "ET-574", title: "Laboratory" },
  { code: "BPVI-013", title: "Milk Processing and Packaging" },
  { code: "ET-581(B)", title: "Inventory" },
  { code: "BPVI-014", title: "Dairy Products" },
  { code: "ET-581(C)", title: "Building Services" },
  { code: "BPVI-015", title: "Dairy Products" },
  { code: "BPVI-001", title: "Food Fundamentals" },
  { code: "BPVI-016", title: "Dairy Products" },
  { code: "BPVI-002", title: "Principles of Post Harvest" },
  { code: "BPVI-017", title: "QualityAssurance Management of Fruits" },
  { code: "BPVI-018", title: "Dairy Management and Qy oa lfCt" },
  { code: "BPVI-021", title: "Fundamentals of Food" },
  { code: "BPVI-003", title: "Food Chemistry and Meat Science" },
  { code: "BPVI-022", title: "MeatAnimals andAbattair dkf" },
  { code: "BPVI-023", title: "Fresh Meat Technology" },
  { code: "BPVI-036", title: "Processing of Pulses and Oil Seeds" },
  { code: "BPVI-024", title: "Processed Meat nkyk" },
  { code: "BAPI-001", title: "Organic Production System" },
  { code: "BPVI-037", title: "Food Quality Testing and" },
  {
    code: "BAPI-002",
    title: "Inspection and Certification Evaluation of Organic Produce",
  },
  { code: "BAPI-003", title: "Economics and Marketing of Organic Produce" },
  { code: "BPVI-038", title: "Entrepreneurship and Marketing" },
  { code: "BLPI-001", title: "Introduction to Sericulture" },
  { code: "BLP-004", title: "Crop Production" },
  { code: "BPVI-027", title: "Utilization ofAnimal By" },
  { code: "BAP-001", title: "Introduction to Organic Manual) Farming" },
  { code: "BPVI-028", title: "Marketing and" },
  { code: "NPV-001", title: "Awareness Programme Entrepreneurship" },
  { code: "MNR-001", title: "IndianAgricultural Qyka rFkk lfCt" },
  { code: "MNR-002", title: "Agriculture Policy" },
  { code: "BLPI-002", title: "Host Plants Cultivation" },
  { code: "BLPI-003", title: "Silkworm Reasing" },
  { code: "MNRE-015", title: "Cooperatives and" },
  { code: "NEX-01", title: "M" },
  { code: "MNRE-016", title: "Project Analysis" },
  { code: "BPVI-025", title: "Meat Packaging and Quantity Assurance" },
  { code: "OLP-001", title: "Introduction to Poultry Farming" },
  { code: "BPVI-026", title: "Poultry Products Technology" },
  { code: "OLPI-001", title: "Poultry Housing and" },
  { code: "BPVI-031", title: "Food Fundamentals" },
  { code: "OLPI-002", title: "Poultry Feeds and Feeding" },
  { code: "BPVI-032", title: "Food Microbiology" },
  { code: "OLPI-002", title: "Poultry Feeds and Feeding" },
  { code: "BPVI-033", title: "Milling of Wheat Maize and Coarse Grains" },
  { code: "OLPL-001", title: "Poultry Health Care and" },
  { code: "BPVI-034", title: "Baking and Flour" },
  { code: "OLPL-002", title: "Poultry Farm Training" },
  { code: "ONR-001", title: "Introduction to Water Harvesting" },
  { code: "BPVI-035", title: "Padding Processing" },
  { code: "ONR-002", title: "Basics of Hydrology" },
  { code: "BLP-001", title: "(English)" },
  { code: "ONR-003", title: "Water Harvesting " },
  { code: "BLP-001", title: "(Hindi)" },
  { code: "MVPP", title: "" },
  { code: "ONRL-001", title: "Practical Training at Water" },
  { code: "MAM-001", title: "Introduction to Plantation" },
  { code: "MDE-411", title: "Growth" },
  { code: "MAM-002", title: "Crop Production" },
  { code: "MDE-413", title: "Learner Support Technology" },
  { code: "MAM-003", title: "Post Harvest Management" },
  {
    code: "MDE-414",
    title: "Management of Distance and Value Addition Education",
  },
  { code: "MAM-004", title: "Human Resource " },
  { code: "MDE-415", title: "Research for Distance Marketing" },
  { code: "MDE-416", title: "Curriculum Development" },
  { code: "MAMP-001", title: "Project Handbook" },
  { code: "MVP-001", title: "Food Fundamentals and" },
  {
    code: "MDE-418",
    title: "Educational Communication Chemistry Technologies",
  },
  { code: "MVPI-001", title: "Food Microbiology" },
  { code: "MDE-419", title: "Staff Training" },
  { code: "MVP-002", title: "Food Laws and Standards" },
  { code: "MVP-003", title: "Principles of Food Safety" },
  { code: "MDEP-420", title: "Project Work" },
  { code: "MVP-004", title: "Food Safety and Quality" },
  { code: "MVPL-001", title: "Food Safety and Quality" },
  { code: "ATR-1", title: "Translation Management Systems O" },
  { code: "MVPL-002", title: "Chemical Analysis and" },
  { code: "AFW-1", title: "Feature Writing" },
  { code: "AWRE-01", title: "Writing for Radio" },
  { code: "BEG-004", title: "English in Daily Life" },
  { code: "BAPI-003", title: "tSfod mit dh vFkZO" },
  { code: "BEG-005", title: "English in Education" },
  { code: "BEG-006", title: "Joining the Work Force" },
  { code: "BAP-001", title: "tSfod" },
  { code: "BEGE-101", title: "From Language to" },
  { code: "BAPI-001", title: "TSkfod mRiknu iz" },
  { code: "BAPI-002", title: "tSfod mit dk fujh" },
  { code: "BEGE-102", title: "The Structure of  oa izek" },
  { code: "BEGE-103", title: "Communication Skills in English" },
  { code: "BEGE-104", title: "English for Business" },
  { code: "MEG-10", title: "English Studies in India" },
  { code: "MEG-10", title: "Reader" },
  { code: "BEGE-105", title: "Understanding Prose" },
  { code: "MEG-11", title: "American Novel" },
  { code: "BEGE-106", title: "Understanding Poetry" },
  { code: "MEG-12", title: "A Survey Course in" },
  { code: "BEGE-108", title: "Reading the Novel" },
  { code: "MEG-14", title: "Contemporary Indian" },
  {
    code: "DCE-1",
    title: "General Principles of Literature in English Writing",
  },
  { code: "DCE-2", title: "Feature Writing" },
  { code: "MEG-14", title: "Reader" },
  { code: "DCE-3", title: "Short Story" },
  { code: "BHDE-101", title: "fgnh ea sfPNd" },
  { code: "DCE-4", title: "Writing for Media Radio ikB" },
  { code: "EHD-02", title: "fgUnh dkO" },
  { code: "DCE-5", title: "Writing Poetry" },
  { code: "EHD-03", title: "fgnh lkfgR" },
  { code: "FEG-01", title: "Foundation Course  oa lkfgR" },
  { code: "EHD-04", title: "e" },
  { code: "FEG-02", title: "Foundation Course lkfgR" },
  { code: "CTE-01", title: "The Language Learner" },
  { code: "EHD-05", title: "vk" },
  { code: "CTE-02", title: "The Structure of English" },
  { code: "CTE-03", title: "Teaching Strategies" },
  { code: "BHDE-106", title: "fgnh Hkkkk" },
  { code: "CTE-04", title: "Teaching English" },
  { code: "BHDE-107", title: "fgnh ljpuk" },
  { code: "CTE-05", title: "Teaching English" },
  { code: "BHDE-108", title: "iz" },
  { code: "BHDA-101", title: "lekpkj y" },
  { code: "MEG-01", title: "British Poetry" },
  { code: "MEG-02", title: "British Drama" },
  { code: "BHDF-101", title: "fgUnh ea vk" },
  { code: "MEG-03", title: "The British Novel" },
  { code: "FHD-02", title: "fgUnh ea vk" },
  { code: "MEG-04", title: "Aspects of Language" },
  { code: "BRPA-101", title: "jfM" },
  { code: "MEG-05", title: "Literary Criticism and" },
  { code: "BSKF-01", title: "lLdr ea vk" },
  { code: "MEG-06", title: "American Literature" },
  { code: "MHD-01", title: "fgUnh dkO" },
  { code: "MEG-07", title: "Indian English Literature" },
  { code: "MHD-02", title: "vk" },
  { code: "MEG-07", title: "Reader" },
  { code: "MHD-03", title: "miU" },
  { code: "MEG-08", title: "New Literatures in English" },
  { code: "MHD-04", title: "UkkVd vkSj vU" },
  { code: "MEG-09", title: "Australian Literature" },
  { code: "MHD-05", title: "lkfgR" },
  { code: "MBP-001", title: "Introduction to Publishing lekykpuk" },
  { code: "MHD-06", title: "fgUnh Hkkkk vkSj lkfgR" },
  { code: "MBP-002", title: "Editing and Pre" },
  { code: "MBP-003", title: "Production" },
  { code: "MHD-07", title: "Hkkkk foKku vkSj fgUnh Hkkkk" },
  { code: "MBP-004", title: "Marketing" },
  { code: "MHD-09", title: "dgkuh dk Lo" },
  { code: "MBP-005", title: "Editing Books for Children" },
  { code: "MHD-11", title: "fgUnh dgkuh" },
  { code: "MBP-006", title: "Editing Scientific" },
  { code: "MHD-13", title: "miU" },
  { code: "MBP-007", title: "Editing Textbooks" },
  { code: "MHD-14", title: "fgUnh miU" },
  { code: "MBP-008", title: "Training Manual" },
  { code: "BBHF-001", title: "Bhojpuri" },
  { code: "MHD-15", title: "fgUnh miU" },
  { code: "BULE-001", title: "(Urdu)" },
  { code: "MHD-16", title: "Hkkjrh" },
  { code: "BULE-002", title: "(Urdu)" },
  { code: "MHD-21", title: "ehjk dk fo'kk v" },
  {
    code: "FAS-01",
    title: "Foundation Course in SCHOOL OF LAW (SOL) Assamese",
  },
  { code: "MIR-011", title: "Cyberspace Technology and" },
  { code: "FBG-01", title: "Foundation Course in Social Issues" },
  { code: "MIR-012", title: "Regulation of Cyberspace" },
  { code: "FGT-01", title: "Foundation Course in" },
  { code: "MIR-013", title: "Commerce and Cyberspace" },
  { code: "MIR-014", title: "Privacy and Data Protection" },
  { code: "FKD-01", title: "Foundation Course in Kanada" },
  { code: "CHR-11", title: "Human Rights" },
  { code: "FMT-01", title: "Foundation Course in ekuo vf" },
  { code: "FML-01", title: "Foundation Course in" },
  { code: "CHR-12", title: "Human Rights in India" },
  { code: "FOR-01", title: "Foundation" },
  { code: "MIR-021", title: "Overview of Intellectual" },
  { code: "FPB-01", title: "Foundation Course in" },
  { code: "MIR-022", title: "International Framework for" },
  { code: "FTG-01", title: "Foundation Course in" },
  { code: "MIR-023", title: "Indian Patent Law and" },
  { code: "FTM-01", title: "Foundation Course in" },
  { code: "MIRP-001", title: "Project Handbook" },
  { code: "CPI", title: "Consumer Protection Issues" },
  { code: "FUD-01", title: "Foundation Course in Urdu" },
  { code: "ACS-01", title: "Application Oriented Course" },
  { code: "MLE-024", title: "National Environmental" },
  { code: "MLE-025", title: "National Legal Frameworks and Processes" },
  { code: "BLEP-001", title: "Clinical Course on Legal Research Writing" },
  { code: "MLE-026", title: "Environment Protection Advocacy" },
  { code: "BLE-001", title: "Introduction to the Indian" },
  { code: "MLEP-027", title: "Project" },
  { code: "BLE-031", title: "Understanding Human" },
  { code: "BLE-002", title: "Introduction to Law" },
  { code: "BLE-003", title: "Law" },
  { code: "BLE-032", title: "Law Policies and Institutional Groups" },
  { code: "BLE-004", title: "Rural Local Self dkuuh uhfr" },
  { code: "BLE-011", title: "Co" },
  { code: "BLE-033", title: "Rehabilitation and" },
  { code: "BLE-012", title: "Co" },
  { code: "BLE-035", title: "Understanding International" },
  { code: "BLE-013", title: "Business Law asApplicable Humanitarian Law" },
  { code: "BLE-036", title: "Application of IHL" },
  { code: "BLE-014", title: "Business Law asApplicable to Co" },
  { code: "BLE-037", title: "IHL Issues of Concern in SouthAsia" },
  { code: "MLE-011", title: "Criminal Justice System" },
  { code: "MIP-101", title: "General Introduction to" },
  { code: "MLE-012", title: "Indian Penal Code" },
  { code: "MLE-013", title: "Criminal Justice Processes" },
  { code: "MIP-102", title: "Patents" },
  { code: "MLE-014", title: "Criminal JusticeAdministration" },
  { code: "MIP-103", title: "(English)" },
  {
    code: "MLE-015",
    title: "Challenges to Criminal Layout Designs of Justice System",
  },
  { code: "MLE-016", title: "Criminal Justice Research and Advocacy" },
  { code: "MIP-104", title: "Trademarks Domain" },
  { code: "MLEP-017", title: "Clinical Course Project" },
  { code: "MLE-021", title: "Introduction to Environment" },
  { code: "MIP-105", title: "Copyrights and Related" },
  {
    code: "MLE-022",
    title: "Introduction to Environment Rights Law and Policy",
  },
  { code: "MIP-106", title: "Plant Varieties Protection" },
  {
    code: "MLE-023",
    title: "International Environmental Biotechnology and Law and Policy",
  },
  { code: "MIP-107", title: "Trade Secrets " },
  { code: "BOS-001", title: "B" },
  { code: "BOS-002", title: "B" },
  { code: "MIP-108", title: "Management of IPRS" },
  { code: "BOS-003", title: "B" },
  { code: "BOS-004", title: "B" },
  {
    code: "MCC-001",
    title: "Fundamentals of Ophthalmic Techniques Cardiovascular System",
  },
  { code: "BOS-005", title: "B" },
  {
    code: "MCC-002",
    title: "Fundamentals of Ophthalmic Techniques Cardiovascular System",
  },
  { code: "MME-005", title: "Clinical Geriatrics" },
  { code: "MCC-003", title: "Common Cardiovascular Diseases" },
  { code: "MMEL-005", title: "Clinical Geriatrics Practical" },
  { code: "MCC-004", title: "Common Cardiovascular" },
  { code: "MME-004", title: "Basic Geriatrics" },
  { code: "MMEL-004", title: "Basic Geriatrics" },
  { code: "MCC-005", title: "Common Cardiovascular Diseases" },
  { code: "BNS-101", title: "Nursing Foundation" },
  { code: "MCC-006", title: "Preventive Cardiology" },
  { code: "BNSL-101", title: "Nursing Foundation" },
  { code: "MCC-007", title: "Cardiovascular Related" },
  { code: "BNS-102", title: "Applied Sciences" },
  { code: "BNSL-102", title: "Applied Sciences" },
  { code: "MCCL-001", title: "Cardiovascular Evaluation" },
  { code: "BNS-103", title: "Maternal Health Nursing" },
  { code: "MCCL-002", title: "Cardiovascular Evaluation" },
  { code: "BNSL-103", title: "Maternal Health Nursing" },
  { code: "MCCL-003", title: "Management of Common" },
  { code: "BNS-105", title: "Behavioural Sciences" },
  { code: "BNSL-105", title: "Behavioural Sciences" },
  { code: "MCCL-004", title: "Management of Congenital Heart Diseases" },
  { code: "BNS-106", title: "Medical Surgical Nursing" },
  { code: "MCCL-005", title: "Preventive Cardiology" },
  { code: "BNSL-106", title: "MedicalSurgicalNursing Practice" },
  { code: "MCCL-006", title: "Intensive Coronary Care" },
  { code: "BNS-107", title: "Paediatric Nursing" },
  { code: "MME-201", title: "Preventive MCH" },
  { code: "BNSL-107", title: "Paediatric Nursing" },
  { code: "MMEL-201", title: "Preventive MCH (Practical" },
  { code: "BNS-108", title: "Mental Health Nursing" },
  { code: "MME-202", title: "Reproductive Health" },
  { code: "BNSL-108", title: "Mental Health Nursing" },
  { code: "BNS-109", title: "Community Health Nursing" },
  { code: "MMEL-202", title: "Reproductive Health" },
  { code: "BNSL-109", title: "Community Health Nursing" },
  { code: "MME-203", title: "Child Health" },
  { code: "BNS-110", title: "NursingAdministration" },
  { code: "MMEL-203", title: "Child Health (Practical " },
  { code: "BNSL-110", title: "NursingAdministration and" },
  { code: "BNS-111", title: "Nursing Education and" },
  { code: "BNS-014", title: "Resource Management" },
  { code: "BNSL-012", title: "Nursing Service" },
  { code: "BNSL-111", title: "Nursing Education and Administration" },
  { code: "BNSL-011", title: "Nursing Service" },
  { code: "BNSL-112", title: "Computer in Nursing" },
  { code: "BNS-104", title: "Communicative English" },
  { code: "BNS-013", title: "Group Dynamics" },
  { code: "BNSL", title: "" },
  { code: "BNS-012", title: "Management of Educational" },
  { code: "BNSL-017", title: "Institute Hospital and" },
  { code: "BNSL-016", title: "Nursing Practices and" },
  { code: "BNS-011", title: "Principles and Practices of" },
  { code: "MDTL-001", title: "Practical of Fundamental" },
  { code: "BHM-01", title: "Fundamentals" },
  { code: "MDTL-002", title: "Practical of Fundamental" },
  { code: "BHM-02", title: "Health Care Waste" },
  { code: "MDT-003", title: "Clinical Endodontics" },
  { code: "BNS-001", title: "Community Heath" },
  { code: "MDT-002", title: "Clinical Endodontics" },
  { code: "BNSL-001", title: "Community Health" },
  { code: "MDT-001", title: "Fundamentals of (Practical Manual) Endodontics" },
  { code: "BNS-002", title: "Reproductive" },
  { code: "MDTL-004", title: "Implantology I" },
  { code: "BNSL-002", title: "PracticalAspects of" },
  { code: "MDTL-004", title: "Practicals of Oral" },
  { code: "MDT-005", title: "Advanced Surgical" },
  { code: "BNS-003", title: "Community Health Implantology Service" },
  { code: "MDT-004", title: "Fundamentals of" },
  { code: "BNSL-003", title: "Community Health Implantology Service (PM)" },
  { code: "BNS-002", title: "Reproductive and" },
  { code: "BNS-004", title: "Management of" },
  { code: "BNSL-004", title: "Management of" },
  { code: "BNS-017", title: "Community Health Community" },
  { code: "BNSL-015", title: "Integrated Management" },
  {
    code: "CHEP-01",
    title: "PracticalAspects of of Sick New Born Environment",
  },
  { code: "CHET-01", title: "Our Environment" },
  { code: "BNS-015", title: "Nursing Care of New" },
  { code: "CHET-02", title: "Promoting Health" },
  { code: "BOSL", title: "" },
  { code: "CRSI-01", title: "Basics" },
  { code: "BOSL", title: "" },
  { code: "CRSI-02", title: "Speciality Surgery" },
  { code: "CPE", title: "" },
  { code: "CRSI-03", title: "General Surgery" },
  { code: "CPE", title: "" },
  { code: "CRSI-04", title: "Orthopaedics" },
  { code: "MHMI-11", title: "" },
  { code: "CRSI-05", title: "ENT" },
  { code: "MHMI-12", title: "" },
  { code: "CRSI-06", title: "Obstetrics" },
  { code: "MHMI-13", title: "" },
  { code: "PGDHHM-01", title: "Introduction to" },
  { code: "MHM-10", title: "" },
  { code: "CNSHC", title: "" },
  { code: "PGDHHM-02", title: "Introduction to Management" },
  { code: "CNSHC-001", title: "" },
  { code: "PGDHHM-03", title: "Organisation and oMf aHnoasgpeitmalesnt" },
  { code: "PGDHHM-04", title: "Clinical Diagnostic" },
  { code: "MFN-001", title: "Applied Physiology" },
  { code: "MFN-002", title: "Nutritional Biochemistry" },
  { code: "PGDHHM-05", title: "Support and" },
  { code: "MFN-003", title: "Food Microbiology and Utility Services" },
  { code: "MFN-004", title: "Advance Nutrition" },
  { code: "PGDHHM-06Health", title: "System Management" },
  { code: "MFN-005", title: "Clinical and Therapeutic Nutrition" },
  { code: "DNHE-02", title: "Public Health and Hygienic" },
  { code: "MFN-006", title: "Public Nutrition" },
  { code: "DNHE-04", title: "Project Work" },
  { code: "MFN-007", title: "Entrepreneurship" },
  { code: "BOS-007", title: "Visual Optics" },
  { code: "MFN-008", title: "Principles of Food Science" },
  { code: "BOS-008", title: "Dispensing Optics" },
  { code: "BOS-009", title: "Basic Orthotics" },
  { code: "MFN-009", title: "The Search Methods" },
  { code: "BOS-010", title: "Ocular Diseases" },
  { code: "MFN-010", title: "Understanding Computer" },
  { code: "PGDHHM", title: "Log Book" },
  { code: "BOS-15", title: "" },
  { code: "MFNL-002", title: "Nutritional Biochemistry" },
  { code: "BOS-14", title: "" },
  { code: "MFNL-003", title: "Food Microbiology" },
  { code: "BOS-13", title: "" },
  { code: "MFNL-004", title: "Advance Nutrition" },
  { code: "BOS-11", title: "" },
  { code: "MFNL-005", title: "Clinical" },
  { code: "BOSL", title: "" },
  { code: "MFNL-006", title: "Public Nutrition" },
  { code: "BOSL", title: "" },
  { code: "MFNL-007", title: "Entrepreneurship" },
  {
    code: "MRDE-004",
    title: "Entrepreneurship and Service Management Rural Development",
  },
  { code: "MFNL-008", title: "Principles of Food Services" },
  { code: "CNCC-1", title: "Nutrition for the" },
  { code: "MFNP-011", title: "Internship" },
  { code: "MFNP-012", title: "Dissertation" },
  { code: "JMC-01", title: "Introduction to Journalism" },
  { code: "CNCC-2", title: "Organizing Child Care" },
  { code: "JMC-02", title: "Mass Media and Society" },
  { code: "JMC-03", title: "Reporting Writing" },
  { code: "CNCC-2", title: "Organizing Child Care Services" },
  { code: "JMC-04", title: "Public Relations" },
  { code: "RDD-5", title: "Research and Project Work" },
  { code: "RDD-6", title: "Rural Health Care" },
  { code: "MRDP-001", title: "Project Work Handbook" },
  { code: "RDD-7", title: "Communication" },
  { code: "MRDE-101", title: "Rural Social Development" },
  { code: "BFN-001", title: "Hazards to Food Safety" },
  { code: "MRDE", title: "" },
  { code: "BFN-002", title: "Hazards to Food Safety" },
  { code: "MRDE-002", title: "Volntary Action in Rurla" },
  { code: "BFN-003", title: "Food Safety and Quality" },
  { code: "MRD-101", title: "Rural Development" },
  { code: "MRDE-003", title: "Land Reforms and Rural Development" },
  {
    code: "MRD-103",
    title: "Rural Development Hkfe fodkl vkSj Planning and Management",
  },
  { code: "DNHE-1", title: "Nutrition for the vkSj izca" },
  { code: "MFNP-011", title: "Internship" },
  { code: "DNHE-2", title: "tu LokLF" },
  { code: "MFNP-012", title: "Dissertation" },
  { code: "MFNL-007", title: "Entrepreneurship" },
  { code: "DNHE-3", title: "Nutrition and Health and Food Service Education" },
  { code: "CNCC-1", title: "Nutrition for the" },
  { code: "DECE-3", title: "" },
  { code: "BWEE-002", title: "Gander Training Part" },
  { code: "BWEE-006", title: "Organization and" },
  { code: "AFE", title: "" },
  { code: "BFEE-102", title: "" },
  { code: "BWEE-007", title: "Work and Enterpreneurship" },
  { code: "AFE", title: "" },
  { code: "BFEE-103", title: "" },
  { code: "BWEE-008", title: "Credit and Finance" },
  { code: "AFE", title: "" },
  { code: "DNHE-1", title: "Nutrition for the Community" },
  { code: "BFEE-104", title: "" },
  { code: "AFE", title: "" },
  { code: "BFEP-01", title: "" },
  { code: "DNHE-02", title: "tu LokLF" },
  { code: "CFN-01", title: "You and Your Food" },
  { code: "CFN-02", title: "Your Food and its" },
  { code: "DNHE-03", title: "Nutrition and Health Utilization" },
  { code: "CFN-03", title: "Economics of Food" },
  { code: "DECE-01", title: "Organising Child Care" },
  { code: "DECE-02", title: "Child Health and Nutrition" },
  { code: "DECE-3", title: "cPpka ds fy lok" },
  { code: "DECE-03", title: "Services" },
  { code: "DNHE-4", title: "ifj" },
  { code: "DECE-04", title: "Project Work" },
  { code: "RDD-09", title: "vula" },
  { code: "ERD-01", title: "Rural Development in India" },
  { code: "MRDE-101", title: "xkeh" },
  { code: "NCD-001", title: "Awareness" },
  {
    code: "MRD-102",
    title: "Rural Development Package in Disability Programmes (Mental",
  },
  { code: "NCD-002", title: "Awareness" },
  { code: "RDD-06", title: "xkeh" },
  {
    code: "ACC-01",
    title: "Organising Child Care (Visual Impairment) Services",
  },
  { code: "NCD-003", title: "Awareness" },
  { code: "AFE", title: "" },
  { code: "AFE", title: "" },
  { code: "MRD-101", title: "xke fodkl" },
  { code: "AFE", title: "" },
  { code: "MRD-004", title: "xke fodkl ea vula" },
  { code: "MRD-004", title: "Research Methods in Rural Development" },
  { code: "MCS-041", title: "Operating Systems" },
  { code: "MCS-042", title: "Data Communication and Networks" },
  { code: "MCS-011", title: "Problem Solving and Programming" },
  { code: "MCS-043", title: "Advanced Database Management Systems" },
  { code: "MCS-012", title: "Computer Organisation" },
  { code: "MCS-044", title: "Mini Project" },
  { code: "MCSL-045", title: "Lab (UNIX" },
  { code: "MCS-013", title: "Discrete Mathematics" },
  { code: "MCS-051", title: "Advanced Internet Technologies" },
  { code: "MCS-014", title: "SystemAnalysis and Design" },
  { code: "MCS-052", title: "Principles of Management" },
  { code: "MCS-015", title: "Communication Skills" },
  { code: "MCS-053", title: "Computer Graphics" },
  { code: "MCSL-016", title: "Internet Concepts and Web Multimedia" },
  { code: "MCSL-054", title: "Lab Course in" },
  {
    code: "MCSL-017",
    title:
      "Lab (C and Assembly Advanced Internet Language Programming) Technologies and Course",
  },
  { code: "MCS-021", title: "Data and File Structures" },
  { code: "MCS-022", title: "Operating System Concepts" },
  {
    code: "MCSE-003",
    title: "Artificial Intelligence and and Networking Knowledge Management",
  },
  { code: "MCSE-004", title: "Numerical and Statistical" },
  { code: "MCS-023", title: "Introduction to Database Computing" },
  { code: "MCSE-011", title: "Parallel Computing" },
  { code: "MCS-024", title: "Object Oriented Technology" },
  { code: "BCS-011", title: "Computer Basics and" },
  { code: "MCSL-025", title: "Lab Course (for Data" },
  { code: "BCS-012", title: "Basic Mathematics" },
  { code: "BCSL-013", title: "Computer Basics" },
  { code: "MCS-031", title: "Design and Analysis of" },
  { code: "BCSL-021", title: "C Language" },
  { code: "MCS-032", title: "Object OrientedAnalysis" },
  { code: "BCSL-022", title: "Assembly Language" },
  { code: "MCS-033", title: "Advanced Discrete" },
  { code: "BCS-031", title: "Programming in C" },
  { code: "BCS-032", title: "C" },
  { code: "MCS-034", title: "Software Engineering" },
  { code: "BCSL-033", title: "Data and File" },
  {
    code: "MCS-035",
    title: "Accountancy and Financial Structure Lab Management",
  },
  { code: "BCSL-034", title: "Statistical Techniques" },
  { code: "MCSL-036", title: "Lab Course" },
  { code: "BCS-040", title: "Statistical Techniques" },
  { code: "ES-333", title: "Educational Evaluation" },
  { code: "BCS-041", title: "Fundamentals of" },
  { code: "ES-334", title: "Education and Society" },
  { code: "BCS-042", title: "Introductions" },
  { code: "ES-335", title: "Teacher and School" },
  { code: "BCSL-043", title: "Java Programming Lab" },
  { code: "BCSL-044", title: "Statistical Techniques Lab" },
  { code: "ES-341", title: "Teaching of Science" },
  { code: "BCSL-045", title: "Algorithm Design Lab" },
  { code: "BCS-051", title: "Introduction to Software" },
  { code: "ES-342", title: "Teaching of Mathematics" },
  { code: "BCS-052", title: "Network Programming" },
  { code: "ES-343", title: "Teaching of Social Studies" },
  { code: "BCS-053", title: "Web Programming" },
  { code: "BCS-054", title: "Computer Oriented" },
  { code: "ES-344", title: "Teaching of English" },
  { code: "ES-345", title: "" },
  { code: "BCS-055", title: "Business Communication" },
  { code: "ES-361", title: "Educational Technology" },
  { code: "BCSL-056", title: "Network Programming" },
  { code: "BCSL-057", title: "Web Programming Lab" },
  { code: "ES-362", title: "Computers in Education" },
  { code: "BCSL-058", title: "Computer Oriented" },
  { code: "ES-363", title: "Guidance and Counselling" },
  { code: "BCS-062", title: "E" },
  { code: "BCSL-063", title: "Operating Systems" },
  { code: "ES-364", title: "Distance Education" },
  { code: "MES-051", title: "Education" },
  { code: "CIT-001", title: "Fundamentals of Computer" },
  { code: "MES-052", title: "Psychology of Learning and" },
  { code: "CIT-002", title: "Introduction to Information" },
  { code: "MES-053", title: "Educational Management" },
  { code: "CIT-003", title: "Web based Technologies" },
  { code: "MES-054", title: "Methodology of Educational" },
  { code: "CITL-001", title: "Laboratory Course" },
  {
    code: "MES-111",
    title:
      "Growth and Philosophy of SCHOOL OF EDUCATION (SOE) Distance Education",
  },
  { code: "ES-331", title: "Curriculum and Instruction" },
  { code: "MES-056", title: "Educational Technology" },
  { code: "MESE-057", title: "Measurement and Evaluation" },
  { code: "ES-332", title: "Psychology of Development" },
  { code: "MESE-058", title: "Educational and Vocational" },
  { code: "MESE-059", title: "Teacher Education in Indian" },
  { code: "NES-104", title: "Guiding Socio" },
  { code: "MES-055", title: "Comparative Education" },
  {
    code: "MES-015",
    title: "Operational Dimensions National and International of Education",
  },
  { code: "MES-016", title: "Educational Research" },
  { code: "MESE-060", title: "Curriculum Development" },
  { code: "MES-031", title: "ET" },
  { code: "ES-201", title: "Language Teaching" },
  { code: "MES-032", title: "Communication and Hkkkk fdj" },
  { code: "ES-202", title: "Curriculum Planning" },
  { code: "MES-033", title: "Computer Technology" },
  { code: "MES-034", title: "Designing Courseware" },
  { code: "MES-112", title: "Design and Development of" },
  { code: "ES-203", title: "Ik" },
  { code: "MES-113", title: "Learner Support Services" },
  { code: "ES-204", title: "LokLF" },
  { code: "MES-114", title: "Management of Distance vkSj dk" },
  { code: "ES-211", title: "izkFkfed Lrj ij" },
  { code: "MES-115", title: "Communication Technology for f" },
  { code: "ES-212", title: "izkFkfed fo" },
  { code: "MESP-49", title: "Project Work" },
  { code: "MES-005", title: "Human Resource Development" },
  { code: "ES-213", title: "fok" },
  { code: "MES-006", title: "Managing Teaching" },
  { code: "ES-221", title: "izkFkfed fo" },
  { code: "MES-007", title: "School Governance and" },
  { code: "ES-222", title: "fodklksUe" },
  { code: "MES-008", title: "Leadership for Better Schools" },
  { code: "MES-101", title: "Higher Education" },
  { code: "MES-047", title: "Distance and Open Learning" },
  { code: "MES-105", title: "Project Work" },
  { code: "MES-102", title: "Instruction in Higher Education" },
  { code: "MES-011", title: "Understanding Education" },
  { code: "MES-103", title: "Higher Education" },
  { code: "MES-012", title: "Education" },
  { code: "MES-104", title: "Planning" },
  {
    code: "MES-013",
    title: "Learning Learner and Higher Education Development",
  },
  { code: "NES-101", title: "Understanding the Elementary" },
  { code: "MES-014", title: "Societal Context of Education" },
  { code: "MES-045", title: "School Education" },
  { code: "NES-102", title: "Facilitating Growth and" },
  {
    code: "MESE-061",
    title: "Open and Distance Theory Learning Systems (Optional)",
  },
  { code: "NES-103", title: "Guiding Children" },
  { code: "ES-345", title: "fgnh f'k" },
  { code: "BES-001", title: "(Diploma in Elementary" },
  { code: "OVA-001", title: "Indian Cultural Heritage" },
  { code: "OVA-002", title: "Understanding Indian" },
  { code: "BES-002", title: "Diploma in Elementary" },
  { code: "OVA-003", title: "An Introduction to IndianArts" },
  { code: "BES-004", title: "Contemparary Indian Society and Education" },
  { code: "OMU-001", title: "Introduction to Hindustan Music" },
  { code: "BES-008", title: "Language and Early Literacy" },
  { code: "OMU-005", title: "Introduction to" },
  { code: "BES-009", title: "Teaching of Mathematics for Karnatak Music" },
  { code: "ODN-001", title: "Introduction to Indian" },
  { code: "BES-10", title: "Teaching of Environmental Dance Forms" },
  { code: "OTH-001", title: "Introduction to Theatre" },
  { code: "BES-016", title: "Life Enrichment and and Drama" },
  { code: "MFC-001", title: "Folklore and Culture" },
  {
    code: "BES-017",
    title: "School Education Leadership Conceptual Perspectives",
  },
  { code: "MFC-002", title: "Tradition Identity and" },
  { code: "BES-012", title: "Teaching of Mathematics" },
  { code: "BES-018", title: "Teaching of Social Science" },
  { code: "MFC-003", title: "Cultural and Societal" },
  { code: "BES-019", title: "Teaching of Science" },
  { code: "BES-020", title: "Teaching of English" },
  {
    code: "MES-01",
    title:
      "Teaching Learning Process SCHOOL OF VOCATIONAL EDUCATION and Evaluation",
  },
  { code: "MES-02", title: "Life Enrichment and Self" },
  { code: "BPOI-001", title: "Diploma in Business Development" },
  { code: "MES-03", title: "Foundation Course" },
  { code: "MES-04", title: "Head Teaching as" },
  { code: "BPOI-002", title: "Fundamental of School Leaders" },
  { code: "BPOI-003", title: "Procure to Pay ea e" },
  { code: "MES-06", title: "Managing Teaching" },
  { code: "BPOI-004", title: "Order to Cash" },
  { code: "BPOI-006", title: "Social Skills on Business Commu nication" },
  { code: "MES-07", title: "School Governance and Financial Management" },
  { code: "BPOI-007", title: "Diploma in Business fo" },
  { code: "MESE-061", title: "Open and Distance Theory" },
  {
    code: "MVE-001",
    title: "Introduction toAnatomy  Learning Systems (Optional)",
  },
  { code: "MVE-002", title: "Pharmacology and" },
  { code: "MSW-002", title: "Origin and Development of Toxicology" },
  { code: "MVE-003", title: "Pharmaceutics" },
  { code: "MVE-004", title: "Drug Regulatory Affairs" },
  { code: "MSW-003", title: "Social Science Concepts for" },
  { code: "MVE-005", title: "Introduction and Social Workers" },
  { code: "MVE-006", title: "Sales Management" },
  { code: "MVEI-011", title: "Understanding the Learner" },
  { code: "MSW-004", title: "Social Work and Social" },
  { code: "MVEI-012", title: "Assertive and Adoptive Development" },
  { code: "MVEI-013", title: "Software for Visually" },
  { code: "MVEI-014", title: "Communication Skills" },
  { code: "MSW-005", title: "Social Work Practicum" },
  { code: "MVEI-021", title: "Education and Vocational Education" },
  { code: "MSW-006", title: "Social Work Research" },
  { code: "MVEI-022", title: "ICT for Vocational" },
  { code: "MSW-007", title: "Case Work" },
  { code: "MVEI-023", title: "Communication Skills" },
  { code: "MSW-008", title: "Social Group Work" },
  { code: "MVEI-024", title: "Pedagogy" },
  { code: "MSW-009", title: "Community of Organisation" },
  { code: "MSWE", title: "" },
  { code: "BSWE-001", title: "Introduction to Social Work" },
  { code: "BSWL-001", title: "Field Work Journal" },
  { code: "MSWL-001", title: "Social Work Practicum" },
  { code: "BSWL", title: "Field Work Guide" },
  { code: "MSWL-002", title: "Field Work Practicum" },
  { code: "BSWE-002", title: "Social Work Intervention (Practical)" },
  { code: "MSWP-001", title: "Project Work Hand Book on" },
  { code: "BSWL-002", title: "Field Work Journal" },
  { code: "BSWE-003", title: "Social Work Intervention with" },
  { code: "MVE-002", title: "Pharmacology and Toxicology" },
  { code: "MVE-003", title: "Pharmaceutics" },
  { code: "BSWL-003", title: "Field Work Journal" },
  { code: "MVE-004", title: "Drugs Regulatory Affairs" },
  { code: "BSWE-004", title: "Introduction to Family Education" },
  { code: "MVE-005", title: "Introduction to Management" },
  { code: "MSW-001", title: "Origin and Development of Social Work" },
  { code: "MVE-006", title: "Sales Management" },
  { code: "BSWE-005", title: "Introduction to HIV" },
  { code: "BSWE-006", title: "SubstanceAbuse and CounseLling" },
  { code: "BFE-101", title: "Basics of HIV" },
  { code: "MEDS-003", title: "Problems and Issues in Development" },
  { code: "BFE-102", title: "Basics of Family Educations" },
  { code: "MAE-001", title: "Understanding" },
  { code: "BFEE-101", title: "Elective on HIV" },
  { code: "BFEE-102", title: "Elective on Family Educations" },
  { code: "MAE-002", title: "Policy Planning and" },
  { code: "BFEE", title: "" },
  { code: "BFEE-104", title: "Communication and Counselling in HIV" },
  {
    code: "MAE-003",
    title:
      "Knowledge Management Information Dissemination and Networking inAdult Education",
  },
  { code: "MAEL-001", title: "Practical Work Components" },
  { code: "MEDS-005", title: "Planning and Management" },
  { code: "MJM-001", title: "Introduction to Broadcasting" },
  { code: "MEDS-006", title: "Research Methods in" },
  { code: "MJM-002", title: "Production and Presentation" },
  { code: "MJM-003", title: "Recording and Editing" },
  { code: "MEDSP-007", title: "Project Work" },
  { code: "MJME-001", title: "Practical Manual" },
  { code: "MEDSP-004", title: "Project Work" },
  { code: "CCR-BJM-001", title: "Introduction to Community Radio" },
  { code: "MEDSP-007", title: "Project Work" },
  { code: "MEDS-010", title: "Training for Development" },
  { code: "MAE-002", title: "Policy Planning and" },
  { code: "CCR-BJMP-001", title: "Internship Manual" },
  { code: "CCR-BJM-002", title: "Operating a" },
  { code: "MAEL-001", title: "Practical Work Community Radio Components" },
  { code: "MEDS-008", title: "Extension Communication" },
  { code: "JMC-001", title: "" },
  { code: "JMC-002", title: "" },
  { code: "MEDS-009", title: "Development in India" },
  { code: "JMC-003", title: "" },
  { code: "JMC-004", title: "" },
  { code: "MEDS-010", title: "Training for Development" },
  { code: "MEDS-011", title: "Local Self Governance" },
  { code: "MEDSE-015", title: "Family Healthcare" },
  { code: "MEDS-001", title: "Introduction to Extension Education" },
  { code: "BEDS-001", title: "Overview and" },
  {
    code: "MEDS-002",
    title: "Dynamics of Extension Perspective of Values and Development",
  },
  { code: "BEDS-002", title: "Socio" },
  { code: "BEDS-003", title: "Pedagogy of Values" },
  { code: "BEDS-004", title: "Application and Support" },
  { code: "MFC-01", title: "Folklore and Culture" },
  { code: "MEDS-041", title: "Introduction to Urban" },
  {
    code: "MFC-02",
    title: "Tradition Identity and Development Cultural Production",
  },
  { code: "MEDS-042", title: "Challenges in Urban" },
  { code: "MFC-03", title: "Cultural and Societal Issues and Planning" },
  { code: "MFC-04", title: "Tribes of India" },
  { code: "MEDS-043", title: "Dynamics of Urban" },
  { code: "MPYE-16", title: "Philosophy of Sri Aurobindo" },
  { code: "MEDS-044", title: "Monitoring and" },
  { code: "MPYE-15", title: "Gandhian Philosophy" },
  { code: "MPYE-14", title: "Philosophy of Mind" },
  { code: "MPYE-13", title: "Philosophy of Technology" },
  { code: "MEDSP-045", title: "Post Graduate Diploma" },
  { code: "MPYE-12", title: "Tribal Philosophy" },
  { code: "MPYE-11", title: "Philosophy of Art" },
  { code: "MEDSE-046", title: "Development Issues" },
  { code: "MPYE-10", title: "Philosophy of Religion" },
  { code: "MEDSP-17", title: "Dissertation Handbook" },
  { code: "MPYE-09", title: "Philosophy of Science" },
  { code: "MAEP-01", title: "Handbook in" },
  { code: "MPYE-08", title: "Metaphysics" },
  { code: "MAE-004", title: "Extension Education" },
  {
    code: "MPYE-07",
    title: "Research Methodology and Development in Philosophy",
  },
  { code: "MAEE-001", title: "Sustainable Development" },
  { code: "MPYE-06", title: "Dalit Philosophy" },
  { code: "MAE-005", title: "(English)" },
  { code: "MPYE-05", title: "World Religions" },
  {
    code: "MPYE-04",
    title: "Philosophy of Human Development Education Person",
  },
  { code: "MAEE-002", title: "Basics of Legal" },
  { code: "MPYE-03", title: "Epistemology" },
  { code: "MPYE-02", title: "Ethics" },
  { code: "MPYE-01", title: "Logic" },
  { code: "MPY-01", title: "Indian Philosophy" },
  { code: "BAL-001", title: "Basics ofArabic" },
  { code: "MPY-02", title: "Western Philosophy" },
  { code: "BAL-002", title: "Communication Skills" },
  { code: "BPY-01", title: "Indian Philosophy" },
  { code: "DTG-001", title: "General Principles of Teaching" },
  { code: "BPY-02", title: "Logic" },
  { code: "BPY-003", title: "Ancient and Medieval" },
  { code: "MTT-17", title: "dk'kfoKku" },
  { code: "BPY-04", title: "Religions of the World" },
  { code: "MTT-20", title: "vuokn izf" },
  { code: "BPY-05", title: "Indian Philosophy" },
  { code: "MTT-21", title: "vuokn izf'k" },
  { code: "BPY-06", title: "Metaphysics" },
  { code: "PGDT-01", title: "vuokn" },
  { code: "BPY-07", title: "Ethics" },
  { code: "PGDT-02", title: "vuokn dk Hkkfkd vkj Philosophy" },
  { code: "BPY-09", title: "Contemporary Western" },
  { code: "PGDT-03", title: "O" },
  { code: "BPY-10", title: "Epistemology" },
  { code: "BPY-11", title: "Philosophy of Human" },
  { code: "PGDT-04", title: "iz" },
  {
    code: "BPY-12",
    title:
      "Philosophy of Science SCHOOL OF GENDER AND DEVELOPMENT and Cosmology",
  },
  { code: "BPYE-01", title: "Philosophy of Religion" },
  { code: "MWG-001", title: "Theories of Women" },
  { code: "BPYE-02", title: "Tribal and Dalit Philosophy" },
  { code: "MWG-002", title: "Gender and Power" },
  { code: "MWG-003", title: "Constructing Gender" },
  { code: "MTT-001", title: "Hkkjrh" },
  { code: "MTT-002", title: "caXyk" },
  { code: "MWG-004", title: "Gendered Bodies and ryuk vkSj iqu" },
  { code: "MTT-003", title: "caXyk vkSj fgnh ds fofHkUu" },
  { code: "MWGP-001", title: "Project Work Manuall" },
  { code: "MWG-005", title: "Research Methods" },
  { code: "MTT-004", title: "ey" },
  { code: "MWG-006", title: "Gendered" },
  { code: "MWG-007", title: "Postmodernism" },
  { code: "MTT-005", title: "ey" },
  { code: "MWG-008", title: "Gender" },
  { code: "MTT-10", title: "vuokn fl)kr" },
  { code: "MWG-009", title: "Women and Social Structure" },
  { code: "MTT-11", title: "vuokn" },
  { code: "MWG-010", title: "Women and Political Process" },
  { code: "MTT-12", title: "vuokn vkSj HkkkkfoKku" },
  { code: "MWG-011", title: "Women in the Economy" },
  { code: "MTT-13", title: "vuokn ds" },
  { code: "MGS-001", title: "Gender and Development" },
  { code: "MTT-15", title: "vuokn vkSj lkfgR" },
  { code: "MTT-16", title: "vuokn vkSj tulpkj" },
  { code: "MGS-002", title: "Gender Development" },
  { code: "MGSE-004", title: "Gender Issues in Goals and Praxis" },
  { code: "MGS-003", title: "Gender Analysis" },
  { code: "MGS-004", title: "Gender" },
  { code: "MGSE-006", title: "Gender Resources and Policy Making" },
  { code: "MGS-005", title: "Research Methodologies" },
  {
    code: "MGSE-009",
    title:
      "Gender Issues in Work  in Gender and Employment and Development Studies",
  },
  { code: "MGSP-001", title: "Internship" },
  { code: "MGSE-013", title: "Training and Research Project" },
  { code: "MGSE-001", title: "Gender Planning and" },
  { code: "MGSE-020", title: "Gender and Development Policies" },
  { code: "MGSE-002", title: "Gender Audit and Gender" },
  { code: "MGSP-002", title: "Internship" },
  { code: "MGSE-003", title: "Gender Mainstreaming" },
];
