export const courses = [
  // BAG, Bachelor of Arts
  {
    code: "BANC 131",
    title: "Anthropology and Research Methods",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANC 132",
    title: "Fundamentals of Biological Anthropology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANC 133",
    title: "Fundamentals of Social and Cultural Anthropology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANC 134",
    title: "Fundamentals of Archaeological Anthropology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BECC 131",
    title: "Principles of Microeconomics-I",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BECC 132",
    title: "Principles of Microeconomics-II",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BECC 133",
    title: "Principles of Macroeconomics-I",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BECC 134",
    title: "Principles of Macroeconomics-II",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIC 131",
    title: "History of India from the Earliest Times upto c. 300 CE",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIC 132",
    title: "History of India from c.300 to 1206",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIC 133",
    title: "History of India from c.1206 to 1707",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIC 134",
    title: "History of India from c. 1707 to 1950",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSC 131",
    title: "Introduction to Political Theory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSC 132",
    title: "Indian Government and Politics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSC 133",
    title: "Comparative Government and Politics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSC 134",
    title: "Introduction to International Relations",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCC 131",
    title: "Foundations of Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCC 132",
    title: "Introduction to Social Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCC 133",
    title: "Psychological Disorders",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCC 134",
    title: "Statistical Methods and Psychological Research",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAC 131",
    title: "Perspectives on Public Administration",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAC 132",
    title: "Administrative Thinkers",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAC 133",
    title: "Administrative system at Union Level",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAC 134",
    title: "Administrative system at State and DistrictLevels",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOC 131",
    title: "Introduction to Sociology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOC 132",
    title: "Sociology of India",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOC 133",
    title: "Sociological Theories",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOC 134",
    title: "Methods of Sociological Enquiry",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDC 131",
    title: "�हंद�सा�हत्यकाइ�तहास",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDC 132",
    title: "मध्यकाल�न�हंद�क�वता",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDC 133",
    title: "आधु�नक�हंद�क�वता",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDC 134",
    title: "�हंद�गद्यसा�हत्य",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDLA 135",
    title: "�हंद�भाषा : �व�वधप्रयोग",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDLA 136",
    title: "�हंद�भाषा : लेखनकौशल",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDLA 137",
    title: "�हंद�भाषा : संप्रेषाकौशल",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDLA 138",
    title: "�हंद�सा�हत्य : �व�वध�वधाएँ",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BUDC 131",
    title: "Study of Prose & Poetic Form in Urdu",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BUDC 132",
    title: "Study of Urdu Classical Ghazal",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BUDC 133",
    title: "Origin & Development of Urdu Language",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BUDC 134",
    title: "Study of Urdu Nazm",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BUDLA 135",
    title: "Study of Modern Urdu Prose & Poetry",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGC 131",
    title: "Individual & Society",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGC 132",
    title: "Selections From Indian Writing: CulturalDiversity",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGC 133",
    title: "British Literature",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGC 134",
    title: "Reading The Novel",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGLA 135",
    title: "English In Daily Life",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGLA 136",
    title: "English At The Work Place",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGLA 137",
    title: "Language Through Literature",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGLA 138",
    title: "Reading and Speaking Skills",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSKC 131",
    title: "संस्कृत पद्य सा�हत्य",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSKC 132",
    title: "संस्कृत गद्य सा�हत्य",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BSKC 133", title: "संस्कृत नाटक", studyMaterial: ["", "", "", ""] },
  {
    code: "BSKC 134",
    title: "संस्कृत व्याकरण",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSKLA 135",
    title: "संस्कृत सा�हत्य एवं व्याकरण",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BODLA 135",
    title: "Modern Indian Language: Odia",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGULA 135",
    title: "Modern Indian Language: Gujarati",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BMYLA 135",
    title: "Modern Indian Language: Malayalam",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPBLA",
    title: "Modern Indian Language: Punjabi",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BMTC 131", title: "Calculus", studyMaterial: ["", "", "", ""] },
  {
    code: "BMTC 132",
    title: "Differential Equations",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BMTC 133", title: "Real Analysis", studyMaterial: ["", "", "", ""] },
  { code: "BMTC 134", title: "Algebra", studyMaterial: ["", "", "", ""] },
  {
    code: "BESC 131",
    title: "Education: Concept, Nature and Perspectives",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BESC 132",
    title: "Structure and Management of Education ",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BESC 133",
    title: "Curriculum, Teaching-Learning and Assessment",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BESC 134",
    title: "Education as a Practice",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPYC 131",
    title: "Indian Philosophy",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BPYC 132", title: "Ethics", studyMaterial: ["", "", "", ""] },
  { code: "BPYC 133", title: "Logic", studyMaterial: ["", "", "", ""] },
  {
    code: "BPYC 134",
    title: "Western Philosophy: Modern",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANE 145",
    title: "Applied Anthropology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANE 146",
    title: "Anthropology of Indigenous People",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BECE 145",
    title: "Indian Economy – I",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BECE 146",
    title: "Indian Economy – II",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIE 141",
    title: "History of China: C. 1840-1978",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIE 142",
    title: "History of Modern East Asia: Japan (1868-1945)",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIE 143",
    title: "History of Environment",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIE 144",
    title: "Traditions of History Writing in India",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHIE 145",
    title: "Some aspects of European History: C. 1789 – 1945",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSE 141",
    title: "Gandhi and the Contemporary World",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSE 142",
    title: "India’s Foreign Policy in a Changing World",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSE 143",
    title: "State Politics in India",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSE 144",
    title: "Introduction to South Asia",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSE 145",
    title: "Democracy and Development in Northeast India",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPSE 146",
    title: "Conflict Resolution and Peace building",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCE 145",
    title: "Counselling Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCE 146",
    title: "Industrial/ Organisational Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAE 141",
    title: "Right to Information",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAE 142",
    title: "Organisational Behaviour",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAE 143",
    title: "Administrative System in BRICS",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAE 144",
    title: "Social Policies and Administration",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOE 145",
    title: "Religion and Society",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOE 146",
    title: "Marriage, Family and Kinship",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOE 148",
    title: "Social Stratification",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDE 141",
    title: "अिस्मतामूलक �वमशर् और �हंद� सा�हत्य",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDE 142",
    title: "राष्ट्र�य काव्यधारा",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BHDE 143", title: "प्रेमचंद", studyMaterial: ["", "", "", ""] },
  { code: "BHDE 144", title: "छायावाद", studyMaterial: ["", "", "", ""] },
  {
    code: "BUDE 141",
    title: "Study of Poet Mirza Ghalib",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BUDE 142",
    title: "Study of Prose Writer Meer Amman Dehlawi",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGE 141",
    title: "Understanding Prose",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGE 142",
    title: "Understanding Drama",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGE 143",
    title: "Understanding Poetry",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BEGE 145", title: "Soft Skills", studyMaterial: ["", "", "", ""] },
  {
    code: "BSKE 141",
    title: "आयुव�द के मूल आधार",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSKE 142",
    title: "रंगमंच और नाट्य कला",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BMTE 141",
    title: "Linear Algebra",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BMTE 144",
    title: "Numerical Analysis",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BESE 141",
    title: "ICT in Education",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BESE 142",
    title: "Lifelong Learning",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BPYE 141", title: "Metaphysics", studyMaterial: ["", "", "", ""] },
  {
    code: "BPYE 142",
    title: "Social and Political Philosophy",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANS 184",
    title: "Public Health and Epidemiology",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BECS 184", title: "Data Analysis", studyMaterial: ["", "", "", ""] },
  {
    code: "BPCS 183",
    title: "Emotional Intelligence",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 184",
    title: "School Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 185",
    title: "Developing Emotional Competence",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 187",
    title: "Managing Human Resources",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 188",
    title: "Application of Social Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAS 184",
    title: "Logistics Management",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAS 186",
    title: "Stress and Time Management ",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOS 184",
    title: "Techniques of Ethnographic Film Making",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOS 185",
    title: "Society through the Visual",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDS 183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BHDS 184", title: "रे�डयो लेखन", studyMaterial: ["", "", "", ""] },
  {
    code: "BEGS 183",
    title: "Writing And Study Skills",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGS 185",
    title: "English Language Teaching",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGS 186",
    title: "Business Communication",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGDG 172",
    title: "Gender Sensitization: Society and Culture",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCG 171",
    title: "General Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCG 172",
    title: "Youth, Gender and Identity",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCG 173",
    title: "Psychology for Health andWell-being",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCG 174",
    title: "Psychology and Media",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCG 175",
    title: "Psychology for Living",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCG 176",
    title: "Psychology of Gender",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAG 171",
    title: "Disaster Management",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAG 172",
    title: "Governance: Issues and Challenges",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BPAG 173", title: "E-Governance", studyMaterial: ["", "", "", ""] },
  {
    code: "BPAG 174",
    title: "Sustainable Development",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOG 171",
    title: "Indian Society: Images and Realities",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOG 173",
    title: "Rethinking Development",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOG 176",
    title: "Economy and Society",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDG 173",
    title: "समाचार पत्र और फ�चर लेखन",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGG 171",
    title: "Media and Communication Skills",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGG 172",
    title: "Language and Linguistics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGG 173",
    title: "Academic Writing & Composition",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGG 174",
    title: "Creative Writing",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BABG 171",
    title: "Understanding Ambedkar",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPYG 171",
    title: "Applied Ethics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPYG 172",
    title: "Philosophy of Religion",
    studyMaterial: ["", "", "", ""],
  },
  // BCOMG, Bachelor of Commerce
  {
    code: "BCOC 131",
    title: "Financial Accounting",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOC 132",
    title: "Business Organization and Management",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BCOC 133", title: "Business Law", studyMaterial: ["", "", "", ""] },
  {
    code: "BCOC 134",
    title: "Business Mathematics and Statistics",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BCOC 135", title: "Company Law", studyMaterial: ["", "", "", ""] },
  {
    code: "BCOC 136",
    title: "Income Tax Law and Practice",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOC 137",
    title: "Corporate Accounting",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOE 141",
    title: "Principles of Marketing",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOE 143",
    title: "Fundamentals of Financial Management",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOE 142",
    title: "Management Accounting",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOE 144",
    title: "Office Management and Secretarial Practice",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOS 183",
    title: "Computer Application in Business",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BCOS 184", title: "E-Commerce", studyMaterial: ["", "", "", ""] },
  {
    code: "BCOS 185",
    title: "Entrepreneurship",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOS 186",
    title: "Personal Selling and Salesmanship",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOG 171",
    title: "Principles of Micro Economics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOG 172",
    title: "Indian Economy",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGLA 135",
    title: "English In Daily Life",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGLA 136",
    title: "English At The Work Place",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGLA 137",
    title: "Language Through Literature",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOLA 138",
    title: "Business Communication",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDLA 136",
    title: "�हंद� भाषा: लेखन कौशल",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDLA 137",
    title: "�हंद� भाषा: सम्प्रेषण कौशल",
    studyMaterial: ["", "", "", ""],
  },
  // BSCG, Bachelor of Science
  {
    code: "BBYCT 131",
    title: "Biodiversity (Microbes, Algae, Fungi and Archegoniates)",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYCL 132",
    title:
      "Biodiversity (Microbes, Algae, Fungi and Archegoniates): Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYCT 133",
    title: "Plant Ecology and Taxonomy",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYCL 134",
    title: "Plant Ecology and Taxonomy: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYCT 135",
    title: "Plant Anatomy and Embryology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYCL 136",
    title: "Plant Anatomy and Embryology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYCT 137",
    title: "Plant Physiology and Metabolism",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYCL 138",
    title: "Plant Physiology and Metabolism: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCT 131",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCL 132",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCT 133",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry-I",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCL 134",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry-I : Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCT 135",
    title:
      "Solutions, Phase equilibrium, Conductance, Electrochemistry and Functional Group Organic Chemistry-II",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCL 136",
    title:
      "Solutions, Phase equilibrium, Conductance, Electrochemistry and Functional Group Organic Chemistry-II : Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCT 137",
    title: "Coordination Chemistry, States of Matter and Chemical Kinetics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHCL 138",
    title:
      "Coordination Chemistry, States of Matter and Chemical Kinetics: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGGCT 131",
    title: "Physical Geography",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGGCT 132",
    title: "Human Geography",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGGCT 133",
    title: "General Cartography",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGGCL 134",
    title: "General Cartography: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGGCT 135",
    title: "Environmental Geography",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYCT 131",
    title: "Physical and Structural Geology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYCL 132",
    title: "Physical and Structural Geology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYCT 133",
    title: "Crystallography, Mineralogy and Economic Geology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYCL 134",
    title: "Crystallography, Mineralogy and Economic Geology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BGYCT 135", title: "Petrology", studyMaterial: ["", "", "", ""] },
  {
    code: "BGYCL 136",
    title: "Petrology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYCT 137",
    title: "Stratigraphy and Palaeontology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYCL 138",
    title: "Stratigraphy and Palaeontology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BMTC 131", title: "Calculus", studyMaterial: ["", "", "", ""] },
  {
    code: "BMTC 132",
    title: "Differential Equations",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BMTC 133", title: "Real Analysis", studyMaterial: ["", "", "", ""] },
  { code: "BMTC 134", title: "Algebra", studyMaterial: ["", "", "", ""] },
  { code: "BPHCT 131", title: "Mechanics", studyMaterial: ["", "", "", ""] },
  {
    code: "BPHCL 132",
    title: "Mechanics: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHCT 133",
    title: "Electricity and Magnetism",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHCL 134",
    title: "Electricity and Magnetism: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHCT 135",
    title: "Thermal Physics and Statistical Mechanics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHCL 136",
    title: "Thermal Physics and Statistical Mechanics: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHCT 137",
    title: "Wave and Optics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHCL 138",
    title: "Wave and Optics: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCT 131",
    title: "Animal Diversity",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCL 132",
    title: "Animal Diversity: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCT 133",
    title: "Comparative Anatomy and Developmental Biology of Vertebrates",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCL 134",
    title:
      "Comparative Anatomy and Developmental Biology of Vertebrates: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCT 135",
    title: "Physiology and Biochemistry",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCL 136",
    title: "Physiology and Biochemistry: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCT 137",
    title: "Genetics and Evolutionary Biology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYCL 138",
    title: "Genetics and Evolutionary Biology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYET 141",
    title: "Cell and Molecular Biology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYEL 142",
    title: "Cell and Molecular Biology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYET 143",
    title: "Economic Botany and Biotechnology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BBYEL 144",
    title: "Economic Botany and Biotechnology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHET 141",
    title: "Analytical Methods in Chemistry",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHEL 142",
    title: "Analytical Methods in Chemistry: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHET 147",
    title:
      "Organometallics, Bioinorganic Chemistry, PolynuclearHyderocarbons and UV, IR Spectroscopy",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHEL 148",
    title:
      "Organometallics, Bioinorganic Chemistry, Polynuclear Hydrocarbons and UV, IR Spectroscopy: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHET 149",
    title: "Molecules of Life",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCHEL 150",
    title: "Molecules of Life: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGGET 141",
    title: "Geography of India",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGGET 142",
    title: "Economic Geography",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYET 141",
    title: "Ore Geology and Industrial Minerals",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYEL 142",
    title: "Ore Geology and Industrial Minerals: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYET 147",
    title: "Geomorphology and Geotectonics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BGYEL 148",
    title: "Geomorphology and Geotectonics: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BMTE 141",
    title: "Linear Algebra",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BMTE 144",
    title: "Numerical Analysis",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHET 141",
    title: "Elements of Modern Physics",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHEL 142",
    title: "Elements of Modern Physics: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHET 143",
    title: "Digital and Analog Circuits and Instrumentation",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPHEL 144",
    title: "Digital and Analog Circuits and Instrumentation: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BZYET 141", title: "Immunology", studyMaterial: ["", "", "", ""] },
  {
    code: "BZYEL 142",
    title: "Immunology: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYET 143",
    title: "Insect Vectors and Vector Borne Diseases",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BZYEL 144",
    title: "Insect Vectors and Vector Borne Diseases: Laboratory",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANS 183",
    title: "Tourism Anthropology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 185",
    title: "Developing Emotional Competence",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGS 183",
    title: "Writing and Study Skills",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOS 183",
    title: "Computer Application in Business",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDS 183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BANS 184",
    title: "Public Health and Epidemiology",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BECS 184", title: "Data Analysis", studyMaterial: ["", "", "", ""] },
  { code: "BCOS 184", title: "E-Commerce", studyMaterial: ["", "", "", ""] },
  {
    code: "BPAS 184",
    title: "Logistics Management",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 184",
    title: "School Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 186",
    title: "Managing Stress",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOS 184",
    title: "Techniques of Ethnographic Film Making",
    studyMaterial: ["", "", "", ""],
  },
  { code: "BHDS 184", title: "रे �डयो लेखन", studyMaterial: ["", "", "", ""] },
  {
    code: "BPCS 187",
    title: "Managing Human Resources",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BSOS 185",
    title: "Society through the Visual",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGS 185",
    title: "English Language Teaching",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOS 185",
    title: "Entrepreneurship",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPAS 186",
    title: "Stress and Time Management",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BPCS 188",
    title: "Application of Social Psychology",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGS 186",
    title: "Business Communication",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BCOS 186",
    title: "Personal Selling and Slesmanship",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEVAE 181",
    title: "Environmental Studies",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BEGAE 182",
    title: "English Communication Skills",
    studyMaterial: ["", "", "", ""],
  },
  {
    code: "BHDAE 182",
    title: "�हंद� भाषा और संप्रेषण",
    studyMaterial: ["", "", "", ""],
  },
  // BCA, Bachelor of Computer Applications
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
  { code: "", title: "", studyMaterial: ["", "", "", ""] },
];
