export const mastersDegreeCourse = [
  {
    code: "IBO 1",
    title: "International Business Environment",
    studyMaterial: [],
  },
  {
    code: "IBO 2",
    title: "International Marketing Management",
    studyMaterial: [],
  },
  { code: "IBO 3", title: "India’s Foreign Trade", studyMaterial: [] },
  {
    code: "IBO 4",
    title: "Export Import Procedures and Documentation",
    studyMaterial: [],
  },
  {
    code: "IBO 5",
    title: "International Marketing Logistics",
    studyMaterial: [],
  },
  { code: "IBO 6", title: "International Business Finance", studyMaterial: [] },
  {
    code: "MCO 1",
    title: "Organization Theory and Behaviour",
    studyMaterial: [],
  },
  {
    code: "MCO 3",
    title: "Research Methodology and Statistical Analysis",
    studyMaterial: [],
  },
  { code: "MCO 4", title: "Business Environment", studyMaterial: [] },
  {
    code: "MCO 5",
    title: "Accounting for Managerial Decisions",
    studyMaterial: [],
  },
  { code: "MCO 6", title: "Marketing Management", studyMaterial: [] },
  { code: "MCO 7", title: "Financial Management", studyMaterial: [] },
  { code: "MEG 1", title: "British Poetry", studyMaterial: [] },
  { code: "MEG 2", title: "British Drama", studyMaterial: [] },
  { code: "MEG 3", title: "British Novel", studyMaterial: [] },
  { code: "MEG 4", title: "Aspects of Language", studyMaterial: [] },
  { code: "MEG 5", title: "Literary Criticism and Theory", studyMaterial: [] },
  { code: "MEG 6", title: "American Literature", studyMaterial: [] },
  { code: "MEG 7", title: "Indian English Literature", studyMaterial: [] },
  { code: "MEG 8", title: "New Literatures in English", studyMaterial: [] },
  { code: "MEG 9", title: "Australian Literature", studyMaterial: [] },
  { code: "MEG 10", title: "English Studies in India", studyMaterial: [] },
  { code: "MEG 11", title: "American Novel", studyMaterial: [] },
  {
    code: "MEG 12",
    title: "A Survey Course in 20th Century Canadian Literature",
    studyMaterial: [],
  },
  { code: "MEG 13", title: "Writing from the Margins", studyMaterial: [] },
  {
    code: "MEG 14",
    title: "Contemporary Indian Literature in English Translation",
    studyMaterial: [],
  },
  {
    code: "MEG 15",
    title: "Comparative Literature: Theory and Practice",
    studyMaterial: [],
  },
  { code: "MEG 16", title: "Indian Folk Literature", studyMaterial: [] },
  { code: "MPS 1", title: "Political Theory", studyMaterial: [] },
  {
    code: "MPS 2",
    title: "International Relations: Theory and Problems",
    studyMaterial: [],
  },
  {
    code: "MPS 3",
    title: "India: Democracy and Development",
    studyMaterial: [],
  },
  {
    code: "MPS 4",
    title: "Comparative Politics: Issues and Trends",
    studyMaterial: [],
  },
  { code: "MPSE 1", title: "India and the World", studyMaterial: [] },
  {
    code: "MPSE 2",
    title: "State and Society in Latin America",
    studyMaterial: [],
  },
  { code: "MPSE 3", title: "Western Political Thought", studyMaterial: [] },
  {
    code: "MPSE 4",
    title: "Social and Political Thought in Modern India",
    studyMaterial: [],
  },
  { code: "MPSE 5", title: "State and Society in Africa", studyMaterial: [] },
  { code: "MPSE 6", title: "Peace and Conflict Studies", studyMaterial: [] },
  {
    code: "MPSE 7",
    title: "Social Movements and Politics in India",
    studyMaterial: [],
  },
  { code: "MPSE 8", title: "State Politics in India", studyMaterial: [] },
  { code: "MPSE 9", title: "Canada: Politics and Society", studyMaterial: [] },
  {
    code: "MPSE 11",
    title: "The European Union in World Affairs",
    studyMaterial: [],
  },
  {
    code: "MPSE 12",
    title: "State and Society in Australia",
    studyMaterial: [],
  },
  { code: "MPSE 13", title: "Australia’s Foreign Policy", studyMaterial: [] },
  {
    code: "MED 2",
    title: "Sustainable Development: Issues and Challenges",
    studyMaterial: [],
  },
  { code: "MED 8", title: "Globalisation and Environment", studyMaterial: [] },
  { code: "MGP 4", title: "Gandhi’s Political Thought", studyMaterial: [] },
  {
    code: "MGPE 7",
    title: "Non-Violent Movements after Gandhi",
    studyMaterial: [],
  },
  {
    code: "MGPE 8",
    title: "Gandhian Approach to Peace and Conflict Resolution",
    studyMaterial: [],
  },
  {
    code: "MGPE 10",
    title: "Conflict Management, Transformation & Peace Building",
    studyMaterial: [],
  },
  { code: "MGPE 11", title: "Human Security", studyMaterial: [] },
  {
    code: "MGPE 13",
    title: "Civil Society, Political Regimes and Conflict",
    studyMaterial: [],
  },
  { code: "MHI 1", title: "Ancient and Medieval Societies", studyMaterial: [] },
  { code: "MHI 2", title: "Modern World", studyMaterial: [] },
  { code: "MHI 4", title: "Political Structures in India", studyMaterial: [] },
  { code: "MHI 5", title: "History of Indian Economy", studyMaterial: [] },
  { code: "MHI 3", title: "Historiography", studyMaterial: [] },
  { code: "MPSE 3", title: "Western Political Thought", studyMaterial: [] },
  {
    code: "MPSE 4",
    title: "Social and Political Thought in Modern India",
    studyMaterial: [],
  },
  {
    code: "MHI 6",
    title: "Evolution of Social Structures in India through the Ages",
    studyMaterial: [],
  },
  {
    code: "MHI 8",
    title: "History of Ecology and Environment: India",
    studyMaterial: [],
  },
  { code: "MHI 9", title: "Indian National Movement", studyMaterial: [] },
  { code: "MHI 10", title: "Urbanization in India", studyMaterial: [] },
  {
    code: "MSO 1",
    title: "Sociological Theories and Concepts",
    studyMaterial: [],
  },
  {
    code: "MSO 2",
    title: "Research Methods and Methodologies",
    studyMaterial: [],
  },
  { code: "MSO 3", title: "Sociology of Development", studyMaterial: [] },
  { code: "MSO 4", title: "Sociology in India", studyMaterial: [] },
  { code: "MSOE 1", title: "Sociology of Education", studyMaterial: [] },
  {
    code: "MSOE 2",
    title: "Diaspora and Transnational Communities",
    studyMaterial: [],
  },
  { code: "MSOE 3", title: "Sociology of Religion", studyMaterial: [] },
  { code: "MSOE 4", title: "Urban Sociology", studyMaterial: [] },
  {
    code: "MPA 16",
    title: "Decentralization and LocalGovernance",
    studyMaterial: [],
  },
  {
    code: "MPS 3",
    title: "India: Democracy andDevelopment",
    studyMaterial: [],
  },
  {
    code: "MPC 1",
    title: "Cognitive Psychology, Learning and Memory",
    studyMaterial: [],
  },
  { code: "MPC 2", title: "Life Span Psychology", studyMaterial: [] },
  {
    code: "MPC 3",
    title: "Personality: Theories and Assessment",
    studyMaterial: [],
  },
  { code: "MPC 4", title: "Advanced Social Psychology", studyMaterial: [] },
  { code: "MPC 5", title: "Research Methods in Psychology", studyMaterial: [] },
  { code: "MPC 6", title: "Statistics in Psychology", studyMaterial: [] },
  {
    code: "MPCL 7",
    title: "Practicum in Experimental Psychology & Psychological Testing",
    studyMaterial: [],
  },
  { code: "MPCE 11", title: "Psychopathology", studyMaterial: [] },
  { code: "MPCE 12", title: "Psychodiagnostics", studyMaterial: [] },
  { code: "MPCE 13", title: "Psychotherapeutic methods", studyMaterial: [] },
  {
    code: "MPCE 14",
    title: "Practicum in Clinical Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 15", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE 16/46",
    title: "Project/Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 21", title: "Counselling Psychology", studyMaterial: [] },
  {
    code: "MPCE 22",
    title: "Assessment in Counselling and Guidance",
    studyMaterial: [],
  },
  { code: "MPCE 23", title: "Interventions in Counselling", studyMaterial: [] },
  {
    code: "MPCE 24",
    title: "Practicum in Counselling Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 25", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE 26/46",
    title: "Project/ Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 31", title: "Organisational Behaviour", studyMaterial: [] },
  { code: "MPCE 32", title: "Human Resource Development", studyMaterial: [] },
  { code: "MPCE 33", title: "Organisational Development", studyMaterial: [] },
  {
    code: "MPCE 34",
    title: "Practicum in Industrial and Organisational Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 35", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE 36/46",
    title: "Project/ Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MEC 101", title: "Microeconomic Analysis", studyMaterial: [] },
  { code: "MEC 2", title: "Macroeconomic Analysis", studyMaterial: [] },
  { code: "MEC 103", title: "Quantitative Methods", studyMaterial: [] },
  {
    code: "MEC 4",
    title: "Economics of Growth and Development",
    studyMaterial: [],
  },
  { code: "MEC 205", title: "Indian Economic Policy", studyMaterial: [] },
  { code: "MEC 106", title: "Public Economics", studyMaterial: [] },
  {
    code: "MEC 7",
    title: "International Trade and Finance",
    studyMaterial: [],
  },
  {
    code: "MEC 108",
    title: "Economics of Social Sector and Environment",
    studyMaterial: [],
  },
  {
    code: "MEC 109",
    title: "Research Methods in Economics",
    studyMaterial: [],
  },
  { code: "MECE 1", title: "Econometric Methods", studyMaterial: [] },
  {
    code: "MECE 3",
    title: "Actuarial Economics: Theory and Practice",
    studyMaterial: [],
  },
  {
    code: "MECE 4",
    title: "Financial Institutions and Markets",
    studyMaterial: [],
  },
  { code: "MECP 101", title: "Project Work", studyMaterial: [] },
  { code: "MWG 11", title: "Women in the Economy", studyMaterial: [] },
  {
    code: "MGSE 9",
    title: "Gender Issues in Work Employment andProductivity",
    studyMaterial: [],
  },
  {
    code: "MEDSE 46",
    title: "Development Issues and Perspectives",
    studyMaterial: [],
  },
  {
    code: "MPA 11",
    title: "State, Society and Public Administration",
    studyMaterial: [],
  },
  { code: "MPA 12", title: "Administrative Theory", studyMaterial: [] },
  { code: "MPA 13", title: "Public Systems Management", studyMaterial: [] },
  { code: "MPA 14", title: "Human Resource Management", studyMaterial: [] },
  { code: "MPA 15", title: "Public Policy and Analysis", studyMaterial: [] },
  {
    code: "MPA 16",
    title: "Decentralisation and LocalGovernance",
    studyMaterial: [],
  },
  { code: "MPA 17", title: "Electronic Governance", studyMaterial: [] },
  { code: "MPA 18", title: "Disaster Management", studyMaterial: [] },
  {
    code: "MSO 2",
    title: "Research Methodologies and Methods",
    studyMaterial: [],
  },
  {
    code: "MPS 3",
    title: "India: Democracy and Development",
    studyMaterial: [],
  },
  { code: "MPAP 2", title: "Project Work", studyMaterial: [] },
  {
    code: "MLI 101",
    title: "Information, Communication and Society",
    studyMaterial: [],
  },
  {
    code: "MLII 101",
    title: "Information Sources, Systems and Services",
    studyMaterial: [],
  },
  {
    code: "MLI 102",
    title: "Management of Library and Information Centres",
    studyMaterial: [],
  },
  {
    code: "MLII 102",
    title: "Information Processing and Retrieval",
    studyMaterial: [],
  },
  {
    code: "MLII 103",
    title: "Fundamentals of Information Communication Technologies",
    studyMaterial: [],
  },
  {
    code: "MLII 104",
    title: "Information Communication Technologies: Applications",
    studyMaterial: [],
  },
  { code: "MLIP 2", title: "Project", studyMaterial: [] },
  {
    code: "MLIE 101",
    title: "Preservation and Conservation of Library Materials",
    studyMaterial: [],
  },
  { code: "MLIE 102", title: "Research Methodology", studyMaterial: [] },
  { code: "MLIE 103", title: "Academic Library System", studyMaterial: [] },
  { code: "MLIE 104", title: "Technical Writing", studyMaterial: [] },
  {
    code: "MLIE 105",
    title: "Informatrics and Scientometrics",
    studyMaterial: [],
  },
  {
    code: "MLIE 106",
    title: "Public Library System and Services",
    studyMaterial: [],
  },
  {
    code: "MANI 1",
    title: "Anthropology and Methods of Research (Theory and Practical)",
    studyMaterial: [],
  },
  {
    code: "MANI 2",
    title: "Physical Anthropology (Theory and Practical)",
    studyMaterial: [],
  },
  { code: "MAN 1", title: "Social Anthropology (Theory)", studyMaterial: [] },
  {
    code: "MAN 2",
    title: "Archaeological Anthropology (Theory)",
    studyMaterial: [],
  },
  { code: "MANP 1", title: "Field work Dissertation", studyMaterial: [] },
  {
    code: "MANI 3",
    title: "Practicing Anthropology (Theory and Project)",
    studyMaterial: [],
  },
  {
    code: "MANE 1",
    title: "Human Genetics (Theory and Practical)",
    studyMaterial: [],
  },
  {
    code: "MANE 2",
    title: "Human Growth & Development (Theory and Practical)",
    studyMaterial: [],
  },
  {
    code: "MANE 3",
    title: "Comparative Ethnography (Theory)",
    studyMaterial: [],
  },
  { code: "MANE 4", title: "Gender and Society (Theory)", studyMaterial: [] },
  {
    code: "MANE 5",
    title: "Environmental Anthropology (Theory)",
    studyMaterial: [],
  },
  { code: "MGP 1", title: "Gandhi: The Man and His Times", studyMaterial: [] },
  { code: "MGP 2", title: "Philosophy of Gandhi", studyMaterial: [] },
  { code: "MGP 3", title: "Gandhi’s Social Thought", studyMaterial: [] },
  { code: "MGP 4", title: "Gandhi’s Political Thought", studyMaterial: [] },
  { code: "MGPE 6", title: "Gandhi’s Economic Thought", studyMaterial: [] },
  {
    code: "MGPE 7",
    title: "Non-violent Movements after Gandhi",
    studyMaterial: [],
  },
  { code: "MGPE 9", title: "Gandhi in the 21st Century", studyMaterial: [] },
  {
    code: "MGPE 14",
    title: "Gandhi, Ecology and Sustainable Development",
    studyMaterial: [],
  },
  {
    code: "MGP 5",
    title: "Introduction to Peace and Conflict Resolution",
    studyMaterial: [],
  },
  {
    code: "MGPE 8",
    title: "Gandhi Approach to Peace and Conflict Resolutions",
    studyMaterial: [],
  },
  {
    code: "MGPE 10",
    title: "Conflict Management, Transformation and Peace Building",
    studyMaterial: [],
  },
  { code: "MGPE 11", title: "Human Security", studyMaterial: [] },
  { code: "MGPE 12", title: "Women and Peace", studyMaterial: [] },
  {
    code: "MGPE 13",
    title: "Civil Society, Political Regimes and Conflict",
    studyMaterial: [],
  },
  {
    code: "MGPE 15",
    title: "Introduction to Research Methods",
    studyMaterial: [],
  },
  {
    code: "MGPE 16",
    title: "Human Rights: Indian Perspective",
    studyMaterial: [],
  },
  { code: "MGPE 17", title: "ProjectWork", studyMaterial: [] },
  {
    code: "MCS 211",
    title: "Design and Analysis of Algorithms",
    studyMaterial: [],
  },
  { code: "MCS 212", title: "Discrete Mathematics", studyMaterial: [] },
  { code: "MCS 213", title: "Software Engineering", studyMaterial: [] },
  {
    code: "MCS 214",
    title: "Professional Skills and Ethics",
    studyMaterial: [],
  },
  { code: "MCS 215", title: "Security and Cyber Laws", studyMaterial: [] },
  { code: "MCSL 216", title: "DAA and Web Design Lab", studyMaterial: [] },
  { code: "MCSL 217", title: "Software Engineering Lab", studyMaterial: [] },
  {
    code: "MCS 218",
    title: "Data Communication and Computer Networks",
    studyMaterial: [],
  },
  {
    code: "MCS 219",
    title: "Object Oriented Analysis and Design",
    studyMaterial: [],
  },
  { code: "MCS 220", title: "Web Technologies", studyMaterial: [] },
  {
    code: "MCS 221",
    title: "Data Warehousing and Data Mining",
    studyMaterial: [],
  },
  {
    code: "MCSL 222",
    title: "OOAD and Web Technologies Lab",
    studyMaterial: [],
  },
  {
    code: "MCSL 223",
    title: "Computer Network and Data Mining Lab",
    studyMaterial: [],
  },
  {
    code: "MCS 224",
    title: "Artificial Intelligence and Machine Learning",
    studyMaterial: [],
  },
  {
    code: "MCS 225",
    title: "Accountancy and Financial Management",
    studyMaterial: [],
  },
  { code: "MCS 226", title: "Data Science and Big Data", studyMaterial: [] },
  { code: "MCS 227", title: "Cloud Computing and IoT", studyMaterial: [] },
  { code: "MCSL 228", title: "AI and Machine Learning Lab", studyMaterial: [] },
  { code: "MCSL 229", title: "Cloud and Data Science Lab", studyMaterial: [] },
  {
    code: "MCS 230",
    title: "Digital Image Processing and Computer Vision",
    studyMaterial: [],
  },
  { code: "MCS 231", title: "Mobile Computing", studyMaterial: [] },
  { code: "MCSP 232", title: "Project", studyMaterial: [] },
  {
    code: "MRD 101",
    title: "Rural Development – Indian Context",
    studyMaterial: [],
  },
  { code: "MRD 102", title: "Rural Development Programmes", studyMaterial: [] },
  {
    code: "MRD 103",
    title: "Rural Development – Planning and Management",
    studyMaterial: [],
  },
  {
    code: "MRD 4",
    title: "Research Methods in Rural Development",
    studyMaterial: [],
  },
  { code: "MRDP 1", title: "Dissertation", studyMaterial: [] },
  { code: "RDD 6", title: "Rural Health Care", studyMaterial: [] },
  {
    code: "RDD 7",
    title: "Communication and Extension in Rural Development",
    studyMaterial: [],
  },
  { code: "MRDE 101", title: "Rural Social Development", studyMaterial: [] },
  {
    code: "MRDE 2",
    title: "Voluntary Action in Rural Development",
    studyMaterial: [],
  },
  {
    code: "MRDE 3",
    title: "Land Reforms and Rural Development",
    studyMaterial: [],
  },
  {
    code: "MRDE 4",
    title: "Entrepreneurship and Rural Development",
    studyMaterial: [],
  },
  { code: "MFN 1", title: "Applied Physiology", studyMaterial: [] },
  { code: "MFN 2", title: "Nutritional Biochemistry", studyMaterial: [] },
  { code: "MFNL 2", title: "Nutritional Biochemistry", studyMaterial: [] },
  {
    code: "MFN 3",
    title: "Food Safety and Food Microbiology",
    studyMaterial: [],
  },
  {
    code: "MFNL 3",
    title: "Food Safety and Food Microbiology",
    studyMaterial: [],
  },
  { code: "MFN 4", title: "Advance Nutrition", studyMaterial: [] },
  { code: "MFNL 4", title: "Advance Nutrition", studyMaterial: [] },
  {
    code: "MFN 5",
    title: "Clinical and Therapeutic Nutrition",
    studyMaterial: [],
  },
  {
    code: "MFNL 5",
    title: "Clinical and Therapeutic Nutrition",
    studyMaterial: [],
  },
  { code: "MFN 6", title: "Public Nutrition", studyMaterial: [] },
  { code: "MFNL 6", title: "Public Nutrition", studyMaterial: [] },
  {
    code: "MFN 7",
    title: "Entrepreneurship and Food Service Management",
    studyMaterial: [],
  },
  {
    code: "MFNL 7",
    title: "Entrepreneurship and Food Service Management",
    studyMaterial: [],
  },
  { code: "MFN 8", title: "Principles of Food Science", studyMaterial: [] },
  { code: "MFNL 8", title: "Principles of Food Science", studyMaterial: [] },
  {
    code: "MFN 9",
    title: "Research Methods and Biostatistics",
    studyMaterial: [],
  },
  {
    code: "MFN 10",
    title: "Understanding Computer Applications",
    studyMaterial: [],
  },
  { code: "MFNP 11", title: "Internship Programme", studyMaterial: [] },
  { code: "MFNP 12", title: "Dissertation", studyMaterial: [] },
  {
    code: "MCFT 1",
    title: "Human Development and Family Relationships",
    studyMaterial: [],
  },
  {
    code: "MCFTL 1",
    title: "Human Development and Family Relationships Supervised Practicum",
    studyMaterial: [],
  },
  { code: "MCFT 2", title: "Mental Health and Disorders", studyMaterial: [] },
  {
    code: "MCFTL 2",
    title: "Mental Health and Disorders Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT 3",
    title:
      "Counselling and Family Therapy: Basic Concepts & Theoretical Perspectives",
    studyMaterial: [],
  },
  {
    code: "MCFTL 3",
    title:
      "Counselling and Family Therapy: Basic Concepts & Theoretical Perspectives Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT 4",
    title: "Counselling and Family Therapy: Applied Aspects",
    studyMaterial: [],
  },
  {
    code: "MCFTL 4",
    title:
      "Counselling and Family Therapy: Applied Aspects Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT 5",
    title: "Counselling and Family Therapy: Research Methods and Statistics",
    studyMaterial: [],
  },
  {
    code: "MCFTL 5",
    title:
      "Counselling and Family Therapy: Research Methods and Statistics Supervised Practicum",
    studyMaterial: [],
  },
  { code: "MCFTL 8", title: "Reflective Journal", studyMaterial: [] },
  { code: "MCFT 6", title: "Applied Social Psychology", studyMaterial: [] },
  {
    code: "MCFTL 6",
    title: "Applied Social Psychology-Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT 7",
    title: "Counselling and Family Therapy: Applications and Interventions",
    studyMaterial: [],
  },
  {
    code: "MCFTL 7",
    title:
      "Counselling and Family Therapy: Applications and Interventions Supervised Practicum",
    studyMaterial: [],
  },
  { code: "MCFTP 1", title: "Internship", studyMaterial: [] },
  { code: "MCFTP 2", title: "Dissertation", studyMaterial: [] },
  {
    code: "MCFTE 1",
    title: "Marital and Family Therapy & Counselling",
    studyMaterial: [],
  },
  {
    code: "MCFTE 4",
    title: "Marital and Family Therapy & Counselling Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFTE 2",
    title: "Child and Adolescent Counselling and Family Therapy",
    studyMaterial: [],
  },
  {
    code: "MCFTE 5",
    title:
      "Child and Adolescent Counselling and Family Therapy Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFTE 3",
    title: "Substance Abuse Counselling and Family Therapy",
    studyMaterial: [],
  },
  {
    code: "MCFTE 6",
    title:
      "Substance Abuse Counselling and Family Therapy Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MSW 1",
    title: "Origin and Development of Social Work",
    studyMaterial: [],
  },
  {
    code: "MSW 2",
    title: "Professional Social Work: Indian Perspectives",
    studyMaterial: [],
  },
  {
    code: "MSW 5",
    title: "Social Work Practicum and Supervision",
    studyMaterial: [],
  },
  { code: "MSW 3", title: "Basic Social Science Concepts", studyMaterial: [] },
  {
    code: "MSW 4",
    title: "Social Work and Social Development",
    studyMaterial: [],
  },
  { code: "MSW 6", title: "Social Work Research", studyMaterial: [] },
  {
    code: "MSWE 10",
    title: "Social Work in African Context",
    studyMaterial: [],
  },
  {
    code: "MSW 32",
    title: "Social Work and Criminal Justice",
    studyMaterial: [],
  },
  { code: "MSWL 13", title: "Social Work Practicum-I", studyMaterial: [] },
  { code: "MSWL 14", title: "Block Placement", studyMaterial: [] },
  {
    code: "MSW 7",
    title: "Case work and Counselling: Working with Individuals",
    studyMaterial: [],
  },
  {
    code: "MSW 8",
    title: "Social Group Work: Working with Groups",
    studyMaterial: [],
  },
  {
    code: "MSW 9",
    title: "Community Organisation Management for Community Development",
    studyMaterial: [],
  },
  {
    code: "MSW 17",
    title: "Contemporary Methods and Values of Social Work",
    studyMaterial: [],
  },
  {
    code: "MSWE 1",
    title: "HIV/AIDS: Stigma, Discrimination and Prevention",
    studyMaterial: [],
  },
  { code: "MSWE 2", title: "Women and Child Development", studyMaterial: [] },
  { code: "MSWE 7", title: "International Social Work", studyMaterial: [] },
  { code: "MSWE 3", title: "Disaster Management", studyMaterial: [] },
  { code: "MSWP 1", title: "Dissertation (Project work)", studyMaterial: [] },
  { code: "MSWL 15", title: "Social Work Practicum-II", studyMaterial: [] },
  { code: "MSWL 16", title: "Internship", studyMaterial: [] },
  {
    code: "MSW 1",
    title: "Origin and Development of Social Work",
    studyMaterial: [],
  },
  {
    code: "MSW 2",
    title: "Professional Social Work: Indian Perspectives",
    studyMaterial: [],
  },
  {
    code: "MSW 5",
    title: "Social Work Practicum and Supervision",
    studyMaterial: [],
  },
  {
    code: "MSW 8",
    title: "Social Group Work: Working with Groups",
    studyMaterial: [],
  },
  {
    code: "MSW 9",
    title: "Community Organisation Management for Community Development",
    studyMaterial: [],
  },
  { code: "MSWL 46", title: "Social Work Practicum-I", studyMaterial: [] },
  { code: "MSWL 47", title: "Block Placement", studyMaterial: [] },
  {
    code: "MSW 12",
    title: "Introduction to Life Characteristics and Challenges",
    studyMaterial: [],
  },
  {
    code: "MSW 13",
    title: "Introduction to Psychological Basis of Counselling",
    studyMaterial: [],
  },
  {
    code: "MSW 14",
    title: "Relevance of Social Case Work in Counselling",
    studyMaterial: [],
  },
  { code: "MSW 15", title: "Basics of Counselling", studyMaterial: [] },
  { code: "MSW 16", title: "Fields of Counselling", studyMaterial: [] },
  { code: "MSWL 48", title: "Social Work Practicum-II", studyMaterial: [] },
  { code: "MSWL 49", title: "Internship", studyMaterial: [] },
  { code: "MES 11", title: "Understanding Education", studyMaterial: [] },
  {
    code: "MES 12",
    title: "Education: Nature and Purposes",
    studyMaterial: [],
  },
  {
    code: "MES 13",
    title: "Learning, Learner and Development",
    studyMaterial: [],
  },
  { code: "MES 14", title: "Societal Context of Education", studyMaterial: [] },
  {
    code: "MES 15",
    title: "Operational Dimensions of Education",
    studyMaterial: [],
  },
  { code: "MES 16", title: "Educational Research", studyMaterial: [] },
  { code: "MESP 1", title: "Dissertation", studyMaterial: [] },
  {
    code: "MES 101",
    title: "Higher Education: Its Context and Linkages",
    studyMaterial: [],
  },
  {
    code: "MES 102",
    title: "Instruction in Higher Education",
    studyMaterial: [],
  },
  {
    code: "MES 103",
    title: "Higher Education: The Psycho-social Context",
    studyMaterial: [],
  },
  {
    code: "MES 104",
    title: "Planning and Management of Higher Education",
    studyMaterial: [],
  },
  {
    code: "MES 111",
    title: "Growth and Philosophy of Distance Education",
    studyMaterial: [],
  },
  {
    code: "MES 112",
    title: "Design and Development of Self-Learning Print Materials",
    studyMaterial: [],
  },
  { code: "MES 113", title: "Learner Support Services", studyMaterial: [] },
  {
    code: "MES 114",
    title: "Management of Distance Education",
    studyMaterial: [],
  },
  {
    code: "MES 115",
    title: "Communication Technology for Distance Education",
    studyMaterial: [],
  },
  { code: "MES 31", title: "ET -An Overview", studyMaterial: [] },
  {
    code: "MES 32",
    title: "Communication and Information Technology",
    studyMaterial: [],
  },
  { code: "MES 33", title: "Computer Technology", studyMaterial: [] },
  { code: "MES 34", title: "Designing Courseware", studyMaterial: [] },
  {
    code: "MES 41",
    title: "Growth and Development of Educational Management",
    studyMaterial: [],
  },
  {
    code: "MES 42",
    title: "Dimensions of Educational Management",
    studyMaterial: [],
  },
  { code: "MES 43", title: "Organizational Behaviour", studyMaterial: [] },
  { code: "MES 44", title: "Institutional Management", studyMaterial: [] },
  { code: "MAE 1", title: "Understanding Adult Education", studyMaterial: [] },
  {
    code: "MAE 2",
    title: "Policy Planning and Implementation of Adult Education in India",
    studyMaterial: [],
  },
  {
    code: "MAE 3",
    title:
      "Knowledge Management, Information Dissemination and Networking in Adult Education",
    studyMaterial: [],
  },
  {
    code: "MAE 4",
    title: "Extension Education and Development",
    studyMaterial: [],
  },
  { code: "MES 11", title: "Understanding Education", studyMaterial: [] },
  {
    code: "MES 12",
    title: "Education: Nature and Purposes",
    studyMaterial: [],
  },
  {
    code: "MES 13",
    title: "Learning, Learner and Development",
    studyMaterial: [],
  },
  { code: "MES 14", title: "Societal Context of Education", studyMaterial: [] },
  {
    code: "MES 15",
    title: "Operational Dimensions of Education",
    studyMaterial: [],
  },
  { code: "MES 16", title: "Educational Research", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
];
