export const mastersDegreeCourse = [
  {
    code: "IBO-1",
    title: "International Business Environment",
    studyMaterial: [],
  },
  {
    code: "IBO-2",
    title: "International Marketing Management",
    studyMaterial: [],
  },
  { code: "IBO-3", title: "India’s Foreign Trade", studyMaterial: [] },
  {
    code: "IBO-4",
    title: "Export Import Procedures and Documentation",
    studyMaterial: [],
  },
  {
    code: "IBO-5",
    title: "International Marketing Logistics",
    studyMaterial: [],
  },
  { code: "IBO-6", title: "International Business Finance", studyMaterial: [] },
  {
    code: "MCO-1",
    title: "Organization Theory and Behaviour",
    studyMaterial: [],
  },
  {
    code: "MCO-3",
    title: "Research Methodology and Statistical Analysis",
    studyMaterial: [],
  },
  { code: "MCO-4", title: "Business Environment", studyMaterial: [] },
  {
    code: "MCO-5",
    title: "Accounting for Managerial Decisions",
    studyMaterial: [],
  },
  { code: "MCO-6", title: "Marketing Management", studyMaterial: [] },
  { code: "MCO-7", title: "Financial Management", studyMaterial: [] },
  { code: "MEG-1", title: "British Poetry", studyMaterial: [] },
  { code: "MEG-2", title: "British Drama", studyMaterial: [] },
  { code: "MEG-3", title: "British Novel", studyMaterial: [] },
  { code: "MEG-4", title: "Aspects of Language", studyMaterial: [] },
  { code: "MEG-5", title: "Literary Criticism and Theory", studyMaterial: [] },
  { code: "MEG-6", title: "American Literature", studyMaterial: [] },
  { code: "MEG-7", title: "Indian English Literature", studyMaterial: [] },
  { code: "MEG-8", title: "New Literatures in English", studyMaterial: [] },
  { code: "MEG-9", title: "Australian Literature", studyMaterial: [] },
  { code: "MEG-10", title: "English Studies in India", studyMaterial: [] },
  { code: "MEG-11", title: "American Novel", studyMaterial: [] },
  {
    code: "MEG-12",
    title: "A Survey Course in 20th Century Canadian Literature",
    studyMaterial: [],
  },
  { code: "MEG-13", title: "Writing from the Margins", studyMaterial: [] },
  {
    code: "MEG-14",
    title: "Contemporary Indian Literature in English Translation",
    studyMaterial: [],
  },
  {
    code: "MEG-15",
    title: "Comparative Literature: Theory and Practice",
    studyMaterial: [],
  },
  { code: "MEG-16", title: "Indian Folk Literature", studyMaterial: [] },
  { code: "MPS-1", title: "Political Theory", studyMaterial: [] },
  {
    code: "MPS-2",
    title: "International Relations: Theory and Problems",
    studyMaterial: [],
  },
  {
    code: "MPS-3",
    title: "India: Democracy and Development",
    studyMaterial: [],
  },
  {
    code: "MPS-4",
    title: "Comparative Politics: Issues and Trends",
    studyMaterial: [],
  },
  { code: "MPSE-1", title: "India and the World", studyMaterial: [] },
  {
    code: "MPSE-2",
    title: "State and Society in Latin America",
    studyMaterial: [],
  },
  { code: "MPSE-3", title: "Western Political Thought", studyMaterial: [] },
  {
    code: "MPSE-4",
    title: "Social and Political Thought in Modern India",
    studyMaterial: [],
  },
  { code: "MPSE-5", title: "State and Society in Africa", studyMaterial: [] },
  { code: "MPSE-6", title: "Peace and Conflict Studies", studyMaterial: [] },
  {
    code: "MPSE-7",
    title: "Social Movements and Politics in India",
    studyMaterial: [],
  },
  { code: "MPSE-8", title: "State Politics in India", studyMaterial: [] },
  { code: "MPSE-9", title: "Canada: Politics and Society", studyMaterial: [] },
  {
    code: "MPSE-11",
    title: "The European Union in World Affairs",
    studyMaterial: [],
  },
  {
    code: "MPSE-12",
    title: "State and Society in Australia",
    studyMaterial: [],
  },
  { code: "MPSE-13", title: "Australia’s Foreign Policy", studyMaterial: [] },
  {
    code: "MED-2",
    title: "Sustainable Development: Issues and Challenges",
    studyMaterial: [],
  },
  { code: "MED-8", title: "Globalisation and Environment", studyMaterial: [] },
  { code: "MGP-4", title: "Gandhi’s Political Thought", studyMaterial: [] },
  {
    code: "MGPE-7",
    title: "Non-Violent Movements after Gandhi",
    studyMaterial: [],
  },
  {
    code: "MGPE-8",
    title: "Gandhian Approach to Peace and Conflict Resolution",
    studyMaterial: [],
  },
  {
    code: "MGPE-10",
    title: "Conflict Management, Transformation & Peace Building",
    studyMaterial: [],
  },
  { code: "MGPE-11", title: "Human Security", studyMaterial: [] },
  {
    code: "MGPE-13",
    title: "Civil Society, Political Regimes and Conflict",
    studyMaterial: [],
  },
  { code: "MHI-1", title: "Ancient and Medieval Societies", studyMaterial: [] },
  { code: "MHI-2", title: "Modern World", studyMaterial: [] },
  { code: "MHI-4", title: "Political Structures in India", studyMaterial: [] },
  { code: "MHI-5", title: "History of Indian Economy", studyMaterial: [] },
  { code: "MHI-3", title: "Historiography", studyMaterial: [] },
  { code: "MPSE-3", title: "Western Political Thought", studyMaterial: [] },
  {
    code: "MPSE-4",
    title: "Social and Political Thought in Modern India",
    studyMaterial: [],
  },
  {
    code: "MHI-6",
    title: "Evolution of Social Structures in India through the Ages",
    studyMaterial: [],
  },
  {
    code: "MHI-8",
    title: "History of Ecology and Environment: India",
    studyMaterial: [],
  },
  { code: "MHI-9", title: "Indian National Movement", studyMaterial: [] },
  { code: "MHI-10", title: "Urbanization in India", studyMaterial: [] },
  {
    code: "MSO-1",
    title: "Sociological Theories and Concepts",
    studyMaterial: [],
  },
  {
    code: "MSO-2",
    title: "Research Methods and Methodologies",
    studyMaterial: [],
  },
  { code: "MSO-3", title: "Sociology of Development", studyMaterial: [] },
  { code: "MSO-4", title: "Sociology in India", studyMaterial: [] },
  { code: "MSOE-1", title: "Sociology of Education", studyMaterial: [] },
  {
    code: "MSOE-2",
    title: "Diaspora and Transnational Communities",
    studyMaterial: [],
  },
  { code: "MSOE-3", title: "Sociology of Religion", studyMaterial: [] },
  { code: "MSOE-4", title: "Urban Sociology", studyMaterial: [] },
  {
    code: "MPA-16",
    title: "Decentralization and LocalGovernance",
    studyMaterial: [],
  },
  {
    code: "MPS-3",
    title: "India: Democracy andDevelopment",
    studyMaterial: [],
  },
  {
    code: "MPC-1",
    title: "Cognitive Psychology, Learning and Memory",
    studyMaterial: [],
  },
  { code: "MPC-2", title: "Life Span Psychology", studyMaterial: [] },
  {
    code: "MPC-3",
    title: "Personality: Theories and Assessment",
    studyMaterial: [],
  },
  { code: "MPC-4", title: "Advanced Social Psychology", studyMaterial: [] },
  { code: "MPC-5", title: "Research Methods in Psychology", studyMaterial: [] },
  { code: "MPC-6", title: "Statistics in Psychology", studyMaterial: [] },
  {
    code: "MPCL-7",
    title: "Practicum in Experimental Psychology & Psychological Testing",
    studyMaterial: [],
  },
  { code: "MPCE-11", title: "Psychopathology", studyMaterial: [] },
  { code: "MPCE-12", title: "Psychodiagnostics", studyMaterial: [] },
  { code: "MPCE-13", title: "Psychotherapeutic methods", studyMaterial: [] },
  {
    code: "MPCE-14",
    title: "Practicum in Clinical Psychology",
    studyMaterial: [],
  },
  { code: "MPCE-15", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE-16/46",
    title: "Project/Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MPCE-21", title: "Counselling Psychology", studyMaterial: [] },
  {
    code: "MPCE-22",
    title: "Assessment in Counselling and Guidance",
    studyMaterial: [],
  },
  { code: "MPCE-23", title: "Interventions in Counselling", studyMaterial: [] },
  {
    code: "MPCE-24",
    title: "Practicum in Counselling Psychology",
    studyMaterial: [],
  },
  { code: "MPCE-25", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE-26/46",
    title: "Project/ Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MPCE-31", title: "Organisational Behaviour", studyMaterial: [] },
  { code: "MPCE-32", title: "Human Resource Development", studyMaterial: [] },
  { code: "MPCE-33", title: "Organisational Development", studyMaterial: [] },
  {
    code: "MPCE-34",
    title: "Practicum in Industrial and Organisational Psychology",
    studyMaterial: [],
  },
  { code: "MPCE-35", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE-36/46",
    title: "Project/ Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MEC-101", title: "Microeconomic Analysis", studyMaterial: [] },
  { code: "MEC-2", title: "Macroeconomic Analysis", studyMaterial: [] },
  { code: "MEC-103", title: "Quantitative Methods", studyMaterial: [] },
  {
    code: "MEC-4",
    title: "Economics of Growth and Development",
    studyMaterial: [],
  },
  { code: "MEC-205", title: "Indian Economic Policy", studyMaterial: [] },
  { code: "MEC-106", title: "Public Economics", studyMaterial: [] },
  {
    code: "MEC-7",
    title: "International Trade and Finance",
    studyMaterial: [],
  },
  {
    code: "MEC-108",
    title: "Economics of Social Sector and Environment",
    studyMaterial: [],
  },
  {
    code: "MEC-109",
    title: "Research Methods in Economics",
    studyMaterial: [],
  },
  { code: "MECE-1", title: "Econometric Methods", studyMaterial: [] },
  {
    code: "MECE-3",
    title: "Actuarial Economics: Theory and Practice",
    studyMaterial: [],
  },
  {
    code: "MECE-4",
    title: "Financial Institutions and Markets",
    studyMaterial: [],
  },
  { code: "MECP-101", title: "Project Work", studyMaterial: [] },
  { code: "MWG-11", title: "Women in the Economy", studyMaterial: [] },
  {
    code: "MGSE-9",
    title: "Gender Issues in Work Employment andProductivity",
    studyMaterial: [],
  },
  {
    code: "MEDSE-46",
    title: "Development Issues and Perspectives",
    studyMaterial: [],
  },
  {
    code: "MPA-11",
    title: "State, Society and Public Administration",
    studyMaterial: [],
  },
  { code: "MPA-12", title: "Administrative Theory", studyMaterial: [] },
  { code: "MPA-13", title: "Public Systems Management", studyMaterial: [] },
  { code: "MPA-14", title: "Human Resource Management", studyMaterial: [] },
  { code: "MPA-15", title: "Public Policy and Analysis", studyMaterial: [] },
  {
    code: "MPA-16",
    title: "Decentralisation and LocalGovernance",
    studyMaterial: [],
  },
  { code: "MPA-17", title: "Electronic Governance", studyMaterial: [] },
  { code: "MPA-18", title: "Disaster Management", studyMaterial: [] },
  {
    code: "MSO-2",
    title: "Research Methodologies and Methods",
    studyMaterial: [],
  },
  {
    code: "MPS-3",
    title: "India: Democracy and Development",
    studyMaterial: [],
  },
  { code: "MPAP-2", title: "Project Work", studyMaterial: [] },
  {
    code: "MLI-101",
    title: "Information, Communication and Society",
    studyMaterial: [],
  },
  {
    code: "MLII-101",
    title: "Information Sources, Systems and Services",
    studyMaterial: [],
  },
  {
    code: "MLI-102",
    title: "Management of Library and Information Centres",
    studyMaterial: [],
  },
  {
    code: "MLII-102",
    title: "Information Processing and Retrieval",
    studyMaterial: [],
  },
  {
    code: "MLII-103",
    title: "Fundamentals of Information Communication Technologies",
    studyMaterial: [],
  },
  {
    code: "MLII-104",
    title: "Information Communication Technologies: Applications",
    studyMaterial: [],
  },
  { code: "MLIP-2", title: "Project", studyMaterial: [] },
  {
    code: "MLIE-101",
    title: "Preservation and Conservation of Library Materials",
    studyMaterial: [],
  },
  { code: "MLIE-102", title: "Research Methodology", studyMaterial: [] },
  { code: "MLIE-103", title: "Academic Library System", studyMaterial: [] },
  { code: "MLIE-104", title: "Technical Writing", studyMaterial: [] },
  {
    code: "MLIE-105",
    title: "Informatrics and Scientometrics",
    studyMaterial: [],
  },
  {
    code: "MLIE-106",
    title: "Public Library System and Services",
    studyMaterial: [],
  },
  {
    code: "MANI-1",
    title: "Anthropology and Methods of Research (Theory and Practical)",
    studyMaterial: [],
  },
  {
    code: "MANI-2",
    title: "Physical Anthropology (Theory and Practical)",
    studyMaterial: [],
  },
  { code: "MAN-1", title: "Social Anthropology (Theory)", studyMaterial: [] },
  {
    code: "MAN-2",
    title: "Archaeological Anthropology (Theory)",
    studyMaterial: [],
  },
  { code: "MANP-1", title: "Field work Dissertation", studyMaterial: [] },
  {
    code: "MANI-3",
    title: "Practicing Anthropology (Theory and Project)",
    studyMaterial: [],
  },
  {
    code: "MANE-1",
    title: "Human Genetics (Theory and Practical)",
    studyMaterial: [],
  },
  {
    code: "MANE-2",
    title: "Human Growth & Development (Theory and Practical)",
    studyMaterial: [],
  },
  {
    code: "MANE-3",
    title: "Comparative Ethnography (Theory)",
    studyMaterial: [],
  },
  { code: "MANE-4", title: "Gender and Society (Theory)", studyMaterial: [] },
  {
    code: "MANE-5",
    title: "Environmental Anthropology (Theory)",
    studyMaterial: [],
  },
  { code: "MGP-1", title: "Gandhi: The Man and His Times", studyMaterial: [] },
  { code: "MGP-2", title: "Philosophy of Gandhi", studyMaterial: [] },
  { code: "MGP-3", title: "Gandhi’s Social Thought", studyMaterial: [] },
  { code: "MGP-4", title: "Gandhi’s Political Thought", studyMaterial: [] },
  { code: "MGPE-6", title: "Gandhi’s Economic Thought", studyMaterial: [] },
  {
    code: "MGPE-7",
    title: "Non-violent Movements after Gandhi",
    studyMaterial: [],
  },
  { code: "MGPE-9", title: "Gandhi in the 21st Century", studyMaterial: [] },
  {
    code: "MGPE-14",
    title: "Gandhi, Ecology and Sustainable Development",
    studyMaterial: [],
  },
  {
    code: "MGP-5",
    title: "Introduction to Peace and Conflict Resolution",
    studyMaterial: [],
  },
  {
    code: "MGPE-8",
    title: "Gandhi Approach to Peace and Conflict Resolutions",
    studyMaterial: [],
  },
  {
    code: "MGPE-10",
    title: "Conflict Management, Transformation and Peace Building",
    studyMaterial: [],
  },
  { code: "MGPE-11", title: "Human Security", studyMaterial: [] },
  { code: "MGPE-12", title: "Women and Peace", studyMaterial: [] },
  {
    code: "MGPE-13",
    title: "Civil Society, Political Regimes and Conflict",
    studyMaterial: [],
  },
  {
    code: "MGPE-15",
    title: "Introduction to Research Methods",
    studyMaterial: [],
  },
  {
    code: "MGPE-16",
    title: "Human Rights: Indian Perspective",
    studyMaterial: [],
  },
  { code: "MGPE-17", title: "ProjectWork", studyMaterial: [] },
  {
    code: "MCS-211",
    title: "Design and Analysis of Algorithms",
    studyMaterial: [],
  },
  { code: "MCS-212", title: "Discrete Mathematics", studyMaterial: [] },
  { code: "MCS-213", title: "Software Engineering", studyMaterial: [] },
  {
    code: "MCS-214",
    title: "Professional Skills and Ethics",
    studyMaterial: [],
  },
  { code: "MCS-215", title: "Security and Cyber Laws", studyMaterial: [] },
  { code: "MCSL-216", title: "DAA and Web Design Lab", studyMaterial: [] },
  { code: "MCSL-217", title: "Software Engineering Lab", studyMaterial: [] },
  {
    code: "MCS-218",
    title: "Data Communication and Computer Networks",
    studyMaterial: [],
  },
  {
    code: "MCS-219",
    title: "Object Oriented Analysis and Design",
    studyMaterial: [],
  },
  { code: "MCS-220", title: "Web Technologies", studyMaterial: [] },
  {
    code: "MCS-221",
    title: "Data Warehousing and Data Mining",
    studyMaterial: [],
  },
  {
    code: "MCSL-222",
    title: "OOAD and Web Technologies Lab",
    studyMaterial: [],
  },
  {
    code: "MCSL-223",
    title: "Computer Network and Data Mining Lab",
    studyMaterial: [],
  },
  {
    code: "MCS-224",
    title: "Artificial Intelligence and Machine Learning",
    studyMaterial: [],
  },
  {
    code: "MCS-225",
    title: "Accountancy and Financial Management",
    studyMaterial: [],
  },
  { code: "MCS-226", title: "Data Science and Big Data", studyMaterial: [] },
  { code: "MCS-227", title: "Cloud Computing and IoT", studyMaterial: [] },
  { code: "MCSL-228", title: "AI and Machine Learning Lab", studyMaterial: [] },
  { code: "MCSL-229", title: "Cloud and Data Science Lab", studyMaterial: [] },
  {
    code: "MCS-230",
    title: "Digital Image Processing and Computer Vision",
    studyMaterial: [],
  },
  { code: "MCS-231", title: "Mobile Computing", studyMaterial: [] },
  { code: "MCSP-232", title: "Project", studyMaterial: [] },
  {
    code: "MRD-101",
    title: "Rural Development – Indian Context",
    studyMaterial: [],
  },
  { code: "MRD-102", title: "Rural Development Programmes", studyMaterial: [] },
  {
    code: "MRD-103",
    title: "Rural Development – Planning and Management",
    studyMaterial: [],
  },
  {
    code: "MRD-4",
    title: "Research Methods in Rural Development",
    studyMaterial: [],
  },
  { code: "MRDP-1", title: "Dissertation", studyMaterial: [] },
  { code: "RDD-6", title: "Rural Health Care", studyMaterial: [] },
  {
    code: "RDD-7",
    title: "Communication and Extension in Rural Development",
    studyMaterial: [],
  },
  { code: "MRDE-101", title: "Rural Social Development", studyMaterial: [] },
  {
    code: "MRDE-2",
    title: "Voluntary Action in Rural Development",
    studyMaterial: [],
  },
  {
    code: "MRDE-3",
    title: "Land Reforms and Rural Development",
    studyMaterial: [],
  },
  {
    code: "MRDE-4",
    title: "Entrepreneurship and Rural Development",
    studyMaterial: [],
  },
  { code: "MFN-1", title: "Applied Physiology", studyMaterial: [] },
  { code: "MFN-2", title: "Nutritional Biochemistry", studyMaterial: [] },
  { code: "MFNL-2", title: "Nutritional Biochemistry", studyMaterial: [] },
  {
    code: "MFN-3",
    title: "Food Safety and Food Microbiology",
    studyMaterial: [],
  },
  {
    code: "MFNL-3",
    title: "Food Safety and Food Microbiology",
    studyMaterial: [],
  },
  { code: "MFN-4", title: "Advance Nutrition", studyMaterial: [] },
  { code: "MFNL-4", title: "Advance Nutrition", studyMaterial: [] },
  {
    code: "MFN-5",
    title: "Clinical and Therapeutic Nutrition",
    studyMaterial: [],
  },
  {
    code: "MFNL-5",
    title: "Clinical and Therapeutic Nutrition",
    studyMaterial: [],
  },
  { code: "MFN-6", title: "Public Nutrition", studyMaterial: [] },
  { code: "MFNL-6", title: "Public Nutrition", studyMaterial: [] },
  {
    code: "MFN-7",
    title: "Entrepreneurship and Food Service Management",
    studyMaterial: [],
  },
  {
    code: "MFNL-7",
    title: "Entrepreneurship and Food Service Management",
    studyMaterial: [],
  },
  { code: "MFN-8", title: "Principles of Food Science", studyMaterial: [] },
  { code: "MFNL-8", title: "Principles of Food Science", studyMaterial: [] },
  {
    code: "MFN-9",
    title: "Research Methods and Biostatistics",
    studyMaterial: [],
  },
  {
    code: "MFN-10",
    title: "Understanding Computer Applications",
    studyMaterial: [],
  },
  { code: "MFNP-11", title: "Internship Programme", studyMaterial: [] },
  { code: "MFNP-12", title: "Dissertation", studyMaterial: [] },
  {
    code: "MCFT-1",
    title: "Human Development and Family Relationships",
    studyMaterial: [],
  },
  {
    code: "MCFTL-1",
    title: "Human Development and Family Relationships Supervised Practicum",
    studyMaterial: [],
  },
  { code: "MCFT-2", title: "Mental Health and Disorders", studyMaterial: [] },
  {
    code: "MCFTL-2",
    title: "Mental Health and Disorders Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT-3",
    title:
      "Counselling and Family Therapy: Basic Concepts & Theoretical Perspectives",
    studyMaterial: [],
  },
  {
    code: "MCFTL-3",
    title:
      "Counselling and Family Therapy: Basic Concepts & Theoretical Perspectives Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT-4",
    title: "Counselling and Family Therapy: Applied Aspects",
    studyMaterial: [],
  },
  {
    code: "MCFTL-4",
    title:
      "Counselling and Family Therapy: Applied Aspects Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT-5",
    title: "Counselling and Family Therapy: Research Methods and Statistics",
    studyMaterial: [],
  },
  {
    code: "MCFTL-5",
    title:
      "Counselling and Family Therapy: Research Methods and Statistics Supervised Practicum",
    studyMaterial: [],
  },
  { code: "MCFTL-8", title: "Reflective Journal", studyMaterial: [] },
  { code: "MCFT-6", title: "Applied Social Psychology", studyMaterial: [] },
  {
    code: "MCFTL-6",
    title: "Applied Social Psychology-Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFT-7",
    title: "Counselling and Family Therapy: Applications and Interventions",
    studyMaterial: [],
  },
  {
    code: "MCFTL-7",
    title:
      "Counselling and Family Therapy: Applications and Interventions Supervised Practicum",
    studyMaterial: [],
  },
  { code: "MCFTP-1", title: "Internship", studyMaterial: [] },
  { code: "MCFTP-2", title: "Dissertation", studyMaterial: [] },
  {
    code: "MCFTE-1",
    title: "Marital and Family Therapy & Counselling",
    studyMaterial: [],
  },
  {
    code: "MCFTE-4",
    title: "Marital and Family Therapy & Counselling Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFTE-2",
    title: "Child and Adolescent Counselling and Family Therapy",
    studyMaterial: [],
  },
  {
    code: "MCFTE-5",
    title:
      "Child and Adolescent Counselling and Family Therapy Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MCFTE-3",
    title: "Substance Abuse Counselling and Family Therapy",
    studyMaterial: [],
  },
  {
    code: "MCFTE-6",
    title:
      "Substance Abuse Counselling and Family Therapy Supervised Practicum",
    studyMaterial: [],
  },
  {
    code: "MSW-1",
    title: "Origin and Development of Social Work",
    studyMaterial: [],
  },
  {
    code: "MSW-2",
    title: "Professional Social Work: Indian Perspectives",
    studyMaterial: [],
  },
  {
    code: "MSW-5",
    title: "Social Work Practicum and Supervision",
    studyMaterial: [],
  },
  { code: "MSW-3", title: "Basic Social Science Concepts", studyMaterial: [] },
  {
    code: "MSW-4",
    title: "Social Work and Social Development",
    studyMaterial: [],
  },
  { code: "MSW-6", title: "Social Work Research", studyMaterial: [] },
  {
    code: "MSWE-10",
    title: "Social Work in African Context",
    studyMaterial: [],
  },
  {
    code: "MSW-32",
    title: "Social Work and Criminal Justice",
    studyMaterial: [],
  },
  { code: "MSWL-13", title: "Social Work Practicum-I", studyMaterial: [] },
  { code: "MSWL-14", title: "Block Placement", studyMaterial: [] },
  {
    code: "MSW-7",
    title: "Case work and Counselling: Working with Individuals",
    studyMaterial: [],
  },
  {
    code: "MSW-8",
    title: "Social Group Work: Working with Groups",
    studyMaterial: [],
  },
  {
    code: "MSW-9",
    title: "Community Organisation Management for Community Development",
    studyMaterial: [],
  },
  {
    code: "MSW-17",
    title: "Contemporary Methods and Values of Social Work",
    studyMaterial: [],
  },
  {
    code: "MSWE-1",
    title: "HIV/AIDS: Stigma, Discrimination and Prevention",
    studyMaterial: [],
  },
  { code: "MSWE-2", title: "Women and Child Development", studyMaterial: [] },
  { code: "MSWE-7", title: "International Social Work", studyMaterial: [] },
  { code: "MSWE-3", title: "Disaster Management", studyMaterial: [] },
  { code: "MSWP-1", title: "Dissertation (Project work)", studyMaterial: [] },
  { code: "MSWL-15", title: "Social Work Practicum-II", studyMaterial: [] },
  { code: "MSWL-16", title: "Internship", studyMaterial: [] },
  {
    code: "MSW-1",
    title: "Origin and Development of Social Work",
    studyMaterial: [],
  },
  {
    code: "MSW-2",
    title: "Professional Social Work: Indian Perspectives",
    studyMaterial: [],
  },
  {
    code: "MSW-5",
    title: "Social Work Practicum and Supervision",
    studyMaterial: [],
  },
  {
    code: "MSW-8",
    title: "Social Group Work: Working with Groups",
    studyMaterial: [],
  },
  {
    code: "MSW-9",
    title: "Community Organisation Management for Community Development",
    studyMaterial: [],
  },
  { code: "MSWL-46", title: "Social Work Practicum-I", studyMaterial: [] },
  { code: "MSWL-47", title: "Block Placement", studyMaterial: [] },
  {
    code: "MSW-12",
    title: "Introduction to Life Characteristics and Challenges",
    studyMaterial: [],
  },
  {
    code: "MSW-13",
    title: "Introduction to Psychological Basis of Counselling",
    studyMaterial: [],
  },
  {
    code: "MSW-14",
    title: "Relevance of Social Case Work in Counselling",
    studyMaterial: [],
  },
  { code: "MSW-15", title: "Basics of Counselling", studyMaterial: [] },
  { code: "MSW-16", title: "Fields of Counselling", studyMaterial: [] },
  { code: "MSWL-48", title: "Social Work Practicum-II", studyMaterial: [] },
  { code: "MSWL-49", title: "Internship", studyMaterial: [] },
  { code: "MES-11", title: "Understanding Education", studyMaterial: [] },
  {
    code: "MES-12",
    title: "Education: Nature and Purposes",
    studyMaterial: [],
  },
  {
    code: "MES-13",
    title: "Learning, Learner and Development",
    studyMaterial: [],
  },
  { code: "MES-14", title: "Societal Context of Education", studyMaterial: [] },
  {
    code: "MES-15",
    title: "Operational Dimensions of Education",
    studyMaterial: [],
  },
  { code: "MES-16", title: "Educational Research", studyMaterial: [] },
  { code: "MESP-1", title: "Dissertation", studyMaterial: [] },
  {
    code: "MES-101",
    title: "Higher Education: Its Context and Linkages",
    studyMaterial: [],
  },
  {
    code: "MES-102",
    title: "Instruction in Higher Education",
    studyMaterial: [],
  },
  {
    code: "MES-103",
    title: "Higher Education: The Psycho-social Context",
    studyMaterial: [],
  },
  {
    code: "MES-104",
    title: "Planning and Management of Higher Education",
    studyMaterial: [],
  },
  {
    code: "MES-111",
    title: "Growth and Philosophy of Distance Education",
    studyMaterial: [],
  },
  {
    code: "MES-112",
    title: "Design and Development of Self-Learning Print Materials",
    studyMaterial: [],
  },
  { code: "MES-113", title: "Learner Support Services", studyMaterial: [] },
  {
    code: "MES-114",
    title: "Management of Distance Education",
    studyMaterial: [],
  },
  {
    code: "MES-115",
    title: "Communication Technology for Distance Education",
    studyMaterial: [],
  },
  { code: "MES-31", title: "ET -An Overview", studyMaterial: [] },
  {
    code: "MES-32",
    title: "Communication and Information Technology",
    studyMaterial: [],
  },
  { code: "MES-33", title: "Computer Technology", studyMaterial: [] },
  { code: "MES-34", title: "Designing Courseware", studyMaterial: [] },
  {
    code: "MES-41",
    title: "Growth and Development of Educational Management",
    studyMaterial: [],
  },
  {
    code: "MES-42",
    title: "Dimensions of Educational Management",
    studyMaterial: [],
  },
  { code: "MES-43", title: "Organizational Behaviour", studyMaterial: [] },
  { code: "MES-44", title: "Institutional Management", studyMaterial: [] },
  { code: "MAE-1", title: "Understanding Adult Education", studyMaterial: [] },
  {
    code: "MAE-2",
    title: "Policy Planning and Implementation of Adult Education in India",
    studyMaterial: [],
  },
  {
    code: "MAE-3",
    title:
      "Knowledge Management, Information Dissemination and Networking in Adult Education",
    studyMaterial: [],
  },
  {
    code: "MAE-4",
    title: "Extension Education and Development",
    studyMaterial: [],
  },
  { code: "MES-11", title: "Understanding Education", studyMaterial: [] },
  {
    code: "MES-12",
    title: "Education: Nature and Purposes",
    studyMaterial: [],
  },
  {
    code: "MES-13",
    title: "Learning, Learner and Development",
    studyMaterial: [],
  },
  { code: "MES-14", title: "Societal Context of Education", studyMaterial: [] },
  {
    code: "MES-15",
    title: "Operational Dimensions of Education",
    studyMaterial: [],
  },
  { code: "MES-16", title: "Educational Research", studyMaterial: [] },
  {
    code: "MDE-411",
    title: "Growth and Philosophy of Distance Education",
    studyMaterial: [],
  },
  { code: "MDE-412", title: "Instructional Design", studyMaterial: [] },
  {
    code: "MDE-413",
    title: "Learner Support Systems and Services",
    studyMaterial: [],
  },
  {
    code: "MDE-414",
    title: "Management of Distance Education",
    studyMaterial: [],
  },
  {
    code: "MDE-518",
    title: "Educational Communication Technologies",
    studyMaterial: [],
  },
  {
    code: "MDE-415",
    title: "Research Methods for Distance Education",
    studyMaterial: [],
  },
  {
    code: "MDE-416",
    title: "Curriculum Development in Distance Education",
    studyMaterial: [],
  },
  {
    code: "MDE-417",
    title: "Distance Education: Economic Perspective",
    studyMaterial: [],
  },
  {
    code: "MDE-419",
    title: "Staff Training and Development in Distance Education",
    studyMaterial: [],
  },
  { code: "MDEP-520", title: "Project Work", studyMaterial: [] },
  { code: "MAE-1", title: "Understanding Adult Education", studyMaterial: [] },
  {
    code: "MAE-2",
    title: "Policy Planning and Implementation of Adult Education in India",
    studyMaterial: [],
  },
  {
    code: "MAE-3",
    title:
      "Knowledge Management, Information Dissemination and Networking in AdultEducation",
    studyMaterial: [],
  },
  { code: "MES-16", title: "Educational Research", studyMaterial: [] },
  { code: "MAEL-1", title: "Practical Work Components", studyMaterial: [] },
  {
    code: "MAE-4",
    title: "Extension Education and Development",
    studyMaterial: [],
  },
  {
    code: "MAE-5",
    title: "Population and Development Education",
    studyMaterial: [],
  },
  { code: "MAEP-1", title: "Dissertation", studyMaterial: [] },
  { code: "MAEE-1", title: "Sustainable Development", studyMaterial: [] },
  {
    code: "MESE-61",
    title: "Open and Distance LearningSystems",
    studyMaterial: [],
  },
  { code: "MAEE-2", title: "Basics of Legal Awareness", studyMaterial: [] },
  { code: "MESE-62", title: "Vocational Education", studyMaterial: [] },
  {
    code: "MTTM-1",
    title: "Management Functions and Behaviour in Tourism",
    studyMaterial: [],
  },
  {
    code: "MTTM-2",
    title: "Human Resource Planning and Development in Tourism",
    studyMaterial: [],
  },
  { code: "MTTM-3", title: "Managing Personnel in Tourism", studyMaterial: [] },
  {
    code: "MTTM-4",
    title: "Information Management Systems and Tourism",
    studyMaterial: [],
  },
  {
    code: "MTTM-5",
    title: "Accounting and Finance for Managers inTourism",
    studyMaterial: [],
  },
  {
    code: "MTTM-6",
    title: "Marketing for Tourism Managers",
    studyMaterial: [],
  },
  {
    code: "MTTM-7",
    title: "Managing Sales and Promotion in Tourism",
    studyMaterial: [],
  },
  {
    code: "MTTM-8",
    title: "Managing Entrepreneurship and Small Business in Tourism",
    studyMaterial: [],
  },
  { code: "MTTM-9", title: "Understanding Tourism Markets", studyMaterial: [] },
  { code: "MTTM-10", title: "Tourism Impacts", studyMaterial: [] },
  {
    code: "MTTM-11",
    title: "Tourism Planning and Development",
    studyMaterial: [],
  },
  { code: "MTTM-16", title: "Dissertation", studyMaterial: [] },
  {
    code: "MTTM-12",
    title: "Tourism Products: Design and Development",
    studyMaterial: [],
  },
  { code: "MTTM-13", title: "Tourism Operations", studyMaterial: [] },
  {
    code: "MTTM-14",
    title: "Tourist Transport Operations (Road Transport)",
    studyMaterial: [],
  },
  { code: "MTTM-115", title: "MICE Management", studyMaterial: [] },
  { code: "TS-1", title: "Foundation Course in Tourism", studyMaterial: [] },
  {
    code: "TS-2",
    title: "Tourism Development: Products, Operations and CaseStudies",
    studyMaterial: [],
  },
  { code: "TS-3", title: "Management in Tourism", studyMaterial: [] },
  { code: "TS-6", title: "Tourism Marketing", studyMaterial: [] },
  { code: "MPY-1", title: "Indian Philosophy", studyMaterial: [] },
  { code: "MPYE-1", title: "Logic", studyMaterial: [] },
  { code: "MPYE-2", title: "Ethics", studyMaterial: [] },
  { code: "MPYE-3", title: "Epistemology", studyMaterial: [] },
  { code: "MPYE-4", title: "Philosophy of Human Person", studyMaterial: [] },
  { code: "MPYE-5", title: "World Religions", studyMaterial: [] },
  { code: "MPYE-6", title: "Dalit Philosophy", studyMaterial: [] },
  {
    code: "MPYE-7",
    title: "Research Methodology in Philosophy",
    studyMaterial: [],
  },
  {
    code: "MGP-5",
    title: "Introduction to Peace and Conflict Resolution",
    studyMaterial: [],
  },
  { code: "MPY-2", title: "Western Philosophy", studyMaterial: [] },
  { code: "MPYE-8", title: "Metaphysics", studyMaterial: [] },
  {
    code: "MPYE-9",
    title: "Philosophy of Science and Cosmology",
    studyMaterial: [],
  },
  { code: "MPYE-10", title: "Philosophy of Religion", studyMaterial: [] },
  {
    code: "MPYE-11",
    title: "Philosophy of Art (Aesthetics)",
    studyMaterial: [],
  },
  { code: "MPYE-12", title: "Tribal Philosophy", studyMaterial: [] },
  { code: "MPYE-13", title: "Philosophy of Technology", studyMaterial: [] },
  { code: "MPYE-14", title: "Philosophy of Mind", studyMaterial: [] },
  { code: "MPYE-15", title: "Gandhian Philosophy", studyMaterial: [] },
  { code: "MPYE-16", title: "Philosophy of Sri Aurobindo", studyMaterial: [] },
  { code: "MPYP-1", title: "Dissertation", studyMaterial: [] },
  {
    code: "MEV-11",
    title: "Fundamentals of Environmental Science and Ecology",
    studyMaterial: [],
  },
  { code: "MEV-12", title: "Earth Processes", studyMaterial: [] },
  { code: "MEV-13", title: "Environmental Chemistry", studyMaterial: [] },
  {
    code: "MEVL-11",
    title: "Environmental Science Lab Course -1",
    studyMaterial: [],
  },
  {
    code: "MEV-14",
    title: "Sustainable Natural Resource Management",
    studyMaterial: [],
  },
  {
    code: "MEV-15",
    title: "Environmental Pollution, Control and Management",
    studyMaterial: [],
  },
  {
    code: "MEV-16",
    title: "Environmental Impact Assessment",
    studyMaterial: [],
  },
  {
    code: "MEVL-12",
    title: "Environmental Science Lab Course -2",
    studyMaterial: [],
  },
  { code: "MEV-17", title: "Environmental Legislations", studyMaterial: [] },
  {
    code: "MEV-18",
    title: "Environmental Health and Ecotoxicology",
    studyMaterial: [],
  },
  {
    code: "MEV-19",
    title: "Research Methodology for Environmental Science",
    studyMaterial: [],
  },
  {
    code: "MEVL-13",
    title: "Environmental Science Lab Course – 3",
    studyMaterial: [],
  },
  { code: "MEVP-11", title: "Dissertation/Project", studyMaterial: [] },
  { code: "MEVE-11", title: "Global Climate Change", studyMaterial: [] },
  { code: "MEVE-12", title: "Environmental Management", studyMaterial: [] },
  { code: "MEVE-13", title: "Environmental Biotechnology", studyMaterial: [] },
  {
    code: "MEVE-14",
    title: "Biodiversity Conservation and Management",
    studyMaterial: [],
  },
  { code: "MEVE-15", title: "Disaster Management", studyMaterial: [] },
  { code: "MEVE-16", title: "Urban Environment", studyMaterial: [] },
  { code: "MEVE-17", title: "Environment and Society", studyMaterial: [] },
  {
    code: "MEVE-18",
    title: "Instrumentation Techniques for Environmental Monitoring",
    studyMaterial: [],
  },
  { code: "MEVE-19", title: "Environmental Issues", studyMaterial: [] },
  {
    code: "MFC-001",
    title: "Folklore and Culture: Conceptual Perspectives",
    studyMaterial: [],
  },
  {
    code: "MFC-002",
    title: "Tradition, Identity and Cultural Production",
    studyMaterial: [],
  },
  {
    code: "MFC-003",
    title: "Cultural and Societal Transformation",
    studyMaterial: [],
  },
  {
    code: "MFC-004",
    title: "Tribes of India: Identity, Culture and Lore",
    studyMaterial: [],
  },
  { code: "MFCP-005", title: "Project Manual", studyMaterial: [] },
  {
    code: "MFC-006",
    title:
      "Folklore: Canon, Multimediality, Interdisciplinarity and Social Epistemology",
    studyMaterial: [],
  },
  {
    code: "MFC-007",
    title: "Theories and Pedagogy of Folklore",
    studyMaterial: [],
  },
  { code: "MFC-008", title: "Folk Representations", studyMaterial: [] },
  { code: "MFC-009", title: "Approaches to Folklore", studyMaterial: [] },
  {
    code: "MDV-101",
    title: "Introduction to Development and Development Theories",
    studyMaterial: [],
  },
  { code: "MDV-102", title: "Dynamics of Development", studyMaterial: [] },
  {
    code: "MDV-103",
    title: "Issues and Challenges of Development",
    studyMaterial: [],
  },
  { code: "MDV-4", title: "Gender and Development", studyMaterial: [] },
  {
    code: "MDV-106",
    title: "Research Methodology in Development Studies",
    studyMaterial: [],
  },
  {
    code: "MDV-109",
    title: "Development in India - An Overview",
    studyMaterial: [],
  },
  {
    code: "MDV-105",
    title: "Development Planning and Management",
    studyMaterial: [],
  },
  {
    code: "MDV-108",
    title: "Development Communication and Extension",
    studyMaterial: [],
  },
  { code: "MDV-110", title: "Training and Development", studyMaterial: [] },
  {
    code: "MDV-111",
    title: "Local Self Governance and Development",
    studyMaterial: [],
  },
  { code: "MDV-115", title: "Health and Development", studyMaterial: [] },
  {
    code: "MEDS-41",
    title: "Introduction to Urban Development",
    studyMaterial: [],
  },
  {
    code: "MEDS-42",
    title: "Issues and Challenges in Urban Planning and Development",
    studyMaterial: [],
  },
  { code: "MDVP-117", title: "ProjectWork", studyMaterial: [] },
  {
    code: "MWG-1",
    title: "Theories of Women’s and Gender Studies",
    studyMaterial: [],
  },
  { code: "MWG-2", title: "Gender and Power", studyMaterial: [] },
  {
    code: "MWG-3",
    title: "Constructing Gender through Arts & Media",
    studyMaterial: [],
  },
  { code: "MWG-4", title: "Gendered Bodies & Sexualities", studyMaterial: [] },
  { code: "MWGP-1", title: "ProjectWork", studyMaterial: [] },
  {
    code: "MWG-5",
    title: "Research Methods (Common course for both specializations)",
    studyMaterial: [],
  },
  { code: "MWG-6", title: "Gendered Nation", studyMaterial: [] },
  { code: "MWG-7", title: "Postmodernism & Gender", studyMaterial: [] },
  { code: "MWG-8", title: "Gender & Life Narratives", studyMaterial: [] },
  {
    code: "MWG-5",
    title: "Research Methods (Common course for both specializations)",
    studyMaterial: [],
  },
  { code: "MWG-9", title: "Women & Social Structure", studyMaterial: [] },
  { code: "MWG-10", title: "Women & Political Process", studyMaterial: [] },
  { code: "MWG-11", title: "Women in Economy", studyMaterial: [] },
  {
    code: "MGS-1",
    title: "Gender and Development: Concepts, Approaches and Strategies",
    studyMaterial: [],
  },
  {
    code: "MGS-2",
    title: "Gender, Development Goals and Praxis",
    studyMaterial: [],
  },
  { code: "MGS-3", title: "Gender Analysis", studyMaterial: [] },
  {
    code: "MGS-4",
    title: "Gender-Sensitive Planning and Policy Making",
    studyMaterial: [],
  },
  {
    code: "MGS-5",
    title: "Research Methodologies in Gender and Development Studies",
    studyMaterial: [],
  },
  {
    code: "MGSP-1",
    title: "Internship-I / Field based Research Project-I",
    studyMaterial: [],
  },
  {
    code: "MGSP-2",
    title: "Internship-II / Field based Research Project-II",
    studyMaterial: [],
  },
  {
    code: "MGSE-1",
    title: "Gender Planning and Development Policies",
    studyMaterial: [],
  },
  {
    code: "MGSE-2",
    title: "Gender Audit and Gender Budgeting",
    studyMaterial: [],
  },
  { code: "MGSE-3", title: "Gender Mainstreaming", studyMaterial: [] },
  {
    code: "MGSE-4",
    title:
      "Gender Issues in Agriculture, Rural Livelihoods and Natural Resource Management",
    studyMaterial: [],
  },
  {
    code: "MGSE-6",
    title: "Gender, Resources and Entitlements",
    studyMaterial: [],
  },
  {
    code: "MGSE-7",
    title: "Gender, Organization and Leadership",
    studyMaterial: [],
  },
  {
    code: "MGSE-9",
    title: "Gender Issues in Work, Employment and Productivity",
    studyMaterial: [],
  },
  {
    code: "MGSE-10",
    title: "Gender and Entrepreneurship Development",
    studyMaterial: [],
  },
  {
    code: "MGSE-13",
    title: "Gender Training and Empowerment",
    studyMaterial: [],
  },
  {
    code: "MGSE-20",
    title: "Gender and Financial Inclusion",
    studyMaterial: [],
  },
  { code: "MTT-10", title: "Anuvad Sidhhant", studyMaterial: [] },
  { code: "MTT-11", title: "Anuvad: Itihas aur Parampara", studyMaterial: [] },
  { code: "MTT-12", title: "Anuvad aur Bhashavigyan", studyMaterial: [] },
  { code: "MTT-13", title: "Anuvad ke Kshetra", studyMaterial: [] },
  {
    code: "MTT-14",
    title: "Anuvad Evam Bhartiya Bhashayen",
    studyMaterial: [],
  },
  { code: "MTT-15", title: "Anuvad aur Sahitya", studyMaterial: [] },
  { code: "MTT-16", title: "Anuvad aur Jansanchar", studyMaterial: [] },
  {
    code: "MTT-17",
    title: "Koshvigyan, Paribhashik Shabdavali aur Anuvad",
    studyMaterial: [],
  },
  {
    code: "MTT-18",
    title: "Anuvad Evam Antarsanskritik Adhyayan",
    studyMaterial: [],
  },
  { code: "MTT-19", title: "Anuvad ki Rajniti", studyMaterial: [] },
  { code: "MTT-20", title: "Anuvad Prakriya", studyMaterial: [] },
  { code: "MTT-21", title: "Anuvad Prashikshan", studyMaterial: [] },
  {
    code: "MTTP-22",
    title: "Pariyojana (Pariyojana Karya aur Maukhiki)",
    studyMaterial: [],
  },
  { code: "MMT-1", title: "Programming & Data Structures", studyMaterial: [] },
  { code: "MMT-2", title: "Linear Algebra", studyMaterial: [] },
  { code: "MMT-4", title: "Real Analysis", studyMaterial: [] },
  { code: "MMT-5", title: "Complex Analysis", studyMaterial: [] },
  {
    code: "MMT-7",
    title: "Differential Equations and Numerical Solutions",
    studyMaterial: [],
  },
  { code: "MMT-3", title: "Algebra", studyMaterial: [] },
  { code: "MMT-6", title: "Functional Analysis", studyMaterial: [] },
  { code: "MMT-8", title: "Probability and Statistics", studyMaterial: [] },
  { code: "MMT-9", title: "Mathematical Modelling", studyMaterial: [] },
  { code: "MMTE-1", title: "Graph Theory", studyMaterial: [] },
  {
    code: "MMTE-2",
    title: "Design & Analysis of Algorithms",
    studyMaterial: [],
  },
  {
    code: "MMTE-3",
    title: "Pattern Recognition & Image Processing",
    studyMaterial: [],
  },
  { code: "MMTE-4", title: "Computer Graphics", studyMaterial: [] },
  { code: "MMTE-5", title: "Coding Theory", studyMaterial: [] },
  { code: "MMTE-6", title: "Cryptography", studyMaterial: [] },
  { code: "MMTE-7", title: "Soft Computing & Applications", studyMaterial: [] },
  { code: "MMTP-1", title: "Project (Compulsory)", studyMaterial: [] },
  {
    code: "MJM-20",
    title: "Introduction to Journalism and Mass Communication",
    studyMaterial: [],
  },
  { code: "MJM-21", title: "Reporting Techniques", studyMaterial: [] },
  {
    code: "MJM-22",
    title: "Writing and Editing for Print Media",
    studyMaterial: [],
  },
  {
    code: "MJM-23",
    title: "Broadcast and Online Journalism",
    studyMaterial: [],
  },
  { code: "MJM-24", title: "Media and Society", studyMaterial: [] },
  { code: "MJM-25", title: "Media Ethics and Laws", studyMaterial: [] },
  { code: "MJML-20", title: "Practical: Print and Online", studyMaterial: [] },
  { code: "MJML-21", title: "Practical: Audiovisual", studyMaterial: [] },
  { code: "MJM-26", title: "Print Media", studyMaterial: [] },
  { code: "MJM-27", title: "Electronic Media", studyMaterial: [] },
  { code: "MJM-28", title: "Digital Media", studyMaterial: [] },
  {
    code: "MJM-29",
    title: "Advertising and Public Relations",
    studyMaterial: [],
  },
  {
    code: "MJM-30",
    title: "Communication and Media Studies",
    studyMaterial: [],
  },
  {
    code: "MJM-31",
    title: "Communication Research Methods",
    studyMaterial: [],
  },
  {
    code: "MJML-22",
    title: "Practical (Research Methodology)",
    studyMaterial: [],
  },
  { code: "MJMP-20", title: "Major Project Work", studyMaterial: [] },
  { code: "MVA-020", title: "Modern Art of India", studyMaterial: [] },
  {
    code: "MVAL-021",
    title: "Understanding Elements of Art",
    studyMaterial: [],
  },
  {
    code: "MVAL-022",
    title: "Study of Principle of Composition",
    studyMaterial: [],
  },
  { code: "MVA-023", title: "Modern Western Art", studyMaterial: [] },
  { code: "MVAL-024", title: "Study of Nature", studyMaterial: [] },
  {
    code: "MVAL-025",
    title: "Study of Folk, Tribal and Traditional Art Styles",
    studyMaterial: [],
  },
  {
    code: "MVA-026",
    title: "Understanding Aesthetics and Art Education",
    studyMaterial: [],
  },
  { code: "MVAL-027", title: "Creative Portraiture", studyMaterial: [] },
  { code: "MVAL-028", title: "Creative Composition", studyMaterial: [] },
  {
    code: "MVA-029",
    title: "Research Methods and Dissertation",
    studyMaterial: [],
  },
  { code: "MVAL-030", title: "Creative Landscape", studyMaterial: [] },
  { code: "MVAL-031", title: "Creative Expression", studyMaterial: [] },
  {
    code: "MSEI-021",
    title: "Introduction to Information Security",
    studyMaterial: [],
  },
  { code: "MSEI-022", title: "Network Security", studyMaterial: [] },
  { code: "MSEI-023", title: "Cyber Security", studyMaterial: [] },
  { code: "MSE-024", title: "Policy, Standards and Laws", studyMaterial: [] },
  {
    code: "MSEI-025",
    title: "Application and Business Security Developments",
    studyMaterial: [],
  },
  { code: "MSEI-026", title: "BCP, DR Planning and Audit", studyMaterial: [] },
  { code: "MSEI-027", title: "Digital Forensics", studyMaterial: [] },
  { code: "MSEP-028", title: "Project-1", studyMaterial: [] },
  {
    code: "MSE-029",
    title: "Cyber Attack: use of Technology in Cyberspace",
    studyMaterial: [],
  },
  {
    code: "MSE-030",
    title: "Cloud and Infrastructure Security",
    studyMaterial: [],
  },
  { code: "MSE-031", title: "Cyber Security using Python", studyMaterial: [] },
  { code: "MCS-226", title: "Data Science and Big Data", studyMaterial: [] },
  {
    code: "MSEL-032",
    title: "Practical (Cyber Attacks, Cloud Security and Data Recovery etc.)",
    studyMaterial: [],
  },
  {
    code: "MSE-033",
    title: "Web Application Testing and Audit",
    studyMaterial: [],
  },
  { code: "MSE-034", title: "E-commerce and Cyberspace", studyMaterial: [] },
  { code: "MSE-035", title: "IoT Security", studyMaterial: [] },
  {
    code: "MSE-036",
    title: "Latest Trends in Information and Cyber Security",
    studyMaterial: [],
  },
  {
    code: "MSEL-037",
    title: "Practical (Web Application, Audits, e-commerce security and IoT)",
    studyMaterial: [],
  },
  { code: "MSEP-038", title: "Project-II", studyMaterial: [] },
  { code: "MER-001", title: "Business Environment", studyMaterial: [] },
  {
    code: "MER-002",
    title: "Fundamentals of Entrepreneurship",
    studyMaterial: [],
  },
  {
    code: "MER-003",
    title: "Business Ideation and OpportunityIdentification",
    studyMaterial: [],
  },
  {
    code: "MER-004",
    title: "Business Development and Entrepreneurial Competencies",
    studyMaterial: [],
  },
  {
    code: "MER-005",
    title: "IPR & Technology Commercialization",
    studyMaterial: [],
  },
  {
    code: "MER-006",
    title: "Management of New and Small Enterprises",
    studyMaterial: [],
  },
  {
    code: "MER-007",
    title: "Government Initiatives & MSME Development",
    studyMaterial: [],
  },
  { code: "MER-008", title: "Finance & Accounting", studyMaterial: [] },
  { code: "MERP-001", title: "Project I", studyMaterial: [] },
  { code: "MER-009", title: "Marketing Management", studyMaterial: [] },
  {
    code: "MER-010",
    title: "Organizational Management and Labour Relations",
    studyMaterial: [],
  },
  {
    code: "MER-011",
    title: "Start Up, Incubation and Business Ethics",
    studyMaterial: [],
  },
  {
    code: "MER-012",
    title: "Business Research Methods & Applications",
    studyMaterial: [],
  },
  { code: "MER-013", title: "IT and Entrepreneurship", studyMaterial: [] },
  {
    code: "MER-014",
    title: "Innovation and Strategic Management",
    studyMaterial: [],
  },
  { code: "MER-015", title: "Social Entrepreneurship", studyMaterial: [] },
  { code: "MERP-002", title: "Project II", studyMaterial: [] },
];
