export const mastersDegreeCourse = [
  {
    code: "IBO 1",
    title: "International Business Environment",
    studyMaterial: [],
  },
  {
    code: "IBO 2",
    title: "International Marketing Management",
    studyMaterial: [],
  },
  { code: "IBO 3", title: "India’s Foreign Trade", studyMaterial: [] },
  {
    code: "IBO 4",
    title: "Export Import Procedures and Documentation",
    studyMaterial: [],
  },
  {
    code: "IBO 5",
    title: "International Marketing Logistics",
    studyMaterial: [],
  },
  { code: "IBO 6", title: "International Business Finance", studyMaterial: [] },
  {
    code: "MCO 1",
    title: "Organization Theory and Behaviour",
    studyMaterial: [],
  },
  {
    code: "MCO 3",
    title: "Research Methodology and Statistical Analysis",
    studyMaterial: [],
  },
  { code: "MCO 4", title: "Business Environment", studyMaterial: [] },
  {
    code: "MCO 5",
    title: "Accounting for Managerial Decisions",
    studyMaterial: [],
  },
  { code: "MCO 6", title: "Marketing Management", studyMaterial: [] },
  { code: "MCO 7", title: "Financial Management", studyMaterial: [] },
  { code: "MEG 1", title: "British Poetry", studyMaterial: [] },
  { code: "MEG 2", title: "British Drama", studyMaterial: [] },
  { code: "MEG 3", title: "British Novel", studyMaterial: [] },
  { code: "MEG 4", title: "Aspects of Language", studyMaterial: [] },
  { code: "MEG 5", title: "Literary Criticism and Theory", studyMaterial: [] },
  { code: "MEG 6", title: "American Literature", studyMaterial: [] },
  { code: "MEG 7", title: "Indian English Literature", studyMaterial: [] },
  { code: "MEG 8", title: "New Literatures in English", studyMaterial: [] },
  { code: "MEG 9", title: "Australian Literature", studyMaterial: [] },
  { code: "MEG 10", title: "English Studies in India", studyMaterial: [] },
  { code: "MEG 11", title: "American Novel", studyMaterial: [] },
  {
    code: "MEG 12",
    title: "A Survey Course in 20th Century Canadian Literature",
    studyMaterial: [],
  },
  { code: "MEG 13", title: "Writing from the Margins", studyMaterial: [] },
  {
    code: "MEG 14",
    title: "Contemporary Indian Literature in English Translation",
    studyMaterial: [],
  },
  {
    code: "MEG 15",
    title: "Comparative Literature: Theory and Practice",
    studyMaterial: [],
  },
  { code: "MEG 16", title: "Indian Folk Literature", studyMaterial: [] },
  { code: "MPS 1", title: "Political Theory", studyMaterial: [] },
  {
    code: "MPS 2",
    title: "International Relations: Theory and Problems",
    studyMaterial: [],
  },
  {
    code: "MPS 3",
    title: "India: Democracy and Development",
    studyMaterial: [],
  },
  {
    code: "MPS 4",
    title: "Comparative Politics: Issues and Trends",
    studyMaterial: [],
  },
  { code: "MPSE 1", title: "India and the World", studyMaterial: [] },
  {
    code: "MPSE 2",
    title: "State and Society in Latin America",
    studyMaterial: [],
  },
  { code: "MPSE 3", title: "Western Political Thought", studyMaterial: [] },
  {
    code: "MPSE 4",
    title: "Social and Political Thought in Modern India",
    studyMaterial: [],
  },
  { code: "MPSE 5", title: "State and Society in Africa", studyMaterial: [] },
  { code: "MPSE 6", title: "Peace and Conflict Studies", studyMaterial: [] },
  {
    code: "MPSE 7",
    title: "Social Movements and Politics in India",
    studyMaterial: [],
  },
  { code: "MPSE 8", title: "State Politics in India", studyMaterial: [] },
  { code: "MPSE 9", title: "Canada: Politics and Society", studyMaterial: [] },
  {
    code: "MPSE 11",
    title: "The European Union in World Affairs",
    studyMaterial: [],
  },
  {
    code: "MPSE 12",
    title: "State and Society in Australia",
    studyMaterial: [],
  },
  { code: "MPSE 13", title: "Australia’s Foreign Policy", studyMaterial: [] },
  {
    code: "MED 2",
    title: "Sustainable Development: Issues and Challenges",
    studyMaterial: [],
  },
  { code: "MED 8", title: "Globalisation and Environment", studyMaterial: [] },
  { code: "MGP 4", title: "Gandhi’s Political Thought", studyMaterial: [] },
  {
    code: "MGPE 7",
    title: "Non-Violent Movements after Gandhi",
    studyMaterial: [],
  },
  {
    code: "MGPE 8",
    title: "Gandhian Approach to Peace and Conflict Resolution",
    studyMaterial: [],
  },
  {
    code: "MGPE 10",
    title: "Conflict Management, Transformation & Peace Building",
    studyMaterial: [],
  },
  { code: "MGPE 11", title: "Human Security", studyMaterial: [] },
  {
    code: "MGPE 13",
    title: "Civil Society, Political Regimes and Conflict",
    studyMaterial: [],
  },
  { code: "MHI 1", title: "Ancient and Medieval Societies", studyMaterial: [] },
  { code: "MHI 2", title: "Modern World", studyMaterial: [] },
  { code: "MHI 4", title: "Political Structures in India", studyMaterial: [] },
  { code: "MHI 5", title: "History of Indian Economy", studyMaterial: [] },
  { code: "MHI 3", title: "Historiography", studyMaterial: [] },
  { code: "MPSE 3", title: "Western Political Thought", studyMaterial: [] },
  {
    code: "MPSE 4",
    title: "Social and Political Thought in Modern India",
    studyMaterial: [],
  },
  {
    code: "MHI 6",
    title: "Evolution of Social Structures in India through the Ages",
    studyMaterial: [],
  },
  {
    code: "MHI 8",
    title: "History of Ecology and Environment: India",
    studyMaterial: [],
  },
  { code: "MHI 9", title: "Indian National Movement", studyMaterial: [] },
  { code: "MHI 10", title: "Urbanization in India", studyMaterial: [] },
  {
    code: "MSO 1",
    title: "Sociological Theories and Concepts",
    studyMaterial: [],
  },
  {
    code: "MSO 2",
    title: "Research Methods and Methodologies",
    studyMaterial: [],
  },
  { code: "MSO 3", title: "Sociology of Development", studyMaterial: [] },
  { code: "MSO 4", title: "Sociology in India", studyMaterial: [] },
  { code: "MSOE 1", title: "Sociology of Education", studyMaterial: [] },
  {
    code: "MSOE 2",
    title: "Diaspora and Transnational Communities",
    studyMaterial: [],
  },
  { code: "MSOE 3", title: "Sociology of Religion", studyMaterial: [] },
  { code: "MSOE 4", title: "Urban Sociology", studyMaterial: [] },
  {
    code: "MPA 16",
    title: "Decentralization and LocalGovernance",
    studyMaterial: [],
  },
  {
    code: "MPS 3",
    title: "India: Democracy andDevelopment",
    studyMaterial: [],
  },
  {
    code: "MPC 1",
    title: "Cognitive Psychology, Learning and Memory",
    studyMaterial: [],
  },
  { code: "MPC 2", title: "Life Span Psychology", studyMaterial: [] },
  {
    code: "MPC 3",
    title: "Personality: Theories and Assessment",
    studyMaterial: [],
  },
  { code: "MPC 4", title: "Advanced Social Psychology", studyMaterial: [] },
  { code: "MPC 5", title: "Research Methods in Psychology", studyMaterial: [] },
  { code: "MPC 6", title: "Statistics in Psychology", studyMaterial: [] },
  {
    code: "MPCL 7",
    title: "Practicum in Experimental Psychology & Psychological Testing",
    studyMaterial: [],
  },
  { code: "MPCE 11", title: "Psychopathology", studyMaterial: [] },
  { code: "MPCE 12", title: "Psychodiagnostics", studyMaterial: [] },
  { code: "MPCE 13", title: "Psychotherapeutic methods", studyMaterial: [] },
  {
    code: "MPCE 14",
    title: "Practicum in Clinical Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 15", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE 16/46",
    title: "Project/Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 21", title: "Counselling Psychology", studyMaterial: [] },
  {
    code: "MPCE 22",
    title: "Assessment in Counselling and Guidance",
    studyMaterial: [],
  },
  { code: "MPCE 23", title: "Interventions in Counselling", studyMaterial: [] },
  {
    code: "MPCE 24",
    title: "Practicum in Counselling Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 25", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE 26/46",
    title: "Project/ Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 31", title: "Organisational Behaviour", studyMaterial: [] },
  { code: "MPCE 32", title: "Human Resource Development", studyMaterial: [] },
  { code: "MPCE 33", title: "Organisational Development", studyMaterial: [] },
  {
    code: "MPCE 34",
    title: "Practicum in Industrial and Organisational Psychology",
    studyMaterial: [],
  },
  { code: "MPCE 35", title: "Internship", studyMaterial: [] },
  {
    code: "MPCE 36/46",
    title: "Project/ Applied Positive Psychology",
    studyMaterial: [],
  },
  { code: "MEC 101", title: "Microeconomic Analysis", studyMaterial: [] },
  { code: "MEC 2", title: "Macroeconomic Analysis", studyMaterial: [] },
  { code: "MEC 103", title: "Quantitative Methods", studyMaterial: [] },
  {
    code: "MEC 4",
    title: "Economics of Growth and Development",
    studyMaterial: [],
  },
  { code: "MEC 205", title: "Indian Economic Policy", studyMaterial: [] },
  { code: "MEC 106", title: "Public Economics", studyMaterial: [] },
  {
    code: "MEC 7",
    title: "International Trade and Finance",
    studyMaterial: [],
  },
  {
    code: "MEC 108",
    title: "Economics of Social Sector and Environment",
    studyMaterial: [],
  },
  {
    code: "MEC 109",
    title: "Research Methods in Economics",
    studyMaterial: [],
  },
  { code: "MECE 1", title: "Econometric Methods", studyMaterial: [] },
  {
    code: "MECE 3",
    title: "Actuarial Economics: Theory and Practice",
    studyMaterial: [],
  },
  {
    code: "MECE 4",
    title: "Financial Institutions and Markets",
    studyMaterial: [],
  },
  { code: "MECP 101", title: "Project Work", studyMaterial: [] },
  { code: "MWG 11", title: "Women in the Economy", studyMaterial: [] },
  {
    code: "MGSE 9",
    title: "Gender Issues in Work Employment andProductivity",
    studyMaterial: [],
  },
  {
    code: "MEDSE 46",
    title: "Development Issues and Perspectives",
    studyMaterial: [],
  },
  {
    code: "MPA 11",
    title: "State, Society and Public Administration",
    studyMaterial: [],
  },
  { code: "MPA 12", title: "Administrative Theory", studyMaterial: [] },
  { code: "MPA 13", title: "Public Systems Management", studyMaterial: [] },
  { code: "MPA 14", title: "Human Resource Management", studyMaterial: [] },
  { code: "MPA 15", title: "Public Policy and Analysis", studyMaterial: [] },
  {
    code: "MPA 16",
    title: "Decentralisation and LocalGovernance",
    studyMaterial: [],
  },
  { code: "MPA 17", title: "Electronic Governance", studyMaterial: [] },
  { code: "MPA 18", title: "Disaster Management", studyMaterial: [] },
  {
    code: "MSO 2",
    title: "Research Methodologies and Methods",
    studyMaterial: [],
  },
  {
    code: "MPS 3",
    title: "India: Democracy and Development",
    studyMaterial: [],
  },
  { code: "MPAP 2", title: "Project Work", studyMaterial: [] },
  {
    code: "MLI 101",
    title: "Information, Communication and Society",
    studyMaterial: [],
  },
  {
    code: "MLII 101",
    title: "Information Sources, Systems and Services",
    studyMaterial: [],
  },
  {
    code: "MLI 102",
    title: "Management of Library and Information Centres",
    studyMaterial: [],
  },
  {
    code: "MLII 102",
    title: "Information Processing and Retrieval",
    studyMaterial: [],
  },
  {
    code: "MLII 103",
    title: "Fundamentals of Information Communication Technologies",
    studyMaterial: [],
  },
  {
    code: "MLII 104",
    title: "Information Communication Technologies: Applications",
    studyMaterial: [],
  },
  { code: "MLIP 2", title: "Project", studyMaterial: [] },
  {
    code: "MLIE 101",
    title: "Preservation and Conservation of Library Materials",
    studyMaterial: [],
  },
  { code: "MLIE 102", title: "Research Methodology", studyMaterial: [] },
  { code: "MLIE 103", title: "Academic Library System", studyMaterial: [] },
  { code: "MLIE 104", title: "Technical Writing", studyMaterial: [] },
  {
    code: "MLIE 105",
    title: "Informatrics and Scientometrics",
    studyMaterial: [],
  },
  {
    code: "MLIE 106",
    title: "Public Library System and Services",
    studyMaterial: [],
  },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
  { code: "", title: "", studyMaterial: [] },
];
