import { Degree, TermType, Category } from "../../constants/types";

export const awarenessAndAppreciationProgrammes = [
  {
    code: "APDF",
    title: "Awareness Programme on Dairy Farming",
    name: "APDF",
    fullName: "Awareness Programme on Dairy Farming",
    degree: Degree.awarenessAndAppreciation,
    termType: TermType.Quarter,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "Module-1", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-2", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-3", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-4", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-5", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-6", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-7", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-8", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-9", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-10", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-11", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-12", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-13", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-14", category: Category.NONE, credit: 0 },
    ],
  },
  {
    code: "ACPSD",
    title: "Appreciation Course on Population and Sustainable Development",
    name: "ACPSD",
    fullName: "Appreciation Course on Population and Sustainable Development",
    degree: Degree.awarenessAndAppreciation,
    termType: TermType.Quarter,
    termsCount: 1,
    collegeCode: "IGNOU",
  },
];
