import { Category, Degree, TermType } from "../../constants/types";

export const awarenessAndAppreciationProgrammes = [
  {
    code: "APDF",
    title: "Awareness Programme on Dairy Farming",
    degree: Degree.awarenessAndAppreciation,
    termType: TermType.Quarter,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "No formal education, Able to Read and Write Hindi/Telugu",
    mediumOfInstruction: "Hindi and Telugu",
    duration: "Minimum two months and Maximum six months; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1100/- for full programme",
    schoolCode: "SOA",
    totalCredits: 0,
    programmeStructure: [
      { term: 1, courseCode: "Module-1", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-2", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-3", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-4", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-5", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-6", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-7", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-8", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-9", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-10", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-11", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-12", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-13", category: Category.NONE, credit: 0 },
      { term: 1, courseCode: "Module-14", category: Category.NONE, credit: 0 },
    ],
  },
  {
    code: "ACE",
    title: "Appreciation Course on Environment",
    degree: Degree.awarenessAndAppreciation,
    termType: TermType.Quarter,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation from a recognized University or equivalent qualification",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 3 months and Maximum 1 Year; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,100/- for full programme",
    schoolCode: "SOS",
    totalCredits: 0,
  },
  {
    code: "ACPSD",
    title: "Appreciation Course on Population and Sustainable Development",
    degree: Degree.awarenessAndAppreciation,
    termType: TermType.Quarter,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s Degree or equivalent from any recognized University",
    mediumOfInstruction: "English",
    duration: "Minimum 3 months and Maximum 1 year; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 900/- for full programme",
    schoolCode: "SOITS",
    totalCredits: 132,
  },
];
