import { Category, Degree, TermType } from "../../constants/types";

export const bachelorsHonoursDegreeProgrammes = [
  {
    code: "BAECH",
    title: "Bachelor of Arts (Honours) Economics",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 11,400/- for full programme to be paid year wise @ Rs. 3,800/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/-is Rs.4,000/",
    schoolCode: "SOSS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BECC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BECC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPAG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BECC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BECC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BPAG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BECC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BECC-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BECC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPCG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BSOG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BEGG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BECC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BECC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BECC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BHDC-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BEGG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BECC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BECC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BECE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BECE-143", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BECC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BECC-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BECE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BECE-144", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BAHIH",
    title: "Bachelor of Arts (Honours) History",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 11,400/- for full programme to be paid year wise @ Rs. 3,800/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/-is Rs.4,000/",
    schoolCode: "SOSS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BHIC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BHIC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPAG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BHIC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BHIC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BHIC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BHIC-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BHIC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BSOG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPCG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BEGG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BHIC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BHIC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BHIC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BEGG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BHIC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BHIC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BHIE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BHIE-143", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BHIC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BHIC-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BHIE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BHIE-144", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BAPSH",
    title: "Bachelor of Arts (Honours) Political Science",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 11,400/- for full programme to be paid year wise @ Rs. 3,800/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/-is Rs.4,000/",
    schoolCode: "SOSS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BPSC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPSC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPAG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BPSC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPSC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPAG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BPSC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPAC-101", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPSC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BSOG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPCG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BEGG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BPSC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPAC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPSC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BEGG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BPSC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BPSC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BPSE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPSE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPSE-145", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BPSC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BPSC-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BPSE-142", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPSE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPSE-146", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BAPCH",
    title: "Bachelor of Arts (Honours) Psychology",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 11,400/- for full programme to be paid year wise @ Rs. 3,800/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/-is Rs.4,000/",
    schoolCode: "SOSS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BPCC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPCC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPAG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BPCC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPCC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPAG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BPCC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPCC-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPCC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BSOG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BEGG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BPCC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPCC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPCC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BEGG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BPCC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BPCC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BPCE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPCE-143", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BPCC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BPCC-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BPCE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPCE-144", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BAPAH",
    title: "Bachelor of Arts (Honours) Public Administration",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 11,400/- for full programme to be paid year wise @ Rs. 3,800/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/-is Rs.4,000/",
    schoolCode: "SOSS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BPAC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPAC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BPAC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPAC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BPAC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPAC-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPAC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BEGG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BPAC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPAC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPAC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BEGG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BPAC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BPAC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BPAE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPAE-143", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BPAC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BPAC-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BPAE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPAE-144", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BASOH",
    title: "Bachelor of Arts (Honours) Sociology",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 11,400/- for full programme to be paid year wise @ Rs. 3,800/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/-is Rs.4,000/",
    schoolCode: "SOSS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BSOC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BSOC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPAG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BSOC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BSOC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPAG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BSOC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BSOC-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BSOC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BEGG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BSOC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BEGG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BSOC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BSOC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BSOE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BSOE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BANE-143", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BSOC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BSOC-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BSOE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BSOE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BANE-144", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BSCANH",
    title: "Bachelor of Science (Honours) Anthropology",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure: "Rs. 18,000/- for full programme to be paid year wise @ Rs. 6,000/- per year.",
    schoolCode: "SOSS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BANC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BANC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPAG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BANC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BANC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPAG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BANC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANC-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BSOG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPCG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BEGG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BANC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BANC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BANC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BEGG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BANC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BANC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BANE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BANE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BANE-147", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BANC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BANC-114", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BANE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BANE-154", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BSOE-144", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BSCBCH",
    title: "Bachelor of Science (Honours) in Biochemistry",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10 + 2 pass with science subjects, namely, Biology, Chemistry and Physics",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 43,500/- for full programme to be paid year wise @ Rs. 14,500/- per year. Fee to be paidin 1st year, including Registration Fee of Rs.200/-is Rs.14,700/",
    schoolCode: "SOS",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BBCCT-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BBCCL-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BBCCT-103", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BBCCL-104", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BCHCT-131", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BCHCL-132", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BBCCT-105", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BBCCL-106", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BBCCT-107", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BBCCL-108", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BCHCT-147", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BCHCL-148", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BBCCT-109", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BBCCL-110", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BBCCT-111", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BBCCL-112", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BBCCT-113", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BBCCL-114", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BBCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BBYCT-131", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BBYCL-132", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BBCCT-115", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BBCCL-116", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BBCCT-117", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BBCCL-118", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BBCCT-119", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BBCCL-120", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BBCS-185", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BZYCT-131", category: Category.GE, credit: 6 },
      { term: 4, courseCode: "BZYCL-132", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BBCCT-121", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BBCCL-122", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BBCCT-123", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BBCCL-124", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BBCET-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BBCEL-142", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BBCET-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BBCEL-146", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BBCCT-125", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BBCCL-126", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BBCCT-127", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BBCCL-128", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BBCET-143", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BBCEL-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BBCET-151", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BBCEL-152", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BAEGH",
    title: "Bachelor of Arts English (Honours)",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "A total of Rs. 11 , 4 00/- is to be paid year-wise for the full programme, @ Rs.3, 8 00/year. Fee to be paid in the first year including a registration fee of 200/- is Rs. 4 , 0 00/-.",
    schoolCode: "SOH",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BEGC-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEGC-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPYG-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BPAC-171", category: Category.GE, credit: 6 },
      { term: 1, courseCode: "BABG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BEGC-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGC-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPAG-172", category: Category.GE, credit: 6 },
      { term: 2, courseCode: "BPYG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BEGC-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BEGC-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BEGC-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BSOG-173", category: Category.GE, credit: 6 },
      { term: 3, courseCode: "BHDG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BEGC-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BEGC-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BEGC-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BEGC-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BEGC-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BEGE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BEGE-143", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BEGC-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BEGC-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BEGE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BEGE-144", category: Category.DSE, credit: 6 },
    ],
  },
  {
    code: "BAPFHMH",
    title: "Bachelor of Performing Arts – Hindustani Music (Honours)",
    degree: Degree.bachelorsHonours,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction:
      "Hindi (Although the SLM will be given in Hindi students will be allowed to write their assignments and exams in English also.)",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "A total of Rs. 27,600/- is to be paid year-wise for the full programme, @ Rs. 9 , 2 00/year. Fee to be paid in the first year including a registration fee of 200/- is Rs.9, 4 00/-.",
    schoolCode: "SOPVA",
    totalCredits: 148,
    programmeStructure: [
      { term: 1, courseCode: "BHMCT-101", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BHMCL-102", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },
      { term: 1, courseCode: "BSOG-171", category: Category.GE, credit: 6 },

      { term: 2, courseCode: "BHMCT-103", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BHMCL-104", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BGDG-172", category: Category.GE, credit: 6 },

      { term: 3, courseCode: "BHMCT-105", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BHMCL-106", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BHMCL-107", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BSOG-173", category: Category.GE, credit: 6 },

      { term: 4, courseCode: "BHMCT-108", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BHMCP-109", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BHMCL-110", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCG-174", category: Category.GE, credit: 6 },

      { term: 5, courseCode: "BHMCT-111", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BHMCL-112", category: Category.CC, credit: 6 },
      { term: 5, courseCode: "BPFT-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPFT-142", category: Category.DSE, credit: 6 },

      { term: 6, courseCode: "BHMCT-113", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BHMCL-114", category: Category.CC, credit: 6 },
      { term: 6, courseCode: "BPFT-143", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPFL-144", category: Category.DSE, credit: 6 },
    ],
  },
];
