import { Category, Degree, TermType } from "../../constants/types";

export const bachelorsDegreeProgrammes = [
  {
    code: "BAG",
    title: "Bachelor of Arts",
    degree: Degree.bachelors,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "For B.A. Rs. 9,900/- for full programme to be paid year wise @ Rs. 3,300/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/- Is Rs.3,500/-",
    schoolCode: "SOH",
    totalCredits: 132,
    programmeStructure: [
      { term: 1, courseCode: "BHDLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEGLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BUDLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BSKLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BMYLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BGULA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BODLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPBLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BODLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPBLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BANC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BECC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BHIC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPCC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPSC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPAC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BSOC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEGC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BHDC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BUDC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BSKC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BMTC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BESC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPYC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },

      { term: 2, courseCode: "BHDLA-136", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGLA-136", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BANC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BECC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BHIC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPCC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPSC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPAC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BSOC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BHDC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BUDC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BSKC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BMTC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BESC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPYC-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },

      { term: 3, courseCode: "BHDLA-137", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BEGLA-137", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BECC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BHIC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPCC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPSC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPAC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BSOC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BEGC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BHDC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BUDC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BSKC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BMTC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BESC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPYC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },

      { term: 4, courseCode: "BHDLA-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BEGLA-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BANC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BECC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BHIC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPCC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPSC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPAC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSOC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BEGC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BHDC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BULC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BSKC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BMTC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BESC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPYC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },

      { term: 5, courseCode: "BANE-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BECE-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BHIE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BHIE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BHIE-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPAE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPAE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPCE-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPSE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPSE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPSE-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BSOE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BSOE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BSOE-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BEGE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BEGE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BEGE-145", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BHDE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BHDE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BUDE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BSKE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BMTE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BESE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPYE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPCS-187", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BSOS-185", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BEGG-171", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BEGG-173", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BHDG-173", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BPAG-171", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BPAG-173", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BPCG-171", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BPCG-173", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BPCG-175", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BSOG-171", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BSOG-173", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BABG-171", category: Category.GE, credit: 6 },
      { term: 5, courseCode: "BPYG-171", category: Category.GE, credit: 6 },

      { term: 6, courseCode: "BANE-146", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BECE-146", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BHIE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BHIE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPAE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPAE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPCE-146", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPSE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPSE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPSE-146", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BSOE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BSOE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BSOE-146", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BSOE-148", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BEGE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BHDE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BHDE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BUDE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BSKE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BMTE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BMTE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPYE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPAS-186", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BPCS-188", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BGDG-172", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BEGG-172", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BEGG-174", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BPAG-172", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BPAG-174", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BPCG-172", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BPCG-174", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BPCG-176", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BSOG-176", category: Category.GE, credit: 6 },
      { term: 6, courseCode: "BPYG-172", category: Category.GE, credit: 6 },
    ],
  },
  {
    code: "BCOMG",
    title: "Bachelor of Commerce",
    degree: Degree.bachelors,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 9,900/- for full programme to be paid year wise @Rs. 3,300/- per year. Fee to be paid in 1st year, including Registration Fee of Rs.200/-is Rs.3,500/-.",
    schoolCode: "SOMS",
    totalCredits: 132,
    programmeStructure: [
      { term: 1, courseCode: "BEGLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BCOC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BCOC-132", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },

      { term: 2, courseCode: "BHDLA-136", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGLA-136", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BCOC-133", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BCOC-134", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },

      { term: 3, courseCode: "BHDLA-137", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BEGLA-137", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BCOC-135", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BCOC-136", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BCOS-183", category: Category.SEC, credit: 4 },

      { term: 4, courseCode: "BCOLA-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BCOC-137", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BCOC-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BCOS-184", category: Category.SEC, credit: 4 },

      { term: 5, courseCode: "BCOE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BCOE-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BCOS-185", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BCOG-171", category: Category.GE, credit: 6 },

      { term: 6, courseCode: "BCOE-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BCOE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BCOS-186", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BCOG-172", category: Category.GE, credit: 6 },
    ],
  },
  {
    code: "BSCG",
    title: "Bachelor of Science",
    degree: Degree.bachelors,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure:
      "Rs. 14,700/- for full programme to be paid year wise @ Rs.4,900/- per year. Fee to be paid in first year, including Registration Fee of Rs.200/- is Rs.5,100/-",
    schoolCode: "SOS",
    totalCredits: 132,
    programmeStructure: [
      { term: 1, courseCode: "BBYCT-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BBYCL-132", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BCHCT-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BCHCL-132", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BGGCT-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BGYCT-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BGYCL-132", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BMTC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPHCT-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BPHCL-132", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BZYCT-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BZYCL-132", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },

      { term: 2, courseCode: "BBYCT-133", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BBYCL-134", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BCHCT-133", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BCHCL-134", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BGGCT-132", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BGYCT-133", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BGYCL-134", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPHCT-133", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BPHCL-134", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BZYCT-133", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BZYCL-134", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },

      { term: 3, courseCode: "BBYCT-135", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BBYCL-136", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BCHCT-135", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BCHCL-136", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BGGCT-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BGGCL-134", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BGYCT-135", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BGYCL-136", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BMTC-133", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPHCT-135", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BPHCL-136", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BZYCT-135", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BZYCL-136", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BANS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BPCS-185", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BEGS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BHDS-183", category: Category.SEC, credit: 4 },
      { term: 3, courseCode: "BCOS-183", category: Category.SEC, credit: 4 },

      { term: 4, courseCode: "BBYCT-137", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BBYCL-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BCHCT-137", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BCHCL-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BGGCT-135", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BGYCT-137", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BGYCL-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BMTC-134", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPHCT-137", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BPHCL-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BZYCT-137", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BZYCL-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BANS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BECS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPAS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BPCS-186", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BSOS-184", category: Category.SEC, credit: 4 },
      { term: 4, courseCode: "BHDS-184", category: Category.SEC, credit: 4 },

      { term: 5, courseCode: "BBYET-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BBYEL-142", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BCHET-149", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BCHEL-150", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BGGET-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BGYET-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BGYEL-142", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BMTE-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPHET-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPHEL-142", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BZYET-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BZYEL-142", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BPCS-187", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BSOS-185", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BEGS-185", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BCOS-185", category: Category.SEC, credit: 4 },

      { term: 6, courseCode: "BBYET-143", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BBYEL-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BGGET-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BGYET-147", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BGYEL-148", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BMTE-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPHET-143", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPHEL-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BZYET-143", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BZYEL-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BCHET-147", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BCHEL-148", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BCHET-141", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BCHEL-142", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BPAS-186", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BPCS-188", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BCOS-186", category: Category.SEC, credit: 4 },
    ],
  },
  {
    code: "BCA",
    title: "Bachelor of Computer Applications",
    degree: Degree.bachelors,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure: "Rs. 42,000/- for full programme to be paid Semester wise @Rs. 7,000/- per semester",
    schoolCode: "SOCIS",
    totalCredits: 99,
    programmeDetail: {
      first: [
        { course: "FEG-2", credit: 4 },
        { course: "ECO-1", credit: 4 },
        { course: "BCS-11", credit: 3 },
        { course: "BCS-12", credit: 4 },
        { course: "BCSL-13", credit: 2 },
      ],
      second: [
        { course: "ECO-2", credit: 4 },
        { course: "MCS-11", credit: 3 },
        { course: "MCS-12", credit: 4 },
        { course: "MCS-15", credit: 2 },
        { course: "MCS-13", credit: 2 },
        { course: "BCSL-21", credit: 1 },
        { course: "BCSL-22", credit: 1 },
      ],
      third: [
        { course: "MCS-21", credit: 4 },
        { course: "MCS-23", credit: 3 },
        { course: "MCS-14", credit: 3 },
        { course: "BCS-31", credit: 3 },
        { course: "BCSL-32", credit: 1 },
        { course: "BCSL-33", credit: 1 },
        { course: "BCSL-34", credit: 1 },
      ],
      fourth: [
        { course: "BCS-40", credit: 4 },
        { course: "MCS-24", credit: 3 },
        { course: "BCS-41", credit: 4 },
        { course: "BCS-42", credit: 2 },
        { course: "MCSL-16", credit: 2 },
        { course: "BCSL-43", credit: 1 },
        { course: "BCSL-44", credit: 1 },
        { course: "BCSL-45", credit: 1 },
      ],
      fifth: [
        { course: "BCS-51", credit: 3 },
        { course: "BCS-52", credit: 3 },
        { course: "BCS-53", credit: 2 },
        { course: "BCS-54", credit: 3 },
        { course: "BCS-55", credit: 2 },
        { course: "BCSL-56", credit: 1 },
        { course: "BCSL-57", credit: 1 },
        { course: "BCSL-58", credit: 1 },
      ],
      sixth: [
        { course: "BCS-62", credit: 2 },
        { course: "MCS-22", credit: 4 },
        { course: "BCSL-63", credit: 1 },
        { course: "BCSP-64", credit: 8 },
      ],
    },
    programmeStructure: [
      { term: 1, courseCode: "FEG-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "ECO-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BCS-11", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BCS-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BCSL-13", category: Category.NONE, credit: 2 },

      { term: 2, courseCode: "ECO-2", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCS-11", category: Category.NONE, credit: 3 },
      { term: 2, courseCode: "MCS-12", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCS-15", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCS-13", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "BCSL-21", category: Category.NONE, credit: 1 },
      { term: 2, courseCode: "BCSL-22", category: Category.NONE, credit: 1 },

      { term: 3, courseCode: "MCS-21", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MCS-23", category: Category.NONE, credit: 3 },
      { term: 3, courseCode: "MCS-14", category: Category.NONE, credit: 3 },
      { term: 3, courseCode: "BCS-31", category: Category.NONE, credit: 3 },
      { term: 3, courseCode: "BCSL-32", category: Category.NONE, credit: 1 },
      { term: 3, courseCode: "BCSL-33", category: Category.NONE, credit: 1 },
      { term: 3, courseCode: "BCSL-34", category: Category.NONE, credit: 1 },

      { term: 4, courseCode: "BCS-40", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MCS-24", category: Category.NONE, credit: 3 },
      { term: 4, courseCode: "BCS-41", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "BCS-42", category: Category.NONE, credit: 2 },
      { term: 4, courseCode: "MCSL-16", category: Category.NONE, credit: 2 },
      { term: 4, courseCode: "BCSL-43", category: Category.NONE, credit: 1 },
      { term: 4, courseCode: "BCSL-44", category: Category.NONE, credit: 1 },
      { term: 4, courseCode: "BCSL-45", category: Category.NONE, credit: 1 },

      { term: 5, courseCode: "BCS-51", category: Category.NONE, credit: 3 },
      { term: 5, courseCode: "BCS-52", category: Category.NONE, credit: 3 },
      { term: 5, courseCode: "BCS-53", category: Category.NONE, credit: 2 },
      { term: 5, courseCode: "BCS-54", category: Category.NONE, credit: 3 },
      { term: 5, courseCode: "BCS-55", category: Category.NONE, credit: 2 },
      { term: 5, courseCode: "BCSL-56", category: Category.NONE, credit: 1 },
      { term: 5, courseCode: "BCSL-57", category: Category.NONE, credit: 1 },
      { term: 5, courseCode: "BCSL-58", category: Category.NONE, credit: 1 },

      { term: 6, courseCode: "BCS-62", category: Category.NONE, credit: 2 },
      { term: 6, courseCode: "MCS-22", category: Category.NONE, credit: 4 },
      { term: 6, courseCode: "BCSL-63", category: Category.NONE, credit: 1 },
      { term: 6, courseCode: "BCSP-64", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "BLIS",
    title: "Bachelor of Library and Information Sciences",
    degree: Degree.bachelors,
    termType: TermType.Year,
    termsCount: 1,
    eligibility:
      "Bachelor’s Degree with 50% marks and 45% for General and for the SC/ST/OBC/PH category respectively. OR Bachelor’s Degree with Diploma (one year) in Library Science OR Bachelor’s Degree with 2 years of working experience in Library and Information Centre",
    mediumOfInstruction: "English. Students can write assignments and TEE in Hindi language also.",
    duration: "Minimum 1 year and Maximum 2 years; offered in both January and July cycle of admissions.",
    feeStructure: "Rs. 7,700/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 36,
    programmeDetail: {
      first: [
        { course: "BLI-221", credit: 4 },
        { course: "BLI-222", credit: 4 },
        { course: "BLI-223", credit: 4 },
        { course: "BLI-224", credit: 4 },
        { course: "BLI-225", credit: 4 },
        { course: "BLIE-226", credit: 4 },
        { course: "BLIE-227", credit: 4 },
        { course: "BLIE-228", credit: 4 },
        { course: "BLIE-229", credit: 4 },
      ],
    },
    programmeStructure: [
      { term: 1, courseCode: "BLI-221", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLI-222", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLI-223", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLI-224", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLI-225", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLIE-226", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLIE-227", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLIE-228", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLIE-229", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "BTS",
    title: "Bachelor of Arts (Tourism Studies)",
    degree: Degree.bachelors,
    termType: TermType.Year,
    termsCount: 3,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure: "Rs. 11,400/- for full programme to be paid year wise @Rs. 3,800/- per year",
    schoolCode: "SOTHSM",
    totalCredits: 96,
    programmeDetail: {
      first: [
        { course: "TS-1", credit: 8 },
        { course: "TS-2", credit: 8 },
        { course: "BSHF-101", credit: 8 },
        { course: "BHC-11", credit: 4 },
        { course: "BHC-12", credit: 4 },
        { course: "BEGF-101", credit: 4 },
        { course: "BHC-13", credit: 4 },
        { course: "FEG-2", credit: 4 },
        { course: "BHDF-101", credit: 4 },
        { course: "BTMS-185", credit: 4 },
      ],
      second: [
        { course: "TS-4", credit: 8 },
        { course: "TS-5", credit: 8 },
        { course: "FST-1", credit: 8 },
        { course: "CIT-1", credit: 4 },
        { course: "CIT-2", credit: 4 },
        { course: "PTS-1", credit: 8 },
      ],
      third: [
        { course: "TS-3", credit: 8 },
        { course: "TS-6", credit: 8 },
        { course: "TS-7", credit: 8 },
        { course: "PTS-6", credit: 4 },
        { course: "CIT-3", credit: 4 },
        { course: "BHDA-101", credit: 4 },
      ],
    },
    programmeStructure: [
      { term: 1, courseCode: "TS-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "TS-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BSHF-101", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BHC-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHC-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEGF-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHC-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "FEG-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHDF-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BTMS-185", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "TS-4", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "TS-5", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "FST-1", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "CIT-1", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "CIT-2", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "PTS-1", category: Category.NONE, credit: 8 },

      { term: 3, courseCode: "TS-3", category: Category.NONE, credit: 8 },
      { term: 3, courseCode: "TS-6", category: Category.NONE, credit: 8 },
      { term: 3, courseCode: "TS-7", category: Category.NONE, credit: 8 },
      { term: 3, courseCode: "PTS-6", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "CIT-3", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "BHDA-101", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "BSWG",
    title: "Bachelor of Social Work",
    degree: Degree.bachelors,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure: "Rs. 17,400/- for full programme to be paid @ Rs.5,800/- per year.",
    schoolCode: "SOSW",
    totalCredits: 132,
    programmeDetail: {
      first: [
        { course: "BHDLA-135", credit: 6 },
        { course: "BEGLA-135", credit: 6 },
        { course: "BSW-121", credit: 6 },
        { course: "BSWL-104", credit: 10 },
      ],
      second: [
        { course: "BSW-122", credit: 6 },
        { course: "BSW-123", credit: 6 },
        { course: "BSWL-105", credit: 10 },
      ],
      third: [
        { course: "BSW-124", credit: 6 },
        { course: "BSW-125", credit: 6 },
        { course: "BSWL-106", credit: 10 },
      ],
      fourth: [
        { course: "BSW-126", credit: 6 },
        { course: "BSW-127", credit: 6 },
        { course: "BSWL-107", credit: 10 },
      ],
      fifth: [
        { course: "BSW-128", credit: 6 },
        { course: "BSW-129", credit: 6 },
        { course: "BSWL-108", credit: 10 },
      ],
      sixth: [
        { course: "BSW-130", credit: 6 },
        { course: "BSW-131", credit: 6 },
        { course: "BSWL-109", credit: 10 },
      ],
    },
    programmeStructure: [
      { term: 1, courseCode: "BHDLA-135", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BEGLA-135", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BSW-121", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BSWL-104", category: Category.NONE, credit: 10 },

      { term: 2, courseCode: "BSW-122", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "BSW-123", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "BSWL-105", category: Category.NONE, credit: 10 },

      { term: 3, courseCode: "BSW-124", category: Category.NONE, credit: 6 },
      { term: 3, courseCode: "BSW-125", category: Category.NONE, credit: 6 },
      { term: 3, courseCode: "BSWL-106", category: Category.NONE, credit: 10 },

      { term: 4, courseCode: "BSW-126", category: Category.NONE, credit: 6 },
      { term: 4, courseCode: "BSW-127", category: Category.NONE, credit: 6 },
      { term: 4, courseCode: "BSWL-107", category: Category.NONE, credit: 10 },

      { term: 5, courseCode: "BSW-128", category: Category.NONE, credit: 6 },
      { term: 5, courseCode: "BSW-129", category: Category.NONE, credit: 6 },
      { term: 5, courseCode: "BSWL-108", category: Category.NONE, credit: 10 },

      { term: 6, courseCode: "BSW-130", category: Category.NONE, credit: 6 },
      { term: 6, courseCode: "BSW-131", category: Category.NONE, credit: 6 },
      { term: 6, courseCode: "BSWL-109", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "BBARL",
    title: "Bachelor of Business Administration (Retailing)",
    degree: Degree.bachelors,
    termType: TermType.Year,
    termsCount: 3,
    eligibility:
      "Category A–Direct Entry: 10+2 /equivalent. University provides reservation of seats as per Government of India rules. Category B – Sponsored Admission: The sponsor is allowed to nominate employees, who have passed 10+2/equivalent, from their Retail Organization. The sponsor will submit a letter on the company’s letter head issued by the competent authority along with an individual application form of the candidate nominated with the Programme fee through a Demand Draft drawn in favour of IGNOU payable at New Delhi.",
    mediumOfInstruction: "English",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure: "Rs. 27,000/- for full programme to be paid year wise @ Rs.9,000/- per year.",
    schoolCode: "SOMS",
    totalCredits: 96,
    programmeDetail: {
      first: [
        { course: "BRL-1", credit: 4 },
        { course: "BRL-2", credit: 4 },
        { course: "BRL-3", credit: 4 },
        { course: "BRL-4", credit: 4 },
        { course: "BRLT-5", credit: 4 },
      ],
      second: [
        { course: "BRL-6", credit: 4 },
        { course: "BRL-7", credit: 4 },
        { course: "BRL-8", credit: 4 },
        { course: "ECO-1", credit: 4 },
        { course: "BCOA-1", credit: 4 },
        { course: "AMK-1", credit: 4 },
        { course: "BRLT-9", credit: 8 },
      ],
      third: [
        { course: "BRL-10", credit: 4 },
        { course: "BRL-11", credit: 4 },
        { course: "BRL-12", credit: 4 },
        { course: "BRL-13", credit: 4 },
        { course: "BRL-15", credit: 4 },
        { course: "BRLT-16", credit: 12 },
      ],
    },
    programmeStructure: [
      { term: 1, courseCode: "BRL-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRL-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRL-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRL-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRLT-5", category: Category.NONE, credit: 16 },

      { term: 2, courseCode: "BRL-6", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "BRL-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "BRL-8", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "ECO-1", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "BCOA-1", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "AMK-1", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "BRLT-9", category: Category.NONE, credit: 8 },

      { term: 3, courseCode: "BRL-10", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "BRL-11", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "BRL-12", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "BRL-13", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "BRL-15", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "BRLT-16", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "BAVTM",
    title: "Bachelor of Arts (Vocational Studies) Tourism Management",
    degree: Degree.bachelors,
    termType: TermType.Semester,
    termsCount: 6,
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 3 years and Maximum 6 years; offered in both January and July cycle of admission.",
    feeStructure: "Rs. 12600/- for full programme to be paid Rs.4200/- per year",
    schoolCode: "SOTHSM",
    totalCredits: 132,
    programmeStructure: [
      { term: 1, courseCode: "BHDLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEGLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BUDLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BSKLA-135", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BTMC-131", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BTMC-132", category: Category.CC, credit: 6 },
      { term: 1, courseCode: "BEVAE-181", category: Category.AECC, credit: 4 },

      { term: 2, courseCode: "BHDLA-136", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGLA-136", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BTMC-133", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BTMC-134", category: Category.CC, credit: 6 },
      { term: 2, courseCode: "BEGAE-182", category: Category.AECC, credit: 4 },
      { term: 2, courseCode: "BHDAE-182", category: Category.AECC, credit: 4 },

      { term: 3, courseCode: "BHDLA-137", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BEGLA-137", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BTMC-135", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BTMC-136", category: Category.CC, credit: 6 },
      { term: 3, courseCode: "BCOS-183", category: Category.SEC, credit: 4 },

      { term: 4, courseCode: "BHDLA-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BEGLA-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BTMC-137", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BTMC-138", category: Category.CC, credit: 6 },
      { term: 4, courseCode: "BCOS-184", category: Category.SEC, credit: 4 },

      { term: 5, courseCode: "BTME-141", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BTME-143", category: Category.DSE, credit: 6 },
      { term: 5, courseCode: "BTMS-185", category: Category.SEC, credit: 4 },
      { term: 5, courseCode: "BTMG-171", category: Category.GE, credit: 6 },

      { term: 6, courseCode: "BTMG-171", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BTME-144", category: Category.DSE, credit: 6 },
      { term: 6, courseCode: "BEGS-186", category: Category.SEC, credit: 4 },
      { term: 6, courseCode: "BTMG-172", category: Category.GE, credit: 6 },
    ],
  },
];
