export const bachelorsHonoursDegreeProgrammes = [
  {
    code: "BAECH",
    title: "Bachelor of Arts (Honours) Economics",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BAECH",
    fullName: "Bachelor of Arts (Honours) Economics",
    collegeCode: "IGNOU",
  },
  {
    code: "BAHIH",
    title: "Bachelor of Arts (Honours) History",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BAHIH",
    fullName: "Bachelor of Arts (Honours) History",
    collegeCode: "IGNOU",
  },
  {
    code: "BAPSH",
    title: "Bachelor of Arts (Honours) Political Science",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BAPSH",
    fullName: "Bachelor of Arts (Honours) Political Science",
    collegeCode: "IGNOU",
  },
  {
    code: "BAPCH",
    title: "Bachelor of Arts (Honours) Psychology",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BAPCH",
    fullName: "Bachelor of Arts (Honours) Psychology",
    collegeCode: "IGNOU",
  },
  {
    code: "BAPAH",
    title: "Bachelor of Arts (Honours) Public Administration",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BAPAH",
    fullName: "Bachelor of Arts (Honours) Public Administration",
    collegeCode: "IGNOU",
  },
  {
    code: "BASOH",
    title: "Bachelor of Arts (Honours) Sociology",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BASOH",
    fullName: "Bachelor of Arts (Honours) Sociology",
    collegeCode: "IGNOU",
  },
  {
    code: "BSCANH",
    title: "Bachelor of Science (Honours) Anthropology",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BSCANH",
    fullName: "Bachelor of Science (Honours) Anthropology",
    collegeCode: "IGNOU",
  },
  {
    code: "BSCBCH",
    title: "Bachelor of Science (Honours) in Biochemistry",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BSCBCH",
    fullName: "Bachelor of Science (Honours) in Biochemistry",
    collegeCode: "IGNOU",
  },
  {
    code: "BAEGH",
    title: "Bachelor of Arts English (Honours)",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BAEGH",
    fullName: "Bachelor of Arts English (Honours)",
    collegeCode: "IGNOU",
  },
  {
    code: "BAPFHMH",
    title: "Bachelor of Performing Arts – Hindustani Music (Honours)",
    degree: 0,
    termType: 1,
    termsCount: 6,
    name: "BAPFHMH",
    fullName: "Bachelor of Performing Arts – Hindustani Music (Honours)",
    collegeCode: "IGNOU",
  },
];
