import { Degree } from "../../constants/types";

export const certificateProgrammes = [
  {
    code: "CLIS",
    title: "Certificate in Library and Information Science",
    name: "CLIS",
    fullName: "Certificate in Library and Information Science",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CDM",
    title: "Certificate in Disaster Management",
    name: "CDM",
    fullName: "Certificate in Disaster Management",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CES",
    title: "Certificate in Environmental Studies",
    name: "CES",
    fullName: "Certificate in Environmental Studies",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CLTA",
    title: "Certificate Programme on Life and Thought of Dr. B.R. Ambedkar",
    name: "CLTA",
    fullName: "Certificate Programme on Life and Thought of Dr. B.R. Ambedkar",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPSCM",
    title: "Certificate in Peace Studies and Conflict Management",
    name: "CPSCM",
    fullName: "Certificate in Peace Studies and Conflict Management",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CFN",
    title: "Certificate in Food and Nutrition",
    name: "CFN",
    fullName: "Certificate in Food and Nutrition",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CNCC",
    title: "Certificate in Nutrition and Child Care",
    name: "CNCC",
    fullName: "Certificate in Nutrition and Child Care",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CRD",
    title: "Certificate in Rural Development",
    name: "CRD",
    fullName: "Certificate in Rural Development",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CIG",
    title: "Certificate in Guidance",
    name: "CIG",
    fullName: "Certificate in Guidance",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CIT",
    title: "Certificate in Information Technology",
    name: "CIT",
    fullName: "Certificate in Information Technology",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CMAD",
    title: "Certificate in Mobile Application Development",
    name: "CMAD",
    fullName: "Certificate in Mobile Application Development",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CTE",
    title: "Certificate in Teaching of English as a Second Language",
    name: "CTE",
    fullName: "Certificate in Teaching of English as a Second Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CFE",
    title: "Certificate in Functional English (Basic Level)",
    name: "CFE",
    fullName: "Certificate in Functional English (Basic Level)",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CUL",
    title: "Certificate in Urdu Language",
    name: "CUL",
    fullName: "Certificate in Urdu Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CHR",
    title: "Certificate in Human Rights",
    name: "CHR",
    fullName: "Certificate in Human Rights",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CCP",
    title: "Certificate in Consumer Protection",
    name: "CCP",
    fullName: "Certificate in Consumer Protection",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CCLBL",
    title: "Certificate in Co-operation, Co-operative Law & Business Laws",
    name: "CCLBL",
    fullName: "Certificate in Co-operation, Co-operative Law & Business Laws",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CAHT",
    title: "Certificate in Anti Human Trafficking",
    name: "CAHT",
    fullName: "Certificate in Anti Human Trafficking",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CIHL",
    title: "Certificate in International Humanitarian Law",
    name: "CIHL",
    fullName: "Certificate in International Humanitarian Law",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CNM",
    title: "Certificate Programme in NGO Management",
    name: "CNM",
    fullName: "Certificate Programme in NGO Management",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CBS",
    title: "Certificate in Business Skills",
    name: "CBS",
    fullName: "Certificate in Business Skills",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CCITSK",
    title: "Certificate in Communication & IT Skills",
    name: "CCITSK",
    fullName: "Certificate in Communication & IT Skills",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "ACISE",
    title: "Advanced Certificate in Information Security",
    name: "ACISE",
    fullName: "Advanced Certificate in Information Security",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CFDE",
    title: "Certificate in Fashion Design",
    name: "CFDE",
    fullName: "Certificate in Fashion Design",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CTS",
    title: "Certificate in Tourism Studies",
    name: "CTS",
    fullName: "Certificate in Tourism Studies",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPLT",
    title: "Certificate Programme in Laboratory Techniques",
    name: "CPLT",
    fullName: "Certificate Programme in Laboratory Techniques",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CTPM",
    title: "Certificate Programme in Teaching of Primary School Mathematics",
    name: "CTPM",
    fullName: "Certificate Programme in Teaching of Primary School Mathematics",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CAFE",
    title: "Certificate in HIV and Family Education",
    name: "CAFE",
    fullName: "Certificate in HIV and Family Education",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CSWCJS",
    title: "Certificate in Social Work and Criminal Justice System",
    name: "CSWCJS",
    fullName: "Certificate in Social Work and Criminal Justice System",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CTRBS",
    title: "Certificatein Tribal Studies",
    name: "CTRBS",
    fullName: "Certificatein Tribal Studies",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CIS",
    title: "Certificate in Sericulture",
    name: "CIS",
    fullName: "Certificate in Sericulture",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "COF",
    title: "Certificate in Organic Farming",
    name: "COF",
    fullName: "Certificate in Organic Farming",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CWHM",
    title: "Certificate in Water Harvesting & Management",
    name: "CWHM",
    fullName: "Certificate in Water Harvesting & Management",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPF",
    title: "Certificate in Poultry Farming",
    name: "CPF",
    fullName: "Certificate in Poultry Farming",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CIB",
    title: "Certificate in Beekeeping",
    name: "CIB",
    fullName: "Certificate in Beekeeping",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CAL",
    title: "Certificate in Arabic Language",
    name: "CAL",
    fullName: "Certificate in Arabic Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CFL",
    title: "Certificate in French Language",
    name: "CFL",
    fullName: "Certificate in French Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CRUL",
    title: "Certificate in Russian Language",
    name: "CRUL",
    fullName: "Certificate in Russian Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CJL",
    title: "Certificate in Japanese Language",
    name: "CJL",
    fullName: "Certificate in Japanese Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CKLC",
    title: "Certificate in Korean Language & Culture",
    name: "CKLC",
    fullName: "Certificate in Korean Language & Culture",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CSLC",
    title: "Certificate in Spanish Language & Culture",
    name: "CSLC",
    fullName: "Certificate in Spanish Language & Culture",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CGL",
    title: "Certificate in German Language",
    name: "CGL",
    fullName: "Certificate in German Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPEL",
    title: "Certificate in Persian Language",
    name: "CPEL",
    fullName: "Certificate in Persian Language",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CFAID",
    title: "Certificate in First Aid",
    name: "CFAID",
    fullName: "Certificate in First Aid",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPY",
    title: "Certificate Programme in Yoga",
    name: "CPY",
    fullName: "Certificate Programme in Yoga",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CHCWM",
    title: "Certificate in Health Care Waste Management",
    name: "CHCWM",
    fullName: "Certificate in Health Care Waste Management",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CNIN",
    title: "Certificate in Newborn and Infant Nursing",
    name: "CNIN",
    fullName: "Certificate in Newborn and Infant Nursing",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CMCHN",
    title: "Certificate in Maternal and Child Health Nursing",
    name: "CMCHN",
    fullName: "Certificate in Maternal and Child Health Nursing",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CHBHC",
    title: "Certificate in Home Based Health Care",
    name: "CHBHC",
    fullName: "Certificate in Home Based Health Care",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CGDA",
    title: "Certificate in General Duty Assistance",
    name: "CGDA",
    fullName: "Certificate in General Duty Assistance",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CGCA",
    title: "Certificate in Geriatric Care Assistance",
    name: "CGCA",
    fullName: "Certificate in Geriatric Care Assistance",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPHA",
    title: "Certificate in Phlebotomy Assistance",
    name: "CPHA",
    fullName: "Certificate in Phlebotomy Assistance",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CHHA",
    title: "Certificate in Home Health Assistance",
    name: "CHHA",
    fullName: "Certificate in Home Health Assistance",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CCH",
    title: "Certificate in Community Health",
    name: "CCH",
    fullName: "Certificate in Community Health",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CAHC",
    title: "Certificate in Adolescent Health and Counseling",
    name: "CAHC",
    fullName: "Certificate in Adolescent Health and Counseling",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CVAP",
    title: "Certificate in Visual Arts – Painting",
    name: "CVAP",
    fullName: "Certificate in Visual Arts – Painting",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CVAA",
    title: "Certificate in Visual Arts – Applied Art",
    name: "CVAA",
    fullName: "Certificate in Visual Arts – Applied Art",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPATHA",
    title: "Certificate in Performing Arts – Theatre Arts",
    name: "CPATHA",
    fullName: "Certificate in Performing Arts – Theatre Arts",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPAHM",
    title: "Certificate in Performing Arts Hindustani Music",
    name: "CPAHM",
    fullName: "Certificate in Performing Arts Hindustani Music",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPAKM",
    title: "Certificate in Performing Arts Karnatak Music",
    name: "CPAKM",
    fullName: "Certificate in Performing Arts Karnatak Music",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPABN",
    title: "Certificate in Performing Arts Bharatanatyam",
    name: "CPABN",
    fullName: "Certificate in Performing Arts Bharatanatyam",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CETM",
    title: "Certificate in Energy Technology and Management",
    name: "CETM",
    fullName: "Certificate in Energy Technology and Management",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CCPD",
    title:
      "Certificate of Competency in Power Distribution (Electrical Technicians)",
    name: "CCPD",
    fullName:
      "Certificate of Competency in Power Distribution (Electrical Technicians)",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CPVE",
    title: "Certificate Programme in Value Education",
    name: "CPVE",
    fullName: "Certificate Programme in Value Education",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CSWM",
    title: "Certificate in Solid Waste Management",
    name: "CSWM",
    fullName: "Certificate in Solid Waste Management",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CCR",
    title: "Certificate in Community Radio",
    name: "CCR",
    fullName: "Certificate in Community Radio",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "CGAS",
    title: "Certificate in Gender, Agriculture and Sustainable Development",
    name: "CGAS",
    fullName: "Certificate in Gender, Agriculture and Sustainable Development",
    degree: Degree.certificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
];
