import { Category, Degree, TermType } from "../../constants/types";

export const certificateProgrammes = [
  {
    code: "CLIS",
    title: "Certificate in Library and Information Science",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 Passed",
    mediumOfInstruction: "English. Students can write assignments and TEE in Hindi language also.",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,000/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BLI-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLII-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLII-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLII-14", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CDM",
    title: "Certificate in Disaster Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,600/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "CDM-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "CDM-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CES",
    title: "Certificate in Environmental Studies",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,400/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "AHE-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "TS-5", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "PES-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CLTA",
    title: "Certificate Programme on Life and Thought of Dr. B.R. Ambedkar",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 900/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BAB-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAB-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAB-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAB-104", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPSCM",
    title: "Certificate in Peace Studies and Conflict Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "10+2 in any discipline, (Those who don't posses 10+2 qualification can also be admitted after clearing IGNOU's preparatory programme.",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,500/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BGP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGP-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGP-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGPP-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CFN",
    title: "Certificate in Food and Nutrition",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "No formal qualification, Minimum age of 18 years as on the last date for receipt of Admission form.",
    mediumOfInstruction:
      "English & HindiEnglish, Hindi, Assamese, Gujarati, Kannada, Malayalam, Marathi, Punjabi, Tamil and Oriya.",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,400/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "CFN-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CFN-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CFN-3", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CNCC",
    title: "Certificate in Nutrition and Child Care",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,000/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "CNCC-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "CNCC-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CRD",
    title: "Certificate in Rural Development",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s Degree",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,800/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "MRD-101", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRD-102", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRD-103", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CIG",
    title: "Certificate in Guidance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Teachers of recognized Institutions OR Pass in Matriculation/SSC",
    mediumOfInstruction: "English, Hindi and Odia",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,000/- for full programme",
    schoolCode: "SOE",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "NES-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "NES-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "NES-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "NES-104", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CIT",
    title: "Certificate in Information Technology",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10 th Pass OR SSC OR DLC from Microsoft or equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 6,000/- for full programme",
    schoolCode: "SOCIS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "CIT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CIT-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CIT-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CITL-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CMAD",
    title: "Certificate in Mobile Application Development",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "(1) 10+2 OR (2) 10 th Standard with 2 or 3 years Diploma / Equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,000/- for full programme",
    schoolCode: "SOCIS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "BCS-091", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BCS-092", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BCS-093", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BCS-094", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BCSL-091", category: Category.NONE, credit: 5 },
    ],
  },
  {
    code: "CTE",
    title: "Certificate in Teaching of English as a Second Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation or 3 years of B.EL.ED or 2 years PTT, ETT or 10+2 with 2 years teaching experience",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,400/- for full programme",
    schoolCode: "SOH",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "CTE-101", category: Category.C, credit: 4 },
      { term: 1, courseCode: "CTE-102", category: Category.C, credit: 4 },
      { term: 1, courseCode: "CTE-103", category: Category.C, credit: 4 },
      { term: 1, courseCode: "CTE-104", category: Category.E, credit: 4 },
      { term: 1, courseCode: "CTE-105", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "CFE",
    title: "Certificate in Functional English (Basic Level)",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 4,000/- for full programme",
    schoolCode: "SOH",
    totalCredits: 12,
    programmeStructure: [
      { term: 1, courseCode: "BEG-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEG-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEG-6", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CUL",
    title: "Certificate in Urdu Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 with no maximum age limit.",
    mediumOfInstruction: "Bilingual Hindi/Urdu",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,200/- for full programme",
    schoolCode: "SOH",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OUL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "OUL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CHR",
    title: "Certificate in Human Rights",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,600/- for full programme",
    schoolCode: "SOL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "CHR-11", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "CHR-12", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CCP",
    title: "Certificate in Consumer Protection",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,800/- for full programme",
    schoolCode: "SOL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "CPI-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CPI-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CPI-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CPIP-104", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CCLBL",
    title: "Certificate in Co-operation, Co-operative Law & Business Laws",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 for in-service personnel (with minimum three years service) OR  Any degree for fresher",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 7,400/- for full programme",
    schoolCode: "SOL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BLE-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-14", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CAHT",
    title: "Certificate in Anti Human Trafficking",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Any Graduate,10+2 with five years of experience in the related field/10th standard (after doing bridge course from IGNOU, they will be admitted).",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,300/- for full programme",
    schoolCode: "SOL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BLE-31", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-32", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-33", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLEP-34", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CIHL",
    title: "Certificate in International Humanitarian Law",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,400/- for full programme",
    schoolCode: "SOL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BLE-35", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-36", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-37", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLEP-38", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CNM",
    title: "Certificate Programme in NGO Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or Matriculate with at least 3 years of work experience in NGO sector.",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,800/- for full programme",
    schoolCode: "SOMS",
    totalCredits: 12,
    programmeStructure: [
      { term: 1, courseCode: "BMS-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BMS-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BMS-3", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CBS",
    title: "Certificate in Business Skills",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,200/- for full programme",
    schoolCode: "SOMS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "ECO-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "PCO-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BCOA-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CITL-1", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CCITSK",
    title: "Certificate in Communication & IT Skills",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 pass with English as one of the subject",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,700/- for full programme",
    schoolCode: "SOVET",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BPOI-6", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BPOI-7", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "ACISE",
    title: "Advanced Certificate in Information Security",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,400/- for full programme",
    schoolCode: "SOVET",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "OSEI-41", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OSEI-42", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OSE-43", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OSEI-44", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CFDE",
    title: "Certificate in Fashion Design",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 (Senior Secondary)",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 4,400/- for full programme",
    schoolCode: "SOVET",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BFDI-71", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFDI-72", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFDI-73", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFD-74", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CTS",
    title: "Certificate in Tourism Studies",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,000/- for full programme",
    schoolCode: "SOTHSM",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "TS-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "TS-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CPLT",
    title: "Certificate Programme in Laboratory Techniques",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "10+2 with Science subjects or equivalent OR pass in Higher Secondary with Science subjects or equivalent and one year of experience of working in a School/College/University science laboratory OR 10 th pass or equivalent with Science subjects and two years experience ofworking in a School/College/University science laboratory",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 4,200/- for full programme",
    schoolCode: "SOS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "CLT-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CLTL-101", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLT-102", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLTL-102", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLT-103", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLTL-103", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLT-104", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLTL-104", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CTPM",
    title: "Certificate Programme in Teaching of Primary School Mathematics",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Adult with 10 th pass",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,800/- for full programme",
    schoolCode: "SOS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "AMT-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "LMT-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CAFE",
    title: "Certificate in HIV and Family Education",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,000/- for full programme",
    schoolCode: "SOSW",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BFE-101", category: Category.C, credit: 4 },
      { term: 1, courseCode: "BFE-102", category: Category.C, credit: 4 },
      { term: 1, courseCode: "BFEE-101", category: Category.E, credit: 4 },
      { term: 1, courseCode: "BFEE-102", category: Category.E, credit: 4 },
      { term: 1, courseCode: "BFEE-103", category: Category.E, credit: 4 },
      { term: 1, courseCode: "BFEE-104", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "CSWCJS",
    title: "Certificate in Social Work and Criminal Justice System",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,300/- for full programme",
    schoolCode: "SOSW",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MSW-31", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-32", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSWL-33", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CTRBS",
    title: "Certificatein Tribal Studies",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 900/- for full programme",
    schoolCode: "SOSW",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BSW-41", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BSW-42", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BSW-43", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BSW-44", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CIS",
    title: "Certificate in Sericulture",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "10 th pass out OR non-10 th pass-out having two years experience in the field of sericulture. The experience certificate should be from the extension officials of the Dept of Sericulture/Agriculture/Extension/Recognized NGOs/ Industry.",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 4,200/- for full programme",
    schoolCode: "SOA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BLP-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BLPI-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BLPI-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BLP-4", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "COF",
    title: "Certificate in Organic Farming",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "12 th pass",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 4,800/- for full programme",
    schoolCode: "SOA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BAP-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BAPI-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BAPI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAPI-3", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CWHM",
    title: "Certificate in Water Harvesting & Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,200/- for full programme",
    schoolCode: "SOA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "ONR-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "ONR-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "ONR-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "ONRL-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPF",
    title: "Certificate in Poultry Farming",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "8th Pass",
    mediumOfInstruction: "English, Hindi, Mizo and Telugu",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OLP-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OLPI-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "OLPI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OLPL-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OLPL-2", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CIB",
    title: "Certificate in Beekeeping",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "8th Pass or Professional Beekeepers",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,300/- for full programme",
    schoolCode: "SOA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OAPI-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OAPI-12", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "OAPI-13", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CAL",
    title: "Certificate in Arabic Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or 18 years of age",
    mediumOfInstruction: "English/Arabic",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,800/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BAL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BAL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CFL",
    title: "Certificate in French Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 and 18 years of age (minimum)",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 6,600/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 12,
    programmeStructure: [
      { term: 1, courseCode: "BFLI-1", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BFLI-2", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BFLI-3", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BFLI-4", category: Category.NONE, credit: 3 },
    ],
  },
  {
    code: "CRUL",
    title: "Certificate in Russian Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Minimum age 18 years. No formal qualification is required Class 10 level of English proficiency is desiable.",
    mediumOfInstruction: "Russian and English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,500/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "ORU-001", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "ORUL-002", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CJL",
    title: "Certificate in Japanese Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or equivalent with knowledge of English, Minimum 18 years of age.",
    mediumOfInstruction: "Japanese and English",
    duration: "Minimum 1 years and Maximum 3 years; offered in July cycle of admissions",
    feeStructure: "Rs. 5,500/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BJLI-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJLI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJLI-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJLI-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CKLC",
    title: "Certificate in Korean Language & Culture",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or equivalent with knowledge of English, Minimum 18 years of age.",
    mediumOfInstruction: "Korean and English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,500/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BKL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BKL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CSLC",
    title: "Certificate in Spanish Language & Culture",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 with the knowledge of English",
    mediumOfInstruction: "Spanish and English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 4,500/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BSL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BSL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CGL",
    title: "Certificate in German Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "German and English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,500/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 14,
    programmeStructure: [
      { term: 1, courseCode: "BGL-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGL-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGL-3", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CPEL",
    title: "Certificate in Persian Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or 18 years of age",
    mediumOfInstruction: "English & Persian",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,600/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BPEL-11", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BPEL-12", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CFAID",
    title: "Certificate in First Aid",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "The programme is open for all those who have completed class 10th examination",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,100/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BNS-40", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-40", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CPY",
    title: "Certificate Programme in Yoga",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Class XII pass from any recognized board (any stream)",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,000/- for full Programme",
    schoolCode: "SOHS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BYG-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BYG-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BYGL-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CHCWM",
    title: "Certificate in Health Care Waste Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,700/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BHM-101", category: Category.C, credit: 6 },
      { term: 1, courseCode: "BHM-102", category: Category.C, credit: 6 },
      { term: 1, courseCode: "BHME-101", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-102", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-103", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-104", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-105", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-106", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHMP-101", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHML-101", category: Category.E, credit: 2 },
    ],
  },
  {
    code: "CNIN",
    title: "Certificate in Newborn and Infant Nursing",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Nursing Professionals (RNRM) with Diploma in General Nursing and Midwifery (GNM) / B.Sc. (N) or above",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,900/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BNS-115", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-115", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CMCHN",
    title: "Certificate in Maternal and Child Health Nursing",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Nursing Professionals (RNRM) with Diploma in General Nursing and Midwifery (GNM) and above OR Auxiliary Nurse Midwife (ANM) /Female Health Worker (FHW)/Health Supervisor (HS)/ Lady Health Visitor (LHV)/Public Health Nurse (PHN).",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,900/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BNS-117", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-117", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CHBHC",
    title: "Certificate in Home Based Health Care",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10 th pass (Matriculation)",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,400/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 14,
    programmeStructure: [
      { term: 1, courseCode: "CNS-HC-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CNS-HCP-1", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CGDA",
    title: "Certificate in General Duty Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 Pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 6,000/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "BHT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BHTL-3", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CGCA",
    title: "Certificate in Geriatric Care Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 Pass with Science.",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 6,500/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 20,
    programmeStructure: [
      { term: 1, courseCode: "BHT-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHTL-8", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CPHA",
    title: "Certificate in Phlebotomy Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 Pass with Science",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 7,500/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 20,
    programmeStructure: [
      { term: 1, courseCode: "BHT-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHTL-13", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CHHA",
    title: "Certificate in Home Health Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 Pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 6,000/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "BHT-16", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-17", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BHTL-18", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CCH",
    title: "Certificate in Community Health",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "GNM/B.Sc. Nursing/PB B.Sc. Nursing/ Ayurveda Practitioners/ BAMS",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 15,000/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "BNS-41", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNS-42", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNS-43", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CAHC",
    title: "Certificate in Adolescent Health and Counseling",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Teacher who are teaching in primary, middle, secondary & higher secondary school or any graduates.",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,000/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 14,
    programmeStructure: [
      { term: 1, courseCode: "CNS-AH-001", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CNS-AH-002", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CNS-AHL-001", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CVAP",
    title: "Certificate in Visual Arts – Painting",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOPVA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVAL-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OVAL-5", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OVAL-6", category: Category.NONE, credit: 3 },
    ],
  },
  {
    code: "CVAA",
    title: "Certificate in Visual Arts – Applied Art",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOPVA",
    totalCredits: 13,
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVAL-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OVAL-7", category: Category.NONE, credit: 3 },
    ],
  },
  {
    code: "CPATHA",
    title: "Certificate in Performing Arts – Theatre Arts",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOPVA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OTH-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OTHL-2", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OTHL-3", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OTHL-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPAHM",
    title: "Certificate in Performing Arts Hindustani Music",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English, (Program Delivery – Through Web Enabled Academic Support).",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOPVA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMU-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMUL-2", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-3", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPAKM",
    title: "Certificate in Performing Arts Karnatak Music",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOPVA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMU-5", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMUL-6", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-7", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-8", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPABN",
    title: "Certificate in Performing Arts Bharatanatyam",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOPVA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "ODN-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "ODNL-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "ODNL-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "ODNL-13", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CETM",
    title: "Certificate in Energy Technology and Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10th pass",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 2,700/- for full programme",
    schoolCode: "SOET",
    totalCredits: 20,
    programmeStructure: [
      { term: 1, courseCode: "OEY-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OEY-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "OEY-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "OEYP-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CCPD",
    title: "Certificate of Competency in Power Distribution (Electrical Technicians)",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Electrical Technicians /Equivalent tradesman or manpower working in electricity/power sector, adults 8th pass onwards, OR Candidates having 10th /12th /Degree/ Diploma/ ITI are eligible",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,200/- for full programme",
    schoolCode: "SOET",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "OEE-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OEE-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OEEL-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CSWATT",
    title: "Certificate in Solid Wastes Treatment Techniques",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,000/- for full programme",
    schoolCode: "SOET",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BWA-001", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWA-002", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BWA-003", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWA-004", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWAP-001", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CPVE",
    title: "Certificate Programme in Value Education",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 1,800/- for full programme",
    schoolCode: "SOEDS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BEDS-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CSWM",
    title: "Certificate in Solid Waste Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2",
    mediumOfInstruction: "Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOITS",
    totalCredits: 18,
    programmeStructure: [
      { term: 1, courseCode: "BEV-001", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BEV-002", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BEV-003", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CCR",
    title: "Certificate in Community Radio",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English & Hindi",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 5,900/- for full programme",
    schoolCode: "SOJNMS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BJM-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJM-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJMP-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CGAS",
    title: "Certificate in Gender, Agriculture and Sustainable Development",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 6 months and Maximum 2 years; offered in both January & July cycle of admissions.",
    feeStructure: "Rs. 3,800/- for full programme",
    schoolCode: "SOGDS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MGS-041", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MGS-042", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MGS-043", category: Category.NONE, credit: 4 },
    ],
  },
];
