import { Degree, TermType, Category } from "../../constants/types";

export const certificateProgrammes = [
  {
    code: "CLIS",
    title: "Certificate in Library and Information Science",
    name: "CLIS",
    fullName: "Certificate in Library and Information Science",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BLI-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLII-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLII-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLII-14", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CDM",
    title: "Certificate in Disaster Management",
    name: "CDM",
    fullName: "Certificate in Disaster Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CDM-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "CDM-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CES",
    title: "Certificate in Environmental Studies",
    name: "CES",
    fullName: "Certificate in Environmental Studies",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "AHE-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "TS-5", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "PES-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CLTA",
    title: "Certificate Programme on Life and Thought of Dr. B.R. Ambedkar",
    name: "CLTA",
    fullName: "Certificate Programme on Life and Thought of Dr. B.R. Ambedkar",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BAB-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAB-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAB-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAB-104", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPSCM",
    title: "Certificate in Peace Studies and Conflict Management",
    name: "CPSCM",
    fullName: "Certificate in Peace Studies and Conflict Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BGP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGP-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGP-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGPP-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CFN",
    title: "Certificate in Food and Nutrition",
    name: "CFN",
    fullName: "Certificate in Food and Nutrition",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CFN-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CFN-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CFN-3", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CNCC",
    title: "Certificate in Nutrition and Child Care",
    name: "CNCC",
    fullName: "Certificate in Nutrition and Child Care",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CNCC-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "CNCC-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CRD",
    title: "Certificate in Rural Development",
    name: "CRD",
    fullName: "Certificate in Rural Development",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "MRD-101", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRD-102", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRD-103", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CIG",
    title: "Certificate in Guidance",
    name: "CIG",
    fullName: "Certificate in Guidance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "NES-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "NES-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "NES-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "NES-104", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CIT",
    title: "Certificate in Information Technology",
    name: "CIT",
    fullName: "Certificate in Information Technology",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CIT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CIT-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CIT-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CITL-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CMAD",
    title: "Certificate in Mobile Application Development",
    name: "CMAD",
    fullName: "Certificate in Mobile Application Development",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BCS-091", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BCS-092", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BCS-093", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BCS-094", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BCSL-091", category: Category.NONE, credit: 5 },
    ],
  },
  {
    code: "CTE",
    title: "Certificate in Teaching of English as a Second Language",
    name: "CTE",
    fullName: "Certificate in Teaching of English as a Second Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CTE-101", category: Category.C, credit: 4 },
      { term: 1, courseCode: "CTE-102", category: Category.C, credit: 4 },
      { term: 1, courseCode: "CTE-103", category: Category.C, credit: 4 },
      { term: 1, courseCode: "CTE-104", category: Category.E, credit: 4 },
      { term: 1, courseCode: "CTE-105", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "CFE",
    title: "Certificate in Functional English (Basic Level)",
    name: "CFE",
    fullName: "Certificate in Functional English (Basic Level)",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BEG-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEG-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEG-6", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CUL",
    title: "Certificate in Urdu Language",
    name: "CUL",
    fullName: "Certificate in Urdu Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OUL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "OUL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CHR",
    title: "Certificate in Human Rights",
    name: "CHR",
    fullName: "Certificate in Human Rights",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CHR-11", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "CHR-12", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CCP",
    title: "Certificate in Consumer Protection",
    name: "CCP",
    fullName: "Certificate in Consumer Protection",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CPI-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CPI-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CPI-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CPIP-104", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CCLBL",
    title: "Certificate in Co-operation, Co-operative Law & Business Laws",
    name: "CCLBL",
    fullName: "Certificate in Co-operation, Co-operative Law & Business Laws",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BLE-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-14", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CAHT",
    title: "Certificate in Anti Human Trafficking",
    name: "CAHT",
    fullName: "Certificate in Anti Human Trafficking",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BLE-31", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-32", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-33", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLEP-34", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CIHL",
    title: "Certificate in International Humanitarian Law",
    name: "CIHL",
    fullName: "Certificate in International Humanitarian Law",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BLE-35", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-36", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLE-37", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BLEP-38", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CNM",
    title: "Certificate Programme in NGO Management",
    name: "CNM",
    fullName: "Certificate Programme in NGO Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BMS-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BMS-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BMS-3", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CBS",
    title: "Certificate in Business Skills",
    name: "CBS",
    fullName: "Certificate in Business Skills",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "ECO-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "PCO-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BCOA-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CITL-1", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CCITSK",
    title: "Certificate in Communication & IT Skills",
    name: "CCITSK",
    fullName: "Certificate in Communication & IT Skills",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BPOI-6", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BPOI-7", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "ACISE",
    title: "Advanced Certificate in Information Security",
    name: "ACISE",
    fullName: "Advanced Certificate in Information Security",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OSEI-41", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OSEI-42", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OSE-43", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OSEI-44", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CFDE",
    title: "Certificate in Fashion Design",
    name: "CFDE",
    fullName: "Certificate in Fashion Design",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BFDI-71", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFDI-72", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFDI-73", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFD-74", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CTS",
    title: "Certificate in Tourism Studies",
    name: "CTS",
    fullName: "Certificate in Tourism Studies",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "TS-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "TS-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CPLT",
    title: "Certificate Programme in Laboratory Techniques",
    name: "CPLT",
    fullName: "Certificate Programme in Laboratory Techniques",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CLT-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CLTL-101", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLT-102", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLTL-102", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLT-103", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLTL-103", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLT-104", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "CLTL-104", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CTPM",
    title: "Certificate Programme in Teaching of Primary School Mathematics",
    name: "CTPM",
    fullName: "Certificate Programme in Teaching of Primary School Mathematics",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "AMT-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "LMT-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CAFE",
    title: "Certificate in HIV and Family Education",
    name: "CAFE",
    fullName: "Certificate in HIV and Family Education",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BFE-101", category: Category.C, credit: 4 },
      { term: 1, courseCode: "BFE-102", category: Category.C, credit: 4 },
      { term: 1, courseCode: "BFEE-101", category: Category.E, credit: 4 },
      { term: 1, courseCode: "BFEE-102", category: Category.E, credit: 4 },
      { term: 1, courseCode: "BFEE-103", category: Category.E, credit: 4 },
      { term: 1, courseCode: "BFEE-104", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "CSWCJS",
    title: "Certificate in Social Work and Criminal Justice System",
    name: "CSWCJS",
    fullName: "Certificate in Social Work and Criminal Justice System",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "MSW-31", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-32", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSWL-33", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CTRBS",
    title: "Certificatein Tribal Studies",
    name: "CTRBS",
    fullName: "Certificatein Tribal Studies",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BSW-41", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BSW-42", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BSW-43", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BSW-44", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CIS",
    title: "Certificate in Sericulture",
    name: "CIS",
    fullName: "Certificate in Sericulture",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BLP-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BLPI-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BLPI-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BLP-4", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "COF",
    title: "Certificate in Organic Farming",
    name: "COF",
    fullName: "Certificate in Organic Farming",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BAP-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BAPI-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BAPI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAPI-3", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CWHM",
    title: "Certificate in Water Harvesting & Management",
    name: "CWHM",
    fullName: "Certificate in Water Harvesting & Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "ONR-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "ONR-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "ONR-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "ONRL-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPF",
    title: "Certificate in Poultry Farming",
    name: "CPF",
    fullName: "Certificate in Poultry Farming",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OLP-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OLPI-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "OLPI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OLPL-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OLPL-2", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CIB",
    title: "Certificate in Beekeeping",
    name: "CIB",
    fullName: "Certificate in Beekeeping",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OAPI-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OAPI-12", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "OAPI-13", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CAL",
    title: "Certificate in Arabic Language",
    name: "CAL",
    fullName: "Certificate in Arabic Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BAL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BAL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CFL",
    title: "Certificate in French Language",
    name: "CFL",
    fullName: "Certificate in French Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BFLI-1", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BFLI-2", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BFLI-3", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BFLI-4", category: Category.NONE, credit: 3 },
    ],
  },
  {
    code: "CRUL",
    title: "Certificate in Russian Language",
    name: "CRUL",
    fullName: "Certificate in Russian Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "ORU-001", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "ORUL-002", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CJL",
    title: "Certificate in Japanese Language",
    name: "CJL",
    fullName: "Certificate in Japanese Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BJLI-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJLI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJLI-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJLI-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CKLC",
    title: "Certificate in Korean Language & Culture",
    name: "CKLC",
    fullName: "Certificate in Korean Language & Culture",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BKL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BKL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CSLC",
    title: "Certificate in Spanish Language & Culture",
    name: "CSLC",
    fullName: "Certificate in Spanish Language & Culture",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BSL-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BSL-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CGL",
    title: "Certificate in German Language",
    name: "CGL",
    fullName: "Certificate in German Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BGL-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGL-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BGL-3", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CPEL",
    title: "Certificate in Persian Language",
    name: "CPEL",
    fullName: "Certificate in Persian Language",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BPEL-11", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BPEL-12", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CFAID",
    title: "Certificate in First Aid",
    name: "CFAID",
    fullName: "Certificate in First Aid",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BNS-40", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-40", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CPY",
    title: "Certificate Programme in Yoga",
    name: "CPY",
    fullName: "Certificate Programme in Yoga",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BYG-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BYG-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BYGL-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CHCWM",
    title: "Certificate in Health Care Waste Management",
    name: "CHCWM",
    fullName: "Certificate in Health Care Waste Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BHM-101", category: Category.C, credit: 6 },
      { term: 1, courseCode: "BHM-102", category: Category.C, credit: 6 },
      { term: 1, courseCode: "BHME-101", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-102", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-103", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-104", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-105", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHME-106", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHMP-101", category: Category.E, credit: 2 },
      { term: 1, courseCode: "BHML-101", category: Category.E, credit: 2 },
    ],
  },
  {
    code: "CNIN",
    title: "Certificate in Newborn and Infant Nursing",
    name: "CNIN",
    fullName: "Certificate in Newborn and Infant Nursing",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BNS-115", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-115", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CMCHN",
    title: "Certificate in Maternal and Child Health Nursing",
    name: "CMCHN",
    fullName: "Certificate in Maternal and Child Health Nursing",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BNS-117", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-117", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CHBHC",
    title: "Certificate in Home Based Health Care",
    name: "CHBHC",
    fullName: "Certificate in Home Based Health Care",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CNS-HC-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "CNS-HCP-1", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CGDA",
    title: "Certificate in General Duty Assistance",
    name: "CGDA",
    fullName: "Certificate in General Duty Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BHT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BHTL-3", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CGCA",
    title: "Certificate in Geriatric Care Assistance",
    name: "CGCA",
    fullName: "Certificate in Geriatric Care Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BHT-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHTL-8", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CPHA",
    title: "Certificate in Phlebotomy Assistance",
    name: "CPHA",
    fullName: "Certificate in Phlebotomy Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BHT-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHTL-13", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CHHA",
    title: "Certificate in Home Health Assistance",
    name: "CHHA",
    fullName: "Certificate in Home Health Assistance",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BHT-16", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHT-17", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BHTL-18", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "CCH",
    title: "Certificate in Community Health",
    name: "CCH",
    fullName: "Certificate in Community Health",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BNS-41", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNS-42", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNS-43", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "CAHC",
    title: "Certificate in Adolescent Health and Counseling",
    name: "CAHC",
    fullName: "Certificate in Adolescent Health and Counseling",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "CNS-AH-001", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CNS-AH-002", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "CNS-AHL-001", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CVAP",
    title: "Certificate in Visual Arts – Painting",
    name: "CVAP",
    fullName: "Certificate in Visual Arts – Painting",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVAL-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OVAL-5", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OVAL-6", category: Category.NONE, credit: 3 },
    ],
  },
  {
    code: "CVAA",
    title: "Certificate in Visual Arts – Applied Art",
    name: "CVAA",
    fullName: "Certificate in Visual Arts – Applied Art",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVAL-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OVAL-7", category: Category.NONE, credit: 3 },
    ],
  },
  {
    code: "CPATHA",
    title: "Certificate in Performing Arts – Theatre Arts",
    name: "CPATHA",
    fullName: "Certificate in Performing Arts – Theatre Arts",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OTH-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OTHL-2", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OTHL-3", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OTHL-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPAHM",
    title: "Certificate in Performing Arts Hindustani Music",
    name: "CPAHM",
    fullName: "Certificate in Performing Arts Hindustani Music",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMU-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMUL-2", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-3", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPAKM",
    title: "Certificate in Performing Arts Karnatak Music",
    name: "CPAKM",
    fullName: "Certificate in Performing Arts Karnatak Music",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMU-5", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OMUL-6", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-7", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "OMUL-8", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CPABN",
    title: "Certificate in Performing Arts Bharatanatyam",
    name: "CPABN",
    fullName: "Certificate in Performing Arts Bharatanatyam",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OVA-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "OVA-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "ODN-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "ODNL-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "ODNL-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "ODNL-13", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CETM",
    title: "Certificate in Energy Technology and Management",
    name: "CETM",
    fullName: "Certificate in Energy Technology and Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OEY-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OEY-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "OEY-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "OEYP-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CCPD",
    title: "Certificate of Competency in Power Distribution (Electrical Technicians)",
    name: "CCPD",
    fullName: "Certificate of Competency in Power Distribution (Electrical Technicians)",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "OEE-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OEE-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OEEL-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CSWATT",
    title: "Certificate in Solid Wastes Treatment Techniques",
    name: "CSWATT",
    fullName: "Certificate in Solid Wastes Treatment Techniques",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BWA-001", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWA-002", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BWA-003", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWA-004", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWAP-001", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "CPVE",
    title: "Certificate Programme in Value Education",
    name: "CPVE",
    fullName: "Certificate Programme in Value Education",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BEDS-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "CSWM",
    title: "Certificate in Solid Waste Management",
    name: "CSWM",
    fullName: "Certificate in Solid Waste Management",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BEV-001", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BEV-002", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BEV-003", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "CCR",
    title: "Certificate in Community Radio",
    name: "CCR",
    fullName: "Certificate in Community Radio",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "BJM-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJM-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BJMP-1", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "CGAS",
    title: "Certificate in Gender, Agriculture and Sustainable Development",
    name: "CGAS",
    fullName: "Certificate in Gender, Agriculture and Sustainable Development",
    degree: Degree.certificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    programmeStructure: [
      { term: 1, courseCode: "MGS-041", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MGS-042", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MGS-043", category: Category.NONE, credit: 4 },
    ],
  },
];
