export const diplomaProgrammes = [
  {
    code: "DECE",
    title: "Diploma in Early Childhood Care and Education",
    name: "DECE",
    fullName: "Diploma in Early Childhood Care and Education",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DNHE",
    title: "Diploma in Nutrition & Health Education",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DPLAD",
    title: "Diploma in Panchayat Level Administration and Development",
    name: "DPLAD",
    fullName: "Diploma in Panchayat Level Administration and Development",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DEVMT",
    title: "Diploma in Event Management",
    name: "DEVMT",
    fullName: "Diploma in Event Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DTS",
    title: "Diploma in Tourism Studies",
    name: "DTS",
    fullName: "Diploma in Tourism Studies",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DCE",
    title: "Diploma in Creative Writing in English",
    name: "DCE",
    fullName: "Diploma in Creative Writing in English",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DUL",
    title: "Diploma Programme in Urdu",
    name: "DUL",
    fullName: "Diploma Programme in Urdu",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DVAPFV",
    title: "Diploma in Value Added Products from Fruits & Vegetables",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DDT",
    title: "Diploma in Dairy Technology",
    name: "DDT",
    fullName: "Diploma in Dairy Technology",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DMT",
    title: "Diploma in Meat Technology",
    name: "DMT",
    fullName: "Diploma in Meat Technology",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DWM",
    title: "Diploma in Watershed Management",
    name: "DWM",
    fullName: "Diploma in Watershed Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DHORT",
    title: "Diploma in Horticulture",
    name: "DHORT",
    fullName: "Diploma in Horticulture",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DWED",
    title: "Diploma in Women’s Empowerment and Development",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DAFE",
    title: "Diploma in HIV and Family Education",
    name: "DAFE",
    fullName: "Diploma in HIV and Family Education",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DBPOFA",
    title: "Diploma in Business Process Outsourcing Finance and Accounting",
    name: "DBPOFA",
    fullName: "Diploma in Business Process Outsourcing Finance and Accounting",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DMOP",
    title: "Diploma in Modern Office Practice",
    name: "DMOP",
    fullName: "Diploma in Modern Office Practice",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DIPP",
    title: "Diploma in Paralegal Practice",
    name: "DIPP",
    fullName: "Diploma in Paralegal Practice",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DAQ",
    title: "Diploma in Aquaculture",
    name: "DAQ",
    fullName: "Diploma in Aquaculture",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DIR",
    title: "Diploma in Retailing",
    name: "DIR",
    fullName: "Diploma in Retailing",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DTG",
    title: "Diploma in Teaching German as a Foreign Language",
    name: "DTG",
    fullName: "Diploma in Teaching German as a Foreign Language",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DNA",
    title: "Diploma in Nursing Administration",
    name: "DNA",
    fullName: "Diploma in Nursing Administration",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DCCN",
    title: "Diploma in Critical Care Nursing",
    name: "DCCN",
    fullName: "Diploma in Critical Care Nursing",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DTH",
    title: "Diploma in Theatre Arts",
    name: "DTH",
    fullName: "Diploma in Theatre Arts",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DPVE",
    title: "Diploma in Value Education",
    name: "DPVE",
    fullName: "Diploma in Value Education",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "DSCDM",
    title: "DIPLOMA IN SMART CITY DEVELOPMENT AND MANAGEMENT",
    name: "DSCDM",
    fullName: "DIPLOMA IN SMART CITY DEVELOPMENT AND MANAGEMENT",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
];
