import { Category, Degree, TermType } from "../../constants/types";

export const diplomaProgrammes = [
  {
    code: "DECE",
    title: "Diploma in Early Childhood Care and Education",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English, Hindi & Tamil",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 3,000/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "DECE-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "DECE-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "DECE-3", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "DECE-4", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "DNHE",
    title: "Diploma in Nutrition & Health Education",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 3,000/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "DNHE-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "DNHE-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "DNHE-3", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "DNHE-4", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "DPLAD",
    title: "Diploma in Panchayat Level Administration and Development",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 30,
    programmeStructure: [
      { term: 1, courseCode: "BPR-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BPR-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BPR-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BPR-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BPR-5", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "DEVMT",
    title: "Diploma in Event Management",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 7,100/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BHC-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHC-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHC-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHC-14", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHC-15", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BHCP-11", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BHCL-11", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DTS",
    title: "Diploma in Tourism Studies",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 4,500/- for full programme",
    schoolCode: "SOTHSM",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "TS-1", category: Category.C, credit: 8 },
      { term: 1, courseCode: "TS-2", category: Category.C, credit: 8 },
      { term: 1, courseCode: "TS-3", category: Category.C, credit: 8 },
      { term: 1, courseCode: "TS-4", category: Category.E, credit: 8 },
      { term: 1, courseCode: "PTS-4", category: Category.E, credit: 4 },
      { term: 1, courseCode: "TS-5", category: Category.E, credit: 8 },
      { term: 1, courseCode: "PTS-5", category: Category.E, credit: 4 },
      { term: 1, courseCode: "TS-6", category: Category.E, credit: 8 },
      { term: 1, courseCode: "PTS-6", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "DCE",
    title: "Diploma in Creative Writing in English",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or any one without 10 +2 but age should be 20 years or above.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 3,800/- for full programme",
    schoolCode: "SOH",
    totalCredits: 24,
    programmeStructure: [
      { term: 1, courseCode: "DCE-1", category: Category.C, credit: 4 },
      { term: 1, courseCode: "DCE-6", category: Category.C, credit: 4 },
      { term: 1, courseCode: "DCE-2", category: Category.E, credit: 4 },
      { term: 1, courseCode: "DCE-3", category: Category.E, credit: 4 },
      { term: 1, courseCode: "DCE-4", category: Category.E, credit: 4 },
      { term: 1, courseCode: "DCE-5", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "DUL",
    title: "Diploma Programme in Urdu",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "10+2 with Urdu as one of the subjects or its equivalent or Certificate in Urdu Language from IGNOU in lieu of Urdu as a subject, with no maximum age limit.",
    mediumOfInstruction: "Urdu",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 1,600/- for full programme",
    schoolCode: "SOH",
    totalCredits: 24,
    programmeStructure: [
      { term: 1, courseCode: "OUL-3", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "OULP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OULE-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OULE-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "OULE-5", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DVAPFV",
    title: "Diploma in Value Added Products from Fruits & Vegetables",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admissions",
    feeStructure: "Rs. 12,700/- for full programme",
    schoolCode: "SOA",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BPVI-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-8", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DDT",
    title: "Diploma in Dairy Technology",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English, Hindi and Telugu",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admissions",
    feeStructure: "Rs. 15,200/- for full programme",
    schoolCode: "SOA",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BPVI-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-14", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-15", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-16", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-17", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-18", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DMT",
    title: "Diploma in Meat Technology",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admissions",
    feeStructure: "Rs. 12,700/- for full programme",
    schoolCode: "SOA",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BPVI-21", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-22", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-23", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-24", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-25", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-26", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-27", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPVI-28", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DWM",
    title: "Diploma in Watershed Management",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admissions",
    feeStructure: "Rs. 10,600/- for full programme",
    schoolCode: "SOA",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BNRI-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNRI-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNRI-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNRI-104", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNRI-105", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNRI-106", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNRI-107", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNRP-108", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DHORT",
    title: "Diploma in Horticulture",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 Pass",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 3,800/- for full programme",
    schoolCode: "SOA",
    totalCredits: 34,
    programmeStructure: [
      { term: 1, courseCode: "BAP-002", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BAPI-004", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BAPI-005", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BAPI-006", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BAPI-007", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "DWED",
    title: "Diploma in Women’s Empowerment and Development",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 3,600/- for full programme",
    schoolCode: "SOGDS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BWEE-12", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BWEE-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWEE-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWEF-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWEE-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWEE-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BWEE-8", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DAFE",
    title: "Diploma in HIV and Family Education",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 1,500/- for full programme",
    schoolCode: "SOSW",
    totalCredits: 24,
    programmeStructure: [
      { term: 1, courseCode: "BFE-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFEE-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFE-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFEE-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFEE-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BFEE-104", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "DBPOFA",
    title: "Diploma in Business Process Outsourcing Finance and Accounting",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "10+2 or its equivalent with English as compulsory subject & 50% aggregate. OR Bachelors degree and above (with English as compulsory subject at 10+2 level)",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure:
      "Rs.10,000/- for full programme. But when you break it in installments it is as follows 1st Semester Rs. 5,000/- + 2nd Semester Rs. 5,000/-.",
    schoolCode: "SOVET",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BPOI-101", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "BPOI-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPOI-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BPOI-104", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BPOI-105", category: Category.NONE, credit: 3 },
      { term: 1, courseCode: "BPOI-6", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BPOI-7", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "DMOP",
    title: "Diploma in Modern Office Practice",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 6,000/- for full programme",
    schoolCode: "SOVET",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BSSI-11", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BSSI-12", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BSSI-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BSSI-14", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "BSSI-15", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "DIPP",
    title: "Diploma in Paralegal Practice",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 7,400/- for full programme",
    schoolCode: "SOL",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BLE-1", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "BLE-2", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "BLE-3", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "BLE-4", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "BLEP-1", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "DAQ",
    title: "Diploma in Aquaculture",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 Pass",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 6,900/- for full programme",
    schoolCode: "SOS",
    totalCredits: 28,
    programmeStructure: [
      { term: 1, courseCode: "BAQ-1", category: Category.C, credit: 8 },
      { term: 1, courseCode: "BAQP-1", category: Category.C, credit: 6 },
      { term: 1, courseCode: "BAQ-2", category: Category.E, credit: 8 },
      { term: 1, courseCode: "BAQL-1", category: Category.E, credit: 6 },
      { term: 1, courseCode: "BAQ-3", category: Category.E, credit: 8 },
      { term: 1, courseCode: "BAQL-2", category: Category.E, credit: 6 },
    ],
  },
  {
    code: "DIR",
    title: "Diploma in Retailing",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 or its equivalent",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admissions",
    feeStructure: "Rs. 8,000/- for full programme",
    schoolCode: "SOMS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BRL-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRL-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRL-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRL-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BRLT-5", category: Category.NONE, credit: 16 },
    ],
  },
  {
    code: "DTG",
    title: "Diploma in Teaching German as a Foreign Language",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Bachelor’s Degree in German or any discipline with knowledge of B1 (according to the Common European Framework of References for Languages) and/or equivalent language proficiency and who want to teach German as a Foreign Language at Indian secondary schools.",
    mediumOfInstruction: "German",
    duration: "Minimum 1 year and Maximum 3 years; offered only in January cycle of admissions",
    feeStructure: "Rs. 6,200/- for full programme",
    schoolCode: "SOFL",
    totalCredits: 24,
    programmeStructure: [
      { term: 1, courseCode: "DTG-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "DTG-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "DTG-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "DTG-4", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "DNA",
    title: "Diploma in Nursing Administration",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "General Nursing and Midwifery (GNM) with two years of experience in the profession. (for male nurses or nurses who have not done midwifery in the GNM programme should have a certificate in any of the nursing course of 6-9 months duration prescribed by the Indian Nursing Council in lieu of midwifery) OR B.Sc. (Nursing) with no experience",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 9,600/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 28,
    programmeStructure: [
      { term: 1, courseCode: "BNS-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNS-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNS-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNS-14", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BNSL-11", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-12", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "DCCN",
    title: "Diploma in Critical Care Nursing",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Registered Nurse (RN) and (RNRM) at all levels (GNM/BSCN/ or above)",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in January cycle of admissions",
    feeStructure: "Rs. 5,300/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BNS-31", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNS-32", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BNSL-33", category: Category.NONE, credit: 12 },
      { term: 1, courseCode: "BNSL-34", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "DTH",
    title: "Diploma in Theatre Arts",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 7,700/- for full programme",
    schoolCode: "SOPVA",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BTH-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BTHL-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BTHL-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BTHI-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BTHI-5", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "DPVE",
    title: "Diploma in Value Education",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 4,000/- for full programme",
    schoolCode: "SOEDS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "BEDS-001", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-002", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-003", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-004", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEDS-005", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "CHR-12", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "DSCDM",
    title: "DIPLOMA IN SMART CITY DEVELOPMENT AND MANAGEMENT",
    degree: Degree.diploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "10+2 in Science with Mathematics",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 10,000/- for full programme",
    schoolCode: "SOET",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MIO-001", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIO-002", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIO-003", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIO-004", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MIO-005", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MIOP-001", category: Category.NONE, credit: 8 },
    ],
  },
];
