import { Category, Degree, TermType } from "../../constants/types";

export const mastersDegreeProgrammes = [
  {
    code: "MCOM",
    title: "Master of Commerce",
    name: "MCOM",
    fullName: "Master of Commerce",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOMS",
    totalCredits: 72,
    programmeStructure: [
      { term: 1, courseCode: "IBO-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-5", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-6", category: Category.NONE, credit: 6 },

      { term: 2, courseCode: "MCO-1", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MCO-3", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MCO-4", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MCO-5", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MCO-6", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MCO-7", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "MEG",
    title: "Master of Arts (English)",
    name: "MEG",
    fullName: "Master of Arts (English)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOH",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MEG-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MEG-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MEG-3", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MEG-4", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MEG-5", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-6", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-7", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-8", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-9", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-10", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-11", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-12", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-13", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-14", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-15", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MEG-16", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MAUD",
    title: "Master of Arts (Urdu)",
    name: "MAUD",
    fullName: "Master of Arts (Urdu)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOH",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MAUD-001", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAUD-002", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAUD-003", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAUD-004", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MAUD-007", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MAUD-008", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MAUD-009", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MAUD-010", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MPS",
    title: "Master of Arts (Political Science)",
    name: "MPS",
    fullName: "Master of Arts (Political Science)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MPS-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MPS-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MPS-3", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MPS-4", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MPSE-1", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-2", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-3", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-4", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-5", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-6", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-8", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-9", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-11", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-12", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-13", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MED-2", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MED-8", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGP-4", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-8", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-10", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-11", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-13", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "MAH",
    title: "Master of Arts (History)",
    name: "MAH",
    fullName: "Master of Arts (History)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MHI-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MHI-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MHI-4", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MHI-5", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MHI-3", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPSE-3", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPSE-4", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MHI-6", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MHI-8", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MHI-9", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MHI-10", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MSO",
    title: "Master of Arts (Sociology)",
    name: "MSO",
    fullName: "Master of Arts (Sociology)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MSO-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MSO-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MSO-3", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MSO-4", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MSOE-1", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MSOE-2", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MSOE-3", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MSOE-4", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPA-16", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPS-3", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MAPC",
    title: "Master of Arts (Psychology)",
    name: "MAPC",
    fullName: "Master of Arts (Psychology)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MPC-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPC-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPC-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPC-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPC-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPC-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPCL-7", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MPCE-11", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-12", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-13", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-14", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MPCE-15", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPCE-16/46", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MPCE-21", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-22", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-23", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-24", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MPCE-25", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPCE-26/46", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MPCE-31", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-32", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-33", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPCE-34", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MPCE-35", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPCE-36/46", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "MEC",
    title: "Master of Arts (Economics)",
    name: "MEC",
    fullName: "Master of Arts (Economics)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 66,
    programmeStructure: [
      { term: 1, courseCode: "MEC-101", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEC-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEC-103", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEC-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEC-205", category: Category.NONE, credit: 6 },

      { term: 2, courseCode: "MEC-106", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MEC-7", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MEC-108", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MEC-109", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MECE-1", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MECE-3", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MECE-4", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MECP-101", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MWG-11", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MGSE-9", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MEDSE-46", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MPA",
    title: "Master of Arts (Public Administration)",
    name: "MPA",
    fullName: "Master of Arts (Public Administration)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MPA-11", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MPA-12", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MPA-13", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MPA-14", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MPA-15", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPA-16", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPA-17", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MPA-18", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSO-2", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPS-3", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MPAP-2", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MLIS",
    title: "Master of Library and Information Sciences",
    name: "MLIS",
    fullName: "Master of Library and Information Sciences",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "MLI-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLII-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLI-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLII-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLII-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLII-104", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIP-2", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MLIE-101", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MLIE-102", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MLIE-103", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MLIE-104", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MLIE-105", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MLIE-106", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "MAAN",
    title: "Master of Arts (Anthropology)",
    name: "MAAN",
    fullName: "Master of Arts (Anthropology)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MANI-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MANI-2", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAN-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAN-2", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MANP-1", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MANI-3", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MANE-1", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MANE-2", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MANE-3", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MANE-4", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MANE-5", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MGPS",
    title: "Master of Arts (Gandhi and Peace Studies)",
    name: "MGPS",
    fullName: "Master of Arts (Gandhi and Peace Studies)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MGP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGP-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGP-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGP-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-9", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-14", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MGP-5", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-8", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-10", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-11", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-12", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-13", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-15", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-16", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MGPE-17", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MCA_NEW",
    title: "Master of Computer Applications",
    name: "MCA_NEW",
    fullName: "Master of Computer Applications",
    degree: Degree.masters,
    termType: TermType.Semester,
    termsCount: 4,
    collegeCode: "IGNOU",
    schoolCode: "SOCIS",
    totalCredits: 80,
    programmeStructure: [
      { term: 1, courseCode: "MCS-211", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCS-212", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCS-213", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCS-214", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCS-215", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCSL-216", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCSL-217", category: Category.NONE, credit: 2 },

      { term: 2, courseCode: "MCS-218", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCS-219", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCS-220", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCS-221", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCSL-222", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCSL-223", category: Category.NONE, credit: 2 },

      { term: 3, courseCode: "MCS-224", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MCS-225", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MCS-226", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MCS-227", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MCSL-228", category: Category.NONE, credit: 2 },
      { term: 3, courseCode: "MCSL-229", category: Category.NONE, credit: 2 },

      { term: 4, courseCode: "MCS-230", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MCS-231", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MCSP-232", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "MARD",
    title: "Master of Arts (Rural Development)",
    name: "MARD",
    fullName: "Master of Arts (Rural Development)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOCE",
    totalCredits: 66,
    programmeStructure: [
      { term: 1, courseCode: "MRD-101", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRD-102", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRD-103", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRD-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MRDP-1", category: Category.NONE, credit: 12 },

      { term: 2, courseCode: "RDD-6", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "RDD-7", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MRDE-101", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MRDE-2", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MRDE-3", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MRDE-4", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "MSCDFSM",
    title: "Master of Science (Food Nutrition)",
    name: "MSCCFT",
    fullName: "Master of Science (Counselling and Family Therapy)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOCE",
    totalCredits: 72,
    programmeStructure: [
      { term: 1, courseCode: "MFN-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MFN-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MFNL-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MFN-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MFNL-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MFN-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MFNL-6", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MFN-8", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MFNL-8", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MFN-10", category: Category.NONE, credit: 2 },

      { term: 2, courseCode: "MFN-4", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MFNL-4", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MFN-5", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MFNL-5", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MFN-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MFNL-7", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MFN-9", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MFNP-11", category: Category.NONE, credit: 16 },
      { term: 2, courseCode: "MFNP-12", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MSCCFT",
    title: "Master of Science (Counselling and Family Therapy)",
    name: "MSCCFT",
    fullName: "Master of Science (Counselling and Family Therapy)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOCE",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MCFT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-4", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-5", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFTL-8", category: Category.NONE, credit: 2 },

      { term: 2, courseCode: "MCFT-6", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCFTL-6", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCFT-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCFTL-7", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCFTP-1", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MCFTP-2", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MCFTE-1", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCFTE-4", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCFTE-2", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCFTE-5", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCFTE-3", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCFTE-6", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "MSW",
    title: "Master of Social Work",
    name: "MSW",
    fullName: "Master of Social Work",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSW",
    totalCredits: 72,
    programmeStructure: [
      { term: 1, courseCode: "MSW-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSWE-10", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-32", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSWL-13", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MSWL-14", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MSW-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSW-8", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSW-9", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSW-17", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSWE-1", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSWE-2", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSWE-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSWE-3", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSWP-1", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSWL-15", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MSWL-16", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MSWC",
    title: "Master of Social Work (Counselling)",
    name: "MSWC",
    fullName: "Master of Social Work (Counselling)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOSW",
    totalCredits: 72,
    programmeStructure: [
      { term: 1, courseCode: "MSW-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-8", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-9", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSWL-46", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MSWL-47", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MSW-12", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSW-13", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSW-14", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSW-15", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSW-16", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSWL-48", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MSWL-49", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MAEDU",
    title: "Master of Arts (Education)",
    name: "MAEDU",
    fullName: "Master of Arts (Education)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOE",
    totalCredits: 68,
    programmeStructure: [
      { term: 1, courseCode: "MES-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MES-12", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-13", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-14", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-15", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-16", category: Category.NONE, credit: 6 },

      { term: 2, courseCode: "MES-101", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-102", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-103", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-104", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-111", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MES-112", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MES-113", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MES-114", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-115", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-31", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-32", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-33", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-34", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-41", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-42", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-43", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MES-44", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MAE-1", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MAE-2", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MAE-3", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MAE-4", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MESP-1", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "MADE",
    title: "Master of Arts (Distance Education)",
    name: "MADE",
    fullName: "Master of Arts (Distance Education)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "STRIDE",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MDE-411", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDE-412", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDE-413", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDE-414", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDE-518", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MDE-415", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDE-416", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDE-417", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDE-419", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDEP-520", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MAAE",
    title: "Master of Arts (Adult Education)",
    name: "MAAE",
    fullName: "Master of Arts (Adult Education)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOE",
    totalCredits: 68,
    programmeStructure: [
      { term: 1, courseCode: "MAE-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAE-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAE-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-16", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAEL-1", category: Category.NONE, credit: 10 },

      { term: 2, courseCode: "MAE-4", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MAE-5", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MAEP-1", category: Category.NONE, credit: 10 },
      { term: 2, courseCode: "MAEE-1", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MESE-61", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MAEE-2", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MESE-62", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "MTTM",
    title: "Master of Tourism and Travel Management",
    name: "MTTM",
    fullName: "Master of Tourism and Travel Management",
    degree: Degree.masters,
    termType: TermType.Semester,
    termsCount: 4,
    collegeCode: "IGNOU",
    schoolCode: "SOTHSM",
    totalCredits: 68,
    programmeStructure: [
      { term: 1, courseCode: "MTTM-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTTM-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTTM-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTTM-4", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MTTM-5", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MTTM-6", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MTTM-7", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MTTM-8", category: Category.NONE, credit: 4 },

      { term: 3, courseCode: "MTTM-9", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MTTM-10", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MTTM-11", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MTTM-16", category: Category.NONE, credit: 4 },

      { term: 4, courseCode: "MTTM-12", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MTTM-13", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MTTM-14", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MTTM-115", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "MAPY",
    title: "Master of Arts (Philosophy)",
    name: "MAPY",
    fullName: "Master of Arts (Philosophy)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOITS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MPY-1", category: Category.C, credit: 8 },
      { term: 1, courseCode: "MPYE-1", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MPYE-2", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MPYE-3", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MPYE-4", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MPYE-5", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MPYE-6", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MPYE-7", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MGP-5", category: Category.E, credit: 4 },

      { term: 2, courseCode: "MPY-2", category: Category.C, credit: 8 },
      { term: 2, courseCode: "MPYE-8", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-9", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-10", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-11", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-12", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-13", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-14", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-15", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYE-16", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MPYP-1", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "MSCENV",
    title: "Master of Science (Environmental Science)",
    name: "MSCENV",
    fullName: "Master of Science (Environmental Science)",
    degree: Degree.masters,
    termType: TermType.Semester,
    termsCount: 4,
    collegeCode: "IGNOU",
    schoolCode: "SOITS",
    totalCredits: 72,
    programmeStructure: [
      { term: 1, courseCode: "MEV-11", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-12", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-13", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEVL-11", category: Category.C, credit: 4 },

      { term: 2, courseCode: "MEV-14", category: Category.C, credit: 4 },
      { term: 2, courseCode: "MEV-15", category: Category.C, credit: 4 },
      { term: 2, courseCode: "MEV-16", category: Category.C, credit: 4 },
      { term: 2, courseCode: "MEVL-12", category: Category.C, credit: 4 },

      { term: 3, courseCode: "MEV-17", category: Category.C, credit: 4 },
      { term: 3, courseCode: "MEV-18", category: Category.C, credit: 4 },
      { term: 3, courseCode: "MEV-19", category: Category.C, credit: 4 },
      { term: 3, courseCode: "MEVL-13", category: Category.C, credit: 4 },

      { term: 4, courseCode: "MEVP-11", category: Category.C, credit: 8 },

      { term: 0, courseCode: "MEVE-11", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-12", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-13", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-14", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-15", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-16", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-17", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-18", category: Category.E, credit: 4 },
      { term: 0, courseCode: "MEVE-19", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "MAFCS",
    title: "Master of Arts (Folklore and Culture Studies)",
    name: "MAFCS",
    fullName: "Master of Arts (Folklore and Culture Studies)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOITS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MFC-001", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFC-002", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFC-003", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFC-004", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFCP-005", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MFC-006", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MFC-007", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MFC-008", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MFC-009", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MADVS",
    title: "Master of Arts (Development Studies)",
    name: "MADVS",
    fullName: "Master of Arts (Development Studies)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOEDS",
    totalCredits: 72,
    programmeStructure: [
      { term: 1, courseCode: "MDV-101", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-102", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-103", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-106", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-109", category: Category.NONE, credit: 6 },

      { term: 2, courseCode: "MDV-105", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDV-108", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDV-110", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDV-111", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDV-115", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MEDS-41", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MEDS-42", category: Category.NONE, credit: 6 },
      { term: 2, courseCode: "MDVP-117", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "MAWGS",
    title: "Master of Arts (Women and Gender Studies)",
    name: "MAWGS",
    fullName: "Master of Arts (Women and Gender Studies)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOGDS",
    totalCredits: 66,
    programmeStructure: [
      { term: 1, courseCode: "MWG-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MWG-2", category: Category.NONE, credit: 8 },

      { term: 2, courseCode: "MWG-3", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MWG-4", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MWGP-1", category: Category.NONE, credit: 2 },

      { term: 31, courseCode: "MWG-5", category: Category.NONE, credit: 8 },
      { term: 31, courseCode: "MWG-6", category: Category.NONE, credit: 8 },

      { term: 41, courseCode: "MWG-7", category: Category.NONE, credit: 8 },
      { term: 41, courseCode: "MWG-8", category: Category.NONE, credit: 8 },

      { term: 32, courseCode: "MWG-5", category: Category.NONE, credit: 8 },
      { term: 32, courseCode: "MWG-9", category: Category.NONE, credit: 8 },

      { term: 42, courseCode: "MWG-10", category: Category.NONE, credit: 8 },
      { term: 42, courseCode: "MWG-11", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "MAGD",
    title: "Master of Arts (Gender and Development Studies)",
    name: "MAGD",
    fullName: "Master of Arts (Gender and Development Studies)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOGDS",
    totalCredits: 72,
    programmeStructure: [
      { term: 1, courseCode: "MGS-1", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MGS-2", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MGS-3", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MGS-4", category: Category.C, credit: 8 },
      { term: 1, courseCode: "MGS-5", category: Category.C, credit: 8 },
      { term: 1, courseCode: "MGSP-1", category: Category.C, credit: 4 },

      { term: 2, courseCode: "MGSP-2", category: Category.C, credit: 4 },
      { term: 2, courseCode: "MGSE-1", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-2", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-3", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-4", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-6", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-7", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-9", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-10", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-13", category: Category.E, credit: 4 },
      { term: 2, courseCode: "MGSE-20", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "MATS",
    title: "Master of Arts (Translation Studies)",
    name: "MATS",
    fullName: "Master of Arts (Translation Studies)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOTST",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MTT-10", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-14", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-15", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-16", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-17", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MTT-18", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MTT-19", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MTT-20", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MTT-21", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MTTP-22", category: Category.NONE, credit: 16 },
    ],
  },
  {
    code: "MSCMACS",
    title: "Master of Science (Mathematics with Application in Computer Science)",
    name: "MSCMACS",
    fullName: "Master of Science (Mathematics with Application in Computer Science)",
    degree: Degree.masters,
    termType: TermType.Semester,
    termsCount: 4,
    collegeCode: "IGNOU",
    schoolCode: "SOS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MMT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MMT-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MMT-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MMT-5", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MMT-7", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MMT-3", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MMT-6", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MMT-8", category: Category.NONE, credit: 8 },

      { term: 3, courseCode: "MMT-9", category: Category.NONE, credit: 2 },
      { term: 3, courseCode: "MMTE-1", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MMTE-2", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MMTE-3", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MMTE-4", category: Category.NONE, credit: 2 },

      { term: 4, courseCode: "MMTE-5", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MMTE-6", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MMTE-7", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MMTP-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "MAJMC",
    title: "Master of Arts (Journalism and Mass Communication)",
    name: "MAJMC",
    fullName: "Master of Arts (Journalism and Mass Communication)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOJNMS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MJM-20", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-21", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-22", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-23", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-24", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-25", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJML-20", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJML-21", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MJM-26", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MJM-27", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MJM-28", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MJM-29", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MJM-30", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MJM-31", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MJML-22", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MJMP-20", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "MADP",
    title: "Master of Arts (Drawing and Painting)",
    name: "MADP",
    fullName: "Master of Arts (Drawing and Painting)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOPVA",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MVA-020", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVAL-021", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVAL-022", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVA-023", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVAL-024", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVAL-025", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MVA-026", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MVAL-027", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MVAL-028", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MVA-029", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MVAL-030", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MVAL-031", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "MSCIS",
    title: "Master of Science (Information Security)",
    name: "MSCIS",
    fullName: "Master of Science (Information Security)",
    degree: Degree.masters,
    termType: TermType.Semester,
    termsCount: 4,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MSEI-021", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSEI-022", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSEI-023", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSE-024", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MSEI-025", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSEI-026", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSEI-027", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSEP-028", category: Category.NONE, credit: 4 },

      { term: 3, courseCode: "MSE-029", category: Category.NONE, credit: 2 },
      { term: 3, courseCode: "MSE-030", category: Category.NONE, credit: 2 },
      { term: 3, courseCode: "MSE-031", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MCS-226", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MSEL-032", category: Category.NONE, credit: 4 },

      { term: 4, courseCode: "MSE-033", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MSE-034", category: Category.NONE, credit: 2 },
      { term: 4, courseCode: "MSE-035", category: Category.NONE, credit: 2 },
      { term: 4, courseCode: "MSE-036", category: Category.NONE, credit: 2 },
      { term: 4, courseCode: "MSEL-037", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MSEP-038", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "MAER",
    title: "MASTER OF ARTS (ENTREPRENEURSHIP)",
    name: "MAER",
    fullName: "MASTER OF ARTS (ENTREPRENEURSHIP)",
    degree: Degree.masters,
    termType: TermType.Year,
    termsCount: 2,
    collegeCode: "IGNOU",
    schoolCode: "SOVET",
    totalCredits: 64,
    programmeStructure: [
      { term: 1, courseCode: "MER-001", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MER-002", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MER-003", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MER-004", category: Category.NONE, credit: 4 },

      { term: 2, courseCode: "MER-005", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MER-006", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MER-007", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MER-008", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MERP-001", category: Category.NONE, credit: 4 },

      { term: 3, courseCode: "MER-009", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MER-010", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MER-011", category: Category.NONE, credit: 4 },
      { term: 3, courseCode: "MER-012", category: Category.NONE, credit: 4 },

      { term: 4, courseCode: "MER-013", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MER-014", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MER-015", category: Category.NONE, credit: 4 },
      { term: 4, courseCode: "MERP-002", category: Category.NONE, credit: 4 },
    ],
  },
];
