export const mastersDegreeProgrammes = [
  {
    code: "MCOM",
    title: "Master of Commerce",
    name: "MCOM",
    fullName: "Master of Commerce",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MEG",
    title: "Master of Arts (English)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAUD",
    title: "Master of Arts (Urdu)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MPS",
    title: "Master of Arts (Political Science)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MSO",
    title: "Master of Arts (Sociology)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAPC",
    title: "Master of Arts (Psychology)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MEC",
    title: "Master of Arts (Economics)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MPA",
    title: "Master of Arts (Public Administration)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MLIS",
    title: "Master of Library and Information Sciences",
    name: "MLIS",
    fullName: "Master of Library and Information Sciences",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAAN",
    title: "Master of Arts (Anthropology)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MGPS",
    title: "Master of Arts (Gandhi and Peace Studies)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MCA_NEW",
    title: "Master of Computer Applications",
    name: "MCA_NEW",
    fullName: "Master of Computer Applications",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MARD",
    title: "Master of Arts (Rural Development)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MSCCFT",
    title: "Master of Science (Counselling and Family Therapy)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MSW",
    title: "Master of Social Work",
    name: "MSW",
    fullName: "Master of Social Work",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MSWC",
    title: "Master of Social Work (Counselling)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAEDU",
    title: "Master of Arts (Education)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MADE",
    title: "Master of Arts (Distance Education)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAAE",
    title: "Master of Arts (Adult Education)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MTTM",
    title: "Master of Tourism and Travel Management",
    name: "MTTM",
    fullName: "Master of Tourism and Travel Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAPY",
    title: "Master of Arts (Philosophy)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MSCENV",
    title: "Master of Science (Environmental Science)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAFCS",
    title: "Master of Arts (Folklore and Culture Studies)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MADVS",
    title: "Master of Arts (Development Studies)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAWGS",
    title: "Master of Arts (Women and Gender Studies)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAGD",
    title: "Master of Arts (Gender and Development Studies)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MATS",
    title: "Master of Arts (Translation Studies)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MSCMACS",
    title:
      "Master of Science (Mathematics with Application in Computer Science)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAJMC",
    title: "Master of Arts (Journalism and Mass Communication)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MADP",
    title: "Master of Arts (Drawing and Painting)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MSCIS",
    title: "Master of Science (Information Security)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "MAER",
    title: "MASTER OF ARTS (ENTREPRENEURSHIP)",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
];
