export const pgGraduateDiplomaProgrammes = [
  {
    code: "PGDRD",
    title: "Post Graduate Diploma in Rural Development",
    name: "PGDRD",
    fullName: "Post Graduate Diploma in Rural Development",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDCFT",
    title: "Post Graduate Diploma in Counselling and Family Therapy",
    name: "PGDCFT",
    fullName: "Post Graduate Diploma in Counselling and Family Therapy",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDT",
    title: "Post Graduate Diploma in Translation",
    name: "PGDT",
    fullName: "Post Graduate Diploma in Translation",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDIBO",
    title: "Post Graduate Diploma in International Business Operations",
    name: "PGDIBO",
    fullName: "Post Graduate Diploma in International Business Operations",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDAST",
    title: "Post Graduate Diploma in AppliedStatistics",
    name: "PGDAST",
    fullName: "Post Graduate Diploma in AppliedStatistics",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDESD",
    title: "Post Graduate Diploma in Environment and Sustainable Development",
    name: "PGDESD",
    fullName:
      "Post Graduate Diploma in Environment and Sustainable Development",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDAC",
    title: "Post Graduate Diploma in Analytical Chemistry",
    name: "PGDAC",
    fullName: "Post Graduate Diploma in Analytical Chemistry",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDDM",
    title: "Post Graduate Diploma in Disaster Management",
    name: "PGDDM",
    fullName: "Post Graduate Diploma in Disaster Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDMH",
    title: "Post Graduate Diploma in Mental Health",
    name: "PGDMH",
    fullName: "Post Graduate Diploma in Mental Health",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDLAN",
    title: "Post Graduate Diploma in Library Automation and Networking",
    name: "PGDLAN",
    fullName: "Post Graduate Diploma in Library Automation and Networking",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDGPS",
    title: "Post Graduate Diploma in Gandhi and Peace Studies",
    name: "PGDGPS",
    fullName: "Post Graduate Diploma in Gandhi and Peace Studies",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDHE",
    title: "Post Graduate Diploma in Higher Education",
    name: "PGDHE",
    fullName: "Post Graduate Diploma in Higher Education",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDET",
    title: "Post Graduate Diploma in Educational Technology",
    name: "PGDET",
    fullName: "Post Graduate Diploma in Educational Technology",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDSLM",
    title: "Post Graduate Diploma in School Leadership and Management",
    name: "PGDSLM",
    fullName: "Post Graduate Diploma in School Leadership and Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDEMA",
    title: "Post Graduate Diploma in Educational Management and Administration",
    name: "PGDEMA",
    fullName:
      "Post Graduate Diploma in Educational Management and Administration",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDPPED",
    title: "Post Graduate Diploma in Pre Primary Education",
    name: "PGDPPED",
    fullName: "Post Graduate Diploma in Pre Primary Education",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDAE",
    title: "Post Graduate Diploma in Adult Education",
    name: "PGDAE",
    fullName: "Post Graduate Diploma in Adult Education",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDUPDL",
    title: "Post Graduate Diploma in Urban Planning and Development",
    name: "PGDUPDL",
    fullName: "Post Graduate Diploma in Urban Planning and Development",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDDVS",
    title: "Post Graduate Diploma in Development Studies",
    name: "PGDDVS",
    fullName: "Post Graduate Diploma in Development Studies",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDAW",
    title: "Post Graduate Diploma in Animal Welfare",
    name: "PGDAW",
    fullName: "Post Graduate Diploma in Animal Welfare",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDCSR",
    title: "Post Graduate Diploma in Corporate Social Responsibility",
    name: "PGDCSR",
    fullName: "Post Graduate Diploma in Corporate Social Responsibility",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGJMC",
    title: "Post Graduate Diploma in Journalism and Mass Communication",
    name: "PGJMC",
    fullName: "Post Graduate Diploma in Journalism and Mass Communication",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDAPP",
    title: "Post Graduate Diploma in Audio Programme Production",
    name: "PGDAPP",
    fullName: "Post Graduate Diploma in Audio Programme Production",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDIDM",
    title: "Post Graduate Diploma in Digital Media",
    name: "PGDIDM",
    fullName: "Post Graduate Diploma in Digital Media",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDDC",
    title: "Post Graduate Diploma in Development Communication",
    name: "PGDDC",
    fullName: "Post Graduate Diploma in Development Communication",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDFSQM",
    title: "Post Graduate Diploma in Food Safety and Quality Management",
    name: "PGDFSQM",
    fullName: "Post Graduate Diploma in Food Safety and Quality Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDIS",
    title: "Post Graduate Diploma in Information Security",
    name: "PGDIS",
    fullName: "Post Graduate Diploma in Information Security",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDPSM",
    title: "Post Graduate Diploma in Pharmaceutical Sales Management",
    name: "PGDPSM",
    fullName: "Post Graduate Diploma in Pharmaceutical Sales Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDIPR",
    title: "Post Graduate Diploma in Intellectual Property Rights",
    name: "PGDIPR",
    fullName: "Post Graduate Diploma in Intellectual Property Rights",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDCJ",
    title: "Post Graduate Diploma in Criminal Justice",
    name: "PGDCJ",
    fullName: "Post Graduate Diploma in Criminal Justice",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDEOH",
    title: "Post Graduate Diploma in Environmental and Occupational Health",
    name: "PGDEOH",
    fullName: "Post Graduate Diploma in Environmental and Occupational Health",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDFCS",
    title: "Post Graduate Diploma in Folklore and Culture Studies",
    name: "PGDFCS",
    fullName: "Post Graduate Diploma in Folklore and Culture Studies",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDSS",
    title: "Post Graduate Diploma in Sustainability Science",
    name: "PGDSS",
    fullName: "Post Graduate Diploma in Sustainability Science",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDWGS",
    title: "Post Graduate Diploma in Women’s & Gender Studies",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDBP",
    title: "Post Graduate Diploma in Book Publishing",
    name: "PGDBP",
    fullName: "Post Graduate Diploma in Book Publishing",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDCOUN",
    title: "Post Graduate Diploma in Social Work Counselling",
    name: "PGDCOUN",
    fullName: "Post Graduate Diploma in Social Work Counselling",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDHHM",
    title: "Post Graduate Diploma in Hospital and Health Management",
    name: "PGDHHM",
    fullName: "Post Graduate Diploma in Hospital and Health Management",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDGM",
    title: "Post Graduate Diploma in Geriatric Medicine",
    name: "PGDGM",
    fullName: "Post Graduate Diploma in Geriatric Medicine",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDMCH",
    title: "Post Graduate Diploma in Maternal and Child Health",
    name: "PGDMCH",
    fullName: "Post Graduate Diploma in Maternal and Child Health",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDHIVM",
    title: "Post Graduate Diploma in HIV Medicine",
    name: "PGDHIVM",
    fullName: "Post Graduate Diploma in HIV Medicine",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGDCA_NEW",
    title: "Post Graduate Diploma inComputerApplications",
    name: "PGDCA_NEW",
    fullName: "Post Graduate Diploma inComputerApplications",
    degree: 1,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
];
