import { Category, Degree, TermType } from "../../constants/types";

export const pgGraduateDiplomaProgrammes = [
  {
    code: "PGDRD",
    title: "Post Graduate Diploma in Rural Development",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s Degree",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 2,400/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 30,
    programmeStructure: [
      { term: 1, courseCode: "MRD-101", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MRD-102", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MRD-103", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MRDE-101", category: Category.E, credit: 6 },
      { term: 1, courseCode: "RDD-6", category: Category.E, credit: 6 },
      { term: 1, courseCode: "RDD-7", category: Category.E, credit: 6 },
      { term: 1, courseCode: "RDD-5", category: Category.C, credit: 6 },
    ],
  },
  {
    code: "PGDCFT",
    title: "Post Graduate Diploma in Counselling and Family Therapy",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "achelor’s degree in any subject from a recognized University.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admissions",
    feeStructure: "Rs. 16,800/- for full programme",
    schoolCode: "SOCE",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MCFT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-4", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFT-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCFTL-5", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCFTL-8", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "PGDT",
    title: "Post Graduate Diploma in Translation",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s Degree",
    mediumOfInstruction: "Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 4,000/- for full programme",
    schoolCode: "SOTST",
    totalCredits: 30,
    programmeStructure: [
      { term: 1, courseCode: "PGDT-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "PGDT-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "PGDT-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "PGDT-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "PGDT-5", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDIBO",
    title: "Post Graduate Diploma in International Business Operations",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s Degree in any discipline or equivalent.",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 8,200/- for full programme",
    schoolCode: "PGDIBO",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "IBO-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-5", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "IBO-6", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDAST",
    title: "Post Graduate Diploma in AppliedStatistics",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs.7,600/- for full programme.",
    schoolCode: "SOS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MST-1", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MST-2", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MST-3", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MST-4", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MST-5", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MSTL-1", category: Category.C, credit: 2 },
      { term: 1, courseCode: "MSTE-1", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MSTE-2", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MSTL-2", category: Category.E, credit: 2 },
    ],
  },
  {
    code: "PGDESD",
    title: "Post Graduate Diploma in Environment and Sustainable Development",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate from a recognized University/Institution",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 7,000/- for full programme",
    schoolCode: "SOS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MED-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-8", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDAC",
    title: "Post Graduate Diploma in Analytical Chemistry",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Science Graduate with Chemistry or B. Pharma.or B.Tech. degree holders.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 9,600/- for full programme",
    schoolCode: "SOS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MCH-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MCH-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MCH-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MCH-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MCHL-1", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCHL-2", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCHL-3", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCHL-4", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "PGDDM",
    title: "Post Graduate Diploma in Disaster Management",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 6,300/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MPA-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPA-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPA-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPA-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPA-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPA-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPA-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MPAP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MED-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDMH",
    title: "Post Graduate Diploma in Mental Health",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "I. Post graduates in Psychology/Social Work/Nursing OR II. Medical graduates (Allopathy/Homoeopathy/Ayurvedic/Unani/Siddha/ Yoga and Naturopathy/Bachelor’s Degree in Dental Surgery (BDS)",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years. Admission cycle will be once a year in July.",
    feeStructure: "Rs.8,000/-For Full Programme",
    schoolCode: "SOSS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MPC-51", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MPC-52", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MPC-53", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MPC-54", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MPCA-55", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "PGDLAN",
    title: "Post Graduate Diploma in Library Automation and Networking",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s Degree in Library and Information Science",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 17,000/- for full programme",
    schoolCode: "PGDLAN",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MLI-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIL-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLI-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIL-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLI-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIL-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLI-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIL-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLI-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIL-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLI-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIL-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLI-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIL-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLIP-8", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDGPS",
    title: "Post Graduate Diploma in Gandhi and Peace Studies",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline.",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs.3,700/- for full programme",
    schoolCode: "SOSS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MGP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGP-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGP-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGP-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-6", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-9", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-14", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDHE",
    title: "Post Graduate Diploma in Higher Education",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Teachers in an institution of higher education or Post Graduate Degree holders in any subject including a Professional Degree",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 3,000/- for full programme",
    schoolCode: "SOE",
    totalCredits: 34,
    programmeStructure: [
      { term: 1, courseCode: "MES-101", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-102", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-103", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-104", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-105", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-106", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDET",
    title: "Post Graduate Diploma in Educational Technology",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 6,600/- for full programme",
    schoolCode: "SOE",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MES-131", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-32", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-133", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-134", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MESP-135", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "PGDSLM",
    title: "Post Graduate Diploma in School Leadership and Management",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "i) Prospective and In-service Head Teachers/Principal with Graduate Degree from a recognized University OR ii) Graduate /Post Graduate Teachers",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 6,000/- for full programme",
    schoolCode: "SOE",
    totalCredits: 30,
    programmeStructure: [
      { term: 1, courseCode: "MES-004", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-005", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-006", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-007", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-008", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDEMA",
    title: "Post Graduate Diploma in Educational Management and Administration",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 7,000/- for full programme",
    schoolCode: "SOE",
    totalCredits: 34,
    programmeStructure: [
      { term: 1, courseCode: "MES-41", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MES-42", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MES-43", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MES-44", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MESP-49", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MES-45", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MES-46", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MES-47", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MES-48", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "PGDPPED",
    title: "Post Graduate Diploma in Pre Primary Education",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 9,600/- for full programme",
    schoolCode: "SOE",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MES-81", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MES-82", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MES-83", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MES-84", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MESP-85", category: Category.NONE, credit: 16 },
    ],
  },
  {
    code: "PGDAE",
    title: "Post Graduate Diploma in Adult Education",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor's Degree from any recognised University",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admission.",
    feeStructure: "Rs.6,500/- for full programme",
    schoolCode: "SOE",
    totalCredits: 34,
    programmeStructure: [
      { term: 1, courseCode: "MAE-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAE-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAE-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MES-16", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAEL-1", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "PGDUPDL",
    title: "Post Graduate Diploma in Urban Planning and Development",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs.6,000/- for full programme",
    schoolCode: "SOEDS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MEDS-41", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MEDS-42", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MEDS-43", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MEDS-44", category: Category.C, credit: 6 },
      { term: 1, courseCode: "MEDSP-45", category: Category.E, credit: 8 },
      { term: 1, courseCode: "MEDSE-46", category: Category.E, credit: 8 },
    ],
  },
  {
    code: "PGDDVS",
    title: "Post Graduate Diploma in Development Studies",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 5,000/- for full programme",
    schoolCode: "SOEDS",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "MDV-101", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-102", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-103", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-106", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-109", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDV-4", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDAW",
    title: "Post Graduate Diploma in Animal Welfare",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline from a recognized university.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs.5400/- for full programme",
    schoolCode: "SOEDS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MAW-001", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAW-002", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAW-003", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MAW-004", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "PGDCSR",
    title: "Post Graduate Diploma in Corporate Social Responsibility",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 7000/- for full programme",
    schoolCode: "SOEDS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MEDS-051", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEDS-052", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEDS-053", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEDS-054", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MEDSE-046", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MEDSP-051", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "PGJMC",
    title: "Post Graduate Diploma in Journalism and Mass Communication",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Bachelor’s Degree in any subject. The learners should possess working knowledge of computers- MS Office and other simple software and should have internet access",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 12,500/- for full programme and is payable in one installment.",
    schoolCode: "SOJNMS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MJM-20", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-21", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-22", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-23", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-24", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJM-25", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJML-20", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJML-21", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDAPP",
    title: "Post Graduate Diploma in Audio Programme Production",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 10,600/- for full programme",
    schoolCode: "SOJNMS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MJM-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MJM-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MJM-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MJML-1", category: Category.NONE, credit: 16 },
    ],
  },
  {
    code: "PGDIDM",
    title: "Post Graduate Diploma in Digital Media",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s degree in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 5000/- for full programme",
    schoolCode: "SOJNMS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MNM-011", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNM-012", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNM-013", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNM-014", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNM-015", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNML-011", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MNMP-011", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDDC",
    title: "Post Graduate Diploma in Development Communication",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor’s Degree in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 5000/- for full programme and is payable in one installment.",
    schoolCode: "SOJNMS",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "MDC-001", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDC-002", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDC-003", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDC-004", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDC-005", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDCE-006", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MDCP-007", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDFSQM",
    title: "Post Graduate Diploma in Food Safety and Quality Management",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Graduation in Science with Chemistry/ Bio-Chemistry or Microbiology as one of the subjects. OR Degree in allied Sciences like Agriculture/Food Science/Food Technology/Post Harvest Technology/Engineering/ Home Science/Life Science/Microbiology/Biochemistry/Biotechnology/Horticulture/Dairy Technology/Veterinary/ Fisheries/ Hotel Management and Catering/ Hospitality Management, or equivalent etc. OR Science graduate in disciplines like Geography, Statistics with Physics & Maths, Art Subjects and Medical Lab technology and with minimum three years experience in food processing and / or quality control. These students should have minimum 1 year experience in quality control activities. OR Arts/Commerce graduate with diploma in food science/ hotel management disciplines viz fruits and vegetables, dairy technology, meat technology, cereals, pulses and oilseeds etc. with minimum 5 years experience in Food Processing/ Food Quality Control/ Hotel Management (food preparation/ food catering) and out of which 2 years experience should be in quality controlactivities. OR BA/B.Com graduates with minimum 7 years experience in Food Processing/Food Quality Control/Hotel Management (food preparation/ food catering) or holding senior position in Govt./ Semi Govt. Units involved in Food Quality Control.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in July cycle of admission.",
    feeStructure: "Rs.14,400/- for full programme",
    schoolCode: "SOA",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MVP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVPI-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVP-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVP-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVP-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVPL-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVPL-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVPP-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDIS",
    title: "Post Graduate Diploma in Information Security",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Semester,
    termsCount: 2,
    collegeCode: "IGNOU",
    eligibility:
      "B.Sc. (Computer Science)/ BCA/ B.Tech (Computer Sc.)/ B.Tech (IT) or its equivalent. OR Bachelor Degree in any discipline or its equivalent from a recognized university / Institute with CIT/CIC/ACISE/ CISE from IGNOU or a Certificate in Computer Science/ Computer Application from a Govt. recognized institute with a minimum duration of 6 months or studied Computer Course as a part of the curriculum in Bachelor/PG Degree OR Bachelor Degree in any discipline or its equivalent from the recognized university/ institute with 1 year working experience in Computer Application/IT",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs.21,600/- for full programme to be paid semester wise @Rs. 10,800/- per semester",
    schoolCode: "SOVET",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MSEI-21", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSEI-22", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSEI-23", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSE-24", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSEI-25", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSEI-26", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSEI-27", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MSEP-28", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDPSM",
    title: "Post Graduate Diploma in Pharmaceutical Sales Management",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Graduate degree in any discipline with Science in 10+2. OR Graduate degree in any discipline without Science in 10+2 but with 2 years of working experience as a medical representative in a pharma industry.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 7,400/- for full programme",
    schoolCode: "SOVET",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MVE-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MVE-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MVE-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVE-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVE-5", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MVE-6", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDIPR",
    title: "Post Graduate Diploma in Intellectual Property Rights",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 10,200/- for full programme.",
    schoolCode: "SOL",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MIP-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIP-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIP-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIP-104", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIP-105", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIP-106", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIP-107", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIP-108", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDCJ",
    title: "Post Graduate Diploma in Criminal Justice",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Any Graduate, Graduate in Criminology, Social Work & Functionaries of Criminal Justice Administration.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 10,800/- for full programme",
    schoolCode: "SOL",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MLE-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLE-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLE-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLE-14", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLE-15", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLE-16", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MLEP-17", category: Category.NONE, credit: 8 },
    ],
  },
  {
    code: "PGDEOH",
    title: "Post Graduate Diploma in Environmental and Occupational Health",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline with Science at 10+2 level",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 5,900/- for full Programme",
    schoolCode: "SOITS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MEV-1", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-2", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-3", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-4", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-5", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEVP-1", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEVE-1", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MEVE-2", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MEVE-3", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MEVE-4", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "PGDFCS",
    title: "Post Graduate Diploma in Folklore and Culture Studies",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduate in any discipline.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 2,400/- for full programme",
    schoolCode: "SOITS",
    totalCredits: 30,
    programmeStructure: [
      { term: 1, courseCode: "MFC-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFC-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFC-3", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFC-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MFCI-5", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDSS",
    title: "Post Graduate Diploma in Sustainability Science",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Any Bachelor’s Degree from a recognised University",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs.6,200/- for full programme",
    schoolCode: "SOITS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MSD-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSD-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSD-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSD-14", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSD-15", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSD-16", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSD-17", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSDP-18", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGDWGS",
    title: "Post Graduate Diploma in Women’s & Gender Studies",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Semester,
    termsCount: 2,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure:
      "Rs. 6,400/- for full programme fee, to be paid on annual basis (first and second semester registration together)",
    schoolCode: "SOGDS",
    totalCredits: 34,
    programmeStructure: [
      { term: 1, courseCode: "MWG-1", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MWG-2", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MWG-3", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MWG-4", category: Category.NONE, credit: 8 },
      { term: 2, courseCode: "MWGP-1", category: Category.NONE, credit: 2 },
    ],
  },
  {
    code: "PGDBP",
    title: "Post Graduate Diploma in Book Publishing",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Bachelor Degree + knowledge of English & knowledge of word processing",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs.9,000/- for full programme",
    schoolCode: "SOH",
    totalCredits: 30,
    programmeStructure: [
      { term: 1, courseCode: "MBP-001", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MBP-002", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MBP-003", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MBP-004", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MBPP-001", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MBPA-001", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MBP-005", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MBP-006", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MBP-007", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "PGDCOUN",
    title: "Post Graduate Diploma in Social Work Counselling",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "Graduation in any discipline from a recognized university.",
    mediumOfInstruction: "English and Hindi",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure: "Rs. 13,200/- for full programme fee.",
    schoolCode: "SOSW",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "MSW-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-14", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-15", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSW-16", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MSWL-11", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "PGDHHM",
    title: "Post Graduate Diploma in Hospital and Health Management",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "Medical/Dental graduates from a Medical/Dental Institutes of India or other countries recognized by Medical Council of India (MCI) or Dental Council. OR Graduates in Indian System of Medicine (ISM) and Homeopathy, Nursing & Pharmacy recognized by there spective Council with three years of hospital experience. OR Candidates holding MBA degree or PG Diploma in Financial, Material or Personnel Management with five years hospital experience.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in January cycle of admissions.",
    feeStructure: "Rs.25,200/- for full programme.",
    schoolCode: "SOHS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "PGDHHM-1", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "PGDHHM-2", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "PGDHHM-3", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "PGDHHM-4", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "PGDHHM-5", category: Category.NONE, credit: 5 },
      { term: 1, courseCode: "PGDHHM-6", category: Category.NONE, credit: 5 },
    ],
  },
  {
    code: "PGDGM",
    title: "Post Graduate Diploma in Geriatric Medicine",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "MBBS",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in January cycle of admissions.",
    feeStructure: "Rs.26,000/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MME-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MME-5", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MMEL-4", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MMEL-5", category: Category.NONE, credit: 12 },
    ],
  },
  {
    code: "PGDMCH",
    title: "Post Graduate Diploma in Maternal and Child Health",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility:
      "MBBS. For PGDMCH, the experience does not necessarily mean work experience in Government service. It will be counted as period between the date of completion of internship and June 30 of the year in which s/he is applying for admission, irrespective of place of work. PGDMCH is being offered through Programme Study Centre (Medical Colleges) and Skill Development Centres (District Hospitals) which would be allocated by the Regional Centre after finalisation of the admission.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in January cycle of admissions.",
    feeStructure: "Rs.30,000/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "MME-301", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MME-302", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MME-303", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MMEL-301", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MMEL-302", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MMEL-303", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGDHIVM",
    title: "Post Graduate Diploma in HIV Medicine",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Year,
    termsCount: 1,
    collegeCode: "IGNOU",
    eligibility: "MBBS Degree recognized by Medical Council of India (MCI)",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered only in January cycle of admissions",
    feeStructure: "Rs. 60,000/- for full programme",
    schoolCode: "SOHS",
    totalCredits: 36,
    programmeStructure: [
      { term: 1, courseCode: "MCMM-101", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCMM-102", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCMM-103", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCMM-104", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MCMML-105", category: Category.NONE, credit: 8 },
      { term: 1, courseCode: "MCMML-106", category: Category.NONE, credit: 10 },
    ],
  },
  {
    code: "PGDCA_NEW",
    title: "Post Graduate Diploma inComputerApplications",
    degree: Degree.pgGraduateDiploma,
    termType: TermType.Semester,
    termsCount: 2,
    collegeCode: "IGNOU",
    eligibility:
      "Any Bachelor’s degree of minimum 3 (three) year duration from a recognized University AND Mathematics as one of the subject at 10+2 level or Graduation level. OR Any Bachelor’s degree of minimum 3 (three) year duration from a recognized University AND doesn’t have Mathematics as one of the subject at 10+2 level or graduation level. These students are required to successfully complete BCS-012 (Graduate level Mathematics course) as Bridge Course.",
    mediumOfInstruction: "English",
    duration: "Minimum 1 year and Maximum 3 years; offered in both January & July cycle of admissions",
    feeStructure:
      "Rs. 21,600/- for full Programme to be paid semester wise @Rs.10800/- per semester. Non-Maths students have to pay Rs.1400/- additional in the first semester.",
    schoolCode: "SOCIS",
    totalCredits: 32,
    programmeStructure: [
      { term: 1, courseCode: "MCS-201", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCS-202", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCS-203", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MCSL-204", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MCSL-205", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCS-206", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCS-207", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCS-208", category: Category.NONE, credit: 4 },
      { term: 2, courseCode: "MCSL-209", category: Category.NONE, credit: 2 },
      { term: 2, courseCode: "MCSL-210", category: Category.NONE, credit: 2 },
    ],
  },
];
