import { Degree, TermType, Category } from "../../constants/types";

export const pgGraduateCertificateProgrammes = [
  {
    code: "PGCCL",
    title: "Post Graduate Certificate in Cyber Law",
    name: "PGCCL",
    fullName: "Post Graduate Certificate in Cyber Law",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MIR-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIR-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIR-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIR-14", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCPP",
    title: "Post Graduate Certificate in Patent Practice",
    name: "PGCPP",
    fullName: "Post Graduate Certificate in Patent Practice",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOL",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MIR-21", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIR-22", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIR-23", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIRP-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCCC",
    title: "Post Graduate Certificate in Climate Change",
    name: "PGCCC",
    fullName: "Post Graduate Certificate in Climate Change",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOITS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MEV-021", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-022", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-023", category: Category.C, credit: 4 },
      { term: 1, courseCode: "MEV-024", category: Category.E, credit: 4 },
      { term: 1, courseCode: "MEV-025", category: Category.E, credit: 4 },
    ],
  },
  {
    code: "PGCGI",
    title: "Post Graduate Certificate in Geoinformatics",
    name: "PGCGI",
    fullName: "Post Graduate Certificate in Geoinformatics",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MGY-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGY-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGY-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGYL-4", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "ACPDM",
    title: "Advanced Certificate in Power Distribution Management",
    name: "ACPDM",
    fullName: "Advanced Certificate in Power Distribution Management",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOET",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "BEE-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "BEE-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "BEE-3", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGCINDS",
    title: "Post Graduate Certificate in Industrial Safety",
    name: "PGCINDS",
    fullName: "Post Graduate Certificate in Industrial Safety",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOET",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MIS-21", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MIS-22", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MIS-23", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MIS-24", category: Category.NONE, credit: 2 },
      { term: 1, courseCode: "MISP-21", category: Category.NONE, credit: 6 },
    ],
  },
  {
    code: "PGCIPWS",
    title: "Post Graduate Certificate in Inventory Planning and Warehousing for Engineers",
    name: "PGCIPW",
    fullName: "Post Graduate Certificate in Inventory Planning and Warehousing for Engineers",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOET",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MWR-001", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MWR-002", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MWR-003", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MWRP-01", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCAP",
    title: "Post Graduate Certificate in Agriculture Policy",
    name: "PGCAP",
    fullName: "Post Graduate Certificate in Agriculture Policy",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOA",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MNR-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNR-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNRE-15", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MNRE-16", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCGPS",
    title: "Post Graduate Certificate in Gandhi and Peace Studies",
    name: "PGCGPS",
    fullName: "Post Graduate Certificate in Gandhi and Peace Studies",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOSS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MGP-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGP-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-7", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MGPE-8", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCAE",
    title: "Post Graduate Certificate in Adult Education",
    name: "PGCAE",
    fullName: "Post Graduate Certificate in Adult Education",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOE",
    totalCredits: 15,
    programmeStructure: [
      { term: 1, courseCode: "MAE-1", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAE-2", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MAEL-2", category: Category.NONE, credit: 3 },
    ],
  },
  {
    code: "PGCIATIVI",
    title:
      "Post Graduate Certificate in Information and Assistive Technologies for the Instructors of Visually Impaired",
    name: "PGCIATIVI",
    fullName:
      "Post Graduate Certificate in Information and Assistive Technologies for the Instructors of Visually Impaired",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOE",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MVEI-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVEI-12", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVEI-13", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MVEI-14", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCBHT",
    title: "Post Graduate Certificate in Bangla-Hindi Translation",
    name: "PGCBHT",
    fullName: "Post Graduate Certificate in Bangla-Hindi Translation",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOTST",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MTT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-2", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-3", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTTP-1", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCMHT",
    title: "Post Graduate Certificate in Malayalam-Hindi Translation",
    name: "PGCMHT",
    fullName: "Post Graduate Certificate in Malayalam-Hindi Translation",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOTST",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MTT-1", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-4", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTT-5", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MTTP-2", category: Category.NONE, credit: 4 },
    ],
  },
  {
    code: "PGCMDM",
    title: "Post Graduate Certificate in Medical Management of CBRNE Disasters",
    name: "PGCMDM",
    fullName: "Post Graduate Certificate in Medical Management of CBRNE Disasters",
    degree: Degree.pgGraduateCertificate,
    termType: TermType.Semester,
    termsCount: 1,
    collegeCode: "IGNOU",
    schoolCode: "SOHS",
    totalCredits: 16,
    programmeStructure: [
      { term: 1, courseCode: "MME-11", category: Category.NONE, credit: 4 },
      { term: 1, courseCode: "MME-12", category: Category.NONE, credit: 6 },
      { term: 1, courseCode: "MMEL-13", category: Category.NONE, credit: 6 },
    ],
  },
];
