import { Degree } from "../../constants/types";

export const pgGraduateCertificateProgrammes = [
  {
    code: "PGCCL",
    title: "Post Graduate Certificate in Cyber Law",
    name: "PGCCL",
    fullName: "Post Graduate Certificate in Cyber Law",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCPP",
    title: "Post Graduate Certificate in Patent Practice",
    name: "PGCPP",
    fullName: "Post Graduate Certificate in Patent Practice",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCCC",
    title: "Post Graduate Certificate in Climate Change",
    name: "PGCCC",
    fullName: "Post Graduate Certificate in Climate Change",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCGI",
    title: "Post Graduate Certificate in Geoinformatics",
    name: "PGCGI",
    fullName: "Post Graduate Certificate in Geoinformatics",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "ACPDM",
    title: "Advanced Certificate in Power Distribution Management",
    name: "ACPDM",
    fullName: "Advanced Certificate in Power Distribution Management",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCINDS",
    title: "Post Graduate Certificate in Industrial Safety",
    name: "PGCINDS",
    fullName: "Post Graduate Certificate in Industrial Safety",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCIPWS",
    title: "Post Graduate Certificate in Inventory Planning and Warehousing for Engineers",
    name: "PGCIPW",
    fullName: "Post Graduate Certificate in Inventory Planning and Warehousing for Engineers",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCAP",
    title: "Post Graduate Certificate in Agriculture Policy",
    name: "PGCAP",
    fullName: "Post Graduate Certificate in Agriculture Policy",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCGPS",
    title: "Post Graduate Certificate in Gandhi and Peace Studies",
    name: "PGCGPS",
    fullName: "Post Graduate Certificate in Gandhi and Peace Studies",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCAE",
    title: "Post Graduate Certificate in Adult Education",
    name: "PGCAE",
    fullName: "Post Graduate Certificate in Adult Education",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCIATIVI",
    title:
      "Post Graduate Certificate in Information and Assistive Technologies for the Instructors of Visually Impaired",
    name: "PGCIATIVI",
    fullName:
      "Post Graduate Certificate in Information and Assistive Technologies for the Instructors of Visually Impaired",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCBHT",
    title: "Post Graduate Certificate in Bangla-Hindi Translation",
    name: "PGCBHT",
    fullName: "Post Graduate Certificate in Bangla-Hindi Translation",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCMHT",
    title: "Post Graduate Certificate in Malayalam-Hindi Translation",
    name: "PGCMHT",
    fullName: "Post Graduate Certificate in Malayalam-Hindi Translation",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
  {
    code: "PGCMDM",
    title: "Post Graduate Certificate in Medical Management of CBRNE Disasters",
    name: "PGCMDM",
    fullName: "Post Graduate Certificate in Medical Management of CBRNE Disasters",
    degree: Degree.pgGraduateCertificate,
    termType: 1,
    termsCount: 6,
    collegeCode: "IGNOU",
  },
];
