export const awarenessAndAppreciationCourses = [
  {
    code: "Module-1",
    title: "Introduction",
    name: "Module-1",
    fullName: "Introduction",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-2",
    title: "Animal Breeding",
    name: "Module-2",
    fullName: "Animal Breeding",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-3",
    title: "Reproduction",
    name: "Module-3",
    fullName: "Reproduction",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-4",
    title: "Calving and Calf Rearing",
    name: "Module-4",
    fullName: "Calving and Calf Rearing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-5",
    title: "Animal Nutrition/Feed and Fodder Management",
    name: "Module-5",
    fullName: "Animal Nutrition/Feed and Fodder Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-6",
    title: "Milk Production",
    name: "Module-6",
    fullName: "Milk Production",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-7",
    title: "Milk Testing, Milk Handling and Storage",
    name: "Module-7",
    fullName: "Milk Testing, Milk Handling and Storage",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-8",
    title: "Animal Housing and Shelter",
    name: "Module-8",
    fullName: "Animal Housing and Shelter",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-9",
    title: "Health Management",
    name: "Module-9",
    fullName: "Health Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-10",
    title: "Animal Disease Prevention and Control",
    name: "Module-10",
    fullName: "Animal Disease Prevention and Control",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-11",
    title: "Disposal of Dung and Dairy Waste Materials",
    name: "Module-11",
    fullName: "Disposal of Dung and Dairy Waste Materials",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-12",
    title: "Dairy Farm Equipment",
    name: "Module-12",
    fullName: "Dairy Farm Equipment",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-13",
    title: "Dairy Farm Economics and Accounting",
    name: "Module-13",
    fullName: "Dairy Farm Economics and Accounting",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "Module-14",
    title: "Role of different Agencies in Dairy Development",
    name: "Module-14",
    fullName: "Role of different Agencies in Dairy Development",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
];
