export const bachelorsHonoursDegreeCourses = [
  {
    code: "BECC-101",
    title: "Introductory Microeconomics",
    name: "BECC-101",
    fullName: "Introductory Microeconomics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-102",
    title: "Mathematical Methods for Economics I",
    name: "BECC-102",
    fullName: "Mathematical Methods for Economics I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-103",
    title: "Introductory Macroeconomics",
    name: "BECC-103",
    fullName: "Introductory Macroeconomics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-104",
    title: "Mathematical Methods for Economics II",
    name: "BECC-104",
    fullName: "Mathematical Methods for Economics II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-105",
    title: "Intermediate Microeconomics I",
    name: "BECC-105",
    fullName: "Intermediate Microeconomics I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-106",
    title: "Intermediate Macroeconomics I",
    name: "BECC-106",
    fullName: "Intermediate Macroeconomics I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-107",
    title: "Statistical Methods for Economics",
    name: "BECC-107",
    fullName: "Statistical Methods for Economics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-108",
    title: "Intermediate Microeconomics II",
    name: "BECC-108",
    fullName: "Intermediate Microeconomics II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-109",
    title: "Intermediate Macroeconomics II",
    name: "BECC-109",
    fullName: "Intermediate Macroeconomics II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-110",
    title: "Introductory Econometrics",
    name: "BECC-110",
    fullName: "Introductory Econometrics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-111",
    title: "Indian Economy I",
    name: "BECC-111",
    fullName: "Indian Economy I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-112",
    title: "Development Economics I",
    name: "BECC-112",
    fullName: "Development Economics I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-113",
    title: "Indian Economy II",
    name: "BECC-113",
    fullName: "Indian Economy II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECC-114",
    title: "Development Economics II",
    name: "BECC-114",
    fullName: "Development Economics II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-101",
    title: "History of India –I",
    name: "BHIC-101",
    fullName: "History of India –I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-102",
    title: "Social Formations and Cultural Patterns of the Ancient World",
    name: "BHIC-102",
    fullName: "Social Formations and Cultural Patterns of the Ancient World",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-103",
    title: "History of India –II",
    name: "BHIC-103",
    fullName: "History of India –II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-104",
    title: "Social Formations and Cultural Patterns of the Medieval World",
    name: "BHIC-104",
    fullName: "Social Formations and Cultural Patterns of the Medieval World",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-105",
    title: "History of India –III ( c. 750 – 1206)",
    name: "BHIC-105",
    fullName: "History of India –III ( c. 750 – 1206)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-106",
    title: "Rise of the Modern West – I",
    name: "BHIC-106",
    fullName: "Rise of the Modern West – I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-107",
    title: "History of India – IV ( c. 1206 – 1550)",
    name: "BHIC-107",
    fullName: "History of India – IV ( c. 1206 – 1550)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-108",
    title: "Rise of the Modern West – II",
    name: "BHIC-108",
    fullName: "Rise of the Modern West – II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-109",
    title: "History of India –V ( c. 1550 – 1605)",
    name: "BHIC-109",
    fullName: "History of India –V ( c. 1550 – 1605)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-110",
    title: "History of India –VI ( c. 1750 – 1857)",
    name: "BHIC-110",
    fullName: "History of India –VI ( c. 1750 – 1857)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-111",
    title: "History of Modern Europe - I ( c. 1780 - 1939)",
    name: "BHIC-111",
    fullName: "History of Modern Europe - I ( c. 1780 - 1939)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-112",
    title: "History of India –VII ( c. 1605 – 1750)",
    name: "BHIC-112",
    fullName: "History of India –VII ( c. 1605 – 1750)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-113",
    title: "History of India –VIII ( c. 1857 – 1950)",
    name: "BHIC-113",
    fullName: "History of India –VIII ( c. 1857 – 1950)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIC-114",
    title: "History of Modern Europe -II ( c. 1780 – 1939)",
    name: "BHIC-114",
    fullName: "History of Modern Europe -II ( c. 1780 – 1939)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-101",
    title: "Perspectives on Public Administration",
    name: "BPAC-101",
    fullName: "Perspectives on Public Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-108",
    title: "Public Policy and Administration in India",
    name: "BPAC-108",
    fullName: "Public Policy and Administration in India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-101",
    title: "Understanding Political Theory",
    name: "BPSC-101",
    fullName: "Understanding Political Theory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-102",
    title: "Constitutional Government and Democracy in India",
    name: "BPSC-102",
    fullName: "Constitutional Government and Democracy in India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-103",
    title: "Political Theory – Concepts and Debates",
    name: "BPSC-103",
    fullName: "Political Theory – Concepts and Debates",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-104",
    title: "Political Process in India",
    name: "BPSC-104",
    fullName: "Political Process in India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-105",
    title: "Introduction to Comparative Government and Politics",
    name: "BPSC-105",
    fullName: "Introduction to Comparative Government and Politics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-107",
    title: "Perspectives on International Relations and World History",
    name: "BPSC-107",
    fullName: "Perspectives on International Relations and World History",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-109",
    title: "Political Processes and Institutions in Comparative Perspective",
    name: "BPSC-109",
    fullName: "Political Processes and Institutions in Comparative Perspective",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-110",
    title: "Global Politics",
    name: "BPSC-110",
    fullName: "Global Politics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-111",
    title: "Classical Political Philosophy",
    name: "BPSC-111",
    fullName: "Classical Political Philosophy",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-112",
    title: "Indian Political Thought-I",
    name: "BPSC-112",
    fullName: "Indian Political Thought-I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-113",
    title: "Modern Political Philosophy",
    name: "BPSC-113",
    fullName: "Modern Political Philosophy",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSC-114",
    title: "Indian Political Thought-II",
    name: "BPSC-114",
    fullName: "Indian Political Thought-II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-101",
    title: "Introduction to Psychology",
    name: "BPCC-101",
    fullName: "Introduction to Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-102",
    title: "Biopsychology",
    name: "BPCC-102",
    fullName: "Biopsychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
  },
  {
    code: "BPCC-103",
    title: "Psychology of Individual Differences",
    name: "BPCC-103",
    fullName: "Psychology of Individual Differences",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-104",
    title: "Statistical Methods for Psychological Research- I",
    name: "BPCC-104",
    fullName: "Statistical Methods for Psychological Research- I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-105",
    title: "Psychological Research",
    name: "BPCC-105",
    fullName: "Psychological Research",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-106",
    title: "Development of Psychological Thought",
    name: "BPCC-106",
    fullName: "Development of Psychological Thought",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-107",
    title: "Social Psychology",
    name: "BPCC-107",
    fullName: "Social Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-108",
    title: "Statistical Methods for Psychological Research - II",
    name: "BPCC-108",
    fullName: "Statistical Methods for Psychological Research - II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-109",
    title: "Developmental Psychology",
    name: "BPCC-109",
    fullName: "Developmental Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-110",
    title: "Applied Social Psychology",
    name: "BPCC-110",
    fullName: "Applied Social Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-111",
    title: "Understanding Psychological Disorders",
    name: "BPCC-111",
    fullName: "Understanding Psychological Disorders",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-112",
    title: "Organizational Behaviour",
    name: "BPCC-112",
    fullName: "Organizational Behaviour",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-113",
    title: "Understanding and Dealing with Psychological Disorders",
    name: "BPCC-113",
    fullName: "Understanding and Dealing with Psychological Disorders",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCC-114",
    title: "Counselling Psychology",
    name: "BPCC-114",
    fullName: "Counselling Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-101",
    title: "Perspectives on Public Administration",
    name: "BPAC-101",
    fullName: "Perspectives on Public Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-102",
    title: "Administrative Thinkers",
    name: "BPAC-102",
    fullName: "Administrative Thinkers",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-103",
    title: "Administrative System at Union Level",
    name: "BPAC-103",
    fullName: "Administrative System at Union Level",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-104",
    title: "Administrative System at State and District Levels",
    name: "BPAC-104",
    fullName: "Administrative System at State and District Levels",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-105",
    title: "Personnel Administration",
    name: "BPAC-105",
    fullName: "Personnel Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-106",
    title: "Understanding Public Policy",
    name: "BPAC-106",
    fullName: "Understanding Public Policy",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-107",
    title: "Comparative Public Administration",
    name: "BPAC-107",
    fullName: "Comparative Public Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-108",
    title: "Public Policy and Administration in India",
    name: "BPAC-108",
    fullName: "Public Policy and Administration in India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-109",
    title: "Public Systems Management",
    name: "BPAC-109",
    fullName: "Public Systems Management",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-110",
    title: "Urban Local Governance",
    name: "BPAC-110",
    fullName: "Urban Local Governance",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-111",
    title: "Public Finance and Administration",
    name: "BPAC-111",
    fullName: "Public Finance and Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-112",
    title: "Rural Local Governance",
    name: "BPAC-112",
    fullName: "Rural Local Governance",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-113",
    title: "Development Administration",
    name: "BPAC-113",
    fullName: "Development Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAC-114",
    title: "Contemporary Issues and Concerns in Indian Administration",
    name: "BPAC-114",
    fullName: "Contemporary Issues and Concerns in Indian Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-101",
    title: "Introduction to Sociology I",
    name: "BSOC-101",
    fullName: "Introduction to Sociology I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-102",
    title: "Sociology of India – I",
    name: "BSOC-102",
    fullName: "Sociology of India – I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-103",
    title: "Introduction to Sociology II",
    name: "BSOC-103",
    fullName: "Introduction to Sociology II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-104",
    title: "Sociology of India - II",
    name: "BSOC-104",
    fullName: "Sociology of India - II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-105",
    title: "Political Sociology",
    name: "BSOC-105",
    fullName: "Political Sociology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-106",
    title: "Sociology of Religion",
    name: "BSOC-106",
    fullName: "Sociology of Religion",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-107",
    title: "Sociology of Gender",
    name: "BSOC-107",
    fullName: "Sociology of Gender",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-108",
    title: "Economic Sociology",
    name: "BSOC-108",
    fullName: "Economic Sociology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-109",
    title: "Sociology of Kinship",
    name: "BSOC-109",
    fullName: "Sociology of Kinship",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-110",
    title: "Social Stratification",
    name: "BSOC-110",
    fullName: "Social Stratification",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-111",
    title: "Sociological Thinkers -I",
    name: "BSOC-111",
    fullName: "Sociological Thinkers -I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-112",
    title: "Sociological Research Methods -I",
    name: "BSOC-112",
    fullName: "Sociological Research Methods -I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-113",
    title: "Sociological Thinkers -II",
    name: "BSOC-113",
    fullName: "Sociological Thinkers -II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOC-114",
    title: "Sociological Research Methods -II",
    name: "BSOC-114",
    fullName: "Sociological Research Methods -II",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECE-141",
    title: "Economics of Health and Education",
    name: "BECE-141",
    fullName: "Economics of Health and Education",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECE-142",
    title: "Applied Econometrics",
    name: "BECE-142",
    fullName: "Applied Econometrics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECE-143",
    title: "Environmental Economics",
    name: "BECE-143",
    fullName: "Environmental Economics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECE-144",
    title: "Financial Economics",
    name: "BECE-144",
    fullName: "Financial Economics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIE-141",
    title: "History of China (C. 1840 – 1978)",
    name: "BHIE-141",
    fullName: "History of China (C. 1840 – 1978)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIE-142",
    title: "History of Modern East Asia: Japan (C. 1868 – 1945)",
    name: "BHIE-142",
    fullName: "History of Modern East Asia: Japan (C. 1868 – 1945)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIE-143",
    title: "History of Environment",
    name: "BHIE-143",
    fullName: "History of Environment",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHIE-144",
    title: "Traditions of History Writing in India",
    name: "BHIE-144",
    fullName: "Traditions of History Writing in India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSE-141",
    title: "Gandhi and the Contemporary World",
    name: "BPSE-141",
    fullName: "Gandhi and the Contemporary World",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSE-142",
    title: "India’s Foreign Policy in a Globalising World",
    name: "BPSE-142",
    fullName: "India’s Foreign Policy in a Globalising World",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSE-143",
    title: "State Politics in India",
    name: "BPSE-143",
    fullName: "State Politics in India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSE-144",
    title: "Introduction to South Asia",
    name: "BPSE-144",
    fullName: "Introduction to South Asia",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSE-145",
    title: "Democracy and Development in Northeast India",
    name: "BPSE-145",
    fullName: "Democracy and Development in Northeast India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPSE-146",
    title: "Conflict Resolution and Peace Building",
    name: "BPSE-146",
    fullName: "Conflict Resolution and Peace Building",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAE-141",
    title: "Right to Information",
    name: "BPAE-141",
    fullName: "Right to Information",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAE-142",
    title: "Organizational Behaviour",
    name: "BPAE-142",
    fullName: "Organizational Behaviour",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAE-143",
    title: "Administrative System in BRICS",
    name: "BPAE-143",
    fullName: "Administrative System in BRICS",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAE-144",
    title: "Social Policies and Administration",
    name: "BPAE-144",
    fullName: "Social Policies and Administration",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCE-141",
    title: "Positive Psychology",
    name: "BPCE-141",
    fullName: "Positive Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCE-142",
    title: "Forensic Psychology",
    name: "BPCE-142",
    fullName: "Forensic Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCE-143",
    title: "Environmental Psychology",
    name: "BPCE-143",
    fullName: "Environmental Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCE-144",
    title: "Dissertation",
    name: "BPCE-144",
    fullName: "Dissertation",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOE-141",
    title: "Urban Sociology",
    name: "BSOE-141",
    fullName: "Urban Sociology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOE-142",
    title: "Indian Sociological Traditions",
    name: "BSOE-142",
    fullName: "Indian Sociological Traditions",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOE-143",
    title: "Environmental Sociology",
    name: "BSOE-143",
    fullName: "Environmental Sociology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOE-144",
    title: "Reading Ethnographies",
    name: "BSOE-144",
    fullName: "Reading Ethnographies",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANE-143",
    title: "Tribal Cultures of India",
    name: "BANE-143",
    fullName: "Tribal Cultures of India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANE-144",
    title: "Visual Anthropology",
    name: "BANE-144",
    fullName: "Visual Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANS-183",
    title: "Tourism Anthropology",
    name: "BANS-183",
    fullName: "Tourism Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANS-184",
    title: "Public Health and Epidemiology",
    name: "BANS-184",
    fullName: "Public Health and Epidemiology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECS-184",
    title: "Data Analysis",
    name: "BECS-184",
    fullName: "Data Analysis",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-183",
    title: "Emotional Intelligence",
    name: "BPCS-183",
    fullName: "Emotional Intelligence",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-184",
    title: "School Psychology",
    name: "BPCS-184",
    fullName: "School Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-185",
    title: "Developing Emotional Competence",
    name: "BPCS-185",
    fullName: "Developing Emotional Competence",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-186",
    title: "Managing Stress",
    name: "BPCS-186",
    fullName: "Managing Stress",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-187",
    title: "Managing Human Resources",
    name: "BPCS-187",
    fullName: "Managing Human Resources",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-188",
    title: "Application of Social Psychology",
    name: "BPCS-188",
    fullName: "Application of Social Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAS-184",
    title: "Logistics Management",
    name: "BPAS-184",
    fullName: "Logistics Management",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAS-186",
    title: "Stress and Time Management",
    name: "BPAS-186",
    fullName: "Stress and Time Management",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOS-184",
    title: "Techniques of Ethnographic Film Making",
    name: "BSOS-184",
    fullName: "Techniques of Ethnographic Film Making",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOS-185",
    title: "Society through the Visual",
    name: "BSOS-185",
    fullName: "Society through the Visual",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDS-183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    name: "BHDS-183",
    fullName: "अनुवाद �सद्धांत और प्र�व�ध",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDS-184",
    title: "रे �डयो लेखन",
    name: "BHDS-184",
    fullName: "रे �डयो लेखन",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGS-183",
    title: "Writing And Study Skills",
    name: "BEGS-183",
    fullName: "Writing And Study Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGS-185",
    title: "English Language Teaching",
    name: "BEGS-185",
    fullName: "English Language Teaching",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGS-186",
    title: "Business Communication",
    name: "BEGS-186",
    fullName: "Business Communication",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BGDG-172",
    title: "Gender Sensitization: Society and Culture",
    name: "BGDG-172",
    fullName: "Gender Sensitization: Society and Culture",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-171",
    title: "General Psychology",
    name: "BPCG-171",
    fullName: "General Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-172",
    title: "Youth, Gender and Identity",
    name: "BPCG-172",
    fullName: "Youth, Gender and Identity",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-173",
    title: "Psychology for Health and Well-being",
    name: "BPCG-173",
    fullName: "Psychology for Health and Well-being",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-174",
    title: "Psychology and Media",
    name: "BPCG-174",
    fullName: "Psychology and Media",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-175",
    title: "Psychology for Living",
    name: "BPCG-175",
    fullName: "Psychology for Living",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-176",
    title: "Psychology of Gender",
    name: "BPCG-176",
    fullName: "Psychology of Gender",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-171",
    title: "Disaster Management",
    name: "BPAG-171",
    fullName: "Disaster Management",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-172",
    title: "Governance: Issues and Challenges",
    name: "BPAG-172",
    fullName: "Governance: Issues and Challenges",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-173",
    title: "E-Governance",
    name: "BPAG-173",
    fullName: "E-Governance",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-174",
    title: "Sustainable Development",
    name: "BPAG-174",
    fullName: "Sustainable Development",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-171",
    title: "Indian Society: Images and Realities",
    name: "BSOG-171",
    fullName: "Indian Society: Images and Realities",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-173",
    title: "Rethinking Development",
    name: "BSOG-173",
    fullName: "Rethinking Development",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-176",
    title: "Economy and Society",
    name: "BSOG-176",
    fullName: "Economy and Society",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDG-173",
    title: "समाचार पत्र और फ�चर लेखन",
    name: "BHDG-173",
    fullName: "समाचार पत्र और फ�चर लेखन",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-171",
    title: "Media and Communication Skills",
    name: "BEGG-171",
    fullName: "Media and Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-172",
    title: "Language and Linguistics",
    name: "BEGG-172",
    fullName: "Language and Linguistics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-173",
    title: "Academic Writing & Composition",
    name: "BEGG-173",
    fullName: "Academic Writing & Composition",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-174",
    title: "Creative Writing",
    name: "BEGG-174",
    fullName: "Creative Writing",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BABG-171",
    title: "Understanding Ambedkar",
    name: "BABG-171",
    fullName: "Understanding Ambedkar",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPYG-171",
    title: "Applied Ethics",
    name: "BPYG-171",
    fullName: "Applied Ethics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPYG-172",
    title: "Philosophy of Religion",
    name: "BPYG-172",
    fullName: "Philosophy of Religion",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-101",
    title: "Introduction to Biological Anthropology",
    name: "BANC-101",
    fullName: "Introduction to Biological Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-102",
    title: "Introduction to Social and Cultural Anthropology",
    name: "BANC-102",
    fullName: "Introduction to Social and Cultural Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-103",
    title: "Archaeological Anthropology",
    name: "BANC-103",
    fullName: "Archaeological Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-104",
    title: "Fundamentals of Human Origin and Evolution",
    name: "BANC-104",
    fullName: "Fundamentals of Human Origin and Evolution",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-105",
    title: "Tribes and Peasants in India",
    name: "BANC-105",
    fullName: "Tribes and Peasants in India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-106",
    title: "Human Ecology: Biological and Cultural Dimensions",
    name: "BANC-106",
    fullName: "Human Ecology: Biological and Cultural Dimensions",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-107",
    title: "Biological Diversity in Human Populations",
    name: "BANC-107",
    fullName: "Biological Diversity in Human Populations",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-108",
    title: "Theories of Culture and Society",
    name: "BANC-108",
    fullName: "Theories of Culture and Society",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-109",
    title: "Human Growth and Development",
    name: "BANC-109",
    fullName: "Human Growth and Development",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-110",
    title: "Research Methods",
    name: "BANC-110",
    fullName: "Research Methods",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-111",
    title: "Human Population Genetics",
    name: "BANC-111",
    fullName: "Human Population Genetics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-112",
    title: "Anthropology in Practice",
    name: "BANC-112",
    fullName: "Anthropology in Practice",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-113",
    title: "Forensic Anthropology",
    name: "BANC-113",
    fullName: "Forensic Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANC-114",
    title: "Anthropology of India",
    name: "BANC-114",
    fullName: "Anthropology of India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANE-141",
    title: "Physiological Anthropology",
    name: "BANE-141",
    fullName: "Physiological Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANE-143",
    title: "Tribal Cultures of India",
    name: "BANE-143",
    fullName: "Tribal Cultures of India",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANE-144",
    title: "Visual Anthropology",
    name: "BANE-144",
    fullName: "Visual Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANE-147",
    title: "Urban Anthropology",
    name: "BANE-147",
    fullName: "Urban Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANE-154",
    title: "Dissertation",
    name: "BANE-154",
    fullName: "Dissertation",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOE-144",
    title: "Reading Ethnographies",
    name: "BSOE-144",
    fullName: "Reading Ethnographies",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEVAE-181",
    title: "Environmental Studies",
    name: "BEVAE-181",
    fullName: "Environmental Studies",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGAE-182",
    title: "English Communication Skills",
    name: "BEGAE-182",
    fullName: "English Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDAE-182",
    title: "�हंद� भाषा और संप्रेषण",
    name: "BHDAE-182",
    fullName: "�हंद� भाषा और संप्रेषण",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANS-183",
    title: "Tourism Anthropology",
    name: "BANS-183",
    fullName: "Tourism Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANS-184",
    title: "Public Health and Epidemiology",
    name: "BANS-184",
    fullName: "Public Health and Epidemiology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BECS-184",
    title: "Data Analysis",
    name: "BECS-184",
    fullName: "Data Analysis",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-183",
    title: "Emotional Intelligence",
    name: "BPCS-183",
    fullName: "Emotional Intelligence",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-184",
    title: "School Psychology",
    name: "BPCS-184",
    fullName: "School Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-185",
    title: "Developing Emotional Competence",
    name: "BPCS-185",
    fullName: "Developing Emotional Competence",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-186",
    title: "Managing Stress",
    name: "BPCS-186",
    fullName: "Managing Stress",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-187",
    title: "Managing Human Resources",
    name: "BPCS-187",
    fullName: "Managing Human Resources",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-188",
    title: "Application of Social Psychology",
    name: "BPCS-188",
    fullName: "Application of Social Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAS-184",
    title: "Logistics Management",
    name: "BPAS-184",
    fullName: "Logistics Management",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAS-186",
    title: "Stress and Time Management",
    name: "BPAS-186",
    fullName: "Stress and Time Management",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOS-184",
    title: "Techniques of Ethnographic Film Making",
    name: "BSOS-184",
    fullName: "Techniques of Ethnographic Film Making",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOS-185",
    title: "Society through the Visual",
    name: "BSOS-185",
    fullName: "Society through the Visual",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDS-183",
    title: "अनुवाद �सद्धांत और प्र�व�ध",
    name: "BHDS-183",
    fullName: "अनुवाद �सद्धांत और प्र�व�ध",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDS-184",
    title: "रे �डयो लेखन",
    name: "BHDS-184",
    fullName: "रे �डयो लेखन",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGS-183",
    title: "Writing And Study Skills",
    name: "BEGS-183",
    fullName: "Writing And Study Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGS-185",
    title: "English Language Teaching",
    name: "BEGS-185",
    fullName: "English Language Teaching",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGS-186",
    title: "Business Communication",
    name: "BEGS-186",
    fullName: "Business Communication",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BGDG-172",
    title: "Gender Sensitization: Society and Culture",
    name: "BGDG-172",
    fullName: "Gender Sensitization: Society and Culture",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-171",
    title: "General Psychology",
    name: "BPCG-171",
    fullName: "General Psychology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-172",
    title: "Youth, Gender and Identity",
    name: "BPCG-172",
    fullName: "Youth, Gender and Identity",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-173",
    title: "Psychology for Health and Well-being",
    name: "BPCG-173",
    fullName: "Psychology for Health and Well-being",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-174",
    title: "Psychology and Media",
    name: "BPCG-174",
    fullName: "Psychology and Media",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-175",
    title: "Psychology for Living",
    name: "BPCG-175",
    fullName: "Psychology for Living",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-176",
    title: "Psychology of Gender",
    name: "BPCG-176",
    fullName: "Psychology of Gender",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-171",
    title: "Disaster Management",
    name: "BPAG-171",
    fullName: "Disaster Management",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-172",
    title: "Governance: Issues and Challenges",
    name: "BPAG-172",
    fullName: "Governance: Issues and Challenges",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-173",
    title: "E-Governance",
    name: "BPAG-173",
    fullName: "E-Governance",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPAG-174",
    title: "Sustainable Development",
    name: "BPAG-174",
    fullName: "Sustainable Development",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-171",
    title: "Indian Society: Images and Realities",
    name: "BSOG-171",
    fullName: "Indian Society: Images and Realities",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-173",
    title: "Rethinking Development",
    name: "BSOG-173",
    fullName: "Rethinking Development",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-176",
    title: "Economy and Society",
    name: "BSOG-176",
    fullName: "Economy and Society",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDG-173",
    title: "समाचार पत्र और फ�चर लेखन",
    name: "BHDG-173",
    fullName: "समाचार पत्र और फ�चर लेखन",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-171",
    title: "Media and Communication Skills",
    name: "BEGG-171",
    fullName: "Media and Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-172",
    title: "Language and Linguistics",
    name: "BEGG-172",
    fullName: "Language and Linguistics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-173",
    title: "Academic Writing & Composition",
    name: "BEGG-173",
    fullName: "Academic Writing & Composition",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGG-174",
    title: "Creative Writing",
    name: "BEGG-174",
    fullName: "Creative Writing",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BABG-171",
    title: "Understanding Ambedkar",
    name: "BABG-171",
    fullName: "Understanding Ambedkar",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPYG-171",
    title: "Applied Ethics",
    name: "BPYG-171",
    fullName: "Applied Ethics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPYG-172",
    title: "Philosophy of Religion",
    name: "BPYG-172",
    fullName: "Philosophy of Religion",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-101",
    title: "Molecules of Life",
    name: "BBCCT-101",
    fullName: "Molecules of Life",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-102",
    title: "Molecules of Life: Laboratory",
    name: "BBCCL-102",
    fullName: "Molecules of Life: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-103",
    title: "Cell Biology",
    name: "BBCCT-103",
    fullName: "Cell Biology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-104",
    title: "Cell Biology: Laboratory",
    name: "BBCCL-104",
    fullName: "Cell Biology: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-105",
    title: "Proteins",
    name: "BBCCT-105",
    fullName: "Proteins",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-106",
    title: "Proteins: Laboratory",
    name: "BBCCL-106",
    fullName: "Proteins: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-107",
    title: "Enzymes",
    name: "BBCCT-107",
    fullName: "Enzymes",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-108",
    title: "Enzymes: Laboratory",
    name: "BBCCL-108",
    fullName: "Enzymes: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-109",
    title: "Metabolism of Carbohydrates and Lipids",
    name: "BBCCT-109",
    fullName: "Metabolism of Carbohydrates and Lipids",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-110",
    title: "Metabolism of Carbohydrates and Lipids",
    name: "BBCCL-110",
    fullName: "Metabolism of Carbohydrates and Lipids",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-111",
    title: "Membrane Biology and Bioenergetics",
    name: "BBCCT-111",
    fullName: "Membrane Biology and Bioenergetics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-112",
    title: "Membrane Biology And Bioenergetics: Laboratory",
    name: "BBCCL-112",
    fullName: "Membrane Biology And Bioenergetics: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-113",
    title: "Metabolism of Amino Acids and Nucleotides",
    name: "BBCCT-113",
    fullName: "Metabolism of Amino Acids and Nucleotides",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-114",
    title: "Metabolism of Amino Acids and Nucleotides: Laboratory",
    name: "BBCCL-114",
    fullName: "Metabolism of Amino Acids and Nucleotides: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-115",
    title: "Human Physiology",
    name: "BBCCT-115",
    fullName: "Human Physiology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-116",
    title: "Human Physiology: Laboratory",
    name: "BBCCL-116",
    fullName: "Human Physiology: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-117",
    title: "Gene Organization Replication and Repair",
    name: "BBCCT-117",
    fullName: "Gene Organization Replication and Repair",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-118",
    title: "Gene Organization Replication and Repair: Laboratory",
    name: "BBCCL-118",
    fullName: "Gene Organization Replication and Repair: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-119",
    title: "Hormone: Biochemistry and Function",
    name: "BBCCT-119",
    fullName: "Hormone: Biochemistry and Function",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-120",
    title: "Hormone: Biochemistry and Function: Laboratory",
    name: "BBCCL-120",
    fullName: "Hormone: Biochemistry and Function: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-121",
    title: "Concepts in Genetics",
    name: "BBCCT-121",
    fullName: "Concepts in Genetics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-122",
    title: "Concepts in Genetics: Laboratory",
    name: "BBCCL-122",
    fullName: "Concepts in Genetics: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-123",
    title: "Gene Expression and Regulation",
    name: "BBCCT-123",
    fullName: "Gene Expression and Regulation",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-124",
    title: "Gene Expression and Regulation: Laboratory",
    name: "BBCCL-124",
    fullName: "Gene Expression and Regulation: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-125",
    title: "Genetic Engineering and Biotechnology",
    name: "BBCCT-125",
    fullName: "Genetic Engineering and Biotechnology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-126",
    title: "Genetic Engineering and Biotechnology: Laboratory",
    name: "BBCCT-126",
    fullName: "Genetic Engineering and Biotechnology: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCT-127",
    title: "Immunology",
    name: "BBCCT-127",
    fullName: "Immunology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCCL-128",
    title: "Immunology: Laboratory",
    name: "BBCCL-128",
    fullName: "Immunology: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCET-141",
    title: "Nutritional Biochemistry",
    name: "BBCET-141",
    fullName: "Nutritional Biochemistry",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCEL-142",
    title: "Nutritional Biochemistry: Laboratory",
    name: "BBCEL-142",
    fullName: "Nutritional Biochemistry: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCET-143",
    title: "Basic Microbiology",
    name: "BBCET-143",
    fullName: "Basic Microbiology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCEL-144",
    title: "Basic Microbiology: Laboratory",
    name: "BBCEL-144",
    fullName: "Basic Microbiology: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCET-145",
    title: "Molecular basis of non-infectious human diseases",
    name: "BBCET-145",
    fullName: "Molecular basis of non-infectious human diseases",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCEL-146",
    title: "Molecular basis of non-infectious human diseases: Laboratory",
    name: "BBCEL-146",
    fullName: "Molecular basis of non-infectious human diseases: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCET-151",
    title: "Plant Biochemistry",
    name: "BBCET-151",
    fullName: "Plant Biochemistry",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCEL-152",
    title: "Plant Biochemistry: Laboratory",
    name: "BBCEL-152",
    fullName: "Plant Biochemistry: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEVAE-181",
    title: "Environmental Studies",
    name: "BEVAE-181",
    fullName: "Environmental Studies",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGAE-182",
    title: "English Communication Skills",
    name: "BEGAE-182",
    fullName: "English Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDAE-182",
    title: "�हंद� भाषा और संप्रेषण",
    name: "BHDAE-182",
    fullName: "�हंद� भाषा और संप्रेषण",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCS-183",
    title: "Tools & Techniques in Biochemistry",
    name: "BBCS-183",
    fullName: "Tools & Techniques in Biochemistry",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBCS-185",
    title: "Bioinformatics",
    name: "BBCS-185",
    fullName: "Bioinformatics",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BCHCT-131",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons",
    name: "BCHCT-131",
    fullName:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BCHCL-132",
    title:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons: Laboratory",
    name: "BCHCL-132",
    fullName:
      "Atomic Structure, Bonding, General Organic Chemistry and Aliphatic Hydrocarbons: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BCHCT-133",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry I",
    name: "BCHCT-133",
    fullName:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry I",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BCHCL-134",
    title:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry I: Laboratory",
    name: "BCHCL-134",
    fullName:
      "Chemical Energetics, Equilibria and Functional Group Organic Chemistry I: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBYCT-131",
    title: "Biodiversity (Microbes, Algae, Fungi and Archegoniates)",
    name: "BBYCT-131",
    fullName: "Biodiversity (Microbes, Algae, Fungi and Archegoniates)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BBYCL-132",
    title:
      "Biodiversity (Microbes, Algae, Fungi and Archegoniates): Laboratory",
    name: "BBYCL-132",
    fullName:
      "Biodiversity (Microbes, Algae, Fungi and Archegoniates): Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BZYCT-131",
    title: "Animal Diversity",
    name: "BZYCT-131",
    fullName: "Animal Diversity",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BZYCL-132",
    title: "Animal Diversity: Laboratory",
    name: "BZYCL-132",
    fullName: "Animal Diversity: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-101",
    title: "Indian Classical Literature",
    name: "BEGC-101",
    fullName: "Indian Classical Literature",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-102",
    title: "European Classical Literature",
    name: "BEGC-102",
    fullName: "European Classical Literature",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-103",
    title: "Indian Writing in English",
    name: "BEGC-103",
    fullName: "Indian Writing in English",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-104",
    title: "British Poetry and Drama: 14th- 17th Centuries",
    name: "BEGC-104",
    fullName: "British Poetry and Drama: 14th- 17th Centuries",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-105",
    title: "American Literature",
    name: "BEGC-105",
    fullName: "American Literature",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-106",
    title: "Popular Literature",
    name: "BEGC-106",
    fullName: "Popular Literature",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-107",
    title: "British Poetry and Drama: 17th & 18th Centuries",
    name: "BEGC-107",
    fullName: "British Poetry and Drama: 17th & 18th Centuries",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-108",
    title: "British Literature: 18th Century",
    name: "BEGC-108",
    fullName: "British Literature: 18th Century",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-109",
    title: "British Romantic Literature",
    name: "BEGC-109",
    fullName: "British Romantic Literature",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-110",
    title: "British Literature: 19th Century",
    name: "BEGC-110",
    fullName: "British Literature: 19th Century",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-111",
    title: "Women's Writing",
    name: "BEGC-111",
    fullName: "Women's Writing",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-112",
    title: "British Literature: The Early 20th Century",
    name: "BEGC-112",
    fullName: "British Literature: The Early 20th Century",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-113",
    title: "Modern European Drama",
    name: "BEGC-113",
    fullName: "Modern European Drama",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGC-114",
    title: "Postcolonial Literatures",
    name: "BEGC-114",
    fullName: "Postcolonial Literatures",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGE-141",
    title: "Understanding Prose",
    name: "BEGE-141",
    fullName: "Understanding Prose",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGE-143",
    title: "Understanding Poetry",
    name: "BEGE-143",
    fullName: "Understanding Poetry",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGE-142",
    title: "Understanding Drama",
    name: "BEGE-142",
    fullName: "Understanding Drama",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGE-144",
    title: "Understanding The Novel",
    name: "BEGE-144",
    fullName: "Understanding The Novel",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEVAE-181",
    title: "Envirnoment Studies",
    name: "BEVAE-181",
    fullName: "Envirnoment Studies",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGAE-182",
    title: "English Communication Skills",
    name: "BEGAE-182",
    fullName: "English Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANS-183",
    title: "Tourism Anthropology",
    name: "BANS-183",
    fullName: "Tourism Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGS-183",
    title: "Writing and Study Skills",
    name: "BEGS-183",
    fullName: "Writing and Study Skills",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-186",
    title: "Managing Stress",
    name: "BPCS-186",
    fullName: "Managing Stress",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-171",
    title: "Indian Society: Images and Realities",
    name: "BSOG-171",
    fullName: "Indian Society: Images and Realities",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BGDG-172",
    title: "Gender Sensitisation, Society & culture",
    name: "BGDG-172",
    fullName: "Gender Sensitisation, Society & culture",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-173",
    title: "Rethinking Development",
    name: "BSOG-173",
    fullName: "Rethinking Development",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDG-173",
    title: "समाचार पत्र और फ�चर लेखन",
    name: "BHDG-173",
    fullName: "समाचार पत्र और फ�चर लेखन",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-174",
    title: "Psychology and Media",
    name: "BPCG-174",
    fullName: "Psychology and Media",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCT-101",
    title: "Introduction to Hindustani Music and its Fundamentals",
    name: "BHMCT-101",
    fullName: "Introduction to Hindustani Music and its Fundamentals",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCL-102",
    title: "Hindustani Music Vocal Practicum - 1",
    name: "BHMCL-102",
    fullName: "Hindustani Music Vocal Practicum - 1",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCT-103",
    title: "Fundamentals of Hindustani Music",
    name: "BHMCT-103",
    fullName: "Fundamentals of Hindustani Music",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCL-104",
    title: "Hindustani Music Vocal Practicum - 2",
    name: "BHMCL-104",
    fullName: "Hindustani Music Vocal Practicum - 2",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCT-105",
    title: "Study of Forms, Instruments and Traditions of Hindustani Music",
    name: "BHMCT-105",
    fullName: "Study of Forms, Instruments and Traditions of Hindustani Music",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCL-106",
    title: "Hindustani Music Vocal Practicum – 3",
    name: "BHMCL-106",
    fullName: "Hindustani Music Vocal Practicum – 3",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCL-107",
    title: "Hindustani Music Vocal Practicum – 4",
    name: "BHMCL-107",
    fullName: "Hindustani Music Vocal Practicum – 4",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCT-108",
    title: "Study of Treatises, Gharanas, Elementary Karnatak Music",
    name: "BHMCT-108",
    fullName: "Study of Treatises, Gharanas, Elementary Karnatak Music",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCP-109",
    title: "Dissertation",
    name: "BHMCP-109",
    fullName: "Dissertation",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCL-110",
    title: "Hindustani Music Vocal Practicum – 5",
    name: "BHMCL-110",
    fullName: "Hindustani Music Vocal Practicum – 5",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCT-111",
    title: "Study of Modern Works, Gharanas, Biographies and Other Genres",
    name: "BHMCT-111",
    fullName: "Study of Modern Works, Gharanas, Biographies and Other Genres",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCL-112",
    title: "Hindustani Music Vocal Practicum – 6",
    name: "BHMCL-112",
    fullName: "Hindustani Music Vocal Practicum – 6",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCT-113",
    title:
      "Study of Gharanas, Elementary Western Music, and Interdisciplinary study of Music",
    name: "BHMCT-113",
    fullName:
      "Study of Gharanas, Elementary Western Music, and Interdisciplinary study of Music",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHMCL-114",
    title: "Hindustani Music Vocal Practicum – 7",
    name: "BHMCL-114",
    fullName: "Hindustani Music Vocal Practicum – 7",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPFT-141",
    title: "Study of Natyashastra",
    name: "BPFT-141",
    fullName: "Study of Natyashastra",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPFT-142",
    title: "Arts and Aesthetics: Indian & Western Concepts",
    name: "BPFT-142",
    fullName: "Arts and Aesthetics: Indian & Western Concepts",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BFPT-143",
    title: "Pedagogy of Performing Arts",
    name: "BFPT-143",
    fullName: "Pedagogy of Performing Arts",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BFPT-144",
    title: "Integrated Performance project (Practical)",
    name: "BFPT-144",
    fullName: "Integrated Performance project (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEVAE-181",
    title: "Environmental Studies",
    name: "BEVAE-181",
    fullName: "Environmental Studies",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BEGAE-182",
    title: "Communication Skills in English Language",
    name: "BEGAE-182",
    fullName: "Communication Skills in English Language",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BHDAE-182",
    title: "Hindi Bhasha aur Sampreshan",
    name: "BHDAE-182",
    fullName: "Hindi Bhasha aur Sampreshan",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BANS-183",
    title: "Tourism Anthropology",
    name: "BANS-183",
    fullName: "Tourism Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCS-186",
    title: "Managing Stress",
    name: "BPCS-186",
    fullName: "Managing Stress",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-171",
    title: "Indian Society: Images and Reality",
    name: "BSOG-171",
    fullName: "Indian Society: Images and Reality",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BGDG-172",
    title: "Gender Sensibility",
    name: "BGDG-172",
    fullName: "Gender Sensibility",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BSOG-173",
    title: "Rethinking Development",
    name: "BSOG-173",
    fullName: "Rethinking Development",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
  {
    code: "BPCG-174",
    title: "Psychology and Media",
    name: "BPCG-174",
    fullName: "Psychology and Media",
    collegeCode: "IGNOU",
    programmeCode: "BCOMG",
    term: 1,
  },
];
