export const certificateCourses = [
  { code: "BLI-11", title: "Libraries: An Introduction" },
  { code: "BLII-12", title: "Document Processing and Organisation" },
  { code: "BLII-13", title: "Information Sources and Library Services" },
  { code: "BLII-14", title: "ICT in Libraries" },
  { code: "CDM-1", title: "Foundation Course in Disaster Management" },
  { code: "CDM-2", title: "Disaster Management: Methods & Techniques" },
  { code: "AHE-1", title: "Human Environment (without AHE Project)" },
  { code: "TS-5", title: "Ecology, Environment and Tourism" },
  { code: "PES-1", title: "Project Work - Environmental Studies" },
  { code: "BAB-101", title: "B.R. Ambedkar: Thinker, His Time" },
  { code: "BAB-102", title: "B.R. Ambedkar: Society and Culture" },
  { code: "BAB-103", title: "Economic Throught of B.R. Ambedkar" },
  { code: "BAB-104", title: "State, Democracy and Nation Building" },
  { code: "BGP-1", title: "Introduction to Peace and Conflict Management" },
  { code: "BGP-2", title: "Indian Perspectives on Peace and Conflict" },
  { code: "BGP-3", title: "Conflicts and Peace: Global Perspective" },
  { code: "BGPP-1", title: "Project Work" },
  { code: "CFN-1", title: "You and Your Food" },
  { code: "CFN-2", title: "Your Food and its Utilisation" },
  { code: "CFN-3", title: "Economics of Food" },
  { code: "CNCC-1", title: "Nutrition for the Community" },
  { code: "CNCC-2", title: "Organising Child Care Services" },
  { code: "MRD-101", title: "Rural Development: Indian Context" },
  { code: "MRD-102", title: "Rural Development Programmes" },
  { code: "MRD-103", title: "Rural Development Planning and Management" },
  { code: "NES-101", title: "Understanding the Elementary School Child" },
  { code: "NES-102", title: "Facilitating Growth and Development" },
  { code: "NES-103", title: "Guiding Children’s Learning" },
  { code: "NES-104", title: "Guiding Socio-emotional Development of Children" },
  { code: "CIT-1", title: "Fundamentals of Computer Systems" },
  { code: "CIT-2", title: "Introduction to Information Technology" },
  { code: "CIT-3", title: "Web based Technologies & Multimedia Applications" },
  { code: "CITL-1", title: "Laboratory Course" },
  { code: "BCS-091", title: "Introduction to Mobile Architecture" },
  { code: "BCS-092", title: "Introduction to Databases" },
  { code: "BCS-093", title: "Introduction to Android" },
  { code: "BCS-094", title: "Programming using Python" },
  { code: "BCSL-091", title: "Laboratory Course" },
  { code: "CTE-101", title: "The Language and the Learner" },
  { code: "CTE-102", title: "The Structure of English" },
  { code: "CTE-103", title: "Teaching Strategies" },
  { code: "CTE-104", title: "Teaching English-Elementary School" },
  { code: "CTE-105", title: "Teaching English-Secondary School" },
  { code: "BEG-4", title: "English in Daily Life" },
  { code: "BEG-5", title: "English in Education" },
  { code: "BEG-6", title: "Joining the Work Force" },
  { code: "OUL-1", title: "Script & Pronunciation" },
  { code: "OUL-2", title: "Communicative & Comprehensive Skills" },
  { code: "CHR-11", title: "Human Rights: Evolution, Concepts and Concerns" },
  { code: "CHR-12", title: "Human Rights in India" },
  { code: "CPI-101", title: "Consumer and Consumer Protection Legislations" },
  {
    code: "CPI-102",
    title: "Redressal of Consumer Grievances: Role of Various Stake Holders",
  },
  { code: "CPI-103", title: "Consumer Protection Issues" },
  { code: "CPIP-104", title: "Project Work in Consumer Protection" },
  {
    code: "BLE-11",
    title:
      "Cooperation: Genesis, Principles, Values, Policy, Growth and Development",
  },
  { code: "BLE-12", title: "Co-operative Law" },
  { code: "BLE-13", title: "Business Law as applicable to Cooperatives – I" },
  { code: "BLE-14", title: "Business Law as applicable to Cooperatives – II" },
  { code: "BLE-31", title: "Understanding Human Trafficking" },
  {
    code: "BLE-32",
    title: "Law Policies and Institutional Response to Human Trafficking",
  },
  { code: "BLE-33", title: "Rehabilitation and Prevention" },
  { code: "BLEP-34", title: "Project Work" },
  { code: "BMS-1", title: "Introduction to NGO Management" },
  { code: "BMS-2", title: "Management Functions" },
  { code: "BMS-3", title: "Health Care Management" },
  { code: "ECO-1", title: "Business Organisation" },
  { code: "PCO-1", title: "Preparatory Course in Commerce" },
  { code: "BCOA-1", title: "Business Communication & Entrepreneurship" },
  { code: "CITL-1", title: "Laboratory Course" },
  { code: "BPOI-6", title: "English Communication/Communication Skills" },
  { code: "BPOI-6(P)", title: "English Communication/Communication Skills" },
  { code: "BPOI-7", title: "IT Skills" },
  { code: "BPOI-7(P)", title: "IT Skills" },
  { code: "OSEI-41", title: "Information Security" },
  { code: "OSEI-41(P)", title: "Information Security" },
  { code: "OSEI-42", title: "Securing Internet Access" },
  { code: "OSEI-42(P)", title: "Securing Internet Access" },
  { code: "OSE-43", title: "Information Technology Security" },
  { code: "OSEI-44", title: "Server Security" },
  { code: "OSEI-44 (P)", title: "Server Security" },
  { code: "BFDI-71", title: "Fundamentals of Fashion Design" },
  { code: "BFDI-71(P)", title: "Fundamentals of Fashion Design" },
  { code: "BFDI-72", title: "Basics of Pattem Making and Sewing" },
  { code: "BFDI-72(P)", title: "Basics of Pattem Making and Sewing" },
  { code: "BFDI-73", title: "Introduction to Fashion Industry" },
  { code: "BFDI-73(P)", title: "Introduction to Fashion Industry" },
  { code: "BFD-74", title: "Communication and Entrepreneurship" },
  { code: "TS-1", title: "Foundation Course in Tourism" },
  {
    code: "TS-2",
    title: "Tourism Development: Products, Operations and Case Studies",
  },
  { code: "CLT-101", title: "Good Laboratory Practices" },
  { code: "CLTL-101", title: "Good Laboratory Practices: Basic Exercises" },
  { code: "CLT-102", title: "Laboratory Techniques in Biology" },
  { code: "CLTL-102", title: "Basic Experiments in Biology" },
  { code: "CLT-103", title: "Laboratory Techniques in Chemistry" },
  { code: "CLTL-103", title: "Basic Experiments in Chemistry" },
  { code: "CLT-104", title: "Laboratory Techniques in Physics" },
  { code: "CLTL-104", title: "Basic Experiments in Physics" },
  { code: "AMT-1", title: "Teaching of Primary School Mathematics" },
  { code: "LMT-1", title: "Learning Mathematics" },
  { code: "BFE-101", title: "Basics ofHIV/AIDS" },
  { code: "BFE-102", title: "Basics of Family Education" },
  { code: "BFEE-101", title: "Elective on HIV/AIDS" },
  { code: "BFEE-102", title: "Elective on Family Education" },
  { code: "BFEE-103", title: "Alcohol, Drugs & HIV" },
  { code: "BFEE-104", title: "Commmunication & Counselling in HIV" },
  {
    code: "MSW-31",
    title: "Social Work Intervention in Correctional Settings (Compulsory)",
  },
  { code: "MSW-32", title: "Social Work and Criminal Justice (Compulsory)" },
  {
    code: "MSWL-33",
    title: "Social Work Practicum in Correctional Settings (Compulsory)",
  },
  { code: "BSW-41", title: "Understanding Tribals" },
  { code: "BSW-42", title: "Tribal Society" },
  { code: "BSW-43", title: "Tribals of South and Central India" },
  { code: "BSW-44", title: "Tribals in North and Northeast Region of India" },
  { code: "BLP-1", title: "Introduction to Sericulture" },
  { code: "BLPI-2", title: "Host Plant Cultivation" },
  { code: "BLPI-3", title: "Silkworm Rearing" },
  { code: "BLP-4", title: "Crop Protection" },
  { code: "BAP-1", title: "Introduction to Organic Farming" },
  { code: "BAPI-1", title: "Organic Production System" },
  { code: "BAPI-2", title: "Inspection and Certification of Organic Produce" },
  { code: "BAPI-3", title: "Economics and Marketing of Organic Produce" },
  { code: "ONR-1", title: "Introduction to Water Harvesting" },
  { code: "ONR-2", title: "Basics of Hydrology" },
  { code: "ONR-3", title: "Water Harvesting, Conservation and Utilization" },
  { code: "ONRL-1", title: "Practical Training at Water Harvesting Agency" },
  { code: "OLP-1", title: "Introduction to Poultry Farming" },
  { code: "OLPI-1", title: "Poultry Housing and Management" },
  { code: "OLPI-2", title: "Poultry Feeds and Feeding" },
  { code: "OLPL-1", title: "Poultry Health Care and Bio-security Measures" },
  { code: "OLPL-2", title: "Poultry Farm Training" },
  { code: "OAPI-11", title: "Introduction to Beekeeping" },
  { code: "OAPI-12", title: "Management of Honey Bee Colonies" },
  { code: "OAPI-13", title: "Hive Products and Economics of Beekeeping" },
  { code: "BAL-1", title: "Basics of Arabic" },
  { code: "BAL-2", title: "Communication Skills" },
  { code: "BFLI-1", title: "Talking About Oneself" },
  { code: "BFLI-2", title: "Interaction" },
  { code: "BFLI-3", title: "Space" },
  { code: "BFLI-4", title: "Time" },
  { code: "ORU-001", title: "Communication Skills-I" },
  { code: "ORUL-002", title: "Communication Skills-II" },
  { code: "BJLI-1", title: "Basic Japanese - 01" },
  { code: "BJLI-2", title: "Basic Japanese - 02" },
  { code: "BJLI-3", title: "Basic Japanese - 03" },
  { code: "BJLI-4", title: "Basic Japanese - 04" },
  { code: "BKL-1", title: "Basics of Korean – I" },
  { code: "BKL-2", title: "Basics of Korean – II" },
  { code: "BSL-1", title: "Basics of Spanish Language and Culture-I" },
  { code: "BSL-2", title: "Basics of Spanish Language and Culture-II" },
  { code: "BGL-1", title: "German Language Course-I" },
  { code: "BGL-2", title: "German Language Course-II" },
  { code: "BGL-3", title: "German Language Course-III" },
  { code: "BPEL-11", title: "Basics of Persian" },
  { code: "BPEL-12", title: "Communication Skills" },
  { code: "BNS-40", title: "Basics of First Aid (Theory)" },
  { code: "BNSL-40", title: "Skills in First Aid (Practical)" },
  { code: "BYG-1", title: "Introduction to Yoga and Yogic texts" },
  { code: "BYG-2", title: "Yoga and Health" },
  {
    code: "BYGL-1",
    title: "Shat Kriyas, Yogic Kriyas, Asanas, Pranayama, Mantra Japa",
  },
  {
    code: "BHM-101",
    title:
      "Fundamentals: Environment and Health, Health Care Waste Management Regulations",
  },
  {
    code: "BHM-102",
    title: "Health Care Waste Management: Concepts, Technologies and Training",
  },
  {
    code: "BHME-101",
    title: "Inter-relationship between Health and Environment",
  },
  { code: "BHME-102", title: "Worker Safety and Patient Safety" },
  {
    code: "BHME-103",
    title:
      "Current Status of Health Care Waste Management and Legislation in the Regional Countries",
  },
  { code: "BHME-104", title: "Managerial and Systems Approach" },
  { code: "BHME-105", title: "Special Considerations of Waste Management" },
  {
    code: "BHME-106",
    title: "Administrative and Legal Aspects of Waste Management",
  },
  { code: "BHMP-101", title: "Project" },
  { code: "BHML-101", title: "Workshop" },
  { code: "BNS-115", title: "Nursing Care of New Born and Infant" },
  {
    code: "BNSL-115",
    title: "Nursing Practices and Procedures in Care of Newborn and Infant",
  },
  { code: "BNS-117", title: "Maternal and Child Health Care" },
  {
    code: "BNSL-117",
    title: "Practices and Procedures in Maternal and Child Health Care",
  },
  { code: "CNS-HC-1", title: "Home Based Care (Theory)" },
  { code: "CNS-HCP-1", title: "Skills Related to Home Based Care (Practical)" },
  { code: "BHT-1", title: "Foundation of General Duty Assistance" },
  { code: "BHT-2", title: "Basic Needs of PatientCare" },
  { code: "BHTL-3", title: "Fundamental Skills for General Duty Assistance" },
  { code: "BHT-6", title: "Foundation for Geriatric Care Assistance" },
  { code: "BHT-7", title: "Special Needs of Geriatric Patients" },
  { code: "BHTL-8", title: "Skills for Geriatric Care Assistance" },
  { code: "BHT-11", title: "Basic Phlebotomy Assistance" },
  { code: "BHT-12", title: "Handling of Blood Samples" },
  { code: "BHTL-13", title: "Skills for Phlebotomy Assistance" },
  { code: "BHT-16", title: "Basic Home Health Assistance" },
  { code: "BHT-17", title: "Applied Home Health Assistance" },
  { code: "BHTL-18", title: "Skills for Home Health Assistance" },
  { code: "BNS-41", title: "Foundations of Community Health" },
  { code: "BNS-42", title: "Primary Health Care in Common Conditions" },
  { code: "BNS-43", title: "Public Health and Primary Health Care Skills" },
  { code: "CNS-AH-001", title: "Theory Course – 1Fundamentals of Adolescence" },
  {
    code: "CNS-AH-002",
    title: "Theory Course – 2 Issues & Challenges during Adolescence",
  },
  {
    code: "CNS-AHL 001",
    title:
      "Practical Title of the course: Practical Manual on Adolescent Health",
  },
  { code: "OVA-1", title: "Indian Cultural Heritage (Theory)" },
  { code: "OVA-2", title: "Understanding Indian Art Forms (Theory)" },
  { code: "OVA-3", title: "An Introduction to Indian Arts (Theory)" },
  { code: "OVAL-4", title: "Direct Study from Simple Objects (Practical)" },
  { code: "OVAL-5", title: "Study from Still Life (Practical)" },
  { code: "OVAL-6", title: "Composition in Painting (Practical)" },
  { code: "OVAL-7", title: "Geometrical Design (Practical)" },
  { code: "OTH-1", title: "An Introduction to Theatre & Drama (Theory)" },
  { code: "OTHL-2", title: "Voice & Speech (Practical)" },
  { code: "OTHL-3", title: "Physical Aspects of Acting (Practical)" },
  { code: "OTHL-4", title: "Method Acting-Stanislavisky (Practical)" },
  { code: "OMU-1", title: "An Introduction to Hindustani Music (Theory)" },
  { code: "OMUL-2", title: "(Practical-1)" },
  { code: "OMUL-3", title: "(Practical-2)" },
  { code: "OMUL-4", title: "(Practical-3)" },
  { code: "OMU-5", title: "An Introduction to Karnatak Music (Theory)" },
  { code: "OMUL-6", title: "Paper-1 (Practical)" },
  { code: "OMUL-7", title: "Paper-2 (Practical)" },
  { code: "OMUL-8", title: "Paper-3 (Practical)" },
  { code: "ODN-1", title: "Introduction to Indian Dance Forms (Theory)" },
  { code: "ODNL-11", title: "Bharatanatyam 1 (Practical)" },
  { code: "ODNL-12", title: "Bharatanatyam 2 (Practical)" },
  { code: "ODNL-13", title: "Music and Talas (Practical)" },
  { code: "OEY-1", title: "Energy Resources and Conversion Processes" },
  { code: "OEY-2", title: "Renewable Energy Technologies and their Uses" },
  { code: "OEY-3", title: "Energy Management: Audit and Conservation" },
  { code: "OEYP-4", title: "Energy Projects" },
  { code: "OEE-1", title: "Electricity and Safety Measures" },
  { code: "OEE-2", title: "Power Distribution System – Basics" },
  { code: "OEEL-1", title: "Practical in Power Distribution" },
  { code: "BWA-001", title: "Solid Wastes & Regulatory Framework" },
  { code: "BWA-002", title: "Solid Wastes Collection and Transportation" },
  {
    code: "BWA-003",
    title: "Solid Wastes Processing and Treatment Techniques",
  },
  { code: "BWA-004", title: "Disposal of Wastes" },
  { code: "BWAP-001", title: "Project" },
  { code: "BEDS-1", title: "Overview and Perspectives of Values (Theory)" },
  { code: "BEDS-2", title: "Socio-Psychological Basis (Theory)" },
  { code: "BEDS-3", title: "Pedagogy of Values (Theory)" },
  {
    code: "BEDS-4",
    title: "Application Support Skills (Theory) and Activities",
  },
  { code: "BEV-001", title: "Introduction to Solid Waste Management" },
  {
    code: "BEV-002",
    title: "Municipal, Agricultural, Industrial and Hazardous Waste Management",
  },
  {
    code: "BEV-003",
    title:
      "Plastic, E-waste, Biomedical and Construction and Demolition Waste management",
  },
  { code: "BJM-1", title: "Introduction to Community Radio" },
  { code: "BJM-2", title: "Operating a Community Radio" },
  { code: "BJMP-1", title: "Practical/Internship (10 days)" },
  {
    code: "MGS-041",
    title: "Introduction to Gender, Agriculture and Sustainable development",
  },
  { code: "MGS-042", title: "Gender dynamics in Agriculture" },
  { code: "MGS-043", title: "Gender and Sustainable Development" },
];
