export const certificateCourses = [
  {
    code: "BLI-11",
    title: "Libraries: An Introduction",
    name: "BLI-11",
    fullName: "Libraries: An Introduction",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLII-12",
    title: "Document Processing and Organisation",
    name: "BLII-12",
    fullName: "Document Processing and Organisation",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLII-13",
    title: "Information Sources and Library Services",
    name: "BLII-13",
    fullName: "Information Sources and Library Services",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLII-14",
    title: "ICT in Libraries",
    name: "BLII-14",
    fullName: "ICT in Libraries",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CDM-1",
    title: "Foundation Course in Disaster Management",
    name: "CDM-1",
    fullName: "Foundation Course in Disaster Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CDM-2",
    title: "Disaster Management: Methods & Techniques",
    name: "CDM-2",
    fullName: "Disaster Management: Methods & Techniques",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "AHE-1",
    title: "Human Environment (without AHE Project)",
    name: "AHE-1",
    fullName: "Human Environment (without AHE Project)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "TS-5",
    title: "Ecology, Environment and Tourism",
    name: "TS-5",
    fullName: "Ecology, Environment and Tourism",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "PES-1",
    title: "Project Work - Environmental Studies",
    name: "PES-1",
    fullName: "Project Work - Environmental Studies",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAB-101",
    title: "B.R. Ambedkar: Thinker, His Time",
    name: "BAB-101",
    fullName: "B.R. Ambedkar: Thinker, His Time",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAB-102",
    title: "B.R. Ambedkar: Society and Culture",
    name: "BAB-102",
    fullName: "B.R. Ambedkar: Society and Culture",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAB-103",
    title: "Economic Throught of B.R. Ambedkar",
    name: "BAB-103",
    fullName: "Economic Throught of B.R. Ambedkar",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAB-104",
    title: "State, Democracy and Nation Building",
    name: "BAB-104",
    fullName: "State, Democracy and Nation Building",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BGP-1",
    title: "Introduction to Peace and Conflict Management",
    name: "BGP-1",
    fullName: "Introduction to Peace and Conflict Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BGP-2",
    title: "Indian Perspectives on Peace and Conflict",
    name: "BGP-2",
    fullName: "Indian Perspectives on Peace and Conflict",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BGP-3",
    title: "Conflicts and Peace: Global Perspective",
    name: "BGP-3",
    fullName: "Conflicts and Peace: Global Perspective",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BGPP-1",
    title: "Project Work",
    name: "BGPP-1",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CFN-1",
    title: "You and Your Food",
    name: "CFN-1",
    fullName: "You and Your Food",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CFN-2",
    title: "Your Food and its Utilisation",
    name: "CFN-2",
    fullName: "Your Food and its Utilisation",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CFN-3",
    title: "Economics of Food",
    name: "CFN-3",
    fullName: "Economics of Food",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CNCC-1",
    title: "Nutrition for the Community",
    name: "CNCC-1",
    fullName: "Nutrition for the Community",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CNCC-2",
    title: "Organising Child Care Services",
    name: "CNCC-2",
    fullName: "Organising Child Care Services",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MRD-101",
    title: "Rural Development: Indian Context",
    name: "MRD-101",
    fullName: "Rural Development: Indian Context",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MRD-102",
    title: "Rural Development Programmes",
    name: "MRD-102",
    fullName: "Rural Development Programmes",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MRD-103",
    title: "Rural Development Planning and Management",
    name: "MRD-103",
    fullName: "Rural Development Planning and Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "NES-101",
    title: "Understanding the Elementary School Child",
    name: "NES-101",
    fullName: "Understanding the Elementary School Child",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "NES-102",
    title: "Facilitating Growth and Development",
    name: "NES-102",
    fullName: "Facilitating Growth and Development",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "NES-103",
    title: "Guiding Children’s Learning",
    name: "NES-103",
    fullName: "Guiding Children’s Learning",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "NES-104",
    title: "Guiding Socio-emotional Development of Children",
    name: "NES-104",
    fullName: "Guiding Socio-emotional Development of Children",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CIT-1",
    title: "Fundamentals of Computer Systems",
    name: "CIT-1",
    fullName: "Fundamentals of Computer Systems",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CIT-2",
    title: "Introduction to Information Technology",
    name: "CIT-2",
    fullName: "Introduction to Information Technology",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CIT-3",
    title: "Web based Technologies & Multimedia Applications",
    name: "CIT-3",
    fullName: "Web based Technologies & Multimedia Applications",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CITL-1",
    title: "Laboratory Course",
    name: "CITL-1",
    fullName: "Laboratory Course",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BCS-091",
    title: "Introduction to Mobile Architecture",
    name: "BCS-091",
    fullName: "Introduction to Mobile Architecture",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BCS-092",
    title: "Introduction to Databases",
    name: "BCS-092",
    fullName: "Introduction to Databases",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BCS-093",
    title: "Introduction to Android",
    name: "BCS-093",
    fullName: "Introduction to Android",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BCS-094",
    title: "Programming using Python",
    name: "BCS-094",
    fullName: "Programming using Python",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BCSL-091",
    title: "Laboratory Course",
    name: "BCSL-091",
    fullName: "Laboratory Course",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CTE-101",
    title: "The Language and the Learner",
    name: "CTE-101",
    fullName: "The Language and the Learner",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CTE-102",
    title: "The Structure of English",
    name: "CTE-102",
    fullName: "The Structure of English",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CTE-103",
    title: "Teaching Strategies",
    name: "CTE-103",
    fullName: "Teaching Strategies",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CTE-104",
    title: "Teaching English-Elementary School",
    name: "CTE-104",
    fullName: "Teaching English-Elementary School",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CTE-105",
    title: "Teaching English-Secondary School",
    name: "CTE-105",
    fullName: "Teaching English-Secondary School",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEG-4",
    title: "English in Daily Life",
    name: "BEG-4",
    fullName: "English in Daily Life",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEG-5",
    title: "English in Education",
    name: "BEG-5",
    fullName: "English in Education",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEG-6",
    title: "Joining the Work Force",
    name: "BEG-6",
    fullName: "Joining the Work Force",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OUL-1",
    title: "Script & Pronunciation",
    name: "OUL-1",
    fullName: "Script & Pronunciation",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OUL-2",
    title: "Communicative & Comprehensive Skills",
    name: "OUL-2",
    fullName: "Communicative & Comprehensive Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CHR-11",
    title: "Human Rights: Evolution, Concepts and Concerns",
    name: "CHR-11",
    fullName: "Human Rights: Evolution, Concepts and Concerns",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CHR-12",
    title: "Human Rights in India",
    name: "CHR-12",
    fullName: "Human Rights in India",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CPI-101",
    title: "Consumer and Consumer Protection Legislations",
    name: "CPI-101",
    fullName: "Consumer and Consumer Protection Legislations",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CPI-102",
    title: "Redressal of Consumer Grievances: Role of Various Stake Holders",
    name: "CPI-102",
    fullName: "Redressal of Consumer Grievances: Role of Various Stake Holders",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CPI-103",
    title: "Consumer Protection Issues",
    name: "CPI-103",
    fullName: "Consumer Protection Issues",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CPIP-104",
    title: "Project Work in Consumer Protection",
    name: "CPIP-104",
    fullName: "Project Work in Consumer Protection",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLE-11",
    title:
      "Cooperation: Genesis, Principles, Values, Policy, Growth and Development",
    name: "BLE-11",
    fullName:
      "Cooperation: Genesis, Principles, Values, Policy, Growth and Development",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLE-12",
    title: "Co-operative Law",
    name: "BLE-12",
    fullName: "Co-operative Law",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLE-13",
    title: "Business Law as applicable to Cooperatives – I",
    name: "BLE-13",
    fullName: "Business Law as applicable to Cooperatives – I",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLE-14",
    title: "Business Law as applicable to Cooperatives – II",
    name: "BLE-14",
    fullName: "Business Law as applicable to Cooperatives – II",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLE-31",
    title: "Understanding Human Trafficking",
    name: "BLE-31",
    fullName: "Understanding Human Trafficking",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLE-32",
    title: "Law Policies and Institutional Response to Human Trafficking",
    name: "BLE-32",
    fullName: "Law Policies and Institutional Response to Human Trafficking",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLE-33",
    title: "Rehabilitation and Prevention",
    name: "BLE-33",
    fullName: "Rehabilitation and Prevention",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLEP-34",
    title: "Project Work",
    name: "BLEP-34",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BMS-1",
    title: "Introduction to NGO Management",
    name: "BMS-1",
    fullName: "Introduction to NGO Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BMS-2",
    title: "Management Functions",
    name: "BMS-2",
    fullName: "Management Functions",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BMS-3",
    title: "Health Care Management",
    name: "BMS-3",
    fullName: "Health Care Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ECO-1",
    title: "Business Organisation",
    name: "ECO-1",
    fullName: "Business Organisation",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "PCO-1",
    title: "Preparatory Course in Commerce",
    name: "PCO-1",
    fullName: "Preparatory Course in Commerce",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BCOA-1",
    title: "Business Communication & Entrepreneurship",
    name: "BCOA-1",
    fullName: "Business Communication & Entrepreneurship",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CITL-1",
    title: "Laboratory Course",
    name: "CITL-1",
    fullName: "Laboratory Course",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BPOI-6",
    title: "English Communication/Communication Skills",
    name: "BPOI-6",
    fullName: "English Communication/Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BPOI-6(P)",
    title: "English Communication/Communication Skills",
    name: "BPOI-6(P)",
    fullName: "English Communication/Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BPOI-7",
    title: "IT Skills",
    name: "BPOI-7",
    fullName: "IT Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BPOI-7(P)",
    title: "IT Skills",
    name: "BPOI-7(P)",
    fullName: "IT Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OSEI-41",
    title: "Information Security",
    name: "OSEI-41",
    fullName: "Information Security",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OSEI-41(P)",
    title: "Information Security",
    name: "OSEI-41(P)",
    fullName: "Information Security",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OSEI-42",
    title: "Securing Internet Access",
    name: "OSEI-42",
    fullName: "Securing Internet Access",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OSEI-42(P)",
    title: "Securing Internet Access",
    name: "OSEI-42(P)",
    fullName: "Securing Internet Access",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OSE-43",
    title: "Information Technology Security",
    name: "OSE-43",
    fullName: "Information Technology Security",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OSEI-44",
    title: "Server Security",
    name: "OSEI-44",
    fullName: "Server Security",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OSEI-44(P)",
    title: "Server Security",
    name: "OSEI-44(P)",
    fullName: "Server Security",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFDI-71",
    title: "Fundamentals of Fashion Design",
    name: "BFDI-71",
    fullName: "Fundamentals of Fashion Design",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFDI-71(P)",
    title: "Fundamentals of Fashion Design",
    name: "BFDI-71(P)",
    fullName: "Fundamentals of Fashion Design",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFDI-72",
    title: "Basics of Pattem Making and Sewing",
    name: "BFDI-72",
    fullName: "Basics of Pattem Making and Sewing",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFDI-72(P)",
    title: "Basics of Pattem Making and Sewing",
    name: "BFDI-72(P)",
    fullName: "Basics of Pattem Making and Sewing",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFDI-73",
    title: "Introduction to Fashion Industry",
    name: "BFDI-73",
    fullName: "Introduction to Fashion Industry",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFDI-73(P)",
    title: "Introduction to Fashion Industry",
    name: "BFDI-73(P)",
    fullName: "Introduction to Fashion Industry",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFD-74",
    title: "Communication and Entrepreneurship",
    name: "BFD-74",
    fullName: "Communication and Entrepreneurship",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "TS-1",
    title: "Foundation Course in Tourism",
    name: "TS-1",
    fullName: "Foundation Course in Tourism",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "TS-2",
    title: "Tourism Development: Products, Operations and Case Studies",
    name: "TS-2",
    fullName: "Tourism Development: Products, Operations and Case Studies",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLT-101",
    title: "Good Laboratory Practices",
    name: "CLT-101",
    fullName: "Good Laboratory Practices",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLTL-101",
    title: "Good Laboratory Practices: Basic Exercises",
    name: "CLTL-101",
    fullName: "Good Laboratory Practices: Basic Exercises",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLT-102",
    title: "Laboratory Techniques in Biology",
    name: "CLT-102",
    fullName: "Laboratory Techniques in Biology",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLTL-102",
    title: "Basic Experiments in Biology",
    name: "CLTL-102",
    fullName: "Basic Experiments in Biology",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLT-103",
    title: "Laboratory Techniques in Chemistry",
    name: "CLT-103",
    fullName: "Laboratory Techniques in Chemistry",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLTL-103",
    title: "Basic Experiments in Chemistry",
    name: "CLTL-103",
    fullName: "Basic Experiments in Chemistry",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLT-104",
    title: "Laboratory Techniques in Physics",
    name: "CLT-104",
    fullName: "Laboratory Techniques in Physics",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CLTL-104",
    title: "Basic Experiments in Physics",
    name: "CLTL-104",
    fullName: "Basic Experiments in Physics",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "AMT-1",
    title: "Teaching of Primary School Mathematics",
    name: "AMT-1",
    fullName: "Teaching of Primary School Mathematics",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "LMT-1",
    title: "Learning Mathematics",
    name: "LMT-1",
    fullName: "Learning Mathematics",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFE-101",
    title: "Basics ofHIV/AIDS",
    name: "BFE-101",
    fullName: "Basics ofHIV/AIDS",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFE-102",
    title: "Basics of Family Education",
    name: "BFE-102",
    fullName: "Basics of Family Education",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFEE-101",
    title: "Elective on HIV/AIDS",
    name: "BFEE-101",
    fullName: "Elective on HIV/AIDS",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFEE-102",
    title: "Elective on Family Education",
    name: "BFEE-102",
    fullName: "Elective on Family Education",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFEE-103",
    title: "Alcohol, Drugs & HIV",
    name: "BFEE-103",
    fullName: "Alcohol, Drugs & HIV",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFEE-104",
    title: "Commmunication & Counselling in HIV",
    name: "BFEE-104",
    fullName: "Commmunication & Counselling in HIV",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MSW-31",
    title: "Social Work Intervention in Correctional Settings (Compulsory)",
    name: "MSW-31",
    fullName: "Social Work Intervention in Correctional Settings (Compulsory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MSW-32",
    title: "Social Work and Criminal Justice (Compulsory)",
    name: "MSW-32",
    fullName: "Social Work and Criminal Justice (Compulsory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MSWL-33",
    title: "Social Work Practicum in Correctional Settings (Compulsory)",
    name: "MSWL-33",
    fullName: "Social Work Practicum in Correctional Settings (Compulsory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BSW-41",
    title: "Understanding Tribals",
    name: "BSW-41",
    fullName: "Understanding Tribals",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BSW-42",
    title: "Tribal Society",
    name: "BSW-42",
    fullName: "Tribal Society",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BSW-43",
    title: "Tribals of South and Central India",
    name: "BSW-43",
    fullName: "Tribals of South and Central India",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BSW-44",
    title: "Tribals in North and Northeast Region of India",
    name: "BSW-44",
    fullName: "Tribals in North and Northeast Region of India",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLP-1",
    title: "Introduction to Sericulture",
    name: "BLP-1",
    fullName: "Introduction to Sericulture",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLPI-2",
    title: "Host Plant Cultivation",
    name: "BLPI-2",
    fullName: "Host Plant Cultivation",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLPI-3",
    title: "Silkworm Rearing",
    name: "BLPI-3",
    fullName: "Silkworm Rearing",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BLP-4",
    title: "Crop Protection",
    name: "BLP-4",
    fullName: "Crop Protection",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAP-1",
    title: "Introduction to Organic Farming",
    name: "BAP-1",
    fullName: "Introduction to Organic Farming",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAPI-1",
    title: "Organic Production System",
    name: "BAPI-1",
    fullName: "Organic Production System",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAPI-2",
    title: "Inspection and Certification of Organic Produce",
    name: "BAPI-2",
    fullName: "Inspection and Certification of Organic Produce",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAPI-3",
    title: "Economics and Marketing of Organic Produce",
    name: "BAPI-3",
    fullName: "Economics and Marketing of Organic Produce",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ONR-1",
    title: "Introduction to Water Harvesting",
    name: "ONR-1",
    fullName: "Introduction to Water Harvesting",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ONR-2",
    title: "Basics of Hydrology",
    name: "ONR-2",
    fullName: "Basics of Hydrology",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ONR-3",
    title: "Water Harvesting, Conservation and Utilization",
    name: "ONR-3",
    fullName: "Water Harvesting, Conservation and Utilization",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ONRL-1",
    title: "Practical Training at Water Harvesting Agency",
    name: "ONRL-1",
    fullName: "Practical Training at Water Harvesting Agency",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OLP-1",
    title: "Introduction to Poultry Farming",
    name: "OLP-1",
    fullName: "Introduction to Poultry Farming",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OLPI-1",
    title: "Poultry Housing and Management",
    name: "OLPI-1",
    fullName: "Poultry Housing and Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OLPI-2",
    title: "Poultry Feeds and Feeding",
    name: "OLPI-2",
    fullName: "Poultry Feeds and Feeding",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OLPL-1",
    title: "Poultry Health Care and Bio-security Measures",
    name: "OLPL-1",
    fullName: "Poultry Health Care and Bio-security Measures",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OLPL-2",
    title: "Poultry Farm Training",
    name: "OLPL-2",
    fullName: "Poultry Farm Training",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OAPI-11",
    title: "Introduction to Beekeeping",
    name: "OAPI-11",
    fullName: "Introduction to Beekeeping",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OAPI-12",
    title: "Management of Honey Bee Colonies",
    name: "OAPI-12",
    fullName: "Management of Honey Bee Colonies",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OAPI-13",
    title: "Hive Products and Economics of Beekeeping",
    name: "OAPI-13",
    fullName: "Hive Products and Economics of Beekeeping",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAL-1",
    title: "Basics of Arabic",
    name: "BAL-1",
    fullName: "Basics of Arabic",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BAL-2",
    title: "Communication Skills",
    name: "BAL-2",
    fullName: "Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFLI-1",
    title: "Talking About Oneself",
    name: "BFLI-1",
    fullName: "Talking About Oneself",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFLI-2",
    title: "Interaction",
    name: "BFLI-2",
    fullName: "Interaction",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFLI-3",
    title: "Space",
    name: "BFLI-3",
    fullName: "Space",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BFLI-4",
    title: "Time",
    name: "BFLI-4",
    fullName: "Time",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ORU-001",
    title: "Communication Skills-I",
    name: "ORU-001",
    fullName: "Communication Skills-I",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ORUL-002",
    title: "Communication Skills-II",
    name: "ORUL-002",
    fullName: "Communication Skills-II",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BJLI-1",
    title: "Basic Japanese - 01",
    name: "BJLI-1",
    fullName: "Basic Japanese - 01",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BJLI-2",
    title: "Basic Japanese - 02",
    name: "BJLI-2",
    fullName: "Basic Japanese - 02",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BJLI-3",
    title: "Basic Japanese - 03",
    name: "BJLI-3",
    fullName: "Basic Japanese - 03",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BJLI-4",
    title: "Basic Japanese - 04",
    name: "BJLI-4",
    fullName: "Basic Japanese - 04",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BKL-1",
    title: "Basics of Korean – I",
    name: "BKL-1",
    fullName: "Basics of Korean – I",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BKL-2",
    title: "Basics of Korean – II",
    name: "BKL-2",
    fullName: "Basics of Korean – II",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BSL-1",
    title: "Basics of Spanish Language and Culture-I",
    name: "BSL-1",
    fullName: "Basics of Spanish Language and Culture-I",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BSL-2",
    title: "Basics of Spanish Language and Culture-II",
    name: "BSL-2",
    fullName: "Basics of Spanish Language and Culture-II",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BGL-1",
    title: "German Language Course-I",
    name: "BGL-1",
    fullName: "German Language Course-I",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BGL-2",
    title: "German Language Course-II",
    name: "BGL-2",
    fullName: "German Language Course-II",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BGL-3",
    title: "German Language Course-III",
    name: "BGL-3",
    fullName: "German Language Course-III",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BPEL-11",
    title: "Basics of Persian",
    name: "BPEL-11",
    fullName: "Basics of Persian",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BPEL-12",
    title: "Communication Skills",
    name: "BPEL-12",
    fullName: "Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNS-40",
    title: "Basics of First Aid (Theory)",
    name: "BNS-40",
    fullName: "Basics of First Aid (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNSL-40",
    title: "Skills in First Aid (Practical)",
    name: "BNSL-40",
    fullName: "Skills in First Aid (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BYG-1",
    title: "Introduction to Yoga and Yogic texts",
    name: "BYG-1",
    fullName: "Introduction to Yoga and Yogic texts",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BYG-2",
    title: "Yoga and Health",
    name: "BYG-2",
    fullName: "Yoga and Health",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BYGL-1",
    title: "Shat Kriyas, Yogic Kriyas, Asanas, Pranayama, Mantra Japa",
    name: "BYGL-1",
    fullName: "Shat Kriyas, Yogic Kriyas, Asanas, Pranayama, Mantra Japa",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHM-101",
    title:
      "Fundamentals: Environment and Health, Health Care Waste Management Regulations",
    name: "BHM-101",
    fullName:
      "Fundamentals: Environment and Health, Health Care Waste Management Regulations",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHM-102",
    title: "Health Care Waste Management: Concepts, Technologies and Training",
    name: "BHM-102",
    fullName:
      "Health Care Waste Management: Concepts, Technologies and Training",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHME-101",
    title: "Inter-relationship between Health and Environment",
    name: "BHME-101",
    fullName: "Inter-relationship between Health and Environment",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHME-102",
    title: "Worker Safety and Patient Safety",
    name: "BHME-102",
    fullName: "Worker Safety and Patient Safety",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHME-103",
    title:
      "Current Status of Health Care Waste Management and Legislation in the Regional Countries",
    name: "BHME-103",
    fullName:
      "Current Status of Health Care Waste Management and Legislation in the Regional Countries",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHME-104",
    title: "Managerial and Systems Approach",
    name: "BHME-104",
    fullName: "Managerial and Systems Approach",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHME-105",
    title: "Special Considerations of Waste Management",
    name: "BHME-105",
    fullName: "Special Considerations of Waste Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHME-106",
    title: "Administrative and Legal Aspects of Waste Management",
    name: "BHME-106",
    fullName: "Administrative and Legal Aspects of Waste Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHMP-101",
    title: "Project",
    name: "BHMP-101",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHML-101",
    title: "Workshop",
    name: "BHML-101",
    fullName: "Workshop",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNS-115",
    title: "Nursing Care of New Born and Infant",
    name: "BNS-115",
    fullName: "Nursing Care of New Born and Infant",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNSL-115",
    title: "Nursing Practices and Procedures in Care of Newborn and Infant",
    name: "BNSL-115",
    fullName: "Nursing Practices and Procedures in Care of Newborn and Infant",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNS-117",
    title: "Maternal and Child Health Care",
    name: "BNS-117",
    fullName: "Maternal and Child Health Care",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNSL-117",
    title: "Practices and Procedures in Maternal and Child Health Care",
    name: "BNSL-117",
    fullName: "Practices and Procedures in Maternal and Child Health Care",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CNS-HC-1",
    title: "Home Based Care (Theory)",
    name: "BNSL-117",
    fullName: "Practices and Procedures in Maternal and Child Health Care",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CNS-HCP-1",
    title: "Skills Related to Home Based Care (Practical)",
    name: "CNS-HCP-1",
    fullName: "Skills Related to Home Based Care (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-1",
    title: "Foundation of General Duty Assistance",
    name: "BHT-1",
    fullName: "Foundation of General Duty Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-2",
    title: "Basic Needs of PatientCare",
    name: "BHT-2",
    fullName: "Basic Needs of PatientCare",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHTL-3",
    title: "Fundamental Skills for General Duty Assistance",
    name: "BHTL-3",
    fullName: "Fundamental Skills for General Duty Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-6",
    title: "Foundation for Geriatric Care Assistance",
    name: "BHT-6",
    fullName: "Foundation for Geriatric Care Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-7",
    title: "Special Needs of Geriatric Patients",
    name: "BHT-7",
    fullName: "Special Needs of Geriatric Patients",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHTL-8",
    title: "Skills for Geriatric Care Assistance",
    name: "BHTL-8",
    fullName: "Skills for Geriatric Care Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-11",
    title: "Basic Phlebotomy Assistance",
    name: "BHT-11",
    fullName: "Basic Phlebotomy Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-12",
    title: "Handling of Blood Samples",
    name: "BHT-12",
    fullName: "Handling of Blood Samples",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHTL-13",
    title: "Skills for Phlebotomy Assistance",
    name: "BHTL-13",
    fullName: "Skills for Phlebotomy Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-16",
    title: "Basic Home Health Assistance",
    name: "BHT-16",
    fullName: "Basic Home Health Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHT-17",
    title: "Applied Home Health Assistance",
    name: "BHT-17",
    fullName: "Applied Home Health Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BHTL-18",
    title: "Skills for Home Health Assistance",
    name: "BHTL-18",
    fullName: "Skills for Home Health Assistance",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNS-41",
    title: "Foundations of Community Health",
    name: "BNS-41",
    fullName: "Foundations of Community Health",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNS-42",
    title: "Primary Health Care in Common Conditions",
    name: "BNS-42",
    fullName: "Primary Health Care in Common Conditions",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BNS-43",
    title: "Public Health and Primary Health Care Skills",
    name: "BNS-43",
    fullName: "Public Health and Primary Health Care Skills",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CNS-AH-001",
    title: "Theory Course – 1Fundamentals of Adolescence",
    name: "CNS-AH-001",
    fullName: "Theory Course – 1Fundamentals of Adolescence",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CNS-AH-002",
    title: "Theory Course – 2 Issues & Challenges during Adolescence",
    name: "CNS-AH-002",
    fullName: "Theory Course – 2 Issues & Challenges during Adolescence",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "CNS-AHL-001",
    title:
      "Practical Title of the course: Practical Manual on Adolescent Health",
    name: "CNS-AHL-001",
    fullName:
      "Practical Title of the course: Practical Manual on Adolescent Health",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OVA-1",
    title: "Indian Cultural Heritage (Theory)",
    name: "OVA-1",
    fullName: "Indian Cultural Heritage (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OVA-2",
    title: "Understanding Indian Art Forms (Theory)",
    name: "OVA-2",
    fullName: "Understanding Indian Art Forms (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OVA-3",
    title: "An Introduction to Indian Arts (Theory)",
    name: "OVA-3",
    fullName: "An Introduction to Indian Arts (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OVAL-4",
    title: "Direct Study from Simple Objects (Practical)",
    name: "OVAL-4",
    fullName: "Direct Study from Simple Objects (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OVAL-5",
    title: "Study from Still Life (Practical)",
    name: "OVAL-5",
    fullName: "Study from Still Life (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OVAL-6",
    title: "Composition in Painting (Practical)",
    name: "OVAL-6",
    fullName: "Composition in Painting (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OVAL-7",
    title: "Geometrical Design (Practical)",
    name: "OVAL-7",
    fullName: "Geometrical Design (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OTH-1",
    title: "An Introduction to Theatre & Drama (Theory)",
    name: "OTH-1",
    fullName: "An Introduction to Theatre & Drama (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OTHL-2",
    title: "Voice & Speech (Practical)",
    name: "OTHL-2",
    fullName: "Voice & Speech (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OTHL-3",
    title: "Physical Aspects of Acting (Practical)",
    name: "OTHL-3",
    fullName: "Physical Aspects of Acting (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OTHL-4",
    title: "Method Acting-Stanislavisky (Practical)",
    name: "OTHL-4",
    fullName: "Method Acting-Stanislavisky (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMU-1",
    title: "An Introduction to Hindustani Music (Theory)",
    name: "OMU-1",
    fullName: "An Introduction to Hindustani Music (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMUL-2",
    title: "(Practical-1)",
    name: "OMUL-2",
    fullName: "(Practical-1)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMUL-3",
    title: "(Practical-2)",
    name: "OMUL-3",
    fullName: "(Practical-2)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMUL-4",
    title: "(Practical-3)",
    name: "OMUL-4",
    fullName: "(Practical-3)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMU-5",
    title: "An Introduction to Karnatak Music (Theory)",
    name: "OMU-5",
    fullName: "An Introduction to Karnatak Music (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMUL-6",
    title: "Paper-1 (Practical)",
    name: "OMUL-6",
    fullName: "Paper-1 (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMUL-7",
    title: "Paper-2 (Practical)",
    name: "OMUL-7",
    fullName: "Paper-2 (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OMUL-8",
    title: "Paper-3 (Practical)",
    name: "OMUL-8",
    fullName: "Paper-3 (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ODN-1",
    title: "Introduction to Indian Dance Forms (Theory)",
    name: "ODN-1",
    fullName: "Introduction to Indian Dance Forms (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ODNL-11",
    title: "Bharatanatyam 1 (Practical)",
    name: "ODNL-11",
    fullName: "Bharatanatyam 1 (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ODNL-12",
    title: "Bharatanatyam 2 (Practical)",
    name: "ODNL-12",
    fullName: "Bharatanatyam 2 (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "ODNL-13",
    title: "Music and Talas (Practical)",
    name: "ODNL-13",
    fullName: "Music and Talas (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OEY-1",
    title: "Energy Resources and Conversion Processes",
    name: "OEY-1",
    fullName: "Energy Resources and Conversion Processes",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OEY-2",
    title: "Renewable Energy Technologies and their Uses",
    name: "OEY-2",
    fullName: "Renewable Energy Technologies and their Uses",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OEY-3",
    title: "Energy Management: Audit and Conservation",
    name: "OEY-3",
    fullName: "Energy Management: Audit and Conservation",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OEYP-4",
    title: "Energy Projects",
    name: "OEYP-4",
    fullName: "Energy Projects",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OEE-1",
    title: "Electricity and Safety Measures",
    name: "OEE-1",
    fullName: "Electricity and Safety Measures",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OEE-2",
    title: "Power Distribution System – Basics",
    name: "OEE-2",
    fullName: "Power Distribution System – Basics",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "OEEL-1",
    title: "Practical in Power Distribution",
    name: "OEEL-1",
    fullName: "Practical in Power Distribution",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BWA-001",
    title: "Solid Wastes & Regulatory Framework",
    name: "BWA-001",
    fullName: "Solid Wastes & Regulatory Framework",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BWA-002",
    title: "Solid Wastes Collection and Transportation",
    name: "BWA-002",
    fullName: "Solid Wastes Collection and Transportation",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BWA-003",
    title: "Solid Wastes Processing and Treatment Techniques",
    name: "BWA-003",
    fullName: "Solid Wastes Processing and Treatment Techniques",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BWA-004",
    title: "Disposal of Wastes",
    name: "BWA-004",
    fullName: "Disposal of Wastes",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BWAP-001",
    title: "Project",
    name: "BWAP-001",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEDS-1",
    title: "Overview and Perspectives of Values (Theory)",
    name: "BEDS-1",
    fullName: "Overview and Perspectives of Values (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEDS-2",
    title: "Socio-Psychological Basis (Theory)",
    name: "BEDS-2",
    fullName: "Socio-Psychological Basis (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEDS-3",
    title: "Pedagogy of Values (Theory)",
    name: "BEDS-3",
    fullName: "Pedagogy of Values (Theory)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEDS-4",
    title: "Application Support Skills (Theory) and Activities",
    name: "BEDS-4",
    fullName: "Application Support Skills (Theory) and Activities",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEV-001",
    title: "Introduction to Solid Waste Management",
    name: "BEV-001",
    fullName: "Introduction to Solid Waste Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEV-002",
    title: "Municipal, Agricultural, Industrial and Hazardous Waste Management",
    name: "BEV-002",
    fullName:
      "Municipal, Agricultural, Industrial and Hazardous Waste Management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BEV-003",
    title:
      "Plastic, E-waste, Biomedical and Construction and Demolition Waste management",
    name: "BEV-003",
    fullName:
      "Plastic, E-waste, Biomedical and Construction and Demolition Waste management",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BJM-1",
    title: "Introduction to Community Radio",
    name: "BJM-1",
    fullName: "Introduction to Community Radio",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BJM-2",
    title: "Operating a Community Radio",
    name: "BJM-2",
    fullName: "Operating a Community Radio",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "BJMP-1",
    title: "Practical/Internship (10 days)",
    name: "BJMP-1",
    fullName: "Practical/Internship (10 days)",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MGS-041",
    title: "Introduction to Gender, Agriculture and Sustainable development",
    name: "MGS-041",
    fullName: "Introduction to Gender, Agriculture and Sustainable development",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MGS-042",
    title: "Gender dynamics in Agriculture",
    name: "MGS-042",
    fullName: "Gender dynamics in Agriculture",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
  {
    code: "MGS-043",
    title: "Gender and Sustainable Development",
    name: "MGS-043",
    fullName: "Gender and Sustainable Development",
    collegeCode: "IGNOU",
    programmeCode: "BSCG",
    term: 1,
  },
];
