export const diplomaCourses = [
  {
    code: "DECE-1",
    title: "Organizing Child Care Services",
    name: "DECE-1",
    fullName: "Organizing Child Care Services",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DECE-2",
    title: "Child Health and Nutrition",
    name: "DECE-2",
    fullName: "Child Health and Nutrition",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DECE-3",
    title: "Services and Programmes for Children",
    name: "DECE-3",
    fullName: "Services and Programmes for Children",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DECE-4",
    title: "Project Work: Working with Young Children in a Child Care Setting",
    name: "DECE-4",
    fullName:
      "Project Work: Working with Young Children in a Child Care Setting",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DNHE-1",
    title: "Nutrition for the Community",
    name: "DNHE-1",
    fullName: "Nutrition for the Community",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DNHE-2",
    title: "Public Health and Hygiene",
    name: "DNHE-2",
    fullName: "Public Health and Hygiene",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DNHE-3",
    title: "Nutrition and Health Education",
    name: "DNHE-3",
    fullName: "Nutrition and Health Education",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DNHE-4",
    title: "Project Work : Nutrition and Health Education",
    name: "DNHE-4",
    fullName: "Project Work : Nutrition and Health Education",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPR-1",
    title: "Panchayats in India: The Context",
    name: "BPR-1",
    fullName: "Panchayats in India: The Context",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPR-2",
    title: "Decentralized Planning and Panchayati Raj",
    name: "BPR-2",
    fullName: "Decentralized Planning and Panchayati Raj",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPR-3",
    title: "Panchayati Raj Institutions and Anti Poverty Programme",
    name: "BPR-3",
    fullName: "Panchayati Raj Institutions and Anti Poverty Programme",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPR-4",
    title: "Project Work",
    name: "BPR-4",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPR-5",
    title: "Basic Computer Literacy",
    name: "BPR-5",
    fullName: "Basic Computer Literacy",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BHC-11",
    title: "Basics of Event Management",
    name: "BHC-11",
    fullName: "Basics of Event Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BHC-12",
    title: "Event Planning",
    name: "BHC-12",
    fullName: "Event Planning",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BHC-13",
    title: "Event Coordination and Control",
    name: "BHC-13",
    fullName: "Event Coordination and Control",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BHC-14",
    title: "Event Marketing and Promotion",
    name: "BHC-14",
    fullName: "Event Marketing and Promotion",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BHC-15",
    title: "Event Financing and Accounting",
    name: "BHC-15",
    fullName: "Event Financing and Accounting",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BHCP-11",
    title: "Internship",
    name: "BHCP-11",
    fullName: "Internship",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BHCL-11",
    title: "Practicum",
    name: "BHCL-11",
    fullName: "Practicum",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "TS-1",
    title: "Foundation Course in Tourism",
    name: "TS-1",
    fullName: "Foundation Course in Tourism",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "TS-2",
    title: "Tourism Development: Products, Operations and Case Studies",
    name: "TS-2",
    fullName: "Tourism Development: Products, Operations and Case Studies",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "TS-3",
    title: "Management in Tourism",
    name: "TS-3",
    fullName: "Management in Tourism",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "TS-4",
    title: "Indian Culture - Perspective for Tourism",
    name: "TS-4",
    fullName: "Indian Culture - Perspective for Tourism",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "PTS-4",
    title: "Project on Indian Culture: Perspective for Tourism",
    name: "PTS-4",
    fullName: "Project on Indian Culture: Perspective for Tourism",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "TS-5",
    title: "Ecology, Environment and Tourism",
    name: "TS-5",
    fullName: "Ecology, Environment and Tourism",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "PTS-5",
    title: "Project on Ecology, Environment and Tourism",
    name: "PTS-5",
    fullName: "Project on Ecology, Environment and Tourism",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "TS-6",
    title: "Tourism Marketing",
    name: "TS-6",
    fullName: "Tourism Marketing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "PTS-6",
    title: "Project on Tourism Marketing",
    name: "PTS-6",
    fullName: "Project on Tourism Marketing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DCE-1",
    title: "General Principles of Writing",
    name: "DCE-1",
    fullName: "General Principles of Writing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DCE-6",
    title: "Guided Project Work",
    name: "DCE-6",
    fullName: "Guided Project Work",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DCE-2",
    title: "Feature Writing",
    name: "DCE-2",
    fullName: "Feature Writing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DCE-3",
    title: "Short Story",
    name: "DCE-3",
    fullName: "Short Story",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DCE-4",
    title: "Writing for Media: Radio and Television",
    name: "DCE-4",
    fullName: "Writing for Media: Radio and Television",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DCE-5",
    title: "Writing Poetry",
    name: "DCE-5",
    fullName: "Writing Poetry",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "OUL-3",
    title: "History of Urdu Language & Literature",
    name: "OUL-3",
    fullName: "History of Urdu Language & Literature",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "OULP-1",
    title: "Project Work",
    name: "OULP-1",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "OULE-1",
    title: "Contemporary Urdu Poetry",
    name: "OULE-1",
    fullName: "Contemporary Urdu Poetry",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "OULE-2",
    title: "Contemporary Urdu Fiction",
    name: "OULE-2",
    fullName: "Contemporary Urdu Fiction",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "OULE-5",
    title: "Principle of Translation",
    name: "OULE-5",
    fullName: "Principle of Translation",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-1",
    title: "Food Fundamentals",
    name: "BPVI-1",
    fullName: "Food Fundamentals",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-2",
    title: "Principles of Post Harvest Management of Fruits and Vegetables",
    name: "BPVI-2",
    fullName: "Principles of Post Harvest Management of Fruits and Vegetables",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-3",
    title: "Food Chemistry and Physiology",
    name: "BPVI-3",
    fullName: "Food Chemistry and Physiology",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-4",
    title: "Food Processing and Engineering-I",
    name: "BPVI-4",
    fullName: "Food Processing and Engineering-I",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-5",
    title: "Food Microbiology",
    name: "BPVI-5",
    fullName: "Food Microbiology",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-6",
    title: "Food Processing and Engineering-II",
    name: "BPVI-6",
    fullName: "Food Processing and Engineering-II",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-7",
    title: "Food Quality Testing and Evaluation",
    name: "BPVI-7",
    fullName: "Food Quality Testing and Evaluation",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-8",
    title: "Entrepreneurship and Marketing",
    name: "BPVI-8",
    fullName: "Entrepreneurship and Marketing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-11",
    title: "Milk Production and Quality of Milk",
    name: "BPVI-11",
    fullName: "Milk Production and Quality of Milk",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-12",
    title: "Dairy Equipment and Utilities",
    name: "BPVI-12",
    fullName: "Dairy Equipment and Utilities",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-13",
    title: "Milk Processing and Packaging",
    name: "BPVI-13",
    fullName: "Milk Processing and Packaging",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-14",
    title: "Dairy Products – I",
    name: "BPVI-14",
    fullName: "Dairy Products – I",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-15",
    title: "Dairy Products - II",
    name: "BPVI-15",
    fullName: "Dairy Products - II",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-16",
    title: "Dairy Products - III",
    name: "BPVI-16",
    fullName: "Dairy Products - III",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-17",
    title: "Quality Assurance",
    name: "BPVI-17",
    fullName: "Quality Assurance",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-18",
    title: "Dairy Management and Entrepreneurship",
    name: "BPVI-18",
    fullName: "Dairy Management and Entrepreneurship",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-21",
    title: "Fundamental of Food and Meat Science",
    name: "BPVI-21",
    fullName: "Fundamental of Food and Meat Science",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-22",
    title: "Meat Animals and Abattoir Practices",
    name: "BPVI-22",
    fullName: "Meat Animals and Abattoir Practices",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-23",
    title: "Fresh Meat Technology",
    name: "BPVI-23",
    fullName: "Fresh Meat Technology",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-24",
    title: "Processed Meat Technology",
    name: "BPVI-24",
    fullName: "Processed Meat Technology",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-25",
    title: "Meat Packaging and Quality Assurance",
    name: "BPVI-25",
    fullName: "Meat Packaging and Quality Assurance",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-26",
    title: "Poultry Products Technology",
    name: "BPVI-26",
    fullName: "Poultry Products Technology",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-27",
    title: "Utilization of Animal By-Products",
    name: "BPVI-27",
    fullName: "Utilization of Animal By-Products",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPVI-28",
    title: "Marketing and Entrepreneurship",
    name: "BPVI-28",
    fullName: "Marketing and Entrepreneurship",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRI-101",
    title: "Fundamentals of Watershed Management",
    name: "BNRI-101",
    fullName: "Fundamentals of Watershed Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRI-102",
    title: "Elements of Hydrology",
    name: "BNRI-102",
    fullName: "Elements of Hydrology",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRI-103",
    title: "Soil and Water Conservation",
    name: "BNRI-103",
    fullName: "Soil and Water Conservation",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRI-104",
    title: "Rainfed Farming",
    name: "BNRI-104",
    fullName: "Rainfed Farming",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRI-105",
    title: "Livestock and Pasture Management",
    name: "BNRI-105",
    fullName: "Livestock and Pasture Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRI-106",
    title: "Horticulture and Agro-Forestry Systems",
    name: "BNRI-106",
    fullName: "Horticulture and Agro-Forestry Systems",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRI-107",
    title: "Funding, Monitoring, Evaluation & Capacity Building",
    name: "BNRI-107",
    fullName: "Funding, Monitoring, Evaluation & Capacity Building",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNRP-108",
    title: "Project Formulation",
    name: "BNRP-108",
    fullName: "Project Formulation",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAP-002",
    title: "Basic Horticulture",
    name: "BAP-002",
    fullName: "Basic Horticulture",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAPI-004",
    title: "Production Technology of Fruit Crops",
    name: "BAPI-004",
    fullName: "Production Technology of Fruit Crops",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAPI-005",
    title: "Production Technology of Vegetable Crops",
    name: "BAPI-005",
    fullName: "Production Technology of Vegetable Crops",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAPI-006",
    title: "Floriculture and Landscaping",
    name: "BAPI-006",
    fullName: "Floriculture and Landscaping",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAPI-007",
    title: "Plant Propagation and Nursery Management",
    name: "BAPI-007",
    fullName: "Plant Propagation and Nursery Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BWEE-12",
    title: "Women and Society: Global Concerns and Local Issues",
    name: "BWEE-12",
    fullName: "Women and Society: Global Concerns and Local Issues",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BWEE-4",
    title: "Strategies for Women’s Empowerment",
    name: "BWEE-4",
    fullName: "Strategies for Women’s Empowerment",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BWEE-5",
    title: "Women and Development",
    name: "BWEE-5",
    fullName: "Women and Development",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BWEF-2",
    title: "Gender Training Perspectives",
    name: "BWEF-2",
    fullName: "Gender Training Perspectives",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BWEE-6",
    title: "Organization and Leadership",
    name: "BWEE-6",
    fullName: "Organization and Leadership",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BWEE-7",
    title: "Work and Enterpreneurship",
    name: "BWEE-7",
    fullName: "Work and Enterpreneurship",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BWEE-8",
    title: "Credit and Finance",
    name: "BWEE-8",
    fullName: "Credit and Finance",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BFE-101",
    title: "Basics of HIV/AIDS",
    name: "BFE-101",
    fullName: "Basics of HIV/AIDS",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BFEE-101",
    title: "Elective on HIV / AIDS",
    name: "BFEE-101",
    fullName: "Elective on HIV / AIDS",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BFE-102",
    title: "Basics of Family Education",
    name: "BFE-102",
    fullName: "Basics of Family Education",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BFEE-102",
    title: "Elective on Family Education",
    name: "BFEE-102",
    fullName: "Elective on Family Education",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BFEE-103",
    title: "Alcohol, Drugs and HIV",
    name: "BFEE-103",
    fullName: "Alcohol, Drugs and HIV",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BFEE-104",
    title: "Communication and Counselling in HIV",
    name: "BFEE-104",
    fullName: "Communication and Counselling in HIV",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-101",
    title: "Introduction to Finance and Accounting BPO",
    name: "BPOI-101",
    fullName: "Introduction to Finance and Accounting BPO",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-102",
    title: "Fundamentals of Accounting",
    name: "BPOI-102",
    fullName: "Fundamentals of Accounting",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-103",
    title: "Procure to Pay (P2P, Accounts Payable)",
    name: "BPOI-103",
    fullName: "Procure to Pay (P2P, Accounts Payable)",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-104",
    title: "Order to Cash (O2C, Accounts Receivable)",
    name: "BPOI-104",
    fullName: "Order to Cash (O2C, Accounts Receivable)",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-105",
    title: "Record to Report (R2R)",
    name: "BPOI-105",
    fullName: "Record to Report (R2R)",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-6",
    title: "English Communication/Communication Skills",
    name: "BPOI-6",
    fullName: "English Communication/Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-6(P)",
    title: "English Communication/Communication Skills",
    name: "BPOI-6(P)",
    fullName: "English Communication/Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-7",
    title: "IT Skills",
    name: "BPOI-7",
    fullName: "IT Skills",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BPOI-7(P)",
    title: "IT Skills",
    name: "BPOI-7(P)",
    fullName: "IT Skills",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BSSI-11",
    title: "Communication Skills",
    name: "BSSI-11",
    fullName: "Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BSSI-12",
    title: "Computer Skills (Both theory and practical)",
    name: "BSSI-12",
    fullName: "Computer Skills (Both theory and practical)",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BSSI-13",
    title: "Secretarial Practice",
    name: "BSSI-13",
    fullName: "Secretarial Practice",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BSSI-14",
    title: "Stenographic Skills (Both theory and practical)",
    name: "BSSI-14",
    fullName: "Stenographic Skills (Both theory and practical)",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BSSI-14(P)",
    title: "Stenographic Skills (Both theory and practical)",
    name: "BSSI-14(P)",
    fullName: "Stenographic Skills (Both theory and practical)",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BSSI-15",
    title: "Office Procedures",
    name: "BSSI-15",
    fullName: "Office Procedures",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BLE-1",
    title: "Introduction to the Indian Legal System",
    name: "BLE-1",
    fullName: "Introduction to the Indian Legal System",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BLE-2",
    title: "Introduction to Law: Substantive and Procedural",
    name: "BLE-2",
    fullName: "Introduction to Law: Substantive and Procedural",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BLE-3",
    title: "Law and Vulnerable Groups",
    name: "BLE-3",
    fullName: "Law and Vulnerable Groups",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BLE-4",
    title: "Rural Local Self Governance",
    name: "BLE-4",
    fullName: "Rural Local Self Governance",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BLEP-1",
    title: "Project",
    name: "BLEP-1",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAQ-1",
    title: "Basics of Aquaculture",
    name: "BAQ-1",
    fullName: "Basics of Aquaculture",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAQP-1",
    title: "Project",
    name: "BAQP-1",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAQ-2",
    title: "Freshwater Aquaculture",
    name: "BAQ-2",
    fullName: "Freshwater Aquaculture",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAQL-1",
    title: "Laboratory",
    name: "BAQL-1",
    fullName: "Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAQ-3",
    title: "Coastal Aquaculture",
    name: "BAQ-3",
    fullName: "Coastal Aquaculture",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BAQL-2",
    title: "Laboratory",
    name: "BAQL-2",
    fullName: "Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BRL-1",
    title: "Overview of Retailing",
    name: "BRL-1",
    fullName: "Overview of Retailing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BRL-2",
    title: "Retail Marketing and Communication",
    name: "BRL-2",
    fullName: "Retail Marketing and Communication",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BRL-3",
    title: "Retail Management Perspectives and Communication",
    name: "BRL-3",
    fullName: "Retail Management Perspectives and Communication",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BRL-4",
    title: "Customer Service Management",
    name: "BRL-4",
    fullName: "Customer Service Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BRLT-5",
    title: "Internship and Viva-Voce",
    name: "BRLT-5",
    fullName: "Internship and Viva-Voce",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DTG-1",
    title: "General Princizieds of Teaching",
    name: "DTG-1",
    fullName: "General Princizieds of Teaching",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DTG-2",
    title: "Skill Development",
    name: "DTG-2",
    fullName: "Skill Development",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DTG-3",
    title: "Classroom Teaching",
    name: "DTG-3",
    fullName: "Classroom Teaching",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "DTG-4",
    title: "Lesson Planning Preparation Evaluation",
    name: "DTG-4",
    fullName: "Lesson Planning Preparation Evaluation",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNS-11",
    title: "Principles and Practice of Nursing Administration",
    name: "BNS-11",
    fullName: "Principles and Practice of Nursing Administration",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNS-12",
    title: "Management of Educational Institute, Hospital & Community",
    name: "BNS-12",
    fullName: "Management of Educational Institute, Hospital & Community",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNS-13",
    title: "Group Dynamics",
    name: "BNS-13",
    fullName: "Group Dynamics",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNS-14",
    title: "Resource Management",
    name: "BNS-14",
    fullName: "Resource Management",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNSL-11",
    title: "Nursing Service Administration-I",
    name: "BNSL-11",
    fullName: "Nursing Service Administration-I",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNSL-12",
    title: "Nursing Service Administration-II",
    name: "BNSL-12",
    fullName: "Nursing Service Administration-II",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNS-31",
    title: "Concept and Principles in Critical Care Nursing",
    name: "BNS-31",
    fullName: "Concept and Principles in Critical Care Nursing",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNS-32",
    title: "Nursing Management in Critical Care Conditions",
    name: "BNS-32",
    fullName: "Nursing Management in Critical Care Conditions",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNSL-33",
    title: "Clinical Nursing Practice in Critical Care-I",
    name: "BNSL-33",
    fullName: "Clinical Nursing Practice in Critical Care-I",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BNSL-34",
    title: "Clinical Nursing Practice in Critical Care-II",
    name: "BNSL-34",
    fullName: "Clinical Nursing Practice in Critical Care-II",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BTH-1",
    title: "Understanding Drama",
    name: "BTH-1",
    fullName: "Understanding Drama",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BTHL-2",
    title: "Theatre Games",
    name: "BTHL-2",
    fullName: "Theatre Games",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BTHL-3",
    title: "Acting Practice, Movement, Voice and Speech",
    name: "BTHL-3",
    fullName: "Acting Practice, Movement, Voice and Speech",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BTHI-4",
    title: "Scene Work",
    name: "BTHI-4",
    fullName: "Scene Work",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BTHI-5",
    title: "Class Room Play Production",
    name: "BTHI-5",
    fullName: "Class Room Play Production",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BEDS-001",
    title: "Overview and Perspectives of Values",
    name: "BEDS-001",
    fullName: "Overview and Perspectives of Values",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BEDS-002",
    title: "Socio-Psychological Basis",
    name: "BEDS-002",
    fullName: "Socio-Psychological Basis",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BEDS-003",
    title: "Pedagogy of Values",
    name: "BEDS-003",
    fullName: "Pedagogy of Values",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BEDS-004",
    title: "Application, Support Skills and Activities",
    name: "BEDS-004",
    fullName: "Application, Support Skills and Activities",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "BEDS-005",
    title: "Life Skills Education",
    name: "BEDS-005",
    fullName: "Life Skills Education",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "CHR-12",
    title: "Human Rights in India",
    name: "CHR-12",
    fullName: "Human Rights in India",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "MIO-001",
    title: "Introduction to Smart Regions: Smart Cities and Smart Villages",
    name: "MIO-001",
    fullName: "Introduction to Smart Regions: Smart Cities and Smart Villages",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "MIO-002",
    title: "Smart Technologies (Hardware and Software)",
    name: "MIO-002",
    fullName: "Smart Technologies (Hardware and Software)",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "MIO-003",
    title: "Smart Urban Energy Systems and Smart Transportation System",
    name: "MIO-003",
    fullName: "Smart Urban Energy Systems and Smart Transportation System",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "MIO-004",
    title: "Smart Cities: Health, Education, Governance & Cyber Security",
    name: "MIO-004",
    fullName: "Smart Cities: Health, Education, Governance & Cyber Security",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "MIO-005",
    title: "Smart Cities: Safe Water, Sanitation and Sustainability",
    name: "MIO-005",
    fullName: "Smart Cities: Safe Water, Sanitation and Sustainability",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
  {
    code: "MIOP-001",
    title: "Project",
    name: "MIOP-001",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "",
    term: 1,
  },
];
