export const diplomaCourses = [
  {
    code: "DECE-1",
    title: "Organizing Child Care Services",
  },
  {
    code: "DECE-2",
    title: "Child Health and Nutrition",
  },
  {
    code: "DECE-3",
    title: "Services and Programmes for Children",
  },
  {
    code: "DECE-4",
    title: "Project Work: Working with Young Children in a Child Care Setting",
  },
  {
    code: "DNHE-1",
    title: "Nutrition for the Community",
  },
  {
    code: "DNHE-2",
    title: "Public Health and Hygiene",
  },
  {
    code: "DNHE-3",
    title: "Nutrition and Health Education",
  },
  {
    code: "DNHE-4",
    title: "Project Work : Nutrition and Health Education",
  },
  {
    code: "BPR-1",
    title: "Panchayats in India: The Context",
  },
  {
    code: "BPR-2",
    title: "Decentralized Planning and Panchayati Raj",
  },
  {
    code: "BPR-3",
    title: "Panchayati Raj Institutions and Anti Poverty Programme",
  },
  {
    code: "BPR-4",
    title: "Project Work",
  },
  {
    code: "BPR-5",
    title: "Basic Computer Literacy",
  },
  {
    code: "BHC-11",
    title: "Basics of Event Management",
  },
  {
    code: "BHC-12",
    title: "Event Planning",
  },
  {
    code: "BHC-13",
    title: "Event Coordination and Control",
  },
  {
    code: "BHC-14",
    title: "Event Marketing and Promotion",
  },
  {
    code: "BHC-15",
    title: "Event Financing and Accounting",
  },
  {
    code: "BHCP-11",
    title: "Internship",
  },
  {
    code: "BHCL-11",
    title: "Practicum",
  },
  {
    code: "TS-1",
    title: "Foundation Course in Tourism",
  },
  {
    code: "TS-2",
    title: "Tourism Development: Products, Operations and Case Studies",
  },
  {
    code: "TS-3",
    title: "Management in Tourism",
  },
  {
    code: "TS-4",
    title: "Indian Culture - Perspective for Tourism",
  },
  {
    code: "PTS-4",
    title: "Project on Indian Culture: Perspective for Tourism",
  },
  { code: "TS-5", title: "Ecology, Environment and Tourism" },
  { code: "PTS-5", title: "Project on Ecology, Environment and Tourism" },
  { code: "TS-6", title: "Tourism Marketing" },
  { code: "PTS-6", title: "Project on Tourism Marketing" },
  { code: "DCE-1", title: "General Principles of Writing" },
  { code: "DCE-6", title: "Guided Project Work" },
  { code: "DCE-2", title: "Feature Writing" },
  { code: "DCE-3", title: "Short Story" },
  { code: "DCE-4", title: "Writing for Media: Radio and Television" },
  { code: "DCE-5", title: "Writing Poetry" },
  { code: "OUL-3", title: "History of Urdu Language & Literature" },
  { code: "OULP-1", title: "Project Work" },
  { code: "OULE-1", title: "Contemporary Urdu Poetry" },
  { code: "OULE-2", title: "Contemporary Urdu Fiction" },
  { code: "OULE-5", title: "Principle of Translation" },
  { code: "BPVI-1", title: "Food Fundamentals" },
  {
    code: "BPVI-2",
    title: "Principles of Post Harvest Management of Fruits and Vegetables",
  },
  { code: "BPVI-3", title: "Food Chemistry and Physiology" },
  { code: "BPVI-4", title: "Food Processing and Engineering-I" },
  { code: "BPVI-5", title: "Food Microbiology" },
  { code: "BPVI-6", title: "Food Processing and Engineering-II" },
  { code: "BPVI-7", title: "Food Quality Testing and Evaluation" },
  { code: "BPVI-8", title: "Entrepreneurship and Marketing" },
  { code: "BPVI-11", title: "Milk Production and Quality of Milk" },
  { code: "BPVI-12", title: "Dairy Equipment and Utilities" },
  { code: "BPVI-13", title: "Milk Processing and Packaging" },
  { code: "BPVI-14", title: "Dairy Products – I" },
  { code: "BPVI-15", title: "Dairy Products - II" },
  { code: "BPVI-16", title: "Dairy Products - III" },
  { code: "BPVI-17", title: "Quality Assurance" },
  { code: "BPVI-18", title: "Dairy Management and Entrepreneurship" },
  { code: "BPVI-21", title: "Fundamental of Food and Meat Science" },
  { code: "BPVI-22", title: "Meat Animals and Abattoir Practices" },
  { code: "BPVI-23", title: "Fresh Meat Technology" },
  { code: "BPVI-24", title: "Processed Meat Technology" },
  { code: "BPVI-25", title: "Meat Packaging and Quality Assurance" },
  { code: "BPVI-26", title: "Poultry Products Technology" },
  { code: "BPVI-27", title: "Utilization of Animal By-Products" },
  { code: "BPVI-28", title: "Marketing and Entrepreneurship" },
  { code: "BNRI-101", title: "Fundamentals of Watershed Management" },
  { code: "BNRI-102", title: "Elements of Hydrology" },
  { code: "BNRI-103", title: "Soil and Water Conservation" },
  { code: "BNRI-104", title: "Rainfed Farming" },
  { code: "BNRI-105", title: "Livestock and Pasture Management" },
  { code: "BNRI-106", title: "Horticulture and Agro-Forestry Systems" },
  {
    code: "BNRI-107",
    title: "Funding, Monitoring, Evaluation & Capacity Building",
  },
  { code: "BNRP-108", title: "Project Formulation" },
  { code: "BAP-002", title: "Basic Horticulture" },
  { code: "BAPI-004", title: "Production Technology of Fruit Crops" },
  { code: "BAPI-005", title: "Production Technology of Vegetable Crops" },
  { code: "BAPI-006", title: "Floriculture and Landscaping" },
  { code: "BAPI-007", title: "Plant Propagation and Nursery Management" },
  {
    code: "BWEE-12",
    title: "Women and Society: Global Concerns and Local Issues",
  },
  { code: "BWEE-4", title: "Strategies for Women’s Empowerment" },
  { code: "BWEE-5", title: "Women and Development" },
  { code: "BWEF-2", title: "Gender Training Perspectives" },
  { code: "BWEE-6", title: "Organization and Leadership" },
  { code: "BWEE-7", title: "Work and Enterpreneurship" },
  { code: "BWEE-8", title: "Credit and Finance" },
  { code: "BFE-101", title: "Basics of HIV/AIDS" },
  { code: "BFEE-101", title: "Elective on HIV / AIDS" },
  { code: "BFE-102", title: "Basics of Family Education" },
  { code: "BFEE-102", title: "Elective on Family Education" },
  { code: "BFEE-103", title: "Alcohol, Drugs and HIV" },
  { code: "BFEE-104", title: "Communication and Counselling in HIV" },
  { code: "BPOI-101", title: "Introduction to Finance and Accounting BPO" },
  { code: "BPOI-102", title: "Fundamentals of Accounting" },
  { code: "BPOI-103", title: "Procure to Pay (P2P, Accounts Payable)" },
  { code: "BPOI-104", title: "Order to Cash (O2C, Accounts Receivable)" },
  { code: "BPOI-105", title: "Record to Report (R2R)" },
  { code: "BPOI-6", title: "English Communication/Communication Skills" },
  { code: "BPOI-6(P)", title: "English Communication/Communication Skills" },
  { code: "BPOI-7", title: "IT Skills" },
  { code: "BPOI-7(P)", title: "IT Skills" },
  { code: "BSSI-11", title: "Communication Skills" },
  { code: "BSSI-12", title: "Computer Skills (Both theory and practical)" },
  { code: "BSSI-13", title: "Secretarial Practice" },
  { code: "BSSI-14", title: "Stenographic Skills (Both theory and practical)" },
  {
    code: "BSSI-14(P)",
    title: "Stenographic Skills (Both theory and practical)",
  },
  { code: "BSSI-15", title: "Office Procedures" },
  { code: "BLE-1", title: "Introduction to the Indian Legal System" },
  { code: "BLE-2", title: "Introduction to Law: Substantive and Procedural" },
  { code: "BLE-3", title: "Law and Vulnerable Groups" },
  { code: "BLE-4", title: "Rural Local Self Governance" },
  { code: "BLEP-1", title: "Project" },
  { code: "BAQ-1", title: "Basics of Aquaculture" },
  { code: "BAQP-1", title: "Project" },
  { code: "BAQ-2", title: "Freshwater Aquaculture" },
  { code: "BAQL-1", title: "Laboratory" },
  { code: "BAQ-3", title: "Coastal Aquaculture" },
  { code: "BAQL-2", title: "Laboratory" },
  { code: "BRL-1", title: "Overview of Retailing" },
  { code: "BRL-2", title: "Retail Marketing and Communication" },
  { code: "BRL-3", title: "Retail Management Perspectives and Communication" },
  { code: "BRL-4", title: "Customer Service Management" },
  { code: "BRLT-5", title: "Internship and Viva-Voce" },
  { code: "DTG-1", title: "General Princizieds of Teaching" },
  { code: "DTG-2", title: "Skill Development" },
  { code: "DTG-3", title: "Classroom Teaching" },
  { code: "DTG-4", title: "Lesson Planning Preparation Evaluation" },
  {
    code: "BNS-11",
    title: "Principles and Practice of Nursing Administration",
  },
  {
    code: "BNS-12",
    title: "Management of Educational Institute, Hospital & Community",
  },
  { code: "BNS-13", title: "Group Dynamics" },
  { code: "BNS-14", title: "Resource Management" },
  { code: "BNSL-11", title: "Nursing Service Administration-I" },
  { code: "BNSL-12", title: "Nursing Service Administration-II" },
  { code: "BNS-31", title: "Concept and Principles in Critical Care Nursing" },
  { code: "BNS-32", title: "Nursing Management in Critical Care Conditions" },
  { code: "BNSL-33", title: "Clinical Nursing Practice in Critical Care-I" },
  { code: "BNSL-34", title: "Clinical Nursing Practice in Critical Care-II" },
  { code: "BTH-1", title: "Understanding Drama" },
  { code: "BTHL-2", title: "Theatre Games" },
  { code: "BTHL-3", title: "Acting Practice, Movement, Voice and Speech" },
  { code: "BTHI-4", title: "Scene Work" },
  { code: "BTHI-5", title: "Class Room Play Production" },
  { code: "BEDS-001", title: "Overview and Perspectives of Values" },
  { code: "BEDS-002", title: "Socio-Psychological Basis" },
  { code: "BEDS-003", title: "Pedagogy of Values" },
  { code: "BEDS-004", title: "Application, Support Skills and Activities" },
  { code: "BEDS-005", title: "Life Skills Education" },
  { code: "CHR-12", title: "Human Rights in India" },
  {
    code: "MIO-001",
    title: "Introduction to Smart Regions: Smart Cities and Smart Villages",
  },
  { code: "MIO-002", title: "Smart Technologies (Hardware and Software)" },
  {
    code: "MIO-003",
    title: "Smart Urban Energy Systems and Smart Transportation System",
  },
  {
    code: "MIO-004",
    title: "Smart Cities: Health, Education, Governance & Cyber Security",
  },
  {
    code: "MIO-005",
    title: "Smart Cities: Safe Water, Sanitation and Sustainability",
  },
  { code: "MIOP-001", title: "Project" },
];
