export const missingCourses = [
  {
    code: "BLI-221",
    title: "Library, Information and Society",
    name: "BLI-221",
    fullName: "Library, Information and Society",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLI-222",
    title: "Information Sources and Services",
    name: "BLI-222",
    fullName: "Information Sources and Services",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLI-223",
    title: "Organising and Managing Information",
    name: "BLI-223",
    fullName: "Organising and Managing Information",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLI-224",
    title: "ICT Fundamentals",
    name: "BLI-224",
    fullName: "ICT Fundamentals",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLI-225",
    title: "Communication Skills",
    name: "BLI-225",
    fullName: "Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLIE-226",
    title: "Management of Library and Information Centre",
    name: "BLIE-226",
    fullName: "Management of Library and Information Centre",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLIE-227",
    title: "Document Processing Practice",
    name: "BLIE-227",
    fullName: "Document Processing Practice",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLIE-228",
    title: "Information Products and Services",
    name: "BLIE-228",
    fullName: "Information Products and Services",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BLIE-229",
    title: "ICT in Libraries",
    name: "BLIE-229",
    fullName: "ICT in Libraries",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-001",
    title: "History of Urdu Language and Literature",
    name: "MAUD-001",
    fullName: "History of Urdu Language and Literature",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-002",
    title: "Urdu Ghazal",
    name: "MAUD-002",
    fullName: "Urdu Ghazal",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-003",
    title: "Urdu Fiction",
    name: "MAUD-003",
    fullName: "Urdu Fiction",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-004",
    title: "Urdu Non-Fiction",
    name: "MAUD-004",
    fullName: "Urdu Non-Fiction",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-007",
    title: "Urdu Nazm",
    name: "MAUD-007",
    fullName: "Urdu Nazm",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-008",
    title: "Classical Urdu P oetry: Qasida, M asnavi, M rsiya",
    name: "MAUD-008",
    fullName: "Classical Urdu P oetry: Qasida, M asnavi, M rsiya",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-009",
    title: "Criticism and R esearch",
    name: "MAUD-009",
    fullName: "Criticism and R esearch",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAUD-010",
    title: "Special Study of M eer Taqi M eer and M irza Ghalib",
    name: "MAUD-010",
    fullName: "Special Study of M eer Taqi M eer and M irza Ghalib",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "TS-1",
    title: "Foundation Course in Tourism",
    name: "TS-1",
    fullName: "Foundation Course in Tourism",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "TS-2",
    title: "Tourism Development: Products, Operations and Case Studies",
    name: "TS-2",
    fullName: "Tourism Development: Products, Operations and Case Studies",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BSHF-101",
    title: "Foundation Course in Humanities & Social Sciences",
    name: "BSHF-101",
    fullName: "Foundation Course in Humanities & Social Sciences",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BHC-11",
    title: "Basic of Event Management *(Credit 4)",
    name: "BHC-11",
    fullName: "Basic of Event Management *(Credit 4)",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BHC-12",
    title: "Event Planning *(Credit 4)",
    name: "BHC-12",
    fullName: "Event Planning *(Credit 4)",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGF-101",
    title: "Foundation Course in English",
    name: "BEGF-101",
    fullName: "Foundation Course in English",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BHC-13",
    title: "Event Coordination and Control*",
    name: "BHC-13",
    fullName: "Event Coordination and Control*",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "FEG-2",
    title: "Foundation Course in English-2",
    name: "FEG-2",
    fullName: "Foundation Course in English-2",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BHDF-101",
    title: "Foundation Course in Hindi",
    name: "BHDF-101",
    fullName: "Foundation Course in Hindi",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BTMS-185",
    title: "Airport Handling",
    name: "BTMS-185",
    fullName: "Airport Handling",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "TS-4",
    title: "Indian Culture: Perspective for Tourism",
    name: "TS-4",
    fullName: "Indian Culture: Perspective for Tourism",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "TS-5",
    title: "Ecology, Environment and Tourism",
    name: "TS-5",
    fullName: "Ecology, Environment and Tourism",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "FST-1",
    title: "Foundation Course in Science and Technology",
    name: "FST-1",
    fullName: "Foundation Course in Science and Technology",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "CIT-1",
    title: "Fundamental of Computer System*",
    name: "CIT-1",
    fullName: "Fundamental of Computer System*",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "CIT-2",
    title: "Introduction To Information Technology*",
    name: "CIT-2",
    fullName: "Introduction To Information Technology*",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "PTS-1",
    title: "Project on Indian Culture, Environment and Tourism",
    name: "PTS-1",
    fullName: "Project on Indian Culture, Environment and Tourism",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "TS-3",
    title: "Management in Tourism",
    name: "TS-3",
    fullName: "Management in Tourism",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "TS-6",
    title: "Tourism Marketing",
    name: "TS-6",
    fullName: "Tourism Marketing",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "TS-7",
    title: "Human Resource Development",
    name: "TS-7",
    fullName: "Human Resource Development",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "PTS-6",
    title: "Project on Tourism Marketing",
    name: "PTS-6",
    fullName: "Project on Tourism Marketing",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "CIT-3",
    title: "Web based Technology & amp; Multimedia Application*",
    name: "CIT-3",
    fullName: "Web based Technology & amp; Multimedia Application*",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BHDA-101",
    title: "Samachar Patra aur Feature Lekhan (Hindi)",
    name: "BHDA-101",
    fullName: "Samachar Patra aur Feature Lekhan (Hindi)",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-101",
    title: "Indian Classical Literature",
    name: "BEGC-101",
    fullName: "Indian Classical Literature",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-102",
    title: "European Classical Literature",
    name: "BEGC-102",
    fullName: "European Classical Literature",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-103",
    title: "Indian Writing in English",
    name: "BEGC-103",
    fullName: "Indian Writing in English",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-104",
    title: "British Poetry and Drama: 14th- 17th Centuries",
    name: "BEGC-104",
    fullName: "British Poetry and Drama: 14th- 17th Centuries",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-105",
    title: "American Literature",
    name: "BEGC-105",
    fullName: "American Literature",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-106",
    title: "Popular Literature",
    name: "BEGC-106",
    fullName: "Popular Literature",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-107",
    title: "British Poetry and Drama: 17th & 18th Centuries",
    name: "BEGC-107",
    fullName: "British Poetry and Drama: 17th & 18th Centuries",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-108",
    title: "British Literature: 18th Century",
    name: "BEGC-108",
    fullName: "British Literature: 18th Century",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-109",
    title: "British Romantic Literature",
    name: "BEGC-109",
    fullName: "British Romantic Literature",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-110",
    title: "British Literature: 19th Century",
    name: "BEGC-110",
    fullName: "British Literature: 19th Century",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-111",
    title: "Women's Writing",
    name: "BEGC-111",
    fullName: "Women's Writing",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-112",
    title: "British Literature: The Early 20th Century",
    name: "BEGC-112",
    fullName: "British Literature: The Early 20th Century",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-113",
    title: "Modern European Drama",
    name: "BEGC-113",
    fullName: "Modern European Drama",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGC-114",
    title: "Postcolonial Literatures",
    name: "BEGC-114",
    fullName: "Postcolonial Literatures",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGE-141",
    title: "Understanding Prose",
    name: "BEGE-141",
    fullName: "Understanding Prose",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGE-143",
    title: "Understanding Poetry",
    name: "BEGE-143",
    fullName: "Understanding Poetry",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGE-142",
    title: "Understanding Drama",
    name: "BEGE-142",
    fullName: "Understanding Drama",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGE-144",
    title: "Understanding The Novel",
    name: "BEGE-144",
    fullName: "Understanding The Novel",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEVAE-181",
    title: "Envirnoment Studies",
    name: "BEVAE-181",
    fullName: "Envirnoment Studies",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGAE-182",
    title: "English Communication Skills",
    name: "BEGAE-182",
    fullName: "English Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BANS-183",
    title: "Tourism Anthropology",
    name: "BANS-183",
    fullName: "Tourism Anthropology",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEGS-183",
    title: "Writing and Study Skills",
    name: "BEGS-183",
    fullName: "Writing and Study Skills",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BPCS-186",
    title: "Managing Stress",
    name: "BPCS-186",
    fullName: "Managing Stress",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BSOG-171",
    title: "Indian Society: Images and Realities",
    name: "BSOG-171",
    fullName: "Indian Society: Images and Realities",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BGDG-172",
    title: "Gender Sensitisation, Society & culture",
    name: "BGDG-172",
    fullName: "Gender Sensitisation, Society & culture",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BSOG-173",
    title: "Rethinking Development",
    name: "BSOG-173",
    fullName: "Rethinking Development",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BHDG-173",
    title: "समाचार पत्र और फ�चर लेखन",
    name: "BHDG-173",
    fullName: "समाचार पत्र और फ�चर लेखन",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BPCG-174",
    title: "Psychology and Media",
    name: "BPCG-174",
    fullName: "Psychology and Media",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BPBLA-135",
    title: "?",
    name: "BPBLA-135",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BCHCT-147",
    title: "?",
    name: "BCHCT-147",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BCHCL-148",
    title: "?",
    name: "BCHCL-148",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BBCCL-126",
    title: "Genetic Engineering and Biotechnology: Laboratory",
    name: "BBCCL-126",
    fullName: "Genetic Engineering and Biotechnology: Laboratory",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BCOC-138",
    title: "?",
    name: "BCOC-138",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BPFT-143",
    title: "?",
    name: "BPFT-143",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BPFL-144",
    title: "?",
    name: "BPFL-144",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BULC-134",
    title: "?",
    name: "BULC-134",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BHDC-174",
    title: "?",
    name: "BHDC-174",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BPAC-171",
    title: "?",
    name: "BPAC-171",
    fullName: "?",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
];
