export const pgGraduateCertificateCourses = [
  {
    code: "MIR-11",
    title: "Cyber Space, Technology and Social Issues",
    name: "MIR-11",
    fullName: "Cyber Space, Technology and Social Issues",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIR-12",
    title: "Regulation of Cyberspace",
    name: "MIR-12",
    fullName: "Regulation of Cyberspace",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIR-13",
    title: "Commerce and Cyberspace",
    name: "MIR-13",
    fullName: "Commerce and Cyberspace",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIR-14",
    title: "Privacy and Data Protection",
    name: "MIR-14",
    fullName: "Privacy and Data Protection",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIR-21",
    title: "Overview of Intellectual Property Rights",
    name: "MIR-21",
    fullName: "Overview of Intellectual Property Rights",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIR-22",
    title: "International Framework for Patents Protection",
    name: "MIR-22",
    fullName: "International Framework for Patents Protection",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIR-23",
    title: "Indian Patent Law and Procedures",
    name: "MIR-23",
    fullName: "Indian Patent Law and Procedures",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIRP-1",
    title: "Project",
    name: "MIRP-1",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MEV-021",
    title: "Introduction to Climate Change",
    name: "MEV-021",
    fullName: "Introduction to Climate Change",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MEV-022",
    title: "Impacts of Climate Change",
    name: "MEV-022",
    fullName: "Impacts of Climate Change",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MEV-023",
    title: "Mitigation and adaptation to Climate Change",
    name: "MEV-023",
    fullName: "Mitigation and adaptation to Climate Change",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MEV-024",
    title: "Climate Change Assessment Tools",
    name: "MEV-024",
    fullName: "Climate Change Assessment Tools",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MEV-025",
    title: "Climate Change and Society",
    name: "MEV-025",
    fullName: "Climate Change and Society",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGY-1",
    title: "Introduction to Geoinformatics",
    name: "MGY-1",
    fullName: "Introduction to Geoinformatics",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGY-2",
    title: "Remote Sensing and Image Interpretation",
    name: "MGY-2",
    fullName: "Remote Sensing and Image Interpretation",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGY-3",
    title:
      "Global Navigation Satellite System and Geographic Information System",
    name: "MGY-3",
    fullName:
      "Global Navigation Satellite System and Geographic Information System",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGYL-4",
    title: "Geoinformatics Practical",
    name: "MGYL-4",
    fullName: "Geoinformatics Practical",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEE-1",
    title: "Power Distribution Sector",
    name: "BEE-1",
    fullName: "Power Distribution Sector",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEE-2",
    title: "Energy Management and IT Applications",
    name: "BEE-2",
    fullName: "Energy Management and IT Applications",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "BEE-3",
    title: "Management of Power Distribution",
    name: "BEE-3",
    fullName: "Management of Power Distribution",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIS-21",
    title: "Safety Philosophy and Principles of Accident Prevention",
    name: "MIS-21",
    fullName: "Safety Philosophy and Principles of Accident Prevention",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIS-22",
    title: "Industrial Safety: Rules and Acts",
    name: "MIS-22",
    fullName: "Industrial Safety: Rules and Acts",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIS-23",
    title: "Safety in Construction Industry",
    name: "MIS-23",
    fullName: "Safety in Construction Industry",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MIS-24",
    title: "Mechanical and Electrical Safety Management",
    name: "MIS-24",
    fullName: "Mechanical and Electrical Safety Management",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MISP-21",
    title: "Project",
    name: "MISP-21",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MWR-001",
    title: "Introduction to Inventory Planning and Control",
    name: "MWR-001",
    fullName: "Introduction to Inventory Planning and Control",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MWR-002",
    title: "Advance Inventory Planning and Control",
    name: "MWR-002",
    fullName: "Advance Inventory Planning and Control",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MWR-003",
    title: "ICT in Warehouse system",
    name: "MWR-003",
    fullName: "ICT in Warehouse system",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MWRP-01",
    title: "Project",
    name: "MWRP-01",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MNR-1",
    title: "Indian Agricultural Development",
    name: "MNR-1",
    fullName: "Indian Agricultural Development",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MNR-2",
    title:
      "Agricultural Policy: Formulation, Components, Process, Implementation and Comparative Analysis",
    name: "MNR-2",
    fullName:
      "Agricultural Policy: Formulation, Components, Process, Implementation and Comparative Analysis",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MNRE-15",
    title: "Cooperatives and Farmers’ Organizations",
    name: "MNRE-15",
    fullName: "Cooperatives and Farmers’ Organizations",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MNRE-16",
    title: "Project Analysis",
    name: "MNRE-16",
    fullName: "Project Analysis",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGP-1",
    title: "Gandhi: The Man and His Times",
    name: "MGP-1",
    fullName: "Gandhi: The Man and His Times",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGP-5",
    title: "Introduction to Peace and Conflict Resolution",
    name: "MGP-5",
    fullName: "Introduction to Peace and Conflict Resolution",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGPE-7",
    title: "Non-violence Movements after Gandhi",
    name: "MGPE-7",
    fullName: "Non-violence Movements after Gandhi",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MGPE-8",
    title: "Gandhian Approach to Peace and Conflict Resolution",
    name: "MGPE-8",
    fullName: "Gandhian Approach to Peace and Conflict Resolution",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAE-1",
    title: "Understanding Adult Education",
    name: "MAE-1",
    fullName: "Understanding Adult Education",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAE-2",
    title: "Policy Planning and Implementation of Adult Education in India",
    name: "MAE-2",
    fullName: "Policy Planning and Implementation of Adult Education in India",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MAEL-2",
    title: "Practical Work: Community-based Practical Activities",
    name: "MAEL-2",
    fullName: "Practical Work: Community-based Practical Activities",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MVEI-11",
    title: "Understanding the Learner",
    name: "MVEI-11",
    fullName: "Understanding the Learner",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MVEI-12",
    title: "Assistive and Adaptive Technologies",
    name: "MVEI-12",
    fullName: "Assistive and Adaptive Technologies",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MVEI-13",
    title: "Software’s for Visually Impaired",
    name: "MVEI-13",
    fullName: "Software’s for Visually Impaired",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MVEI-14",
    title: "Communication Skills",
    name: "MVEI-14",
    fullName: "Communication Skills",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MTT-1",
    title: "Bharatiya Bhashaon Mein Anuvad",
    name: "MTT-1",
    fullName: "Bharatiya Bhashaon Mein Anuvad",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MTT-2",
    title: "Bangla-Hindi Anuvad: Tulana Aur Punah Srijan",
    name: "MTT-2",
    fullName: "Bangla-Hindi Anuvad: Tulana Aur Punah Srijan",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MTT-3",
    title: "Bangla Aur Hindi Ke Vibhinna Bhashik Kshetroan Mein Anuvad",
    name: "MTT-3",
    fullName: "Bangla Aur Hindi Ke Vibhinna Bhashik Kshetroan Mein Anuvad",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MTTP-1",
    title: "Anuvad Pariyojana (Translation Project)",
    name: "MTTP-1",
    fullName: "Anuvad Pariyojana (Translation Project)",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MTT-4",
    title: "Malayalam-Hindi Anuvad: Tulana Aur Punah Srijan",
    name: "MTT-4",
    fullName: "Malayalam-Hindi Anuvad: Tulana Aur Punah Srijan",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MTT-5",
    title: "Malayalam Aur Hindi Ke Vibhinna Bhashik Kshetron Mein Anuvad",
    name: "MTT-5",
    fullName: "Malayalam Aur Hindi Ke Vibhinna Bhashik Kshetron Mein Anuvad",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MTTP-2",
    title: "Anuvad Pariyojana (Translation Project)",
    name: "MTTP-2",
    fullName: "Anuvad Pariyojana (Translation Project)",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MME-11",
    title: "CBRNE Threats and Agents",
    name: "MME-11",
    fullName: "CBRNE Threats and Agents",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MME-12",
    title: "Health Effects and Medical Management of CBRNE Agents",
    name: "MME-12",
    fullName: "Health Effects and Medical Management of CBRNE Agents",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
  {
    code: "MMEL-13",
    title: "Practical Aspects of CBRNE",
    name: "MMEL-13",
    fullName: "Practical Aspects of CBRNE",
    collegeCode: "IGNOU",
    programmeCode: "MCA_NEW",
    term: 1,
  },
];
