export const pgGraduateDiplomaCourses = [
  {
    code: "MCFT-1",
    title: "Human Development and Family Relationships",
    name: "MCFT-1",
    fullName: "Human Development and Family Relationships",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFTL-1",
    title: "Human Development and Family Relationships - Supervised Practicum",
    name: "MCFTL-1",
    fullName:
      "Human Development and Family Relationships - Supervised Practicum",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFT-2",
    title: "Mental Health and Disorders",
    name: "MCFT-2",
    fullName: "Mental Health and Disorders",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFTL-2",
    title: "Mental Health and Disorders-Supervised Practicum",
    name: "MCFTL-2",
    fullName: "Mental Health and Disorders-Supervised Practicum",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFT-3",
    title:
      "Counselling and Family Therapy: Basic Concepts and Theoretical Perspectives",
    name: "MCFT-3",
    fullName:
      "Counselling and Family Therapy: Basic Concepts and Theoretical Perspectives",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFTL-3",
    title:
      "Counselling and Family Therapy: Basic Concepts and Theoretical Perspectives -Supervised Practicum",
    name: "MCFTL-3",
    fullName:
      "Counselling and Family Therapy: Basic Concepts and Theoretical Perspectives -Supervised Practicum",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFT-4",
    title: "Counselling and Family Therapy: Applied Aspects",
    name: "MCFT-4",
    fullName: "Counselling and Family Therapy: Applied Aspects",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFTL-4",
    title:
      "Counselling and Family Therapy: Applied Aspects-Supervised Practicum",
    name: "MCFTL-4",
    fullName:
      "Counselling and Family Therapy: Applied Aspects-Supervised Practicum",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFT-5",
    title: "Counselling and Family Therapy: Research Methods and Statistics",
    name: "MCFT-5",
    fullName: "Counselling and Family Therapy: Research Methods and Statistics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFTL-5",
    title:
      "Counselling and Family Therapy: Research Methods and Statistics-Supervised Practicum",
    name: "MCFTL-5",
    fullName:
      "Counselling and Family Therapy: Research Methods and Statistics-Supervised Practicum",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCFTL-8",
    title: "Reflective Journal",
    name: "MCFTL-8",
    fullName: "Reflective Journal",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDT-1",
    title: "Anuvad: Siddhant Aur Pravidhi",
    name: "PGDT-1",
    fullName: "Anuvad: Siddhant Aur Pravidhi",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDT-2",
    title: "Anuvad Ka Bhashik Aur Samajik Paksh",
    name: "PGDT-2",
    fullName: "Anuvad Ka Bhashik Aur Samajik Paksh",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDT-3",
    title: "Vyavaharik Anuvad Ke Vividh Star Aur Kshetra",
    name: "PGDT-3",
    fullName: "Vyavaharik Anuvad Ke Vividh Star Aur Kshetra",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDT-4",
    title: "Prashasanik Anuvad",
    name: "PGDT-4",
    fullName: "Prashasanik Anuvad",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDT-5",
    title: "Anuvad Pariyojana",
    name: "PGDT-5",
    fullName: "Anuvad Pariyojana",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "IBO-1",
    title: "International Business Environment",
    name: "IBO-1",
    fullName: "International Business Environment",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "IBO-2",
    title: "International Marketing Management",
    name: "IBO-2",
    fullName: "International Marketing Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "IBO-3",
    title: "India’s Foreign Trade",
    name: "IBO-3",
    fullName: "India’s Foreign Trade",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "IBO-4",
    title: "Export Import Procedures and Documentation",
    name: "IBO-4",
    fullName: "Export Import Procedures and Documentation",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "IBO-5",
    title: "International Marketing Logistics",
    name: "IBO-5",
    fullName: "International Marketing Logistics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "IBO-6",
    title: "International Business Finance",
    name: "IBO-6",
    fullName: "International Business Finance",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MST-1",
    title: "Foundation in Mathematics and Statistics",
    name: "MST-1",
    fullName: "Foundation in Mathematics and Statistics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MST-2",
    title: "Descriptive Statistics",
    name: "MST-2",
    fullName: "Descriptive Statistics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MST-3",
    title: "Probability Theory",
    name: "MST-3",
    fullName: "Probability Theory",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MST-4",
    title: "Statistical Inference",
    name: "MST-4",
    fullName: "Statistical Inference",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MST-5",
    title: "Statistical Techniques",
    name: "MST-5",
    fullName: "Statistical Techniques",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSTL-1",
    title: "Basic Statistics Lab",
    name: "MSTL-1",
    fullName: "Basic Statistics Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSTE-1",
    title: "Industrial Statistics-I",
    name: "MSTE-1",
    fullName: "Industrial Statistics-I",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSTE-2",
    title: "Industrial Statistics -II",
    name: "MSTE-2",
    fullName: "Industrial Statistics -II",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSTL-2",
    title: "Industrial Statistics Lab",
    name: "MSTL-2",
    fullName: "Industrial Statistics Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-1",
    title: "Understanding the Environment",
    name: "MED-1",
    fullName: "Understanding the Environment",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-2",
    title: "Sustainable Development: Issues and Challenges",
    name: "MED-2",
    fullName: "Sustainable Development: Issues and Challenges",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-3",
    title: "Energy and Environment",
    name: "MED-3",
    fullName: "Energy and Environment",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-4",
    title: "Towards Participatory Management",
    name: "MED-4",
    fullName: "Towards Participatory Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-5",
    title: "Integrated Environment Management: Urban and Rural",
    name: "MED-5",
    fullName: "Integrated Environment Management: Urban and Rural",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-6",
    title: "Natural Resource Management: Physical and Biotic",
    name: "MED-6",
    fullName: "Natural Resource Management: Physical and Biotic",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-7",
    title: "Agriculture and Environment",
    name: "MED-7",
    fullName: "Agriculture and Environment",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-8",
    title: "Globalisation and Environment",
    name: "MED-8",
    fullName: "Globalisation and Environment",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCH-1",
    title: "Basic Analytical Chemistry",
    name: "MCH-1",
    fullName: "Basic Analytical Chemistry",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCH-2",
    title: "Separation Methods",
    name: "MCH-2",
    fullName: "Separation Methods",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCH-3",
    title: "Spectroscopic Methods",
    name: "MCH-3",
    fullName: "Spectroscopic Methods",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCH-4",
    title: "Electro-analytical and Other Methods",
    name: "MCH-4",
    fullName: "Electro-analytical and Other Methods",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCHL-1",
    title: "Basic Analytical Chemistry Lab",
    name: "MCHL-1",
    fullName: "Basic Analytical Chemistry Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCHL-2",
    title: "Separation Methods Lab",
    name: "MCHL-2",
    fullName: "Separation Methods Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCHL-3",
    title: "Spectroscopic Methods Lab",
    name: "MCHL-3",
    fullName: "Spectroscopic Methods Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCHL-4",
    title: "Electro-analytical and Other Methods Lab",
    name: "MCHL-4",
    fullName: "Electro-analytical and Other Methods Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPA-1",
    title: "Understanding Natural Disasters",
    name: "MPA-1",
    fullName: "Understanding Natural Disasters",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPA-2",
    title: "Understanding Man-made Disasters",
    name: "MPA-2",
    fullName: "Understanding Man-made Disasters",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPA-3",
    title: "Risk Assessment and Vulnerability Analysis",
    name: "MPA-3",
    fullName: "Risk Assessment and Vulnerability Analysis",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPA-4",
    title: "Disaster Preparedness",
    name: "MPA-4",
    fullName: "Disaster Preparedness",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPA-5",
    title: "Disaster Response",
    name: "MPA-5",
    fullName: "Disaster Response",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPA-6",
    title: "Disaster Medicine",
    name: "MPA-6",
    fullName: "Disaster Medicine",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPA-7",
    title: "Rehabilitation, Reconstruction and Recovery",
    name: "MPA-7",
    fullName: "Rehabilitation, Reconstruction and Recovery",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPAP-1",
    title: "Project Work",
    name: "MPAP-1",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MED-4",
    title: "Towards Participatory Management",
    name: "MED-4",
    fullName: "Towards Participatory Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPC-51",
    title: "Fundamentals of Mental Health",
    name: "MPC-51",
    fullName: "Fundamentals of Mental Health",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPC-52",
    title: "Mental Disorders",
    name: "MPC-52",
    fullName: "Mental Disorders",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPC-53",
    title: "Mental Health in Special Areas",
    name: "MPC-53",
    fullName: "Mental Health in Special Areas",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPC-54",
    title: "Services for the Mentally III",
    name: "MPC-54",
    fullName: "Services for the Mentally III",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MPCA-55",
    title: "Internship",
    name: "MPCA-55",
    fullName: "Internship",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLI-1",
    title: "Introduction to Computers",
    name: "MLI-1",
    fullName: "Introduction to Computers",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIL-1",
    title: "Practical",
    name: "MLIL-1",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLI-2",
    title: "Library Automation",
    name: "MLI-2",
    fullName: "Library Automation",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIL-2",
    title: "Practical",
    name: "MLIL-2",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLI-3",
    title: "Information Systems",
    name: "MLI-3",
    fullName: "Information Systems",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIL-3",
    title: "Practical",
    name: "MLIL-3",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLI-4",
    title: "Networking and Internet Technology",
    name: "MLI-4",
    fullName: "Networking and Internet Technology",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIL-4",
    title: "Practical",
    name: "MLIL-4",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLI-5",
    title: "Internet Resources",
    name: "MLI-5",
    fullName: "Internet Resources",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIL-5",
    title: "Practical",
    name: "MLIL-5",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLI-6",
    title: "Content Development",
    name: "MLI-6",
    fullName: "Content Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIL-6",
    title: "Practical",
    name: "MLIL-6",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLI-7",
    title: "Programming",
    name: "MLI-7",
    fullName: "Programming",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIL-7",
    title: "Practical",
    name: "MLIL-7",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLIP-8",
    title: "Project",
    name: "MLIP-8",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGP-1",
    title: "Gandhi: The Man and His Times",
    name: "MGP-1",
    fullName: "Gandhi: The Man and His Times",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGP-2",
    title: "Philosophy of Gandhi",
    name: "MGP-2",
    fullName: "Philosophy of Gandhi",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGP-3",
    title: "Gandhi’s Social Thought",
    name: "MGP-3",
    fullName: "Gandhi’s Social Thought",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGP-4",
    title: "Gandhi’s Political Thought",
    name: "MGP-4",
    fullName: "Gandhi’s Political Thought",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGPE-6",
    title: "Gandhi’s Economic Thought",
    name: "MGPE-6",
    fullName: "Gandhi’s Economic Thought",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGPE-7",
    title: "Non-violent Movements after Gandhi",
    name: "MGPE-7",
    fullName: "Non-violent Movements after Gandhi",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGPE-9",
    title: "Gandhi in the 21st Century",
    name: "MGPE-9",
    fullName: "Gandhi in the 21st Century",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MGPE-14",
    title: "Gandhi, Ecology and Sustainable Development",
    name: "MGPE-14",
    fullName: "Gandhi, Ecology and Sustainable Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-101",
    title: "Higher Education: Its Context and Linkages",
    name: "MES-101",
    fullName: "Higher Education: Its Context and Linkages",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-102",
    title: "Instruction in Higher Education",
    name: "MES-102",
    fullName: "Instruction in Higher Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-103",
    title: "Higher Education: Socio-Psychological Field",
    name: "MES-103",
    fullName: "Higher Education: Socio-Psychological Field",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-104",
    title: "Planning and Management of Higher Education",
    name: "MES-104",
    fullName: "Planning and Management of Higher Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-105",
    title: "Project Work",
    name: "MES-105",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-106",
    title: "Extended Contact Programme",
    name: "MES-106",
    fullName: "Extended Contact Programme",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-131",
    title: "Educational Technology: An Overview",
    name: "MES-131",
    fullName: "Educational Technology: An Overview",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-132",
    title: "Computer in Education",
    name: "MES-132",
    fullName: "Computer in Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-133",
    title: "Selection and Intergration of Technology in Educational Processes",
    name: "MES-133",
    fullName:
      "Selection and Intergration of Technology in Educational Processes",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-134",
    title: "Design, Development and Delivery of Courseware",
    name: "MES-134",
    fullName: "Design, Development and Delivery of Courseware",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MESP-135",
    title: "Project",
    name: "MESP-135",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-004",
    title: "Head Teachers as School Leaders",
    name: "MES-004",
    fullName: "Head Teachers as School Leaders",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-005",
    title: "Human Resource Development",
    name: "MES-005",
    fullName: "Human Resource Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-006",
    title: "Managing Teaching – Learning",
    name: "MES-006",
    fullName: "Managing Teaching – Learning",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-007",
    title: "School Governance and Financial Management",
    name: "MES-007",
    fullName: "School Governance and Financial Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-008",
    title: "Leadership for Better Schools",
    name: "MES-008",
    fullName: "Leadership for Better Schools",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-41",
    title: "Growth and Development of Educational Management",
    name: "MES-41",
    fullName: "Growth and Development of Educational Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-42",
    title: "Dimensions of Educational Management",
    name: "MES-42",
    fullName: "Dimensions of Educational Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-43",
    title: "Organisational Behaviour",
    name: "MES-43",
    fullName: "Organisational Behaviour",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-44",
    title: "Institutional Management",
    name: "MES-44",
    fullName: "Institutional Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MESP-49",
    title: "Project Work",
    name: "MESP-49",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-45",
    title: "School Education",
    name: "MES-45",
    fullName: "School Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-46",
    title: "Higher Education",
    name: "MES-46",
    fullName: "Higher Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-47",
    title: "Open and Distance Education",
    name: "MES-47",
    fullName: "Open and Distance Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-48",
    title: "Alternative Education",
    name: "MES-48",
    fullName: "Alternative Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-81",
    title: "Introduction to Pre-School Education",
    name: "MES-81",
    fullName: "Introduction to Pre-School Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-82",
    title: "Human Development during Early Childhood",
    name: "MES-82",
    fullName: "Human Development during Early Childhood",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-83",
    title: "Principles of Childhood Education",
    name: "MES-83",
    fullName: "Principles of Childhood Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-84",
    title: "Practices in Modern Pre-School Education",
    name: "MES-84",
    fullName: "Practices in Modern Pre-School Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MESP-85",
    title: "Project",
    name: "MESP-85",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAE-1",
    title: "Understanding Adult Education",
    name: "MAE-1",
    fullName: "Understanding Adult Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAE-2",
    title: "Policy Planning and Implementation of Adult Education in India",
    name: "MAE-2",
    fullName: "Policy Planning and Implementation of Adult Education in India",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAE-3",
    title:
      "Knowledge Management, Information Dissemination and Networking in Adult Education",
    name: "MAE-3",
    fullName:
      "Knowledge Management, Information Dissemination and Networking in Adult Education",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MES-16",
    title: "Educational Research",
    name: "MES-16",
    fullName: "Educational Research",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAEL-1",
    title: "Practical Work Components",
    name: "MAEL-1",
    fullName: "Practical Work Components",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-41",
    title: "Introduction to Urban Development",
    name: "MEDS-41",
    fullName: "Introduction to Urban Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-42",
    title: "Issues and Challenges in Urban Planning and Development",
    name: "MEDS-42",
    fullName: "Issues and Challenges in Urban Planning and Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-43",
    title: "Dynamics of Urban Planning and Development",
    name: "MEDS-43",
    fullName: "Dynamics of Urban Planning and Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-44",
    title: "Monitoring and Evaluation of Projects and Programmes",
    name: "MEDS-44",
    fullName: "Monitoring and Evaluation of Projects and Programmes",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDSP-45",
    title: "Project Work",
    name: "MEDSP-45",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDSE-46",
    title: "Development: Issues and Perspectives",
    name: "MEDSE-46",
    fullName: "Development: Issues and Perspectives",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDV-101",
    title: "Introduction to Development and Development Theories",
    name: "MDV-101",
    fullName: "Introduction to Development and Development Theories",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDV-102",
    title: "Dynamics of Development",
    name: "MDV-102",
    fullName: "Dynamics of Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDV-103",
    title: "Issues and Challenges of Development",
    name: "MDV-103",
    fullName: "Issues and Challenges of Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDV-106",
    title: "Research Methodology in Development Studies",
    name: "MDV-106",
    fullName: "Research Methodology in Development Studies",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDV-109",
    title: "Development in India- An Overview",
    name: "MDV-109",
    fullName: "Development in India- An Overview",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDV-4",
    title: "Gender and Development",
    name: "MDV-4",
    fullName: "Gender and Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAW-001",
    title: "Animal Welfare Science and Ethics",
    name: "MAW-001",
    fullName: "Animal Welfare Science and Ethics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAW-002",
    title: "Animal Welfare Issues",
    name: "MAW-002",
    fullName: "Animal Welfare Issues",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAW-003",
    title: "Animal Welfare Laws, Policies and Organizations",
    name: "MAW-003",
    fullName: "Animal Welfare Laws, Policies and Organizations",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MAW-004",
    title: "Animal Welfare Practices, Economics and Livelihood",
    name: "MAW-004",
    fullName: "Animal Welfare Practices, Economics and Livelihood",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-051",
    title: "Fundamentals of CSR",
    name: "MEDS-051",
    fullName: "Fundamentals of CSR",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-052",
    title: "CSR Process",
    name: "MEDS-052",
    fullName: "CSR Process",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-053",
    title: "CSR Implementation",
    name: "MEDS-053",
    fullName: "CSR Implementation",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDS-054",
    title: "CSR Projects and Programmes",
    name: "MEDS-054",
    fullName: "CSR Projects and Programmes",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDSE-046",
    title: "Development: Issues and Perspectives",
    name: "MEDSE-046",
    fullName: "Development: Issues and Perspectives",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEDSP-051",
    title: "Project Work in CSR",
    name: "MEDSP-051",
    fullName: "Project Work in CSR",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-20",
    title: "Introduction to Journalism and Mass Communication",
    name: "MJM-20",
    fullName: "Introduction to Journalism and Mass Communication",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-21",
    title: "Reporting Techniques",
    name: "MJM-21",
    fullName: "Reporting Techniques",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-22",
    title: "Writing and Editing for Print Media",
    name: "MJM-22",
    fullName: "Writing and Editing for Print Media",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-23",
    title: "Broadcast and Online Journalism",
    name: "MJM-23",
    fullName: "Broadcast and Online Journalism",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-24",
    title: "Media and Society",
    name: "MJM-24",
    fullName: "Media and Society",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-25",
    title: "Media Ethics and Laws",
    name: "MJM-25",
    fullName: "Media Ethics and Laws",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJML-20",
    title: "Practical: Print and Online",
    name: "MJML-20",
    fullName: "Practical: Print and Online",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJML-21",
    title: "Practical: Audiovisual",
    name: "MJML-21",
    fullName: "Practical: Audiovisual",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-1",
    title: "Introduction to Broadcasting and Programming",
    name: "MJM-1",
    fullName: "Introduction to Broadcasting and Programming",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-2",
    title: "Production and Presentation",
    name: "MJM-2",
    fullName: "Production and Presentation",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJM-3",
    title: "Recording and Editing",
    name: "MJM-3",
    fullName: "Recording and Editing",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MJML-1",
    title: "Practical",
    name: "MJML-1",
    fullName: "Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MNM-011",
    title: "Understanding Digital Media",
    name: "MNM-011",
    fullName: "Understanding Digital Media",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MNM-012",
    title: "Digital Journalism",
    name: "MNM-012",
    fullName: "Digital Journalism",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MNM-013",
    title: "Media, Information and Empowerment",
    name: "MNM-013",
    fullName: "Media, Information and Empowerment",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MNM-014",
    title: "Contemporary Scenario of Digital Media",
    name: "MNM-014",
    fullName: "Contemporary Scenario of Digital Media",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MNM-015",
    title: "Media Research Methods",
    name: "MNM-015",
    fullName: "Media Research Methods",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MNML-011",
    title: "Digital Journalism Practicals",
    name: "MNML-011",
    fullName: "Digital Journalism Practicals",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MNMP-011",
    title: "Internet Research Project",
    name: "MNMP-011",
    fullName: "Internet Research Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDC-001",
    title: "Fundamentals of Development and Communication",
    name: "MDC-001",
    fullName: "Fundamentals of Development and Communication",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDC-002",
    title: "Human Development and Communication",
    name: "MDC-002",
    fullName: "Human Development and Communication",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDC-003",
    title: "Media in Development Communication",
    name: "MDC-003",
    fullName: "Media in Development Communication",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDC-004",
    title: "Development Journalism for Social Change",
    name: "MDC-004",
    fullName: "Development Journalism for Social Change",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDC-005",
    title: "Development: Information and Communication Technologies",
    name: "MDC-005",
    fullName: "Development: Information and Communication Technologies",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDCE-006",
    title: "Research Methods in Development Communication",
    name: "MDCE-006",
    fullName: "Research Methods in Development Communication",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MDCP-007",
    title: "Project Work",
    name: "MDCP-007",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVP-1",
    title: "Food Fundamentals and Chemistry",
    name: "MVP-1",
    fullName: "Food Fundamentals and Chemistry",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVPI-1",
    title: "Food Microbiology (Integrated)",
    name: "MVPI-1",
    fullName: "Food Microbiology (Integrated)",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVP-2",
    title: "Food Laws and Standards",
    name: "MVP-2",
    fullName: "Food Laws and Standards",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVP-3",
    title: "Principles of Food Safety and Quality Management",
    name: "MVP-3",
    fullName: "Principles of Food Safety and Quality Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVP-4",
    title: "Food Safety and Quality Management Systems",
    name: "MVP-4",
    fullName: "Food Safety and Quality Management Systems",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVPL-1",
    title: "Food Safety and Quality Auditing (Practical)",
    name: "MVPL-1",
    fullName: "Food Safety and Quality Auditing (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVPL-2",
    title: "Chemical Analysis and Quality Assurance (Practical)",
    name: "MVPL-2",
    fullName: "Chemical Analysis and Quality Assurance (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVPP-1",
    title: "Project Work",
    name: "MVPP-1",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-21",
    title: "Introduction to Information Security",
    name: "MSEI-21",
    fullName: "Introduction to Information Security",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-21(P)",
    title: "Introduction to Information Security",
    name: "MSEI-21(P)",
    fullName: "Introduction to Information Security",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-22",
    title: "Network Security",
    name: "MSEI-22",
    fullName: "Network Security",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-22(P)",
    title: "Network Security",
    name: "MSEI-22(P)",
    fullName: "Network Security",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-23",
    title: "Cyber Security",
    name: "MSEI-23",
    fullName: "Cyber Security",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-23(P)",
    title: "Cyber Security",
    name: "MSEI-23(P)",
    fullName: "Cyber Security",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSE-24",
    title: "Policy, Standards and Laws",
    name: "MSE-24",
    fullName: "Policy, Standards and Laws",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-25",
    title: "Application and Business Security Developments",
    name: "MSEI-25",
    fullName: "Application and Business Security Developments",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-25(P)",
    title: "Application and Business Security Developments",
    name: "MSEI-25(P)",
    fullName: "Application and Business Security Developments",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-26",
    title: "BCP, DR Planning and Audit",
    name: "MSEI-26",
    fullName: "BCP, DR Planning and Audit",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-26(P)",
    title: "BCP, DR Planning and Audit",
    name: "MSEI-26(P)",
    fullName: "BCP, DR Planning and Audit",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-27",
    title: "Digital Forensics",
    name: "MSEI-27",
    fullName: "Digital Forensics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEI-27(P)",
    title: "Digital Forensics",
    name: "MSEI-27(P)",
    fullName: "Digital Forensics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSEP-28",
    title: "Project",
    name: "MSEP-28",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVE-1",
    title: "Introduction to Anatomy, Physiology, and Pharmaceutical Chemistry",
    name: "MVE-1",
    fullName:
      "Introduction to Anatomy, Physiology, and Pharmaceutical Chemistry",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVE-2",
    title: "Pharmacology and Toxicology",
    name: "MVE-2",
    fullName: "Pharmacology and Toxicology",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVE-3",
    title: "Pharmaceutics",
    name: "MVE-3",
    fullName: "Pharmaceutics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVE-4",
    title: "Drugs Regulatory Affairs",
    name: "MVE-4",
    fullName: "Drugs Regulatory Affairs",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVE-5",
    title: "Introduction to Management",
    name: "MVE-5",
    fullName: "Introduction to Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MVE-6",
    title: "Sales Management",
    name: "MVE-6",
    fullName: "Sales Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-101",
    title: "General Introduction to IP Rights",
    name: "MIP-101",
    fullName: "General Introduction to IP Rights",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-102",
    title: "Patents",
    name: "MIP-102",
    fullName: "Patents",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-103",
    title:
      "Industrial Design and Layout Designs of Integrated Circuits and Utility Models",
    name: "MIP-103",
    fullName:
      "Industrial Design and Layout Designs of Integrated Circuits and Utility Models",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-104",
    title: "Trademarks, Domain Names, Geographical Indications",
    name: "MIP-104",
    fullName: "Trademarks, Domain Names, Geographical Indications",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-105",
    title: "Copyright and Related Rights",
    name: "MIP-105",
    fullName: "Copyright and Related Rights",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-106",
    title:
      "Plant Varieties Protection, Biotechnology and Traditional Knowledge",
    name: "MIP-106",
    fullName:
      "Plant Varieties Protection, Biotechnology and Traditional Knowledge",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-107",
    title: "Trade Secrets, Competition Law and Protection of TCE",
    name: "MIP-107",
    fullName: "Trade Secrets, Competition Law and Protection of TCE",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MIP-108",
    title: "Management of IPRs",
    name: "MIP-108",
    fullName: "Management of IPRs",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLE-11",
    title: "Criminal Justice System",
    name: "MLE-11",
    fullName: "Criminal Justice System",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLE-12",
    title: "Indian Penal Code",
    name: "MLE-12",
    fullName: "Indian Penal Code",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLE-13",
    title: "Criminal Justice Processes",
    name: "MLE-13",
    fullName: "Criminal Justice Processes",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLE-14",
    title: "Criminal Justice Administration",
    name: "MLE-14",
    fullName: "Criminal Justice Administration",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLE-15",
    title: "Challenges to Criminal Justice System",
    name: "MLE-15",
    fullName: "Challenges to Criminal Justice System",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLE-16",
    title: "Criminal Justice Research and Advocacy",
    name: "MLE-16",
    fullName: "Criminal Justice Research and Advocacy",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MLEP-17",
    title: "Project",
    name: "MLEP-17",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEV-1",
    title: "Introduction to Environmental Health",
    name: "MEV-1",
    fullName: "Introduction to Environmental Health",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEV-2",
    title: "Environmental and Occupational Hazards",
    name: "MEV-2",
    fullName: "Environmental and Occupational Hazards",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEV-3",
    title: "Environmental Law and Management",
    name: "MEV-3",
    fullName: "Environmental Law and Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEV-4",
    title: "Environmental Toxicology",
    name: "MEV-4",
    fullName: "Environmental Toxicology",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEV-5",
    title: "Occupational Health and Safety",
    name: "MEV-5",
    fullName: "Occupational Health and Safety",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEVP-1",
    title: "Project",
    name: "MEVP-1",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEVE-1",
    title: "Environmental Impact Assessment for Environmental Health",
    name: "MEVE-1",
    fullName: "Environmental Impact Assessment for Environmental Health",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEVE-2",
    title: "Health Care",
    name: "MEVE-2",
    fullName: "Health Care",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEVE-3",
    title: "Agriculture and Allied Sector",
    name: "MEVE-3",
    fullName: "Agriculture and Allied Sector",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MEVE-4",
    title: "Industrial Sector",
    name: "MEVE-4",
    fullName: "Industrial Sector",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MFC-1",
    title: "Folklore and Culture: Conceptual Perspectives",
    name: "MFC-1",
    fullName: "Folklore and Culture: Conceptual Perspectives",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MFC-2",
    title: "Tradition, Identity and Cultural Production",
    name: "MFC-2",
    fullName: "Tradition, Identity and Cultural Production",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MFC-3",
    title: "Cultural and Societal Transformation",
    name: "MFC-3",
    fullName: "Cultural and Societal Transformation",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MFC-4",
    title: "Tribes of India: Identity, Culture and Folklore",
    name: "MFC-4",
    fullName: "Tribes of India: Identity, Culture and Folklore",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MFCI-5",
    title: "Project Manual",
    name: "MFCI-5",
    fullName: "Project Manual",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSD-11",
    title: "Sustainability Science",
    name: "MSD-11",
    fullName: "Sustainability Science",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSD-12",
    title: "Ecosystem and Natural Resources",
    name: "MSD-12",
    fullName: "Ecosystem and Natural Resources",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSD-13",
    title: "Socio-Cultural System",
    name: "MSD-13",
    fullName: "Socio-Cultural System",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSD-14",
    title: "Ecological Economics",
    name: "MSD-14",
    fullName: "Ecological Economics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSD-15",
    title: "Institutions, Governance and Policies",
    name: "MSD-15",
    fullName: "Institutions, Governance and Policies",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSD-16",
    title: "Strategies and Models for Sustainability",
    name: "MSD-16",
    fullName: "Strategies and Models for Sustainability",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSD-17",
    title: "Challenges to Sustainable Development",
    name: "MSD-17",
    fullName: "Challenges to Sustainable Development",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSDP-18",
    title: "Project",
    name: "MSDP-18",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MWG-1",
    title: "Theories of Women’s & Gender Studies",
    name: "MWG-1",
    fullName: "Theories of Women’s & Gender Studies",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MWG-2",
    title: "Gender & Power",
    name: "MWG-2",
    fullName: "Gender & Power",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MWG-3",
    title: "Constructing Gender Through Arts & Media",
    name: "MWG-3",
    fullName: "Constructing Gender Through Arts & Media",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MWG-4",
    title: "Gendered Bodies & Sexualities",
    name: "MWG-4",
    fullName: "Gendered Bodies & Sexualities",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MWGP-1",
    title: "Project Work",
    name: "MWGP-1",
    fullName: "Project Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBP-001",
    title: "Introduction to Publishing and its Legal Aspects",
    name: "MBP-001",
    fullName: "Introduction to Publishing and its Legal Aspects",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBP-002",
    title: "Editing and Pre-Press",
    name: "MBP-002",
    fullName: "Editing and Pre-Press",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBP-003",
    title: "Production and Emerging Technologies",
    name: "MBP-003",
    fullName: "Production and Emerging Technologies",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBP-004",
    title: "Marketing, Promotion and Distribution of Books",
    name: "MBP-004",
    fullName: "Marketing, Promotion and Distribution of Books",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBPP-001",
    title: "Project",
    name: "MBPP-001",
    fullName: "Project",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBPA-001",
    title: "Apprenticeship",
    name: "MBPA-001",
    fullName: "Apprenticeship",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBP-005",
    title: "Editing Books for Children",
    name: "MBP-005",
    fullName: "Editing Books for Children",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBP-006",
    title: "Editing Scientific, Technical and Medical Books",
    name: "MBP-006",
    fullName: "Editing Scientific, Technical and Medical Books",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MBP-007",
    title: "Editing Textbooks",
    name: "MBP-007",
    fullName: "Editing Textbooks",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSW-1",
    title: "Origin and Development of Social Work",
    name: "MSW-1",
    fullName: "Origin and Development of Social Work",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSW-12",
    title: "Introduction to Life Characteristics and Challenges",
    name: "MSW-12",
    fullName: "Introduction to Life Characteristics and Challenges",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSW-13",
    title: "Introduction to Psychological Basis of Counselling",
    name: "MSW-13",
    fullName: "Introduction to Psychological Basis of Counselling",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSW-14",
    title: "Relevance of Social Case Work in Counselling",
    name: "MSW-14",
    fullName: "Relevance of Social Case Work in Counselling",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSW-15",
    title: "Basics of Counselling",
    name: "MSW-15",
    fullName: "Basics of Counselling",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSW-16",
    title: "Fields of Counselling",
    name: "MSW-16",
    fullName: "Fields of Counselling",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MSWL-11",
    title: "Social Work Practicum",
    name: "MSWL-11",
    fullName: "Social Work Practicum",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDHHM-1",
    title: "Introduction to Management-I",
    name: "PGDHHM-1",
    fullName: "Introduction to Management-I",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDHHM-2",
    title: "Introduction to Management-II",
    name: "PGDHHM-2",
    fullName: "Introduction to Management-II",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDHHM-3",
    title: "Organization and Management of Hospital",
    name: "PGDHHM-3",
    fullName: "Organization and Management of Hospital",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDHHM-4",
    title: "Clinical, Diagnostic and Therapeutic Services",
    name: "PGDHHM-4",
    fullName: "Clinical, Diagnostic and Therapeutic Services",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDHHM-5",
    title: "Support and Utility Services and Risk Management",
    name: "PGDHHM-5",
    fullName: "Support and Utility Services and Risk Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "PGDHHM-6",
    title: "Health System Management",
    name: "PGDHHM-6",
    fullName: "Health System Management",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MME-4",
    title: "Basic Geriatrics",
    name: "MME-4",
    fullName: "Basic Geriatrics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MME-5",
    title: "Clinical Geriatrics",
    name: "MME-5",
    fullName: "Clinical Geriatrics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MMEL-4",
    title: "Basic Geriatrics",
    name: "MMEL-4",
    fullName: "Basic Geriatrics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MMEL-5",
    title: "Clinical Geriatrics",
    name: "MMEL-5",
    fullName: "Clinical Geriatrics",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MME-301",
    title: "Preventive MCH",
    name: "MME-301",
    fullName: "Preventive MCH",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MME-302",
    title: "Reproductive Health",
    name: "MME-302",
    fullName: "Reproductive Health",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MME-303",
    title: "Child Health",
    name: "MME-303",
    fullName: "Child Health",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MMEL-301",
    title: "Preventive MCH (Practical)",
    name: "MMEL-301",
    fullName: "Preventive MCH (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MMEL-302",
    title: "Reproductive Health (Practical)",
    name: "MMEL-302",
    fullName: "Reproductive Health (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MMEL-303",
    title: "Child Health (Practical)",
    name: "MMEL-303",
    fullName: "Child Health (Practical)",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCMM-101",
    title: "Basics of HIV Infection",
    name: "MCMM-101",
    fullName: "Basics of HIV Infection",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCMM-102",
    title: "National AIDS Control Programme",
    name: "MCMM-102",
    fullName: "National AIDS Control Programme",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCMM-103",
    title: "Systemic Involvement in HIV and STI",
    name: "MCMM-103",
    fullName: "Systemic Involvement in HIV and STI",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCMM-104",
    title: "Management of HIV/AIDS",
    name: "MCMM-104",
    fullName: "Management of HIV/AIDS",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCMML-105",
    title: "Basics Practical",
    name: "MCMML-105",
    fullName: "Basics Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCMML-106",
    title: "Clinical Practical",
    name: "MCMML-106",
    fullName: "Clinical Practical",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCS-201",
    title: "Programming in C and Python",
    name: "MCS-201",
    fullName: "Programming in C and Python",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCS-202",
    title: "Computer Organisation",
    name: "MCS-202",
    fullName: "Computer Organisation",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCS-203",
    title: "Operating Systems",
    name: "MCS-203",
    fullName: "Operating Systems",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCSL-204",
    title: "WINDOWS and LINUX Lab",
    name: "MCSL-204",
    fullName: "WINDOWS and LINUX Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCSL-205",
    title: "C and Python Lab",
    name: "MCSL-205",
    fullName: "C and Python Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCS-206",
    title: "Object Oriented Programming Using Java",
    name: "MCS-206",
    fullName: "Object Oriented Programming Using Java",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCS-207",
    title: "Database Management Systems",
    name: "MCS-207",
    fullName: "Database Management Systems",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCS-208",
    title: "Data Structures and Algorithms",
    name: "MCS-208",
    fullName: "Data Structures and Algorithms",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCSL-209",
    title: "Data Structures and Algorithms Lab",
    name: "MCSL-209",
    fullName: "Data Structures and Algorithms Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
  {
    code: "MCSL-210",
    title: "DBMS and Java Lab",
    name: "MCSL-210",
    fullName: "DBMS and Java Lab",
    collegeCode: "IGNOU",
    programmeCode: "BLIS",
    term: 1,
  },
];
