export const bachelorsDegreeProgrammes = [
  {
    code: "BAG",
    name: "Bachelor of Arts",
    courseList: {
      ALL: [],
      CC: [
        "BANC-131",
        "BANC-132",
        "BANC-133",
        "BANC-134",
        "BECC-131",
        "BECC-132",
        "BECC-133",
        "BECC-134",
        "BHIC-131",
        "BHIC-132",
        "BHIC-133",
        "BHIC-134",
        "BPSC-131",
        "BPSC-132",
        "BPSC-133",
        "BPSC-134",
        "BPCC-131",
        "BPCC-132",
        "BPCC-133",
        "BPCC-134",
        "BPAC-131",
        "BPAC-132",
        "BPAC-133",
        "BPAC-134",
        "BSOC-131",
        "BSOC-132",
        "BSOC-133",
        "BSOC-134",
        "BHDC-131",
        "BHDC-132",
        "BHDC-133",
        "BHDC-134",
        "BHDLA-135",
        "BHDLA-136",
        "BHDLA-137",
        "BHDLA-138",
        "BUDC-131",
        "BUDC-132",
        "BUDC-133",
        "BUDC-134",
        "BUDLA-135",
        "BEGC-131",
        "BEGC-132",
        "BEGC-133",
        "BEGC-134",
        "BEGLA-135",
        "BEGLA-136",
        "BEGLA-137",
        "BEGLA-138",
        "BSKC-131",
        "BSKC-132",
        "BSKC-133",
        "BSKC-134",
        "BSKLA-135",
        "BODLA-135",
        "BGULA-135",
        "BMYLA-135",
        "BPBLA",
        "BMTC-131",
        "BMTC-132",
        "BMTC-133",
        "BMTC-134",
        "BESC-131",
        "BESC-132",
        "BESC-133",
        "BESC-134",
        "BPYC-131",
        "BPYC-132",
        "BPYC-133",
        "BPYC-134",
      ],
      DSE: [
        "BANE-145",
        "BANE-146",
        "BECE-145",
        "BECE-146",
        "BHIE-141",
        "BHIE-142",
        "BHIE-143",
        "BHIE-144",
        "BHIE-145",
        "BPSE-141",
        "BPSE-142",
        "BPSE-143",
        "BPSE-144",
        "BPSE-145",
        "BPSE-146",
        "BPCE-145",
        "BPCE-146",
        "BPAE-141",
        "BPAE-142",
        "BPAE-143",
        "BPAE-144",
        "BSOE-145",
        "BSOE-146",
        "BSOE-148",
        "BHDE-141",
        "BHDE-142",
        "BHDE-143",
        "BHDE-144",
        "BUDE-141",
        "BUDE-142",
        "BEGE-141",
        "BEGE-142",
        "BEGE-143",
        "BEGE-145",
        "BSKE-141",
        "BSKE-142",
        "BMTE-141",
        "BMTE-144",
        "BESE-141",
        "BESE-142",
        "BPYE-141",
        "BPYE-142",
      ],
      AECC: ["BEVAE-181", "BEGAE-182", "BHDAE-182"],
      SEC: [
        "BANS-183",
        "BANS-184",
        "BECS-184",
        "BPCS-183",
        "BPCS-184",
        "BPCS-185",
        "BPCS-186",
        "BPCS-187",
        "BPCS-188",
        "BPAS-184",
        "BPAS-186",
        "BSOS-184",
        "BSOS-185",
        "BHDS-183",
        "BHDS-184",
        "BEGS-183",
        "BEGS-185",
        "BEGS-186",
      ],
      GE: [
        "BGDG-172",
        "BPCG-171",
        "BPCG-172",
        "BPCG-173",
        "BPCG-174",
        "BPCG-175",
        "BPCG-176",
        "BPAG-171",
        "BPAG-172",
        "BPAG-173",
        "BPAG-174",
        "BSOG-171",
        "BSOG-173",
        "BSOG-176",
        "BHDG-173",
        "BEGG-171",
        "BEGG-172",
        "BEGG-173",
        "BEGG-174",
        "BABG-171",
        "BPYG-171",
        "BPYG-172",
      ],
      LA: [],
    },
  },
  {
    code: "BCOMG",
    name: "Bachelor of Commerce",
    courseList: {
      ALL: [],
      CC: [
        "BCOC-131",
        "BCOC-132",
        "BCOC-133",
        "BCOC-134",
        "BCOC-135",
        "BCOC-136",
        "BCOC-137",
      ],
      DSE: ["BCOE-141", "BCOE-143", "BCOE-142", "BCOE-144"],
      AECC: ["BEGAE-182", "BHDAE-182"],
      SEC: ["BCOS-183", "BCOS-184", "BCOS-185", "BCOS-186"],
      GE: ["BCOG-171", "BCOG-172"],
      LA: [
        "BEGLA-135",
        "BEGLA-136",
        "BEGLA-137",
        "BCOLA-138",
        "BHDLA-136",
        "BHDLA-137",
      ],
    },
  },
  {
    code: "BSCG",
    name: "Bachelor of Science",
    courseList: {
      ALL: [],
      CC: [
        "BBYCT-131",
        "BBYCL-132",
        "BBYCT-133",
        "BBYCL-134",
        "BBYCT-135",
        "BBYCL-136",
        "BBYCT-137",
        "BBYCL-138",
        "BCHCT-131",
        "BCHCL-132",
        "BCHCT-133",
        "BCHCL-134",
        "BCHCT-135",
        "BCHCL-136",
        "BCHCL-136",
        "BCHCT-137",
        "BCHCL-138",
        "BGGCT-131",
        "BGGCT-132",
        "BGGCT-133",
        "BGGCL-134",
        "BGGCT-135",
        "BGYCT-131",
        "BGYCL-132",
        "BGYCT-133",
        "BGYCL-134",
        "BGYCT-135",
        "BGYCL-136",
        "BGYCT-137",
        "BGYCL-138",
        "BMTC-131",
        "BMTC-132",
        "BMTC-133",
        "BMTC-134",
        "BPHCT-131",
        "BPHCL-132",
        "BPHCT-133",
        "BPHCL-134",
        "BPHCT-135",
        "BPHCL-136",
        "BPHCT-137",
        "BPHCL-138",
        "BZYCT-131",
        "BZYCL-132",
        "BZYCT-133",
        "BZYCL-134",
        "BZYCT-135",
        "BZYCL-136",
        "BZYCT-137",
        "BZYCL-138",
      ],
      DSE: [
        "BBYET-141",
        "BBYEL-142",
        "BBYET-143",
        "BBYEL-144",
        "BCHET-141",
        "BCHEL-142",
        "BCHET-147",
        "BCHEL-148",
        "BCHET-149",
        "BCHEL-150",
        "BGGET-141",
        "BGGET-142",
        "BGYET-141",
        "BGYEL-142",
        "BGYET-147",
        "BGYEL-148",
        "BMTE-141",
        "BMTE-144",
        "BPHET-141",
        "BPHEL-142",
        "BPHET-143",
        "BPHEL-144",
        "BZYET-141",
        "BZYEL-142",
        "BZYET-143",
        "BZYEL-144",
      ],
      AECC: ["BEVAE-181", "BEGAE-182", "BHDAE-182"],
      SEC: [
        "BANS-183",
        "BPCS-185",
        "BEGS-183",
        "183",
        "BHDS-183",
        "BANS-184",
        "BECS-184",
        "BCOS-184",
        "BPAS-184",
        "BPCS-184",
        "BPCS-186",
        "BSOS-184",
        "BHDS-184",
        "BPCS-187",
        "BSOS-185",
        "BEGS-185",
        "BCOS-185",
        "BPAS-186",
        "BPCS-188",
        "BEGS-186",
        "BCOS-186",
      ],
      GE: [],
      LA: [],
    },
  },
  {
    code: "BCA",
    name: "Bachelor of Computer Applications",
    courseList: {
      ALL: [],
      CC: [],
      DSE: [],
      AECC: [],
      SEC: [],
      GE: [],
      LA: [],
    },
    programmeDetail: {
      first: [
        { course: "FEG-2", credit: 4 },
        { course: "ECO-1", credit: 4 },
        { course: "BCS-11", credit: 3 },
        { course: "BCS-12", credit: 4 },
        { course: "BCSL-13", credit: 2 },
      ],
      second: [
        { course: "ECO-2", credit: 4 },
        { course: "MCS-11", credit: 3 },
        { course: "MCS-12", credit: 4 },
        { course: "MCS-15", credit: 2 },
        { course: "MCS-13", credit: 2 },
        { course: "BCSL-21", credit: 1 },
        { course: "BCSL-22", credit: 1 },
      ],
      third: [
        { course: "MCS-21", credit: 4 },
        { course: "MCS-23", credit: 3 },
        { course: "MCS-14", credit: 3 },
        { course: "BCS-31", credit: 3 },
        { course: "BCSL-32", credit: 1 },
        { course: "BCSL-33", credit: 1 },
        { course: "BCSL-34", credit: 1 },
      ],
      fourth: [
        { course: "BCS-40", credit: 4 },
        { course: "MCS-24", credit: 3 },
        { course: "BCS-41", credit: 4 },
        { course: "BCS-42", credit: 2 },
        { course: "MCSL-16", credit: 2 },
        { course: "BCSL-43", credit: 1 },
        { course: "BCSL-44", credit: 1 },
        { course: "BCSL-45", credit: 1 },
      ],
      fifth: [
        { course: "BCS-51", credit: 3 },
        { course: "BCS-52", credit: 3 },
        { course: "BCS-53", credit: 2 },
        { course: "BCS-54", credit: 3 },
        { course: "BCS-55", credit: 2 },
        { course: "BCSL-56", credit: 1 },
        { course: "BCSL-57", credit: 1 },
        { course: "BCSL-58", credit: 1 },
      ],
      sixth: [
        { course: "BCS-62", credit: 2 },
        { course: "MCS-22", credit: 4 },
        { course: "BCSL-63", credit: 1 },
        { course: "BCSP-64", credit: 8 },
      ],
    },
  },
  // {
  //   code: "BLIS",
  //   name: "",
  //   courseList: {
  //     ALL: ["", "", "", "", ""],
  //     CC: ["", "", "", "", ""],
  //     DSE: ["", "", "", "", ""],
  //     AECC: ["", "", "", "", ""],
  //     SEC: ["", "", "", "", ""],
  //     GE: ["", "", "", "", ""],
  //   },
  // },
  // {
  //   code: "BTS",
  //   name: "",
  //   courseList: {
  //     ALL: ["", "", "", "", ""],
  //     CC: ["", "", "", "", ""],
  //     DSE: ["", "", "", "", ""],
  //     AECC: ["", "", "", "", ""],
  //     SEC: ["", "", "", "", ""],
  //     GE: ["", "", "", "", ""],
  //   },
  // },
  // {
  //   code: "BSWG",
  //   name: "",
  //   courseList: {
  //     ALL: ["", "", "", "", ""],
  //     CC: ["", "", "", "", ""],
  //     DSE: ["", "", "", "", ""],
  //     AECC: ["", "", "", "", ""],
  //     SEC: ["", "", "", "", ""],
  //     GE: ["", "", "", "", ""],
  //   },
  // },
  // {
  //   code: "BBARL",
  //   name: "",
  //   courseList: {
  //     ALL: ["", "", "", "", ""],
  //     CC: ["", "", "", "", ""],
  //     DSE: ["", "", "", "", ""],
  //     AECC: ["", "", "", "", ""],
  //     SEC: ["", "", "", "", ""],
  //     GE: ["", "", "", "", ""],
  //   },
  // },
  // {
  //   code: "BAVTM",
  //   name: "",
  //   courseList: {
  //     ALL: ["", "", "", "", ""],
  //     CC: ["", "", "", "", ""],
  //     DSE: ["", "", "", "", ""],
  //     AECC: ["", "", "", "", ""],
  //     SEC: ["", "", "", "", ""],
  //     GE: ["", "", "", "", ""],
  //   },
  // },
];
